### ISSUE TITLE
Where can I change the fill color of YOLO's segmentation results? I want to change the fill color of each category. Where can I change it?

### ISSUE THREAD

**Issue by litengfeigithub** [ultralytics/ultralytics#18066] opened 2024-12-06 07:46 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Where can I change the fill color of YOLO's segmentation results? I want to change the fill color of each category. Where can I change it?

**Comment by UltralyticsAssistant** [comment] 2024-12-06 07:46
👋 Hello @litengfeigithub, thank you for your interest in Ultralytics 🚀! We recommend a visit to the [Docs](https://docs.ultralytics.com) for new users where you can find many helpful guides and examples, including [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples.

If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us debug it.

If this is a custom ❓ Question like the one you've asked, it would be helpful to know which environment or use case you're working with (e.g., Python scripts, notebooks, or CLI). Please also include relevant code snippets or screenshots to better understand your query.

For customizing YOLO's segmentation visualization, you might want to explore the visualization code typically located in the `plot_results()` or `visualize()` functions in the Ultralytics repository. Referencing the [YOLO Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) in the documentation may also provide insights specific to your use case.

Join the Ultralytics community where it suits you best. For real-time chat, head to [Discord](https://discord.com/invite/ultralytics) 🎧. Prefer in-depth discussions? Check out [Discourse](https://community.ultralytics.com). Or explore threads on our [Subreddit](https://reddit.com/r/Ultralytics) to share experiences and solutions with others.

## Upgrade

Upgrade to the latest `ultralytics` package including all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/) to ensure you're working with the most current features:

```bash
pip install -U ultralytics
```

## Environments

You can test and debug YOLO in any of these verified environments, each preconfigured with dependencies ([CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/), and [PyTorch](https://pytorch.org/)):

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. Refer to [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/).
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/).
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>.

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing. CI tests verify correct operation of all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) on macOS, Windows, and Ubuntu every 24 hours and on every commit.

This is an automated response, but an Ultralytics engineer will review your issue and assist you further as soon as possible. Thank you for your patience! 😊

**Comment by Y-T-G** [comment] 2024-12-06 09:11
Duplicate of https://github.com/ultralytics/ultralytics/issues/18025

**Closed by Y-T-G** 2024-12-06 09:11 UTC
Labels: question, segment

**Comment by litengfeigithub** [comment] 2024-12-07 02:21
thank you very much

**Comment by glenn-jocher** [comment] 2024-12-07 08:07
@litengfeigithub you're welcome! If you have further questions or need additional assistance, feel free to ask.
