### ISSUE TITLE
When detecting, setting stream=True will automatically exit.

### ISSUE THREAD

**Issue by ZJDATY** [ultralytics/ultralytics#14333] opened 2024-07-10 11:02 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When detecting, setting stream=True will automatically exit.It has no log output and automatically exits after running for a few seconds. If I set the stream to False, I can reason normally.My system is ubuntu22.04lts and I am using the latest version of ultralytics-8.2.52,
I am not sure if there are any additional libraries that need to be installed when using stream=True. I have consulted the relevant documentation and have not found any additional libraries that need to be installed.
Here is the code I used:

```
from ultralytics import YOLO
# Load a model
#model = YOLO('yolov8n-seg.pt')  # load a pretrained model (recommended for training)
model = YOLO('runs/detect/train8/weights/best.pt')
source = "rtsp://10.100.22.108:554/live/camera2"
results = model(source, imgsz=[640,640],stream=True,save=False,device =0,show=True)
```

**Comment by glenn-jocher** [comment] 2024-07-10 14:36
Hi @ZJDATY,

Thank you for reaching out and providing detailed information about your issue. It seems like you're encountering an unexpected exit when using `stream=True` during detection.

To help us diagnose the problem more effectively, could you please provide a minimum reproducible example? This will allow us to replicate the issue on our end and identify the root cause. You can find guidelines on how to create a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

In the meantime, please ensure that you are using the latest versions of all relevant packages. Sometimes, issues like these can be resolved by simply updating to the most recent versions.

Additionally, there are no extra libraries required specifically for `stream=True`. However, it's important to ensure that your RTSP stream is accessible and stable. You might want to test the RTSP stream separately using a tool like VLC to confirm its availability.

Here's a slightly modified version of your code to include a basic try-except block for better error handling and logging:

```python
from ultralytics import YOLO

# Load a model
model = YOLO('runs/detect/train8/weights/best.pt')
source = "rtsp://10.100.22.108:554/live/camera2"

try:
    results = model(source, imgsz=[640, 640], stream=True, save=False, device=0, show=True)
    for result in results:
        result.show()
except Exception as e:
    print(f"An error occurred: {e}")
```

This will help capture any exceptions that might be causing the script to exit prematurely and provide more insight into the issue.

Feel free to share any additional logs or error messages you encounter. We're here to help! 😊

**Closed** 2024-07-10 14:55 UTC
Labels: question
