### ISSUE TITLE
OpenVINO model is dynamic even it was converted with dynamic=False

### ISSUE THREAD

**Issue by adrianboguszewski** [ultralytics/ultralytics#14037] opened 2024-06-27 10:06 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

YOLOv8 model after export is dynamic even dynamic was set to False. This happens only if model is quantized.

### Minimal Reproducible Example

```python
from ultralytics import YOLO

model = YOLO("yolov8n") 
model.export(format="openvino", dynamic=False, half=True, int8=True)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment] 2024-06-27 13:55
@adrianboguszewski hi there,

Thank you for bringing this to our attention! It looks like you've encountered an issue where the exported OpenVINO model remains dynamic despite setting `dynamic=False` during export, particularly when the model is quantized.

To help us investigate this further, could you please ensure the following:
1. **Reproducible Example**: You've provided a minimal reproducible example, which is great! If there are any additional steps or specific configurations that might influence this behavior, please include them.
2. **Latest Versions**: Verify that you are using the latest versions of the Ultralytics package and OpenVINO. Sometimes, updates include important fixes and improvements that might resolve the issue.

Here's a quick checklist to ensure everything is up-to-date:
```bash
pip install --upgrade ultralytics openvino
```

If the issue persists after these steps, it would be helpful to have more details about your environment, such as the versions of Python, Ultralytics, and OpenVINO you are using. This information can help us replicate the issue more accurately.

Additionally, you can refer to our [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example) guide for more tips on providing detailed reproducible examples.

We appreciate your patience and cooperation in resolving this matter. If you have any further insights or updates, please feel free to share them here.

**Comment by adrianboguszewski** [comment] 2024-07-03 11:50
@glenn-jocher ?

**Comment by glenn-jocher** [comment] 2024-07-03 19:44
Hi @adrianboguszewski,

Thank you for your patience. It seems like you've encountered an issue where the exported OpenVINO model remains dynamic even when `dynamic=False` is set, particularly with quantization enabled.

To help us investigate this further, please ensure the following:
1. **Reproducible Example**: You've provided a minimal reproducible example, which is great! If there are any additional steps or specific configurations that might influence this behavior, please include them.
2. **Latest Versions**: Verify that you are using the latest versions of the Ultralytics package and OpenVINO. Sometimes, updates include important fixes and improvements that might resolve the issue.

Here's a quick checklist to ensure everything is up-to-date:
```bash
pip install --upgrade ultralytics openvino
```

If the issue persists after these steps, it would be helpful to have more details about your environment, such as the versions of Python, Ultralytics, and OpenVINO you are using. This information can help us replicate the issue more accurately.

Additionally, you can refer to our [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example) guide for more tips on providing detailed reproducible examples.

We appreciate your patience and cooperation in resolving this matter. If you have any further insights or updates, please feel free to share them here.

**Closed** 2024-09-01 18:09 UTC
Labels: TODO, bug
