### ISSUE TITLE
How can I specify where the model is downloaded?

### ISSUE THREAD

**Issue by Septemberlemon** [ultralytics/ultralytics#18435] opened 2024-12-28 17:59 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

here is my config file:
![image](https://github.com/user-attachments/assets/9c613d1f-1422-4ade-a325-fd07e58381b5)
but when I run the code like:
```python
model = YOLO("yolov8n.pt")
```
then it will download model to the current path:
![image](https://github.com/user-attachments/assets/ecac03a9-dd13-48de-ada6-68eed52992a2)
what should I do to let it download to "weights_dir": "C:\\Users\\septemberlemon\\.cache\\ultralytics\\weights" in config json file?

**Comment by UltralyticsAssistant** [comment] 2024-12-28 17:59
👋 Hello @Septemberlemon, thank you for reaching out and your interest in Ultralytics 🚀! We recommend checking out our [Docs](https://docs.ultralytics.com), where new users can find many helpful guides, including usage examples for [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/). These resources often address frequently encountered questions.

If your inquiry relates to custom behavior or settings ❓, please provide additional insights into your configuration, such as the content of your JSON file and how it is being passed to the Ultralytics library. This information will help clarify the issue.

If this is a 🐛 Bug Report, it would be fantastic if you could provide a [minimum reproducible example (MRE)](https://docs.ultralytics.com/help/minimum_reproducible_example/) showcasing the issue. This would allow us to debug the problem more effectively.

To ensure you're using the latest features and fixes, please upgrade your Ultralytics package and dependencies in a **Python>=3.8** environment with:

```bash
pip install -U ultralytics
```

## Explore Verified Environments

YOLO can be used in multiple verified environments, preconfigured with required libraries and hardware support for effortless experimentation. Here are some quick options:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Community Support and Quick Help

For real-time community interactions, join us on [Discord](https://discord.com/invite/ultralytics) 🎧. Prefer detailed discussions? Visit [Discourse](https://community.ultralytics.com) or share insights on our [Subreddit](https://reddit.com/r/Ultralytics).

## Status and CI

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>  
Our CI tests run daily across all supported modes and tasks on macOS, Windows, and Ubuntu. If the badge above is green, everything is operated and verified correctly.

This is an automated response 😊. An Ultralytics engineer will support you further soon!

**Comment by Y-T-G** [comment] 2024-12-28 22:38
Whichever folder you specify before the model name, that's where it will be downloaded.

https://github.com/ultralytics/ultralytics/issues/17513#issuecomment-2472875660

**Comment by Y-T-G** [comment] 2024-12-28 22:39
Duplicate of https://github.com/ultralytics/ultralytics/issues/17513

**Comment by Septemberlemon** [comment] 2024-12-29 18:07
> Whichever folder you specify before the model name, that's where it will be downloaded.
> 
> [#17513 (comment)](https://github.com/ultralytics/ultralytics/issues/17513#issuecomment-2472875660)

so what's the meaning of the config file？

**Comment by Y-T-G** [comment] 2024-12-29 22:11
> so what's the meaning of the config file?

It will search that directory first when loading. If it exists there, it will not download it again.

**Comment by Septemberlemon** [comment] 2024-12-30 06:17
> > so what's the meaning of the config file?
> 
> It will search that directory first when loading model. If the model exists there, it will not download it again.

okay, I've understood
but why don't u design it as also the directory where the model will be download to, I think that will be easier to use

**Comment by Y-T-G** [comment] 2024-12-30 09:08
You can use this to download to that directory.

```python
from ultralytics import settings

model = YOLO(settings["weights_dir"] + "/yolov8n.pt")
```

**Closed** 2024-12-31 12:41 UTC
Labels: question
