### ISSUE TITLE
Training a model using ARM64 devices utilizes only one core

### ISSUE THREAD

**Issue by tilobormann** [ultralytics/ultralytics#14488] opened 2024-07-16 21:40 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

When training a model on ARM64 devices only one CPU core out of 4 or 8 (depending on the device) will be used.

I tested it on RPi5 (BCM2712) and OrangePi5 Plus (RK3855), same result.
I tested it in a docker container and standalone, same result.
settings of: batch=4, device='cpu', workers=4 does not seem to have an effect.

![image](https://github.com/user-attachments/assets/63888637-c596-419e-b2cc-c6579c700c2c)

### Environment

Ultralytics YOLOv8.2.58 🚀 Python-3.11.2 torch-2.3.1 CPU (Cortex-A55)
Setup complete ✅ (8 CPUs, 15.6 GB RAM, 43.7/225.9 GB disk)

OS                  Linux-6.1.43-vendor-rk35xx-aarch64-with-glibc2.36
Environment         Linux
Python              3.11.2
Install             git
RAM                 15.59 GB
CPU                 Cortex-A55
CUDA                None

numpy               ✅ 1.23.5<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.3.1>=1.8.0
torchvision         ✅ 0.18.1>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

# train.py: 

from ultralytics import YOLO

model = YOLO("yolov8n.yaml")  # build a new model from scratch

results = model.train(data="config.yaml", epochs=1, batch=4, device='cpu', workers=4)  # train the model

# config.yaml:
path: /usr/src/ultralytics/data  
train: images/train  
val: images/validation 

names:
  0: alpaca

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment] 2024-07-17 01:09
@tilobormann thanks for reporting this issue. It seems like the multi-core utilization on ARM64 devices isn't working as expected. Could you please ensure you're using the latest version of Ultralytics YOLOv8? If the issue persists, it might be related to how PyTorch handles multiprocessing on ARM architectures. You could try setting the `OMP_NUM_THREADS` environment variable to match the number of CPU cores. If this doesn't help, please let us know so we can investigate further.

**Comment by tilobormann** [comment] 2024-07-17 06:12
@pderrenger thanks for the advise, but it did not change the behavior. 
<code>
export OMP_NUM_THREADS=4
echo $OMP_NUM_THREADS
4
python3 train.py
...
</code>
Same result. BTW: In my train.py I start the training with the following parameters: 
<code>results = model.train(data="config.yaml", epochs=100, batch=4, device='cpu', workers=4)</code>
So what's the difference between workers=4 and your suggestion of OMP_NUM_THREADS?

**Comment by pderrenger** [comment] 2024-07-17 14:03
@tilobormann thanks for trying that out. The `workers` parameter in `model.train` controls the number of data loader workers, which handle data loading in parallel. `OMP_NUM_THREADS` sets the number of threads for OpenMP, which PyTorch uses for parallelizing operations. If neither resolves the issue, please ensure you're using the latest version of Ultralytics YOLOv8. If the problem persists, it might be a deeper compatibility issue with ARM64. We'll continue to investigate.

**Comment by tilobormann** [comment] 2024-07-17 21:37
@pderrenger Thanks Paula for the fast response. yolo checks shows that I'm using the ultralytics version 8.2.58 and as far as i can see this from the repository, this is the latest version. both settings (workers=8 or the export of <code>OMP_NUM_THREADS</code> do not have an effect of the used CPU cores. 

Ultralytics YOLOv8.2.58 🚀 Python-3.12.3 torch-2.3.1 CPU (Cortex-A55)
Setup complete ✅ (8 CPUs, 15.6 GB RAM, 44.4/225.9 GB disk)

OS                  Linux-6.1.43-vendor-rk35xx-aarch64-with-glibc2.39
Environment         Linux
Python              3.12.3
Install             pip
RAM                 15.59 GB
CPU                 Cortex-A55
CUDA                None

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.3.1>=1.8.0
torchvision         ✅ 0.18.1>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

**Comment by glenn-jocher** [comment] 2024-07-17 23:19
I should add here that training on M2 Macbook fully utilizes all cores, so I'm unable to reproduce any problems with CPU utilization on my own ARM64 device.

**Comment by glenn-jocher** [comment] 2024-07-17 23:20
@lakshanthad are you able to reproduce any low CPU utilization rates of RPi when training?

**Comment by tilobormann** [comment] 2024-07-18 11:09
just a comment: I just realized that my training set contained only 1 class (alpacas) and I assumed pytorch maybe is splitting the jobs by different categories. What made some sense in my mind. So I created a new set with 300 pictures from COCO2017 with 12 different classes and re-trained it. But unfortunately my assumtion was wrong. It also uses only one core. 
BTW: also when I run <code>yolo benchmark</code> it shows only 1 core active.

**Comment by glenn-jocher** [comment] 2024-07-18 12:53
@tilobormann yes I'm seeing the same thing on my M2 Macbook, i.e. with `yolo train`:
<img width="1104" alt="Screenshot 2024-07-18 at 14 51 47" src="https://github.com/user-attachments/assets/ee62f156-8ad2-480b-aaa3-07371683d430">

@Laughing-q it looks like we have a CPU utilization issue on CPU, i.e. the screenshot above should show about 800% I think for 8x CPU cores, but it's only showing 1 CPU core being used.

**Comment by glenn-jocher** [comment] 2024-07-18 12:59
@Laughing-q seems related to this ENV variable. I set this to 1 to reduce CPU over-utilization during DDP training that @Burhan-Q was seeing when he was not training in our Docker image but in his own venv.
https://github.com/ultralytics/ultralytics/blob/bfcd85323da7137c031b5104d5f651d949862600/ultralytics/__init__.py#L8

**Comment by lakshanthad** [comment] 2024-07-18 14:56
@glenn-jocher 
Here is training on RPi5 using:
`yolo detect train data=coco8.yaml model=yolov8n.pt epochs=100 imgsz=640`

Afterall, seems to be only utilizing one CPU core

![image](https://github.com/user-attachments/assets/4f253a52-fcab-4726-88a3-852b23009fb9)

**Comment by tilobormann** [comment] 2024-07-19 06:42
@lakshanthad Thanks for verifying the problem. Any chance to fix this soon?

**Comment by Laughing-q** [comment] 2024-07-19 07:14
@tilobormann @glenn-jocher The issue should be fixed in the PR #14544 . :)

**Comment by tilobormann** [comment] 2024-07-19 07:20
Perfect, tanks

**Comment by pderrenger** [comment] 2024-07-19 09:42
You're welcome! If you encounter any more issues or have further questions, feel free to reach out. Happy training!

**Closed** 2024-07-20 18:13 UTC
Labels: bug, fixed
