### ISSUE TITLE
YOLO World fine tuning trains on wrong classes as compared to what is provided

### ISSUE THREAD

**Issue by muaz1236** [ultralytics/ultralytics#18142] opened 2024-12-10 01:43 UTC
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! I have been trying to fine-tune YOLO-World on a custom object-detection dataset having 64 classes as follows: 
```
from ultralytics import YOLO
model_tuned = YOLO("yolov8x-worldv2.pt")
results = model_tuned.train(data="config.yaml", epochs=1)
```

When the fine-tuning starts, the images train_batch0.jpg, train_batch1.jpg, etc. in the folder runs/detect/train are showing **wrong** label numbers than provided, which portrays that YOLO-World is trained on the wrong set of image-label pairs than provided. But when I fine-tune YOLOv9c, the train_batch0.jpg, etc. provide the correct class labels on the same dataset. I have carefully checked the images and labels folders and mapped them with the config.yaml list of classes, which are correct. I even updated ultralytics to the latest version but still wrong. I am not sure, **what could go wrong or is there a bug**? I am attaching config.yaml as a text file here, other associated files/screenshots, and some example label .txt files for your perusal too. Let me know if you need further details. Thanks for your help!

![train_batch0_yolo_world_wrong_ones](https://github.com/user-attachments/assets/b13af9b7-c181-45a0-b714-5be892ef598b)
![train_batch0_yolov9_right_ones](https://github.com/user-attachments/assets/ab59a6d9-4da0-4783-ba01-f88c3aad3957)
[config.yaml.txt](https://github.com/user-attachments/files/18070187/config.yaml.txt)
![images_train_folder_screenshot](https://github.com/user-attachments/assets/75d3f5d1-e475-4075-a6be-15dec6f9b0fa)
![labels_train_folder_screenshot](https://github.com/user-attachments/assets/bd40da30-4b3f-4bb9-91e9-beb748767756)
[bottle_broken_large_000.txt](https://github.com/user-attachments/files/18070251/bottle_broken_large_000.txt)
[capsule_crack_011.txt](https://github.com/user-attachments/files/18070252/capsule_crack_011.txt)
[wood_scratch_003.txt](https://github.com/user-attachments/files/18070253/wood_scratch_003.txt)

**Comment by UltralyticsAssistant** [comment] 2024-12-10 01:44
👋 Hello @muaz1236, thank you for sharing your detailed question and for providing related files/screenshots—it really helps us understand the issue better! 🚀 

We recommend double-checking our [Docs](https://docs.ultralytics.com) for helpful resources, including the [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples, as they often address common questions and potential misconfigurations.

If this is a 🐛 **Bug Report**, please make sure you include or extract a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us debug effectively. For this specific case:
1. Please confirm which version of the `ultralytics` package you are using by running:
   ```bash
   pip show ultralytics
   ```
2. If not already the latest, update your `ultralytics` installation:
   ```bash
   pip install -U ultralytics
   ```
3. Provide us with a simple reproducible code snippet (if possible), along with your dataset setup and configuration settings. This helps us pinpoint the issue more efficiently.

For ❓ **Custom Training Questions**, it may help to provide additional details such as:
- A snippet of your `config.yaml` file (which you’ve already shared—thank you! 😊)
- A few example label `.txt` files (already provided 🌟)
- Training logs and/or error messages (if applicable)

### Community Resources
Don't hesitate to engage with the Ultralytics community for further support or discussions:
- **[Discord](https://discord.com/invite/ultralytics)** 🎧 for real-time conversations
- **[Discourse](https://community.ultralytics.com)** for in-depth troubleshooting or questions
- **[Subreddit](https://reddit.com/r/Ultralytics)** for sharing tips and learning from the community

### Verified Environments
Please ensure you are running YOLO in a supported, up-to-date environment. You can use any of the following options:
- Free GPU Notebooks: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- [**Docker**](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/). Get the latest preconfigured image: <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>
- Cloud VMs such as [GCP](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) or [AWS](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/).

We’ve noted your issue and an Ultralytics engineer will review it soon for further assistance. 😊 Thank you for your patience while we investigate this!

**Comment by Y-T-G** [comment] 2024-12-10 05:02
Probably due to RandomLoadText augmentation.
https://github.com/ultralytics/ultralytics/blob/d170f1ab6ad740369e5508788ab267a6639fc851/ultralytics/data/augment.py#L2135

Is it also the same for validation plots?

**Comment by muaz1236** [comment] 2024-12-10 06:14
@Y-T-G It is not the same for the validation plots namely val_batch0_labels.jpg, etc. These validation plots are giving the correct labels.
Am I right in saying that because of this wrong visualized labels, YOLO-World is not fine-tuning on the correct data or is it just the incorrect visualization and the fine-tuning is still OK?

**Comment by Y-T-G** [comment] 2024-12-10 06:22
It's probably correct.

@Laughing-q

**Comment by Laughing-q** [comment] 2024-12-11 03:38
@Y-T-G @muaz1236 Hey guys the YOLO-World fine-tuning is based on the text of categories, and yes it's related to the `RandomLoadText` augmentation. Basically in `RandomLoadText` we are randomly sampling category names from the category list you provided.
https://github.com/ultralytics/ultralytics/blob/d170f1ab6ad740369e5508788ab267a6639fc851/ultralytics/data/augment.py#L2240-L2252
And you can see here the category indexes `cls` are generated based on the randomly sampled names so the `cls` here might be different among with different batches. But we are calculating the embedding of category names and injecting into the model for training, instead of the category indexes, so the training is all good! No worries!

**Conclusion: the fine-tuning process is all good! the visualization seems incorrect because the generated `cls` could be different among with different batches due to we are randomly sampling category names per batch.**

**Comment by Laughing-q** [comment] 2024-12-11 03:39
@muaz1236 Closing this issue as it seems no bug here! Please feel free to reopen it if you have any related issues! Thank you!

**Closed by Laughing-q** 2024-12-11 03:39 UTC
Labels: question, detect

**Comment by muaz1236** [comment] 2024-12-11 04:27
@Laughing-q thank you for clarifying the visualization differences. I am wondering why you would randomize the category indexes in visualizations despite the fact that the correct category names are injected into the model? Don't this create confusion? And why only in the training batches of yolo-world but not in (say) yolov9?

**Comment by Laughing-q** [comment] 2024-12-11 05:09
@muaz1236 Because YOLO-World we need to text info to get the text embedding but for other detection models like yolov9 we don't need that. And we don't randomize the indexes we randomly sample category names per batch for training, and we need to remain the consistency between the names and indexes hence the indexes are different as well every time.
