### ISSUE TITLE
Visualize data augmentation

### ISSUE THREAD

**Issue by AlexPasqua** [ultralytics/ultralytics#14190] opened 2024-07-03 13:45 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,
is it possible to visualize the result of data augmentation on a small set of images?

It'd be nice to have a visual understanding of what is actually being applied to the data before training, it might be useful for debugging performance issues too.

### Additional

I had a look at the super long discussion in #2412 , but I didn't find an answer to this. What I noticed, though, is that there seems to be a bit of confusion among the community regarding data augmentation in ultralytics, maybe the documentation could go be a bit more exhaustive on the topic (?). Examples would also be useful, both with the CLI and especially with Python, where you don't pass a config file, if I'm not mistaken.

**Comment by glenn-jocher** [comment] 2024-07-03 17:18
@AlexPasqua hello,

Thank you for your question and for thoroughly searching the issues and discussions beforehand! Visualizing data augmentation can indeed provide valuable insights and help debug performance issues.

To visualize the result of data augmentation on a small set of images using YOLOv8, you can leverage the `ultralytics` library in Python. Below is a code example to help you get started:

```python
from ultralytics import YOLO
import matplotlib.pyplot as plt

# Load a YOLOv8 model
model = YOLO('yolov8n.yaml')

# Define a small set of images
images = ['path/to/image1.jpg', 'path/to/image2.jpg']

# Apply data augmentation and visualize
for img_path in images:
    img = model.load_image(img_path)
    augmented_img = model.augment_image(img)
    
    # Plot original and augmented images
    fig, ax = plt.subplots(1, 2, figsize=(12, 6))
    ax[0].imshow(img)
    ax[0].set_title('Original Image')
    ax[1].imshow(augmented_img)
    ax[1].set_title('Augmented Image')
    plt.show()
```

This script loads a YOLOv8 model, applies data augmentation to a small set of images, and visualizes the original and augmented images side by side.

For CLI usage, you can visualize augmentations by running a training command with the `--visualize` flag, which will save augmented images to the `runs/train/exp/` directory:

```bash
yolo train data=coco128.yaml model=yolov8n.yaml epochs=1 --visualize
```

Regarding your feedback on the documentation, we appreciate it and will consider adding more detailed examples and explanations on data augmentation. In the meantime, you can refer to our [preprocessing guide](https://docs.ultralytics.com/guides/preprocessing_annotated_data/) for additional insights.

If you encounter any issues or have further questions, please feel free to share a reproducible example, and ensure you are using the latest version of the packages.

Happy coding! 😊

**Comment by glenn-jocher** [comment] 2024-07-04 13:52
Hello @AlexPasqua,

Thank you for your follow-up! 😊

The code snippet provided earlier was a general example. If you're using a `.pt` checkpoint, you can still visualize data augmentations. Here's an updated version of the code that works with a `.pt` model and includes the necessary imports and functions:

```python
from ultralytics import YOLO
import matplotlib.pyplot as plt
import cv2
import numpy as np

# Load a YOLOv8 model from a .pt checkpoint
model = YOLO('path/to/your/model.pt')

# Define a small set of images
images = ['path/to/image1.jpg', 'path/to/image2.jpg']

# Function to load and preprocess images
def load_image(img_path):
    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    return img

# Function to apply augmentations
def augment_image(model, img):
    # Convert image to tensor and apply augmentations
    img_tensor = model.preprocess(img)
    augmented_img_tensor = model.augment(img_tensor)
    augmented_img = model.postprocess(augmented_img_tensor)
    return augmented_img

# Apply data augmentation and visualize
for img_path in images:
    img = load_image(img_path)
    augmented_img = augment_image(model, img)
    
    # Plot original and augmented images
    fig, ax = plt.subplots(1, 2, figsize=(12, 6))
    ax[0].imshow(img)
    ax[0].set_title('Original Image')
    ax[1].imshow(augmented_img)
    ax[1].set_title('Augmented Image')
    plt.show()
```

### Clarifications:

1. **Loading Images**: The `load_image` function is a custom function to load and preprocess images using OpenCV.
2. **Applying Augmentations**: The `augment_image` function demonstrates how to preprocess, augment, and postprocess images using the model.

### Augmentation Configuration:
The model knows which augmentations to apply based on its configuration. You can specify augmentations in the dataset configuration file (usually a `.yaml` file). For example, you can define augmentations like random crops, flips, rotations, etc., in the `.yaml` file.

### Difference Between Model YAML and CFG Files:
- **Model YAML Files**: These files define the architecture and hyperparameters of the model. They are used to build the model from scratch.
- **CFG Files**: These files are typically used for configuring training parameters, including data augmentation settings, learning rates, and other training-specific parameters.

For more detailed information on data preprocessing and augmentation, you can refer to our [preprocessing guide](https://docs.ultralytics.com/guides/preprocessing_annotated_data/).

If you encounter any further issues or have additional questions, please feel free to share more details or a reproducible example. Ensuring you are using the latest version of the packages can also help resolve potential issues.

Happy experimenting! 🚀

**Comment by DubovitskyDenis** [comment] 2024-07-11 10:48
The model does not have such a methods "preprocess" or "augment"  @glenn-jocher .

**Comment by DubovitskyDenis** [comment] 2024-07-12 03:27
Model does not have a method `train_loader`. @glenn-jocher

**Comment by glenn-jocher** [comment] 2024-07-12 05:38
Hello @DubovitskyDenis,

Thank you for your patience and for pointing that out. I apologize for the oversight. Let's correct this and provide a more accurate approach to visualizing data augmentation.

YOLOv8 does not have a direct `train_loader` method. Instead, you can visualize augmentations by leveraging the built-in data augmentation capabilities during training. Here's an updated example to help you visualize the augmentations:

```python
from ultralytics import YOLO
import matplotlib.pyplot as plt
import cv2
import numpy as np

# Load a YOLOv8 model from a .pt checkpoint
model = YOLO('path/to/your/model.pt')

# Define a small set of images
images = ['path/to/image1.jpg', 'path/to/image2.jpg']

# Function to load and preprocess images
def load_image(img_path):
    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    return img

# Function to apply augmentations using YOLOv8's training pipeline
def visualize_augmentations(model, img):
    # Create a temporary dataset with the single image
    dataset = [{'image': img, 'label': None}]
    
    # Apply augmentations
    for i, data in enumerate(model.train_loader(dataset, augment=True)):
        augmented_img = data['image'].numpy().transpose(1, 2, 0)  # Convert to HWC format
        
        # Plot original and augmented images
        fig, ax = plt.subplots(1, 2, figsize=(12, 6))
        ax[0].imshow(img)
        ax[0].set_title('Original Image')
        ax[1].imshow(augmented_img)
        ax[1].set_title('Augmented Image')
        plt.show()
        break  # Only visualize the first augmented image

# Apply data augmentation and visualize
for img_path in images:
    img = load_image(img_path)
    visualize_augmentations(model, img)
```

This script loads a YOLOv8 model, applies data augmentation using the model's training pipeline, and visualizes the original and augmented images side by side.

If you encounter any further issues or have additional questions, please feel free to share more details or a reproducible example. Ensuring you are using the latest version of the packages can also help resolve potential issues.

Happy experimenting! 🚀

For more detailed information on data preprocessing and augmentation, you can refer to our [preprocessing guide](https://docs.ultralytics.com/guides/preprocessing_annotated_data/).

**Comment by DubovitskyDenis** [comment] 2024-07-12 05:49
I solved this problem through using `YOLODataset` , but you are still using `train_loader` non-existent method. @glenn-jocher

**Comment by glenn-jocher** [comment] 2024-07-12 09:31
Hello @DubovitskyDenis,

Thank you for your patience and for pointing out the oversight. I'm glad to hear you found a solution using `YOLODataset`! 

For others who might be facing similar issues, here's a more accurate approach to visualize data augmentations using the `YOLODataset` class:

```python
from ultralytics import YOLO, YOLODataset
import matplotlib.pyplot as plt
import cv2

# Load a YOLOv8 model from a .pt checkpoint
model = YOLO('path/to/your/model.pt')

# Define a small set of images
images = ['path/to/image1.jpg', 'path/to/image2.jpg']

# Function to load and preprocess images
def load_image(img_path):
    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    return img

# Function to visualize augmentations
def visualize_augmentations(model, img_path):
    img = load_image(img_path)
    dataset = YOLODataset([img], augment=True, img_size=640, stride=32)
    
    for augmented_img, _ in dataset:
        # Plot original and augmented images
        fig, ax = plt.subplots(1, 2, figsize=(12, 6))
        ax[0].imshow(img)
        ax[0].set_title('Original Image')
        ax[1].imshow(augmented_img.permute(1, 2, 0).numpy())
        ax[1].set_title('Augmented Image')
        plt.show()
        break  # Only visualize the first augmented image

# Apply data augmentation and visualize
for img_path in images:
    visualize_augmentations(model, img_path)
```

This script uses the `YOLODataset` class to apply augmentations and visualize the results. 

If you encounter any further issues or have additional questions, please feel free to share more details. Ensuring you are using the latest version of the packages can also help resolve potential issues.

Happy experimenting! 🚀

**Comment by AlexPasqua** [comment] 2024-08-13 08:59
> I solved this problem yesterday through using `YOLODataset` , but you are still using non-existent method `train_loader`. @glenn-jocher

Hi @DubovitskyDenis, could you provide a snipped of the code using `YOLODataset`, please? :slightly_smiling_face:

**Comment by glenn-jocher** [comment] 2024-08-13 15:28
Hi @AlexPasqua, I'm glad to hear you found a solution using `YOLODataset`. If you encounter any further issues or have additional questions, feel free to ask. Your insights could be valuable for others facing similar challenges. Thank you for your contribution!

**Comment by glenn-jocher** [comment] 2024-08-22 04:30
Hi @ygean, could you please share your code snippet using `YOLODataset`? It would be helpful for others facing similar issues. Thank you!

**Comment by DubovitskyDenis** [comment] 2024-08-22 04:47
@ygean @AlexPasqua Sorry for not answering earlier. Today I will add here the instruction on how to view augmented images (due to being busy at work, in about 10 hours).

**Comment by DubovitskyDenis** [comment] 2024-08-22 18:41
@ygean @AlexPasqua 
If you have a folders with images and labels like:
> /path/to/some/images
> /path/to/some/labels
than you can check augmentation via this code:

`from pathlib import Path

from PIL import Image

from ultralytics.utils import IterableSimpleNamespace
from ultralytics.data.dataset import YOLODataset

# create dataset config
default_cfg = IterableSimpleNamespace(task='detect', bgr=0., mode='test', model=None, data=None, epochs=100, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=True, optimizer='auto', verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split='val', save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format='torchscript', keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker='botsort.yaml')
default_cfg.scale = 0.5

my_dataset = YOLODataset(
    data={'names': ['0']},
    img_path="/path/to/some/",
    imgsz=imgsz,
    hyp=default_cfg,
    batch_size=1
)

augmented_image = next(iter(my_dataset))
Image.fromarray(augmented_image['img'].permute((1,2,0)).numpy())`

**Comment by DubovitskyDenis** [comment] 2024-08-22 18:44
@ygean @AlexPasqua 
If you have a folders with images and labels like:
/path/to/some/images
/path/to/some/labels

than you can check augmentation via this code:



```
from pathlib import Path

from PIL import Image

from ultralytics.utils import IterableSimpleNamespace
from ultralytics.data.dataset import YOLODataset

create dataset config
default_cfg = IterableSimpleNamespace(task='detect', bgr=0., mode='test', model=None, data=None, epochs=100, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=True, optimizer='auto', verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split='val', save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format='torchscript', keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker='botsort.yaml')

my_dataset = YOLODataset(
    data={'names': ['0']},
    img_path="/path/to/some/",
    imgsz=640,
    hyp=default_cfg,
    batch_size=1
)

augmented_image = next(iter(my_dataset))
Image.fromarray(augmented_image['img'].permute((1,2,0)).numpy())
```

**Comment by krishna-r97** [comment] 2024-08-22 19:15
> @ygean @AlexPasqua If you have a folders with images and labels like: /path/to/some/images /path/to/some/labels
> 
> than you can check augmentation via this code:
> 
> ```
> from pathlib import Path
> 
> from PIL import Image
> 
> from ultralytics.utils import IterableSimpleNamespace
> from ultralytics.data.dataset import YOLODataset
> 
> create dataset config
> default_cfg = IterableSimpleNamespace(task='detect', bgr=0., mode='test', model=None, data=None, epochs=100, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=True, optimizer='auto', verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split='val', save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format='torchscript', keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker='botsort.yaml')
> 
> my_dataset = YOLODataset(
>     data={'names': ['0']},
>     img_path="/path/to/some/",
>     imgsz=640,
>     hyp=default_cfg,
>     batch_size=1
> )
> 
> augmented_image = next(iter(my_dataset))
> Image.fromarray(augmented_image['img'].permute((1,2,0)).numpy())
> ```

Thanks @DubovitskyDenis This was very helpful

**Comment by DubovitskyDenis** [comment] 2024-08-23 02:45
@krishna-r97 list of class names, this is just example.

**Comment by DubovitskyDenis** [comment] 2024-08-23 02:56
@glenn-jocher I think we can close the issue. This is not a perfect problem solution, but at least something working.

**Closed** 2024-08-26 11:58 UTC
Labels: question

**Comment by glenn-jocher** [comment] 2024-10-15 05:05
Thank you for the update. If you have any more questions or need further assistance, feel free to reach out.

**Comment by glenn-jocher** [comment] 2024-10-26 20:32
@DubovitskyDenis thank you for the update. If you have any more questions or need further assistance, feel free to reach out.

**Comment by glenn-jocher** [comment] 2024-11-03 11:40
Thank you for the update! If you have any further questions or need assistance, feel free to reach out.

**Comment by ipyffor** [comment] 2024-11-12 09:42
> ```python
> model.augment_image
> ```

model.augment_image
Traceback (most recent call last):
  File "/home/gotpl/.conda/envs/torch210/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'YOLO' object has no attribute 'augment_image'

**Comment by DubovitskyDenis** [comment] 2024-11-12 09:50
> > ```python
> > model.augment_image
> > ```
> 
> model.augment_image Traceback (most recent call last): File "/home/gotpl/.conda/envs/torch210/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in **getattr** raise AttributeError(f"'{type(self).**name**}' object has no attribute '{name}'") AttributeError: 'YOLO' object has no attribute 'augment_image'

You can forget about Glenn answers, because they are having no relation to reality.

**Comment by glenn-jocher** [comment] 2024-11-13 20:09
@DubovitskyDenis it seems there was a misunderstanding. The `YOLO` object doesn't have an `augment_image` method. For data augmentation, consider using the `YOLODataset` class as discussed earlier. If you need further assistance, feel free to ask!

**Comment by glenn-jocher** [comment] 2025-01-28 17:58
The example images shown during training with `plots: True` are not augmented; they represent the original data. Augmentations are applied during training but are not reflected in these visualizations. The `visualize: True` setting is for debugging and outputs augmentation visualizations to the `runs` directory, but it may not produce results in all cases depending on the configuration. Regarding your question, "auto_augment" applies predefined augmentation policies like `randaugment`, while "augment" refers to standard augmentation techniques defined in the hyperparameters. For more details, you can refer to the [augmentation settings documentation](https://docs.ultralytics.com/modes/train/#augmentation-settings-and-hyperparameters).

**Comment by olofhq** [comment] 2025-01-29 07:52
Thanks, I would really like `visualize: True` to produce results. It currently does not. The runs directory is though populated with info such as `artifacts`, `metrics`, `params` and `tags`, but nothing where I can see the augmented images. How can I change the configuration to fix this.

**Comment by glenn-jocher** [comment] 2025-01-30 01:50
The `visualize: True` option is designed to output augmentation visualizations, but it may not work in all scenarios. To debug this, ensure your training configuration includes valid augmentation settings (e.g., `mosaic`, `mixup`, or `hsv_h`). If the issue persists, consider using the `YOLODataset` class in Python for manual visualization of augmentations.

**Comment by olofhq** [comment] 2025-02-03 07:53
Hi, 

When running ```model.train(config)``` I get an output on a line that starts with ```engine/trainer:``` that includes ```visualize=True``` and some augment settings such as ```erasing=0.4```, ```hsv_s=0.7``` and ```auto_augment=augmix```. But when going to the directory pointed to in ```Results saved to:``` there are no images. 

I would prefer not to do a workaround if possible. Am I doing something incorrectly at the moment or is it a bug in the software or is this at all not a supported feature?

**Comment by glenn-jocher** [comment] 2025-02-04 04:59
@olofhq the `visualize=True` training setting should save augmentation visualizations to your `runs/train/exp` directory. If they're not appearing, please verify your augmentation parameters are above zero and ensure you have write permissions to the output directory. If the issue persists, feel free to open a GitHub Issue with your complete config and training command for reproduction. We appreciate your feedback to improve visualization reliability!

**Comment by stiv-yakovenko** [comment] 2025-04-20 20:51
No, this code doesn't work any more, on my machine for example it crashes like this:

Scanning segmentation_project_yolo\test\labels.cache... 232 images, 0 backgrounds, 0 corrupt: 100%|██████████| 232/232 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.2.4\plugins\python-ce\helpers\pydev\pydevd.py", line 1500, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.2.4\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\projects\ml-tools\simple_yolo_trainer\preview_ultralytics_augs.py", line 17, in <module>
    my_dataset = YOLODataset(
  File "D:\projects\ml-tools\venv\lib\site-packages\ultralytics\data\dataset.py", line 88, in __init__
    super().__init__(*args, **kwargs)
  File "D:\projects\ml-tools\venv\lib\site-packages\ultralytics\data\base.py", line 138, in __init__
    self.transforms = self.build_transforms(hyp=hyp)
  File "D:\projects\ml-tools\venv\lib\site-packages\ultralytics\data\dataset.py", line 219, in build_transforms
    transforms = v8_transforms(self, self.imgsz, hyp)
  File "D:\projects\ml-tools\venv\lib\site-packages\ultralytics\data\augment.py", line 2413, in v8_transforms
    if hyp.copy_paste_mode == "flip":
  File "D:\projects\ml-tools\venv\lib\site-packages\ultralytics\utils\__init__.py", line 290, in __getattr__
    raise AttributeError(
AttributeError: 
            'IterableSimpleNamespace' object has no attribute 'copy_paste_mode'. This may be caused by a modified or out of date ultralytics
            'default.yaml' file.
Please update your code with 'pip install -U ultralytics' and if necessary replace
            D:\projects\ml-tools\venv\Lib\site-packages\ultralytics\cfg\default.yaml with the latest version from
            https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/default.yaml

> > [@ygean](https://github.com/ygean) [@AlexPasqua](https://github.com/AlexPasqua) If you have folders with images and labels like: /path/to/some/images /path/to/some/labels
> > than you can check augmentation via this code:
> > ```
> > from pathlib import Path
> > 
> > from PIL import Image
> > 
> > from ultralytics.utils import IterableSimpleNamespace
> > from ultralytics.data.dataset import YOLODataset
> > 
> > create dataset config
> > default_cfg = IterableSimpleNamespace(task='detect', bgr=0., mode='test', model=None, data=None, epochs=100, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=True, optimizer='auto', verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split='val', save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format='torchscript', keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker='botsort.yaml')
> > 
> > my_dataset = YOLODataset(
> >     data={'names': ['0']},
> >     img_path="/path/to/some/",
> >     imgsz=640,
> >     hyp=default_cfg,
> >     batch_size=1
> > )
> > 
> > augmented_image = next(iter(my_dataset))
> > Image.fromarray(augmented_image['img'].permute((1,2,0)).numpy())
> > ```
> 
> Nice work, thank you!

**Comment by DubovitskyDenis** [comment] 2025-04-21 05:05
> No, this code doesn't work any more, on my machine for example it crashes like this:
> 
> Scanning segmentation_project_yolo\test\labels.cache... 232 images, 0 backgrounds, 0 corrupt: 100%|██████████| 232/232 [00:00<?, ?it/s] Traceback (most recent call last): File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.2.4\plugins\python-ce\helpers\pydev\pydevd.py", line 1500, in _exec pydev_imports.execfile(file, globals, locals) # execute the script File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.2.4\plugins\python-ce\helpers\pydev_pydev_imps_pydev_execfile.py", line 18, in execfile exec(compile(contents+"\n", file, 'exec'), glob, loc) File "D:\projects\ml-tools\simple_yolo_trainer\preview_ultralytics_augs.py", line 17, in my_dataset = YOLODataset( File "D:\projects\ml-tools\venv\lib\site-packages\ultralytics\data\dataset.py", line 88, in **init** super().**init**(*args, **kwargs) File "D:\projects\ml-tools\venv\lib\site-packages\ultralytics\data\base.py", line 138, in **init** self.transforms = self.build_transforms(hyp=hyp) File "D:\projects\ml-tools\venv\lib\site-packages\ultralytics\data\dataset.py", line 219, in build_transforms transforms = v8_transforms(self, self.imgsz, hyp) File "D:\projects\ml-tools\venv\lib\site-packages\ultralytics\data\augment.py", line 2413, in v8_transforms if hyp.copy_paste_mode == "flip": File "D:\projects\ml-tools\venv\lib\site-packages\ultralytics\utils__init__.py", line 290, in **getattr** raise AttributeError( AttributeError: 'IterableSimpleNamespace' object has no attribute 'copy_paste_mode'. This may be caused by a modified or out of date ultralytics 'default.yaml' file. Please update your code with 'pip install -U ultralytics' and if necessary replace D:\projects\ml-tools\venv\Lib\site-packages\ultralytics\cfg\default.yaml with the latest version from https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/default.yaml
> 
> > > [@ygean](https://github.com/ygean) [@AlexPasqua](https://github.com/AlexPasqua) If you have folders with images and labels like: /path/to/some/images /path/to/some/labels
> > > than you can check augmentation via this code:
> > > ```
> > > from pathlib import Path
> > > 
> > > from PIL import Image
> > > 
> > > from ultralytics.utils import IterableSimpleNamespace
> > > from ultralytics.data.dataset import YOLODataset
> > > 
> > > create dataset config
> > > default_cfg = IterableSimpleNamespace(task='detect', bgr=0., mode='test', model=None, data=None, epochs=100, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=True, optimizer='auto', verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split='val', save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format='torchscript', keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker='botsort.yaml')
> > > 
> > > my_dataset = YOLODataset(
> > >     data={'names': ['0']},
> > >     img_path="/path/to/some/",
> > >     imgsz=640,
> > >     hyp=default_cfg,
> > >     batch_size=1
> > > )
> > > 
> > > augmented_image = next(iter(my_dataset))
> > > Image.fromarray(augmented_image['img'].permute((1,2,0)).numpy())
> > > ```
> > 
> > 
> > Nice work, thank you!

This solution may not be relevant, since I answered in the context of yolov8. When I have the opportunity, I’ll see what has changed there.

**Comment by glenn-jocher** [comment] 2025-04-21 17:43
@stiv-yakovenko Thanks for pointing this out. The code example needs to be updated for the latest Ultralytics version, which requires adding the `copy_paste_mode` parameter. Here's a working version:

```python
from PIL import Image
from ultralytics.utils import IterableSimpleNamespace
from ultralytics.data.dataset import YOLODataset

# Updated config with copy_paste_mode parameter
default_cfg = IterableSimpleNamespace(
    task='detect', bgr=0., mosaic=1.0, mixup=0.0, 
    hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, 
    degrees=0.0, translate=0.1, scale=0.5, 
    shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5,
    copy_paste=0.0, copy_paste_mode='flip',  # Added this parameter
    imgsz=640, augment=True
)

my_dataset = YOLODataset(
    data={'names': {0: 'object'}},  # Dictionary mapping class IDs to names
    img_path="path/to/images",
    imgsz=640,
    augment=True,
    hyp=default_cfg
)

# Get and display an augmented sample
sample = next(iter(my_dataset))
augmented_img = sample['img'].permute(1, 2, 0).numpy()
Image.fromarray(augmented_img)
```

Regarding auto_augment vs regular augmentation: auto_augment applies predefined policy-based transformations specifically for classification tasks (with options 'randaugment', 'autoaugment', or 'augmix'), while regular augmentations like hsv_h, translate, scale, etc. are general transformations applied across all tasks.

For classification tasks, you can add `auto_augment='randaugment'` to see those specific augmentations.
