### ISSUE TITLE
Predicted coordinates of some objects exceed image size coordinates

### ISSUE THREAD

**Issue by xaristeidou** [ultralytics/ultralytics#3914] opened 2023-07-24 10:40 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I noticed a problem in the x,y coordinates of some detections which can result in bugs when working with the coordinates in later stages.

While the image resolution is 640 x 480, there are some predicted x,y coordinates that exceed these boundaries.

```
>>> results[0].boxes.xywh
tensor([[478.3896, 301.4778,  23.4359,  24.9326],
        [325.5826, 284.2389,  21.3517,  24.6148],
        [402.8608, 246.9885,  22.6149,  24.6515],
        [ 17.5177,  17.8046,  46.8148,  36.5457],
        [644.7491,  95.8849,  41.2548,  84.1329],
        [ 83.6791, 213.6855,  39.3638,  61.6566]])
```

The x center coordinate of the 5th detected object is 644 > 640

```
 >>> results[0].boxes.xyxy[4]
tensor([624.1217,  53.8185, 665.3765, 137.9514])
```

Looking at the x1,y1,x2,y2 coordinates, we can see that x2 coordinate is 665 > 640. 

Also these are the normalized ones where some exceed 1.0 values:
```

>>> results[0].boxes.xywhn[4]
tensor([1.0074, 0.1998, 0.0645, 0.1753])

>>> results[0].boxes.xyxyn[4]
tensor([0.9752, 0.1121, 1.0397, 0.2874])
```

I think before the predictions are stored in the lists of coordinates there should be a filtering which will be applied and keep these values inside the normal and allowed boundaries.

### Environment

-YOLO: Ultralytics 8.0.139
-OS: Ubuntu 20.04
-Python: 3.8.10

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment] 2023-07-24 18:18
@xaristeidou thanks for the bug report! Do you have commands we can use to reproduce this behavior?

**Comment by Laughing-q** [comment] 2023-07-25 05:53
@xaristeidou we do have a `clip_boxes` function called inside `scale_boxes` to clip predicted boxes to image size except when the inputs are tensors.
https://github.com/ultralytics/ultralytics/blob/9f5ab67ba2c1437133c9ee3691edc2f16daa99cb/ultralytics/models/yolo/detect/predict.py#L24-L25
Are your inputs tensor type?

**Comment by xaristeidou** [comment] 2023-07-25 06:38
@Laughing-q Input is `<class 'numpy.ndarray'>`

**Comment by Laughing-q** [comment] 2023-07-25 07:40
@xaristeidou I'm not able to reproduce the issue with numpy type.
I have a image here would get predicted boxes that exceeds image size.
Here are my test code and image.
```python
model = YOLO("yolov8s.pt")
im = cv2.imread("test.jpg")
result = model.predict(im, save=True)[0]
assert (result.boxes.xyxyn <= 1.0).all()
```
![image0](https://github.com/ultralytics/ultralytics/assets/61612323/00ad1663-3626-4c1f-b481-869ed140aa95)

Actually the code works fine and would not raise the error `assert (result.boxes.xyxyn <= 1.0).all()`, but if I comment this line `clip_boxes(boxes, img0_shape)` in `scale_boxes` function that I mentioned before, then it would raise the error `assert (result.boxes.xyxyn <= 1.0).all()`.

comment the line `clip_boxes(boxes, img0_shape)`:
![pic-230725-1537-20](https://github.com/ultralytics/ultralytics/assets/61612323/fa439438-68ea-4959-a57b-383415c25dae)
normal case:
![pic-230725-1537-00](https://github.com/ultralytics/ultralytics/assets/61612323/816fc9c4-0197-47a1-a180-140ea1d0de71)

which means function `clip_boxes` there works as we expect(clip the boxes inside boundaries).

**Comment by xaristeidou** [comment] 2023-07-25 09:24
@Laughing-q This happens to me when in tracking mode. When I move the detected object near right end of the image I notice some x1 or x2 coordinates exceeding 640. I tried to save the live video feed which produces this and save it as an mp4, so I can share the model weights I use and this video sample for you to reproduce, but when I tried tracking again on the exported mp4, then the x1, x2 coordinates where clipped to 639.9813.

So I used pretrained weight yolov8m.pt which detect my hand, or a bottle, or a cellphone and I am using a line to check any detection coordinate not normal when I moved the object on the edges there was always detected coordinates  > 1.0 or  < 0.0


Here is how to reproduce it using the following code:

```
from ultralytics import YOLO
import cv2
import os
 
os.chdir("/home/christoforos/Documents/pytorch_files/yolov8")

model = YOLO("yolov8m.pt")

cap = cv2.VideoCapture(0)

# Loop through the video frames
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()
    print(type(frame))
    if success:
        # Run YOLOv8 inference on the frame
        results = model.track(frame, conf = 0.25, classes = [39], save = False, persist = True, tracker = "bytetrack.yaml")
        if (results[0].boxes.xyxyn > 1.0).any() or (results[0].boxes.xyxyn < 0.0).any():
            break

        # Visualize the results on the frame
        annotated_frame = results[0].plot()

        # Display the annotated frame
        cv2.imshow("YOLOv8 Inference", annotated_frame)

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        # Break the loop if the end of the video is reached
        break

# Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()
```


I filter the classes and detect a bottle. Do anything similar with cellphone or whatever you want. Try to move the object to the edges and you will get coordinates higher than 1.0 or lower that 0.0 like the following:

```
>>> results[0].boxes.xyxyn
tensor([[0.6100, 0.1528, 0.7789, 1.0007]])

>>> results[0].boxes.xyxyn
tensor([[ 3.6858e-01, -7.5081e-05,  5.3858e-01,  6.2745e-01]])
```

Let me know if you reproduced the error.

**Comment by xaristeidou** [comment] 2023-07-25 09:36
[bottle.webm](https://github.com/ultralytics/ultralytics/assets/65918758/03b55fed-4d8f-4462-a0ea-7b0db2bb9bd5)

You can use this video sample if you want. It reproduced the error.

**Comment by Laughing-q** [comment] 2023-07-25 13:08
@xaristeidou oh I see, I didn't know you were using track mode. It's possible that happens with track mode, since the logic here is updating the coordinates of tracker to results.boxes.xyxy if using track mode, and in this process we don't clip the boxes I think. I'll take a look.

**Comment by Laughing-q** [comment] 2023-07-25 13:23
@xaristeidou I added clip_boxes for it in here, before the PR merged, you can test it with `update_results` branch to see if it works to you. :)

**Comment by xaristeidou** [comment] 2023-07-25 13:36
@Laughing-q Nice. Do you integrate the changes in later package releases in pypi?

**Comment by glenn-jocher** [comment] 2023-07-25 13:59
@xaristeidou fix PR is merged! This will be part of a new `ultralytics 8.0.142` a little later today.

**Closed** 2023-07-25 13:58 UTC
Labels: bug, fixed
