### ISSUE TITLE
`model.export` onnx model cant use in `DeepStream-Yolo` project

### ISSUE THREAD

**Issue by jaffe-fly** [ultralytics/ultralytics#17418] opened 2024-11-08 10:43 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

onnx code
```
model = YOLO("runs/train2/weights/best.pt")
onnx_file = model.export(format="onnx", dynamic=True)
```
and `deepstream-app -c deepstream_app_config.txt` start
error is
```
WARNING: ../nvdsinfer/nvdsinfer_model_builder.cpp:1494 Deserialize engine failed because file path: /tmp/DeepStream-Yolo/model_b1_gpu0_fp32.engine open error
0:00:09.300830296  8288 0x55b16575f2d0 WARN                 nvinfer gstnvinfer.cpp:679:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:2083> [UID = 1]: deserialize engine from file :/tmp/DeepStream-Yolo/model_b1_gpu0_fp32.engine failed
0:00:09.517878079  8288 0x55b16575f2d0 WARN                 nvinfer gstnvinfer.cpp:679:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2188> [UID = 1]: deserialize backend context from engine from file :/tmp/DeepStream-Yolo/model_b1_gpu0_fp32.engine failed, try rebuild
0:00:09.517906115  8288 0x55b16575f2d0 INFO                 nvinfer gstnvinfer.cpp:682:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:2109> [UID = 1]: Trying to create engine from model files
WARNING: [TRT]: onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
ERROR: [TRT]: 3: [optimizationProfile.cpp::setDimensions::119] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/optimizationProfile.cpp::setDimensions::119, condition: std::all_of(dims.d, dims.d + dims.nbDims, [](int32_t x) noexcept { return x >= 0; })
)
ERROR: [TRT]: 3: [optimizationProfile.cpp::setDimensions::119] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/optimizationProfile.cpp::setDimensions::119, condition: std::all_of(dims.d, dims.d + dims.nbDims, [](int32_t x) noexcept { return x >= 0; })
)
ERROR: [TRT]: 3: [optimizationProfile.cpp::setDimensions::119] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/optimizationProfile.cpp::setDimensions::119, condition: std::all_of(dims.d, dims.d + dims.nbDims, [](int32_t x) noexcept { return x >= 0; })
)

Building the TensorRT Engine

ERROR: [TRT]: 4: [network.cpp::validate::3189] Error Code 4: Internal Error (images: dynamic input is missing dimensions in profile 0.)
Building engine failed

Failed to build CUDA engine
ERROR: ../nvdsinfer/nvdsinfer_model_builder.cpp:733 Failed to create network using custom network creation function
ERROR: ../nvdsinfer/nvdsinfer_model_builder.cpp:799 Failed to get cuda engine from custom library API
0:00:18.955675444  8288 0x55b16575f2d0 ERROR                nvinfer gstnvinfer.cpp:676:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:2129> [UID = 1]: build engine file failed
0:00:19.234750721  8288 0x55b16575f2d0 ERROR                nvinfer gstnvinfer.cpp:676:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2215> [UID = 1]: build backend context failed
0:00:19.234781166  8288 0x55b16575f2d0 ERROR                nvinfer gstnvinfer.cpp:676:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::initialize() <nvdsinfer_context_impl.cpp:1352> [UID = 1]: generate backend failed, check config file settings
0:00:19.236994943  8288 0x55b16575f2d0 WARN                 nvinfer gstnvinfer.cpp:912:gst_nvinfer_start:<primary_gie> error: Failed to create NvDsInferContext instance
0:00:19.237005673  8288 0x55b16575f2d0 WARN                 nvinfer gstnvinfer.cpp:912:gst_nvinfer_start:<primary_gie> error: Config file path: /tmp/DeepStream-Yolo/config_infer_primary_yoloV8.txt, NvDsInfer Error: NVDSINFER_CONFIG_FAILED
** ERROR: <main:706>: Failed to set pipeline to PAUSED
Quitting
nvstreammux: Successfully handled EOS for source_id=0
nvstreammux: Successfully handled EOS for source_id=1
ERROR from primary_gie: Failed to create NvDsInferContext instance
Debug info: gstnvinfer.cpp(912): gst_nvinfer_start (): /GstPipeline:pipeline/GstBin:primary_gie_bin/GstNvInfer:primary_gie:
Config file path: /tmp/DeepStream-Yolo/config_infer_primary_yoloV8.txt, NvDsInfer Error: NVDSINFER_CONFIG_FAILED
App run failed
```
but  in ``DeepStream-Yolo` repo, `python3 export_yoloV8.py -w runs/train3/weights/best.pt --dynamic`  is ok
Is there any difference in the accuracy of these two onnx?

### Environment

in  `ultralytics:latest` docker 

### Minimal Reproducible Example

no

### Additional

no

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment] 2024-11-08 10:44
👋 Hello @jaffe-fly, thank you for your interest in Ultralytics 🚀!

We recommend visiting the [Docs](https://docs.ultralytics.com) for helpful resources. There, new users can find many [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples. It's possible your question or issue has already been addressed in the documentation.

If this is a 🐛 Bug Report, it would be incredibly helpful to provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). This will assist us in debugging the issue more efficiently.

Given your description, it seems the `onnx` export might be encountering compatibility issues with the `DeepStream-Yolo` project. Ensure that your ONNX export settings align with the requirements of the DeepStream application you're using.

If your issue involves ❓ questions about custom training or export processes, please include additional information like dataset image examples and training logs. Also, verify you are following our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

Feel free to connect with our Ultralytics community. For real-time support, join us on [Discord](https://ultralytics.com/discord) 🎧, or engage in more detailed discussions on [Discourse](https://community.ultralytics.com). Additionally, our [Subreddit](https://reddit.com/r/ultralytics) is a great place to share and learn more about similar experiences with YOLO models.

## Upgrade

To ensure your environment is up to date and the issue is not already resolved, upgrade the `ultralytics` package along with all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml). Make sure you are using a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/):

```bash
pip install -U ultralytics
```

## Verified Environments

You can run YOLO in the environments listed below with all dependencies pre-installed, including [CUDA](https://developer.nvidia.com/cuda), [CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/), and [PyTorch](https://pytorch.org/):

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, it means all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are passing, indicating proper functionality of all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) across macOS, Windows, and Ubuntu. 

This is an automated response to help streamline the initial troubleshooting process. An Ultralytics engineer will also assist you soon!

**Comment by inisis** [comment] 2024-11-08 11:42
@jaffe-fly can you share these two onnx models?

**Comment by jaffe-fly** [comment] 2024-11-11 03:35
by my test with `onnx_diff` get this output
```
SummaryResults(exact_match=False, score=0.9997757147673104, a_valid=True, b_valid=True, graph_matches={'initializers': Matches(same=0, a_total=219, b_total=219), 'inputs': Matches(same=0, a_total=1, b_total=1), 'outputs': Matches(same=0, a_total=1, b_total=3), 'nodes': Matches(same=0, a_total=595, b_total=609), 'misc': Matches(same=6, a_total=6, b_total=6)}, root_matches={'misc': Matches(same=7, a_total=10, b_total=10)})
```
[`export_yoloV8.py`](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/utils/export_yoloV8.py) get three `output`,but ` model.export` only get one,

**Closed** 2024-11-11 07:12 UTC
Labels: bug, exports
