### ISSUE TITLE
yolov11 obb Test

### ISSUE THREAD

**Issue by liu15509348793** [ultralytics/ultralytics#16878] opened 2024-10-13 08:59 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is the map of yolov11obb on Dota 1.0 given in ReadMe obtained from the test set submitted to the official Dota website? Or was it obtained in the validation set? If it is submitted to the official website to obtain, can you give me detailed steps, I have trained the yoloobb model now, I don't know how to package it into a format accepted by the official website, is there a ready-made script to use?

**Comment by UltralyticsAssistant** [comment] 2024-10-13 08:59
👋 Hello @liu15509348793, thank you for reaching out about Ultralytics 🚀! An Ultralytics engineer will assist you soon.

In the meantime, please refer to our [Docs](https://docs.ultralytics.com) for valuable insights about our tools, including [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples.

Since you're working on the YOLOv11 OBB model, ensure you've reviewed our [Training Tips](https://docs.ultralytics.com/guides/model-training-tips/) for the best results. For detailed instructions on submission packaging, we don't have a specific script available, but exploring our resources might be helpful.

Feel free to join the Ultralytics community! Engage in real-time on [Discord](https://ultralytics.com/discord) 🎧, participate in discussions on [Discourse](https://community.ultralytics.com), or connect with others on our [Subreddit](https://reddit.com/r/ultralytics).

## Upgrade

To ensure you have the latest features and fixes, upgrade your `ultralytics` package:

```bash
pip install -U ultralytics
```

## Environments

You can try out YOLO in one of our verified environments, with all dependencies ready to go:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If the badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are passing, ensuring reliable operation across platforms.

We appreciate your patience and look forward to helping you further! 😊

**Comment by Y-T-G** [comment] 2024-10-13 10:11
Duplicate of #16799

**Closed** 2024-10-13 10:11 UTC
Labels: question, OBB
