### ISSUE TITLE
ray tune fails with yolov8

### ISSUE THREAD

**Issue by egSat** [ultralytics/ultralytics#17379] opened 2024-11-06 16:58 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Hyperparameter Tuning

### Bug

Hi all!

I'm using ray to search the best hyper parameters for a custom yolov8s model.
When one training ends it raises the following exception:

2024-11-06 16:49:52,200	ERROR tune_controller.py:1331 -- Trial task failed for trial _tune_7a917_00000
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
             ^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/ray/_private/worker.py", line 2745, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/ray/_private/worker.py", line 901, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ParserError): ray::ImplicitFunc.train() (pid=11597, ip=172.17.0.2, actor_id=5b95e8b8af49b9ff0079821c01000000, repr=_tune)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/opt/conda/lib/python3.11/site-packages/ray/air/_internal/util.py", line 104, in run
    self._ret = self._target(*self._args, **self._kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 250, in _trainable_func
    output = fn()
             ^^^^
  File "/opt/conda/lib/python3.11/site-packages/ultralytics/utils/tuner.py", line 106, in _tune
    results = model_to_train.train(**config)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/ultralytics/engine/model.py", line 802, in train
    self.trainer.train()
  File "/opt/conda/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 207, in train
    self._do_train(world_size)
  File "/opt/conda/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 445, in _do_train
    self.save_model()
  File "/opt/conda/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 523, in save_model
    "train_results": self.read_results_csv(),
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 505, in read_results_csv
    return pd.read_csv(self.csv).to_dict(orient="list")
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 15 fields in line 3, saw 16

Trial _tune_7a917_00000 errored after 49 iterations at 2024-11-06 16:49:52. Total running time: 3hr 32min 20s
Error file: /tmp/ray/session_2024-11-06_13-17-28_283877_9452/artifacts/2024-11-06_13-17-31/_tune_2024-11-06_13-17-31/driver_artifacts/_tune_7a917_00000_0_dfl=1.3515,lr0=0.0719,momentum=0.7717,weight_decay=0.0005_2024-11-06_13-17-31/error.txt

### Environment

Ultralytics 8.3.27 🚀 Python-3.11.9 torch-2.4.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4080, 16072MiB)

### Minimal Reproducible Example

# Load a model
model = YOLO("yolov8s.yaml")
dataset_yaml = "/dataset/fish-tune.yaml"
no_epochs = 50
iterations = 100

space ={
    "lr0": tune.uniform(0.008, 0.1),
    'momentum': tune.uniform(0.6, 0.98),
    'weight_decay': tune.uniform(0.0003, 0.0007),
    'dfl': tune.uniform(0.8, 1.8)
}

model.tune( data=dataset_yaml,
            space=space,
            epochs=no_epochs,
            iterations=iterations,
            batch=60,
            optimizer="SGD",
            plots=False,
            save=False,
            val=False,
            use_ray=True,
            gpu_per_trial=1)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment] 2024-11-06 16:59
👋 Hello @egSat, thank you for reaching out to us at Ultralytics 🚀! We appreciate your thorough report on the issue you're encountering with ray tune and YOLOv8.

It seems like there might be a parsing error after one of your training trials completes. To help us delve deeper into this, please double-check that the CSV files generated during training are structured correctly. If you haven't already, providing a minimal reproducible example can be enormously beneficial in debugging this 🐛 bug. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example/) for best practices.

In addition, make sure your environment is up to date. You can upgrade to the latest `ultralytics` package with:

```bash
pip install -U ultralytics
```

For further assistance, you might want to engage with our vibrant community. Join us on [Discord](https://ultralytics.com/discord) for real-time discussions 🎧, or partake in more detailed conversations on [Discourse](https://community.ultralytics.com). Also, why not check out our [Subreddit](https://reddit.com/r/ultralytics) for community insights and tips?

An Ultralytics engineer will review your issue soon, but we hope this information helps in the meantime. Thank you for your patience and for contributing to our community!

## Environments

YOLO can be run seamlessly in various environments. Make sure your environment is prepared with the necessary dependencies, like [CUDA](https://developer.nvidia.com/cuda), [CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/), and [PyTorch](https://pytorch.org/).

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM.
- **Amazon** Deep Learning AMI.
- **Docker Image**: <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

Check the badge above for the status of our integration tests that ensure YOLO is operating correctly across different platforms. If the badge is green, all tests are passing.

**Comment by Y-T-G** [comment] 2024-11-06 17:07
Does it occur every time? The error means the `csv` file was corrupted.

**Comment by egSat** [comment] 2024-11-07 07:19
I stopped after two trials ended, but both of them failed in the same way

**Comment by glenn-jocher** [comment] 2024-11-07 12:32
It sounds like there might be an issue with how the results are being saved or processed. Please ensure that your CSV files are correctly formatted and not corrupted during the trials. If the problem persists, consider checking the logs for any additional error messages that might provide more insight.

**Comment by egSat** [comment] 2024-11-07 12:42
but I dont make any csv file. Just run the tuner with ray option enabled.

**Comment by Y-T-G** [comment] 2024-11-07 12:55
Does it fail with lower number of iterations and epochs? Can you try 5 iterations with 5 epochs?

**Comment by egSat** [comment] 2024-11-07 13:06
I didnt try with fewer epochs and trials, jutst 50 epochs and 100 trials. I could try with fewer values but will take some time

**Comment by glenn-jocher** [comment] 2024-11-07 22:56
Trying with fewer epochs and trials can help identify if the issue persists on a smaller scale, which might make it easier to debug. Let us know how it goes when you have the chance.

**Comment by egSat** [comment] 2024-11-08 08:58
Hi, I tried with 10 epochs and 5 iterations but same error. ( I couldn't set lower values, it raises "AssertionError: grace_period must be <= max_t!")

Also I've tried setting specifically space as: 
space ={
    "lr0": tune.uniform(0.008, 0.07),
}

The error: 
pandas.errors.ParserError: Error tokenizing data. C error: Expected 15 fields in line 3, saw 16

╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Trial name          status           lr0     iter     total time (s)     metrics/precision(B)     metrics/recall(B)     metrics/mAP50(B)     metrics/mAP50-95(B) │
├──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ _tune_ff8dc_00001   RUNNING    0.0299957                                                                                                                         │
│ _tune_ff8dc_00002   PENDING    0.0527373                                                                                                                         │
│ _tune_ff8dc_00003   PENDING    0.0604467                                                                                                                         │
│ _tune_ff8dc_00004   PENDING    0.0518225                                                                                                                         │
│ _tune_ff8dc_00000   ERROR      0.0239371        9            267.561                        0                     0                    0                       0 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

**Comment by egSat** [comment] 2024-11-08 09:26
I've found that the file it fails is runs/detect/train/results.csv  but this file is not created when tuning. 
In runs/detect I can see only tune* folders.
but if I use project=/runs then I can find the results.cvs file.

The content is:
epoch,time,train/box_loss,train/cls_loss,train/dfl_loss,metrics/precision(B),metrics/recall(B),metrics/mAP50(B),metrics/mAP50-95(B),val/box_loss,val/cls_loss,val/dfl_loss,lr/pg0,lr/pg1,lr/pg2
1,42.0944,4.18164,4.96843,3.83669,0,0,0,0,0,0,0,0.0775541,0.010781,0.010781
2,81.9556,3.06298,3.50296,2.64783,0,0,0,0,0,0,0,0,0.0528983,0.0194585,0.0194585
3,117.006,2.80866,3.19849,2.39978,0,0,0,0,0,0,0,1,0.026101,0.0259945,0.0259945
4,144.465,2.66658,3.07865,2.2809,0,0,0,0,0,0,0,2,0.02281,0.02281,0.02281
5,171.972,2.57002,2.89721,2.19105,0,0,0,0,0,0,0,3,0.0195977,0.0195977,0.0195977
6,199.449,2.49623,2.721,2.13429,0,0,0,0,0,0,0,4,0.0163855,0.0163855,0.0163855
7,226.893,2.41421,2.58009,2.06812,0,0,0,0,0,0,0,5,0.0131733,0.0131733,0.0131733
8,254.358,2.36297,2.4839,2.03922,0,0,0,0,0,0,0,6,0.00996111,0.00996111,0.00996111
9,281.825,2.27622,2.38115,1.9535,0,0,0,0,0,0,0,7,0.00674889,0.00674889,0.00674889
10,441.476,2.2302,2.28175,1.92419,0.46294,0.36557,0.31994,0.1221,2.01738,3.21388,1.8789,0.00353668,0.00353668,0.00353668

16 fields, comma-separated.

**Comment by glenn-jocher** [comment] 2024-11-08 17:57
It seems the issue is due to a mismatch in the number of fields in the `results.csv` file. Ensure that each line in the CSV has the same number of fields. You might need to check your training script or the logging mechanism to ensure consistency in the output format.

**Comment by egSat** [comment] 2024-11-08 18:20
But I'm not doing anything different that calling the tune method, Logging the default the library uses. The whole script I use it's shared in the reproducible script.

**Comment by Y-T-G** [comment] 2024-11-08 18:26
@egSat It's reproducible. It will be fixed with https://github.com/ultralytics/ultralytics/pull/17416

**Comment by egSat** [comment] 2024-11-08 21:09
Thank! I've manually applied the fix and works :)
thank you very much!

**Comment by glenn-jocher** [comment] 2024-11-09 09:32
You're welcome! I'm glad to hear the fix worked for you. If you have any more questions, feel free to ask.

**Closed** 2024-11-10 16:04 UTC
Labels: bug
