### ISSUE TITLE
Why this problem which is "SyntaxError: 'momentum ' is not a valid YOLO argument. Similar arguments are i.e. ['momentum=0.937', 'warmup_momentum=0.8']."

### ISSUE THREAD

**Issue by chunxuancao** [ultralytics/ultralytics#16531] opened 2024-09-29 01:31 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### It's my error
```
Traceback (most recent call last):
  File "E:\System_settings\Project\YOLOV10模型开发GUI训练\YOLOV10GUI\gui\UI.py", line 478, in startTraining
    self.model.train(**self.cfg)
  File "E:\System_settings\Project\YOLOV10模型开发GUI训练\ultralytics\engine\model.py", line 547, in train
    self.trainer = (trainer or self._smart_load("trainer"))(overrides=args, _callbacks=self.callbacks)
  File "E:\System_settings\Project\YOLOV10模型开发GUI训练\ultralytics\engine\trainer.py", line 100, in __init__
    self.args = get_cfg(cfg, overrides)
  File "E:\System_settings\Project\YOLOV10模型开发GUI训练\ultralytics\cfg\__init__.py", line 212, in get_cfg
    check_dict_alignment(cfg, overrides)
  File "E:\System_settings\Project\YOLOV10模型开发GUI训练\ultralytics\cfg\__init__.py", line 323, in check_dict_alignment
    raise SyntaxError(string + CLI_HELP_MSG) from e
SyntaxError: 'momentum ' is not a valid YOLO argument. Similar arguments are i.e. ['momentum=0.937', 'warmup_momentum=0.8'].
```

**Comment by UltralyticsAssistant** [comment] 2024-09-29 01:32
👋 Hello @chunxuancao, thank you for reaching out to Ultralytics 🚀! This is an automated response to help guide you, and an Ultralytics engineer will also assist you soon.

If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) so we can better help debug the issue.

For your configuration 🔧, you mentioned encountering a `SyntaxError`. Please ensure that your configuration aligns with the [official documentation](https://docs.ultralytics.com/usage/cfg/). It seems there might be a formatting or typographical error in your arguments, so double-check those potential causes.

To be sure your current setup is up to date and potentially solve the issue, upgrade your `ultralytics` package:

```bash
pip install -U ultralytics
```

Explore our extensive resources to join conversations and gain insights:

- Visit the [Docs](https://docs.ultralytics.com) for more information.
- For real-time chat, connect with us on [Discord](https://ultralytics.com/discord) 🎧.
- Participate in discussions on [Discourse](https://community.ultralytics.com) or [Reddit](https://reddit.com/r/ultralytics).

## Verified Environments

Run YOLOv8 in any of our verified environments with pre-installed dependencies like [CUDA](https://developer.nvidia.com/cuda), [Python](https://www.python.org/), and [PyTorch](https://pytorch.org/):

- Notebooks with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- Google Cloud Deep Learning VM
- Amazon Deep Learning AMI
- Docker Image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a> If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing.

We appreciate your patience and look forward to resolving your issue 😊!

**Comment by chunxuancao** [comment] 2024-09-29 01:35
```
        cfg={
            "epochs":self.epochs.value(),
            "batch":self.batch.value(),
            "patience":self.patience_2.value(),
            "imgsz":self.imgsz.value(),
            "seed":self.seed.value(),
            "save_period":self.save_period.value(),
            "workers":self.workers.value(),
            "weight_decay":self.weight_decay.value(),
            "close_mosaic":self.close_mosaic.value(),
            "lr0":self.lr0.value(),
            "lrf":self.lrf.value(),
            "momentum ":self.momentum .value(),
            "warmup_epochs":self.warmup_epochs.value(),
            "warmup_momentum":self.warmup_momentum.value(),
            "warmup_bias_lr":self.warmup_bias_lr.value(),
            "box":self.box.value(),
            "cls":self.cls.value(),
            "dfl":self.dfl.value(),
            "label_smoothing":self.label_smoothing.value(),
            "dropout":self.dropout.value(),
            "mask_ratio":self.mask_ratio.value(),
            "nbs":self.nbs.value(),
            "save": self.save.isChecked(),
            "cache": self.cache.isChecked(),
            "exist_ok":self.exist_ok.isChecked(),
            "deterministic":self.deterministic.isChecked(),
            "verbose":self.verbose.isChecked(),
            "amp":self.amp.isChecked(),
            "profile":self.profile.isChecked(),
            "val":self.val.isChecked(),
            "plots":self.plots.isChecked(),
            # 数据增强
            "hsv_h":self.hsv_h.value(),
            "hsv_s":self.hsv_s.value(),
            "hsv_v":self.hsv_v.value(),
            "degrees":self.degrees.value(),
            "translate":self.translate.value(),
            "scale":self.scale.value(),
            "shear":self.shear.value(),
            "perspective":self.perspective.value(),
            "flipud":self.flipud.value(),
            "fliplr":self.fliplr.value(),
            "bgr":self.bgr.value(),
            "mosaic":self.mosaic.value(),
            "mixup":self.mixup.value(),
            "copy_paste":self.copy_paste.value(),
            "erasing":self.erasing.value(),
            "crop_fraction":self.crop_fraction.value(),
            "auto_augment":self.auto_augment.currentText(),
            "device":device
        }
        self.cfg['data']=self.data
        self.model.train(**self.cfg)
```
### This is a question with no hyperparameters

**Comment by chunxuancao** [comment] 2024-09-29 01:38
``` 
     self.cfg={
            "epochs":self.epochs.value(),
            "batch":self.batch.value(),
            "patience":self.patience_2.value(),
            "imgsz":self.imgsz.value(),
            "seed":self.seed.value(),
            "save_period":self.save_period.value(),
            "workers":self.workers.value(),
            "weight_decay":self.weight_decay.value(),
            "close_mosaic":self.close_mosaic.value(),
            "lr0":self.lr0.value(),
            "lrf":self.lrf.value(),
            "momentum ":self.momentum .value(),
            "warmup_epochs":self.warmup_epochs.value(),
            "warmup_momentum":self.warmup_momentum.value(),
            "warmup_bias_lr":self.warmup_bias_lr.value(),
            "box":self.box.value(),
            "cls":self.cls.value(),
            "dfl":self.dfl.value(),
            "label_smoothing":self.label_smoothing.value(),
            "dropout":self.dropout.value(),
            "mask_ratio":self.mask_ratio.value(),
            "nbs":self.nbs.value(),
            "save": self.save.isChecked(),
            "cache": self.cache.isChecked(),
            "exist_ok":self.exist_ok.isChecked(),
            "deterministic":self.deterministic.isChecked(),
            "verbose":self.verbose.isChecked(),
            "amp":self.amp.isChecked(),
            "profile":self.profile.isChecked(),
            "val":self.val.isChecked(),
            "plots":self.plots.isChecked(),
            "hsv_h":self.hsv_h.value(),
            "hsv_s":self.hsv_s.value(),
            "hsv_v":self.hsv_v.value(),
            "degrees":self.degrees.value(),
            "translate":self.translate.value(),
            "scale":self.scale.value(),
            "shear":self.shear.value(),
            "perspective":self.perspective.value(),
            "flipud":self.flipud.value(),
            "fliplr":self.fliplr.value(),
            "bgr":self.bgr.value(),
            "mosaic":self.mosaic.value(),
            "mixup":self.mixup.value(),
            "copy_paste":self.copy_paste.value(),
            "erasing":self.erasing.value(),
            "crop_fraction":self.crop_fraction.value(),
            "auto_augment":self.auto_augment.currentText(),
            "device":device
        }
  self.cfg['data']=self.data
  self.model.train(**self.cfg)
```
### This is a question with no hyperparameters
I make a GUI to load the hyperparameters to start trainning

**Comment by chunxuancao** [comment] 2024-09-29 01:41
> 您好，感谢您联系Ultralytics🚀这是一个自动响应，以帮助指导你，一个Ultralytics工程师也将帮助你很快。
> 
> 如果这是一个错误报告，请提供一个[最小的可重复的例子](https://docs.ultralytics.com/help/minimum_reproducible_example/)，这样我们可以更好地帮助调试问题。
> 
> 对于您的配置，您提到遇到`SyntaxError`。🔧请确保您的配置与[官方文档](https://docs.ultralytics.com/usage/cfg/)一致。您的论点中似乎可能存在格式或印刷错误，因此请仔细检查这些潜在原因。
> 
> 要确保您当前的设置是最新的并可能解决问题，请升级您`的ultralytics`包：
> 
> ```shell
> pip install -U ultralytics
> ```
> 
> 探索我们广泛的资源以加入对话并获得见解：
> 
> * 请访问[浏览器](https://docs.ultralytics.com)以了解更多信息。
> * 如需实时聊天，请在[Discord](https://ultralytics.com/discord)上与我们联系。
> * 参与[Discourse](https://community.ultralytics.com)或[Reddit](https://reddit.com/r/ultralytics)上的讨论。
> 
> ##  验证环境
> 在任何经过验证的环境中运行YOLOv8，并预安装[CUDA](https://developer.nvidia.com/cuda)，[Python](https://www.python.org/)和[PyTorch](https://pytorch.org/)等依赖项：
> 
> * 带免费GPU的笔记本电脑：[ <img alt="Run on Gradient" width="130.4375" height="20" src="https://camo.githubusercontent.com/6df71b7d7e0b09a2e97776f416bcd40acf48fc87337f8bcce48e4235537daf1f/68747470733a2f2f6173736574732e706170657273706163652e696f2f696d672f6772616469656e742d62616467652e737667"> ](https://console.paperspace.com/github/ultralytics/ultralytics)[ <img alt="Open In Colab" width="117" height="20" src="https://camo.githubusercontent.com/96889048f8a9014fdeba2a891f97150c6aac6e723f5190236b10215a97ed41f3/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667"> ](https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)[ <img alt="Open In Kaggle" width="111.296875" height="20" src="https://camo.githubusercontent.com/c7135949c5c6882489e68f4af05a78a759460a4db256b86df3097e04419b4d9e/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667"> ](https://www.kaggle.com/ultralytics/yolov8)
> * Google Cloud深度学习虚拟机
> * 亚马逊深度学习AMI
> * Docker镜像[ <img alt="Docker Pulls" width="131" height="20" src="https://camo.githubusercontent.com/6dcbe0a245fadcfd5202d971a92467bd2fcab86efebb2228d73468152c680573/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f756c7472616c79746963733f6c6f676f3d646f636b6572"> ](https://hub.docker.com/r/ultralytics/ultralytics)
> 
> ##  地位
> [ <img alt="Ultralytics CI" width="148" height="20" src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg"> ](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule)如果此标记为绿色，则当前所有[Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule)测试均通过。
> 
> 我们感谢您的耐心，并期待着解决您的问题！😊

     self.cfg={
            "epochs":self.epochs.value(),
            "batch":self.batch.value(),
            "patience":self.patience_2.value(),
            "imgsz":self.imgsz.value(),
            "seed":self.seed.value(),
            "save_period":self.save_period.value(),
            "workers":self.workers.value(),
            "weight_decay":self.weight_decay.value(),
            "close_mosaic":self.close_mosaic.value(),
            "lr0":self.lr0.value(),
            "lrf":self.lrf.value(),
            "momentum ":self.momentum .value(),
            "warmup_epochs":self.warmup_epochs.value(),
            "warmup_momentum":self.warmup_momentum.value(),
            "warmup_bias_lr":self.warmup_bias_lr.value(),
            "box":self.box.value(),
            "cls":self.cls.value(),
            "dfl":self.dfl.value(),
            "label_smoothing":self.label_smoothing.value(),
            "dropout":self.dropout.value(),
            "mask_ratio":self.mask_ratio.value(),
            "nbs":self.nbs.value(),
            "save": self.save.isChecked(),
            "cache": self.cache.isChecked(),
            "exist_ok":self.exist_ok.isChecked(),
            "deterministic":self.deterministic.isChecked(),
            "verbose":self.verbose.isChecked(),
            "amp":self.amp.isChecked(),
            "profile":self.profile.isChecked(),
            "val":self.val.isChecked(),
            "plots":self.plots.isChecked(),
            "hsv_h":self.hsv_h.value(),
            "hsv_s":self.hsv_s.value(),
            "hsv_v":self.hsv_v.value(),
            "degrees":self.degrees.value(),
            "translate":self.translate.value(),
            "scale":self.scale.value(),
            "shear":self.shear.value(),
            "perspective":self.perspective.value(),
            "flipud":self.flipud.value(),
            "fliplr":self.fliplr.value(),
            "bgr":self.bgr.value(),
            "mosaic":self.mosaic.value(),
            "mixup":self.mixup.value(),
            "copy_paste":self.copy_paste.value(),
            "erasing":self.erasing.value(),
            "crop_fraction":self.crop_fraction.value(),
            "auto_augment":self.auto_augment.currentText(),
            "device":device
        }
  self.cfg['data']=self.data
  self.model.train(**self.cfg)

这是一个没有超参数的问题

我做了一个GUI来加载超参数以开始训练

**Comment by chunxuancao** [comment] 2024-09-29 02:09
I find the key hava a blank(Laugh and cry)

**Closed** 2024-09-29 02:08 UTC
Labels: documentation, question, detect

**Comment by glenn-jocher** [comment] 2024-09-29 13:25
It looks like the issue was caused by an extra space in the "momentum" key. Removing the space should resolve the error.
