### ISSUE TITLE
YOLOv8 train & val: Confusion Matrix not complete

### ISSUE THREAD

**Issue by ddracoo** [ultralytics/ultralytics#6302] opened 2023-11-13 08:21 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train, Val

### Bug

The confusion matrix is saved with only the first row of values. Is it a bug? 

It happens during training and validation on a cluster (single gpu).
![image](https://github.com/ultralytics/ultralytics/assets/150657668/f7d4b614-06d1-4de9-aea9-dd0d587f1a91)

### Minimal Reproducible Example

from ultralytics import YOLO

model = YOLO('/cluster/.../weights/best.pt')

metrics = model.val(
  model=model, 
  data='/cluster/.../dataset_file.yaml',
  split='test', 
  imgsz=860, 
  batch=8, 
  save_json=True, 
  device=0
)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment] 2023-11-14 13:49
@ddracoo hello! Thank you for bringing this issue to our attention. It appears you've encountered an incomplete confusion matrix, which is only showing the first row of values. This is certainly not the expected behavior and we will need to look into it.

The confusion matrix should display a comprehensive overview of the model's performance across all classes present in your dataset. If it's only populating the first row with values, this could indicate that it's only considering one class or there is an indexing issue when the matrix gets populated.

Could you please ensure your dataset has multiple classes and they are being correctly recognized during the training and validation process? You might want to review the dataset labels and the corresponding class names in your dataset_file.yaml for any inconsistencies.

If your dataset and class names are correct, I recommend double-checking the version of the YOLOv8 codebase you're using and updating it to the latest version if you haven't already done so. Sometimes these issues can be resolved by updates that have been made to the code after reports from users like you.

If the issue persists after these checks, please create an issue on our GitHub repository providing detailed information about your dataset, the version of the YOLOv8 you are using, and any console logs/errors shown during the training/validation process. Your collaboration would help us tremendously in identifying the root cause of this behavior.

For detailed documentation on how to use the YOLOv8 model and troubleshoot common issues, please refer to the Ultralytics Docs. I hope this helps, and we're looking forward to getting to the bottom of this issue together with the YOLO community!

**Closed** 2023-12-05 13:44 UTC
Labels: bug, non-reproducible
