### ISSUE TITLE
pred_bboxes, gt_bboxes = pred_bboxes[idx], gt_bboxes[gt_idx] IndexError: tensors used as indices must be long, byte or bool tensor

### ISSUE THREAD

**Issue by YellenYeason** [ultralytics/ultralytics#3306] opened 2023-06-21 10:51 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

when I run "
from ultralytics import RTDETR
model = RTDETR("ultralytics/models/rt-detr/rtdetr-l.yaml")
model.info
model.train(data = "ultralytics/datasets/VOC.yaml")"
I got a bug "
pred_bboxes, gt_bboxes = pred_bboxes[idx], gt_bboxes[gt_idx] IndexError: tensors used as indices must be long, byte or bool tensor"

### Environment

yolo  Ultralytic YOLOV8-main
OS: WSL2-ubuntu 20.04
python : 3.9.0

### Additional

I change these codes in loss.py:     
def _get_index(self, match_indices):
        batch_idx = torch.cat([torch.full_like(src, i) for i, (src, _) in enumerate(match_indices)])
        src_idx = torch.cat([src for (src, _) in match_indices])
        dst_idx = torch.cat([dst for (_, dst) in match_indices])
        return (batch_idx.type(torch.long), src_idx.type(torch.long)), dst_idx.type(torch.long)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment] 2023-06-21 13:59
@YellenYeason 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. RTDETR training on VOC works correctly, I'm unable to reproduce any problems using your code.

<img width="1193" alt="Screenshot 2023-06-21 at 15 58 17" src="https://github.com/ultralytics/ultralytics/assets/26833433/42e02d83-56a1-4edb-990c-d108f868ccdf">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by luxiaohao** [comment] 2023-06-25 01:25
@YellenYeason Hello, I have the same problem, may I ask you to deal with it?

**Comment by glenn-jocher** [comment] 2023-06-25 05:50
@luxiaohao Hello! I see that you're experiencing a problem with YOLOv8. I would be glad to assist you. Could you please provide some more information about the issue you're facing? Specifically, it would be helpful to know the exact steps you took before encountering the problem, any error messages you received, and any relevant code that you could share. With this information, I'll do my best to help you resolve the issue. Thank you!

**Comment by yinhaoxiao** [comment] 2023-06-25 06:43
I had the same problem before until I upgrad pytorch to 2.0.1+cu117

**Comment by luxiaohao** [comment] 2023-06-25 07:31
@glenn-jocher 
My environment is：
Ultralytics YOLOv8.0.122  Python-3.8.16 torch-1.10.2+cu113 CUDA:0 (NVIDIA GeForce GTX 1060 6GB, 6144MiB)

I haven't changed anything else special in this version.

It made a mistake here:
..\ultralytics\vit\utils\loss.py", line 201, in _get_loss
    pred_bboxes, gt_bboxes = pred_bboxes[idx], gt_bboxes[gt_idx]
IndexError: tensors used as indices must be long, byte or bool tensors

**Comment by luxiaohao** [comment] 2023-06-25 07:40
@yinhaoxiao I can try later, thanks.

**Comment by glenn-jocher** [comment] 2023-06-25 10:30
@yinhaoxiao Thanks for sharing your environment details. It appears that you are encountering an `IndexError` in the `loss.py` file of the RTDETR model.

This error typically occurs when tensors are used as indices and they need to be of type `long`, `byte`, or `bool`. One potential solution is to ensure that the tensors used as indices are cast to the appropriate type before indexing.

In this specific case, the error is happening in line 201 of the `loss.py` file, where `pred_bboxes` and `gt_bboxes` are being indexed using the `idx` and `gt_idx` tensors, respectively. To fix the issue, you can try casting `idx` and `gt_idx` to `long` tensors before using them for indexing.

You can do this by modifying the code to explicitly cast `idx` and `gt_idx` to `idx.long()` and `gt_idx.long()`, respectively, in the line where the indexing is performed.

Once you make this change, it should resolve the `IndexError` and allow the code to run without issues.

Please let me know if you have any further questions or if there's anything else I can assist you with!

**Comment by wiekern** [comment] 2023-06-25 11:23
actually idx is a tuple like below
idx: (tensor([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3], dtype=torch.int32), tensor([  0,   1,   2,   3,   2,  17,  33,  38, 144, 161, 262,   0,   1,   2,   3,   4,   0, 181, 236, 266], dtype=torch.int32)), so applying .long() on it is incorrect.

**Comment by luxiaohao** [comment] 2023-06-25 11:32
@wiekern @glenn-jocher He is correct.
This can cause a problem which that “AttributeError: 'tuple' object has no attribute 'long'”.

**Comment by luxiaohao** [comment] 2023-06-25 12:01
I try this way:Added 2 lines in front of line 201 to convert the type, and it worked.

idx = (idx[0].long(), idx[1].long())
gt_idx = gt_idx.long()

I don't know if it's okay, if it affects anything else

**Comment by luxiaohao** [comment] 2023-06-25 12:02
@wiekern @glenn-jocher 
I try this way:Added 2 lines in front of line 201 to convert the type, and it worked.

idx = (idx[0].long(), idx[1].long())
gt_idx = gt_idx.long()

I don't know if it's okay, if it affects anything else

**Comment by glenn-jocher** [comment] 2023-06-25 12:17
@luxiaohao Thank you for sharing your approach! I'm glad to hear that it resolved the issue for you. 

Converting `idx` and `gt_idx` to the appropriate data type before indexing is a valid solution. By using the `long()` method on each element of the tuple, you ensure that the tensors are of the correct type for indexing.

Regarding your concern about potential side effects, it's always a good idea to test the modified code thoroughly to ensure that it doesn't introduce any unintended consequences. Keep an eye on any changes in behavior or performance that may arise as a result.

If the modified code is producing the expected results and does not have any negative impact on other parts of the codebase, it should be safe to use in your application.

Please let me know if you have any further questions or if there's anything else I can assist you with!

**Comment by luxiaohao** [comment] 2023-06-26 00:16
@glenn-jocher I have tried to train some models and I haven't found any other problems yet.
Thank you for your immediate help in dealing with the problem.

**Comment by luxiaohao** [comment] 2023-06-26 00:39
@glenn-jocher A new question:
When I try to train "rtdetr" model and open AMP training at the same time,the program is stuck at AMP. 
Close AMP and train,it's ok.

**Comment by glenn-jocher** [comment] 2023-06-26 10:07
@luxiaohao thank you for the update and taking the time to share your feedback! I'm glad to hear that the solution resolves your issue and that you are not facing any other problems at the moment. Please don't hesitate to reach out if you need assistance with YOLOv8 in the future.

**Comment by FourierMourier** [comment] 2023-06-27 09:15
Hi, I got the same error (torch1.13,  ultralytics-8.0.123, rtx3060) but was able to fix it with the following code:

ultralytics/vit/utils/loss.py lines 165-169:
<code>
    def _get_index(self, match_indices: list[tuple[torch.Tensor]]):
        batch_idx: torch.Tensor = torch.cat([torch.full_like(src, i) for i, (src, _) in enumerate(match_indices)]).long()
        src_idx = torch.cat([src.long() for (src, _) in match_indices])
        dst_idx = torch.cat([dst.long() for (_, dst) in match_indices])
        return (batch_idx, src_idx), dst_idx
</code>

**Comment by glenn-jocher** [comment] 2023-06-28 00:29
@FourierMourier hi there! Thank you for reaching out to us regarding this issue. We are sorry to hear that you encountered an error while running YOLOv8. 

Based on what you provided, it appears that you are experiencing an issue with the `loss.py` file in the `vit/utils` directory. Specifically, indexing operations may be encountering errors related to tensor type. 

One potential solution that you can try involves modifying the `loss.py` file as follows:

```
def _get_index(self, match_indices: list[tuple[torch.Tensor]]):
    batch_idx: torch.Tensor = torch.cat([torch.full_like(src, i) for i, (src, _) in enumerate(match_indices)]).long()
    src_idx = torch.cat([src.long() for (src, _) in match_indices])
    dst_idx = torch.cat([dst.long() for (_, dst) in match_indices])
    return (batch_idx, src_idx), dst_idx
```

By updating the last two lines of the `_get_index()` function to explicitly cast `src` and `dst` indices to the `long()` data type before concatenating, you may resolve the error observed.

I hope this helps! Please let me know if you have any further questions or concerns. Thank you for using YOLOv8.

**Comment by FourierMourier** [comment] 2023-06-28 10:15
@glenn-jocher :)

**Comment by glenn-jocher** [comment] 2023-06-28 22:49
@FourierMourier hello,

Thank you for reaching out! We appreciate your interest in YOLOv8. However, it seems that you mentioned YOLOv5 in your issue. Just to clarify, we maintain the Ultralytics YOLOv8 repository and provide support for that particular version. If you have any questions or concerns specifically related to YOLOv8, we'll be more than happy to help.

Please let us know how we can assist you with YOLOv8. We value your feedback and are here to support you.

Best regards,
Glenn Jocher

**Comment by glenn-jocher** [comment] 2023-07-03 18:49
@FourierMourier @YellenYeason @Laughing-q I've opened up PR #3508 to resolve this issue. Can you please test this PR and see if this fixes the problem?

**Comment by FourierMourier** [comment] 2023-07-03 22:45
@glenn-jocher Hi, just tested it locally using the same data on the same machine - works fine without any errors for several epochs, great work!

**Comment by Laughing-q** [comment] 2023-07-04 06:12
@FourierMourier @glenn-jocher this happens only when torch version is 1.x, and yeah the PR works!

**Comment by FourierMourier** [comment] 2023-07-04 07:31
@Laughing-q @glenn-jocher Indeed. It seems I checked PR with torch 2.0+ where everything works as expected but then tried to train with pytorch 1.13 and got "IndexError: tensors used as indices must be long, byte or bool tensors" error message

**Closed** 2023-07-04 08:08 UTC
Labels: bug, fixed

**Comment by Laughing-q** [comment] 2023-07-04 08:12
@FourierMourier Don't worry, I also updated some places in that PR and tested with torch-1.13 and it works successfully. :)
