### ISSUE TITLE
Negative points seems not to be used in any SAM model

### ISSUE THREAD

**Issue by RuellePaul** [ultralytics/ultralytics#16705] opened 2024-10-05 09:33 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Negative points seems to be considered as positive point in SAM model.

Here is an example with 1 positive point and 2 negative

points: [[     704.56      1315.8] [     848.99      1331.6]  [      912.4      1271.7]]
labels: [          1           0           0]

![Capture d’écran 2024-10-05 à 11 31 18](https://github.com/user-attachments/assets/d154237b-5e14-4948-b5e5-407b72a6cee3)

I tried all sam models in this list, and the issue is present for all of them :  

### Environment

Ultralytics 8.3.4 🚀 Python-3.8.0 torch-2.2.2 CPU (Apple M3 Pro)
Setup complete ✅ (11 CPUs, 36.0 GB RAM, 176.1/926.4 GB disk)
None

### Minimal Reproducible Example

from ultralytics import SAM

model = SAM("sam2_t.pt")
results = model("./baloons.jpeg", points=[[150, 150], [100, 100]], labels=[1, 0])

### Additional

I saw a recent fix was released in 8.3.4:

https://github.com/ultralytics/ultralytics/pull/16642

but it does not seems to work

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment] 2024-10-05 09:34
👋 Hello @RuellePaul, thank you for bringing this to our attention 🚀! This is an automated response to let you know that an Ultralytics engineer will be with you soon.

For now, we recommend checking out our [Docs](https://docs.ultralytics.com) where you can find various [SAM Model](https://docs.ultralytics.com/models/sam) usage examples and troubleshoot common issues.

Since you've reported a 🐛 bug related to negative points, please help us by providing a more detailed [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) if possible. This aids in effectively debugging the issue.

To ensure you're using the latest versions with all fixes, upgrade to the latest `ultralytics` package:

```bash
pip install -U ultralytics
```

For discussions and community support, feel free to join our channels:
- Real-time chat on [Discord](https://ultralytics.com/discord) 🎧
- In-depth discussions on [Discourse](https://community.ultralytics.com)
- Sharing insights on our [Subreddit](https://reddit.com/r/ultralytics)

## Verified Environments

Run YOLO in any of these environments to verify dependencies and correct installations:

- **Notebooks**: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud VM**: [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon AMI**: [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker**: [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are passing. These tests ensure the reliability of YOLO on various platforms.

Thank you again, and stay tuned for further assistance! 😊

**Comment by Y-T-G** [comment] 2024-10-05 11:46
This has been fixed in https://github.com/ultralytics/ultralytics/pull/16642

You can try updating to the latest version

**Comment by Y-T-G** [comment] 2024-10-05 11:50
If you're talking about negative points for the same object, then that's an issue that will be fixed by https://github.com/ultralytics/ultralytics/pull/16643

You can upvote the PR.

**Comment by RuellePaul** [comment] 2024-10-05 11:54
I'm already on 8.3.4, which incluses the fix :/

Ill tried on 8.3.5 but I don't think it will resolve the issue

**Comment by Y-T-G** [comment] 2024-10-05 12:00
> I'm already on 8.3.4, which incluses the fix :/
> 
> Ill tried on 8.3.5 but I don't think it will resolve the issue

Yes. I think it's a different issue because `ultralytics` currently doesn't support multiple points per object. It should be fixed in the linked PR.

**Comment by RuellePaul** [comment] 2024-10-05 13:19
Awesome ! I'll try your branch [Y-T-G:sam_multipoint](https://github.com/Y-T-G/ultralytics/tree/sam_multipoint) on my app to see if it is working.

Thank you for quick reply

**Comment by glenn-jocher** [comment] 2024-10-06 01:16
You're welcome! Let us know how it goes or if you have any further questions.

**Comment by glenn-jocher** [comment] 2024-10-13 15:20
Great news 😃! Your original issue may now be resolved ✅ in PR #16643. 

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Closed** 2024-10-13 15:20 UTC
Labels: bug, fixed, detect
