### ISSUE TITLE
Having issues with validation cli command - for RT-DETR - returning metrics as 0

### ISSUE THREAD

**Issue by HaoLin97** [ultralytics/ultralytics#5231] opened 2023-10-04 15:02 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train, Val

### Bug

Hi @glenn-jocher , 
I am getting the same issue as (https://github.com/ultralytics/ultralytics/issues/4504). Whereby using the yolo val command through cli returns a 0 for all metrics and when I view the images from the validation, it shows as numbers instead of designated classes. I tried using CPU and using the python script but both resulted in the result of 0. I've attached screenshots below. I've also tried using the command yolo benchmark but that one just errored out - perhaps benchmark command does not support RT-DETR yet? What I am trying to do is to validate the rt-detr model that I retrained on 9 classes, the validation dataset is the same 9 classes. Any insight on what I should do to achieve this?

E.g. What the preds.jpg is showing
![image](https://github.com/ultralytics/ultralytics/assets/33756611/2109f684-41db-4abc-bee9-0ddb4331b94b)
vs what it should be(labels.jpg)
![image](https://github.com/ultralytics/ultralytics/assets/33756611/ee7a4848-f08f-4d45-8892-5bac17b6f40e)

I did get good results from the training output so the model seems to be trained correctly and the formatting of the train and validation yamls are the same.

Train results.jpg:
![image](https://github.com/ultralytics/ultralytics/assets/33756611/c71151fa-fe18-4d79-991e-59400238f536)

E.g. train_pred.jpg
![image](https://github.com/ultralytics/ultralytics/assets/33756611/a47cbc64-7ee5-4cd1-a83b-37c4c6f6b49f)

train_label.jpg
![image](https://github.com/ultralytics/ultralytics/assets/33756611/c183f305-eae5-4932-adfe-1fe43c235e7d)

### Environment

yolo checks

Ultralytics YOLOv8.0.190 🚀 Python-3.10.9 torch-2.0.1+cu117 CUDA:0 (Tesla T4, 14927MiB)

Setup complete ✅ (128 CPUs, 503.5 GB RAM, 585.0/2932.9 GB disk)

OS                  Linux-5.15.0-82-generic-x86_64-with-glibc2.35

Environment         Linux

Python              3.10.9

Install             pip

RAM                 503.46 GB

CPU                 AMD EPYC 7542 32-Core Processor

CUDA                11.7

matplotlib          ✅ 3.7.0>=3.3.0

numpy               ✅ 1.26.0>=1.22.2

opencv-python       ✅ 4.8.1.78>=4.6.0

pillow              ✅ 9.5.0>=7.1.2

pyyaml              ✅ 6.0>=5.3.1

requests            ✅ 2.28.1>=2.23.0

scipy               ✅ 1.10.0>=1.4.1

torch               ✅ 2.0.1>=1.8.0

torchvision         ✅ 0.15.2>=0.9.0

tqdm                ✅ 4.64.1>=4.64.0

pandas              ✅ 1.5.3>=1.1.4

seaborn             ✅ 0.12.2>=0.11.0

psutil              ✅ 5.9.0

py-cpuinfo          ✅ 9.0.0

thop                ✅ 0.1.1-2209072238>=0.1.1

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment] 2023-10-04 19:31
@HaoLin97 i'm sorry to hear about the issues you're facing. This seems to be a problem with interpreting the labels. 

Looking at your description and screenshots it appears there's a mismatch in the displayed classes and their corresponding labels during validation. The issue could likely lie with the labeling or class mapping. This suggests that the available class-names list might not be correctly referred or possibly not updated in the validation script, hence it shows numbers instead of the actual class names.

As for your results returning 0 for all metrics, it might be a problem with your validation dataset or the format of it, since your training seems to work fine as per the training images you showed. Please ensure that your validation dataset is correctly labeled, in the right format, and registered correctly in your validation YAML.

As for the benchmark command, I believe the RT-DETR model should be compatible. You might want to double-check your command syntax and the parameters you are using. 

I hope this brings you one step closer to resolving your problem!

**Comment by HaoLin97** [comment] 2023-10-05 13:47
Hi @glenn-jocher,

Thank you for the prompt reply.

I have checked that the classes are the same in the training and validation, I have attached screenshots of the yaml files below:

Training: 
![image](https://github.com/ultralytics/ultralytics/assets/33756611/e76daa14-e245-4c54-8ad2-6459d4fb99c3)

Validation: 
![image](https://github.com/ultralytics/ultralytics/assets/33756611/0c97faf0-e3f5-4e4f-8abd-3def0e32197e)

I've also tried to validate through the python script using the CPU and GPU and neither worked.

![image](https://github.com/ultralytics/ultralytics/assets/33756611/bc86f416-dc56-4ebb-a921-b8d870056329)

But I've also noticed that when using the GPU to validate there is a NMS timeout. Would this be related to the class issue?
![image](https://github.com/ultralytics/ultralytics/assets/33756611/fe1bbfab-71fb-4289-a9a7-b988fa2b625e)

**Comment by glenn-jocher** [comment] 2023-10-06 00:31
Hello @HaoLin97,

Thank you for including those screenshots. They are really helpful in understanding the scope of your issue.

From the validation dataset YAML file, it does appear that the classes are appropriately assigned. You might want to double-check if this is the correct path for your classes. Also, if you have used indexing from 0, you must make sure it’s referenced correctly in all your scripts.

When running your validation through Python script, it seems like it's taking longer than expected and is not producing results. The issue could be due to the size of your dataset, the batch size or the configuration of your model. For the GPU-related NMS timeout, it could be related to the processing capacity of your GPU. Sometimes, a large number of detections can cause this, especially if your GPU is under high load.

As your training seems to be working correctly, this suggests the model is constructed and configured properly. So it would relatively be more of managing and optimizing the validation data and model execution.

To narrow down the problem with zero validation results, ensure that your images in the validation set are being correctly loaded and pre-processed. The problem could reside in the data loader or data pre-processing if this is not the case.

Again, it wouldn’t be a bad idea to check the entire process: starting from data collection, labeling, splitting of data, YAML configuration, and then model architecture. A lot of times, issues like these are data-related.

I hope these suggestions bring you closer to resolving the issue.

**Comment by HaoLin97** [comment] 2023-10-09 12:32
Hi @glenn-jocher ,

I tried to run the validation script with the validation set that I used for training, but I got 0 as result. I would assume that the validation data that I used during training is correctly configured and labeled since the training was successful. 

As regards the NMS, I get the same notification when the batch size is small - on both occasions, there is unused memory on the GPU.

**Comment by glenn-jocher** [comment] 2023-10-09 20:59
Hi @HaoLin97,

Thank you for providing more information about your problem.

When you receive 0 for all the results during validation, it would typically indicate that the model isn't correctly predicting any objects in your validation dataset. Given that your training process was successful, this indeed seems unusual.

You were correct in assuming that your data is likely labeled and configured correctly, as that should have been validated during training. The problem might therefore lie within the validation phase rather than the dataset itself.

The NMS timeout message, which appears regardless of batch size and without fully utilising the GPU, might suggest the bounding boxes generated during inference are too numerous for the non-max suppression process to handle within a reasonable timeframe.

You may want to look into the following:

1. Model configuration: confirm that the model used for validation is the true trained model from the previous step.

2. Threshold values: Look at your confidence threshold value. A lower threshold could be causing an unnecessarily large number of detections, leading to the NMS timeout.

3. Data Loading for Validation: Even though the labels are correct, ensure the validation data loader correctly processes your validation images and annotations similarly to the training phase.

I hope these pointers steer you towards the root cause. Don't hesitate to provide any updates or additional queries you may have for better assistance.

**Comment by HaoLin97** [comment] 2023-10-10 12:16
Hi @glenn-jocher ,

1. I have confirmed that the model I used for validation is one from training, I used the last.pt. 

2. I have increased the threshold and confidence but with no resulting change. 
![image](https://github.com/ultralytics/ultralytics/assets/33756611/84d954e8-b9d2-47b8-8335-a8195c5e1c79)

3. I'm using the default dataloader from ultralytics.

Would it be possible to use the freeze mechanism to "train" the model but not update the parameters, such that I'm using the yolo train code as a validation work around? Or any work around that would allow me to produce metrics of model performance on a validation dataset would be greatly appreciated.

**Comment by glenn-jocher** [comment] 2023-10-10 22:59
Hi @HaoLin97,

Thank you for your continued efforts in troubleshooting this issue.

1. It's good that you have confirmed the use of the correct model for validation. If there's any discrepancy in loading the model's state during validation, it might lead to these kinds of issues.

2. The confidence threshold and IoU values you have adjusted seem reasonable. These values shouldn't cause excessive detections that the NMS process can't handle.

3. As for the data loader, even though you're using the default one from Ultralytics, it's worth checking if all data augmentation and normalization steps match those used during training.

For your question on using the freeze mechanism to produce metrics, while it could work theoretically, it might not be ideal as it's not its intended purpose and could lead to misinterpretations or mistakes.

Instead, I suggest focusing on the validation step to see why it's failing to provide metrics. Double-check the following:

a. Ensure the predictions are being generated in the format expected by the metrics calculation script during validation.
   
b. Verify the mapping between model output and class labels in the validation script. 

A mismatch here may be the root cause of the problem.

I hope this provides guidance to unravel your problem. Keep exploring, and don't hesitate to reach out for more assistance. Good luck!

**Comment by HaoLin97** [comment] 2023-10-16 17:48
Hi @glenn-jocher,

I have found the issue after seeing the issue from https://github.com/ultralytics/ultralytics/issues/4787. It seems like the issue is that yolo val requires the name of the model to contain rtdetr - after I changed the name of the model the validation works. I renamed the file from best.pt to redetr.pt. Although this may not be a bug, it should still be highlighted in the documentation.

All the best on the development and best wishes to the Ultralytics team.

**Closed** 2023-10-16 17:50 UTC
Labels: bug

**Comment by glenn-jocher** [comment] 2023-10-17 02:22
Hi @HaoLin97,

Thank you for taking the time to investigate this and for sharing the solution with us and the rest of the community. We appreciate your diligence!

It's great to hear that changing the name of the model allowed the validation function to work. The software does indeed have specific requirements for the naming convention that we weren't aware was causing any difficulties. So, this information is incredibly valuable.

We're grateful for your suggestion to make this clearer in our documentation. Ensuring that our users have a smooth experience is always our priority, so we will certainly consider updating the documentation to reflect this requirement.

Thank you once again for your kind words and support. We appreciate your contribution to the ongoing development of YOLOv8. Best wishes to you too!

**Comment by chirag-garg9** [comment] 2023-12-27 13:18
I too have the same problem but when i set my device as cpu it works fine but when the device is set to gpu the validation parameters are obtained as 0
I did the above but wasn't able to solve the issue

**Comment by glenn-jocher** [comment] 2023-12-27 15:46
@chirag-garg9 it's insightful that validation works on CPU but yields 0 metrics on GPU. This could hint at a CUDA-related issue. Please try these steps:

1. Verify that you're using compatible versions of PyTorch, CUDA, and the NVIDIA drivers.
2. Ensure that GPU memory isn't being exhausted during validation.
3. If running in a multi-GPU setup, place the model and data on the same GPU device.

If the problem persists, please open a new issue on our GitHub with full details so we can assist you further.
