### ISSUE TITLE
module 'torch' has no attribute 'OutOfMemoryError'

### ISSUE THREAD

**Issue by 165412152** [ultralytics/ultralytics#18433] opened 2024-12-28 16:44 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/38 [00:00<?, ?it/s]/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [245,0,0], thread: [96,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [245,0,0], thread: [97,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [512,0,0], thread: [123,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [512,0,0], thread: [124,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [512,0,0], thread: [125,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [512,0,0], thread: [126,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [512,0,0], thread: [127,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
  0%|          | 0/38 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/autodl-fs/data/PCB/ultralytics/ultralytics/utils/tal.py", line 74, in forward
    return self._forward(pd_scores, pd_bboxes, anc_points, gt_labels, gt_bboxes, mask_gt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/autodl-fs/data/PCB/ultralytics/ultralytics/utils/tal.py", line 102, in _forward
    mask_pos, align_metric, overlaps = self.get_pos_mask(
                                       ^^^^^^^^^^^^^^^^^^
  File "/autodl-fs/data/PCB/ultralytics/ultralytics/utils/tal.py", line 124, in get_pos_mask
    align_metric, overlaps = self.get_box_metrics(pd_scores, pd_bboxes, gt_labels, gt_bboxes, mask_in_gts * mask_gt)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/autodl-fs/data/PCB/ultralytics/ultralytics/utils/tal.py", line 143, in get_box_metrics
    bbox_scores[mask_gt] = pd_scores[ind[0], :, ind[1]][mask_gt]  # b, max_num_obj, h*w
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/autodl-fs/data/PCB/ultralytics/train.py", line 8, in <module>
    model.train(data="PCB.yaml", imgsz=224, batch=16, workers=8, cache=True, epochs=100)  # train the model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/autodl-fs/data/PCB/ultralytics/ultralytics/engine/model.py", line 806, in train
    self.trainer.train()
  File "/autodl-fs/data/PCB/ultralytics/ultralytics/engine/trainer.py", line 207, in train
    self._do_train(world_size)
  File "/autodl-fs/data/PCB/ultralytics/ultralytics/engine/trainer.py", line 380, in _do_train
    self.loss, self.loss_items = self.model(batch)
                                 ^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/autodl-fs/data/PCB/ultralytics/ultralytics/nn/tasks.py", line 111, in forward
    return self.loss(x, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/autodl-fs/data/PCB/ultralytics/ultralytics/nn/tasks.py", line 293, in loss
    return self.criterion(preds, batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/autodl-fs/data/PCB/ultralytics/ultralytics/utils/loss.py", line 234, in __call__
    _, target_bboxes, target_scores, fg_mask, _ = self.assigner(
                                                  ^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/autodl-fs/data/PCB/ultralytics/ultralytics/utils/tal.py", line 75, in forward
    except torch.OutOfMemoryError:
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/torch/__init__.py", line 2003, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'torch' has no attribute 'OutOfMemoryError'


my pip list:
Package                        Version
------------------------------ --------------
absl-py                        2.1.0
anaconda-anon-usage            0.4.4
anyio                          4.4.0
archspec                       0.2.3
argon2-cffi                    23.1.0
argon2-cffi-bindings           21.2.0
arrow                          1.3.0
asttokens                      2.4.1
async-lru                      2.0.4
attrs                          23.2.0
Babel                          2.15.0
beautifulsoup4                 4.12.3
bleach                         6.1.0
boltons                        23.0.0
Brotli                         1.0.9
certifi                        2024.2.2
cffi                           1.16.0
charset-normalizer             2.0.4
comm                           0.2.2
conda                          24.4.0
conda-content-trust            0.2.0
conda-libmamba-solver          24.1.0
conda-package-handling         2.2.0
conda_package_streaming        0.9.0
contourpy                      1.2.1
cryptography                   42.0.5
cycler                         0.12.1
debugpy                        1.8.1
decorator                      5.1.1
defusedxml                     0.7.1
distro                         1.9.0
executing                      2.0.1
fastjsonschema                 2.19.1
filelock                       3.14.0
fonttools                      4.53.0
fqdn                           1.5.1
fsspec                         2024.5.0
grpcio                         1.64.0
h11                            0.14.0
httpcore                       1.0.5
httpx                          0.27.0
idna                           3.7
ipykernel                      6.29.4
ipython                        8.25.0
ipywidgets                     8.1.3
isoduration                    20.11.0
jedi                           0.19.1
Jinja2                         3.1.4
json5                          0.9.25
jsonpatch                      1.33
jsonpointer                    2.1
jsonschema                     4.22.0
jsonschema-specifications      2023.12.1
jupyter_client                 8.6.2
jupyter_core                   5.7.2
jupyter-events                 0.10.0
jupyter-lsp                    2.2.5
jupyter_server                 2.14.1
jupyter_server_terminals       0.5.3
jupyterlab                     4.2.1
jupyterlab-language-pack-zh-CN 4.2.post1
jupyterlab_pygments            0.3.0
jupyterlab_server              2.27.2
jupyterlab_widgets             3.0.11
kiwisolver                     1.4.5
libmambapy                     1.5.8
Markdown                       3.6
MarkupSafe                     2.1.5
matplotlib                     3.9.0
matplotlib-inline              0.1.7
menuinst                       2.0.2
mistune                        3.0.2
mpmath                         1.3.0
nbclient                       0.10.0
nbconvert                      7.16.4
nbformat                       5.10.4
nest-asyncio                   1.6.0
networkx                       3.3
notebook_shim                  0.2.4
numpy                          1.26.4
nvidia-cublas-cu12             12.1.3.1
nvidia-cuda-cupti-cu12         12.1.105
nvidia-cuda-nvrtc-cu12         12.1.105
nvidia-cuda-runtime-cu12       12.1.105
nvidia-cudnn-cu12              8.9.2.26
nvidia-cufft-cu12              11.0.2.54
nvidia-curand-cu12             10.3.2.106
nvidia-cusolver-cu12           11.4.5.107
nvidia-cusparse-cu12           12.1.0.106
nvidia-nccl-cu12               2.20.5
nvidia-nvjitlink-cu12          12.5.40
nvidia-nvtx-cu12               12.1.105
opencv-python                  4.10.0.84
overrides                      7.7.0
packaging                      23.2
pandas                         2.2.3
pandocfilters                  1.5.1
parso                          0.8.4
pexpect                        4.9.0
pillow                         10.3.0
pip                            24.0
platformdirs                   3.10.0
pluggy                         1.0.0
prometheus_client              0.20.0
prompt_toolkit                 3.0.45
protobuf                       5.27.0
psutil                         5.9.8
ptyprocess                     0.7.0
pure-eval                      0.2.2
py-cpuinfo                     9.0.0
pycosat                        0.6.6
pycparser                      2.21
Pygments                       2.18.0
pyparsing                      3.1.2
PySocks                        1.7.1
python-dateutil                2.9.0.post0
python-json-logger             2.0.7
pytz                           2024.2
PyYAML                         6.0.1
pyzmq                          26.0.3
referencing                    0.35.1
requests                       2.31.0
rfc3339-validator              0.1.4
rfc3986-validator              0.1.1
rpds-py                        0.18.1
ruamel.yaml                    0.17.21
scipy                          1.14.1
seaborn                        0.13.2
Send2Trash                     1.8.3
setuptools                     69.5.1
six                            1.16.0
sniffio                        1.3.1
soupsieve                      2.5
stack-data                     0.6.3
supervisor                     4.2.5
sympy                          1.12.1
tensorboard                    2.16.2
tensorboard-data-server        0.7.2
terminado                      0.18.1
tinycss2                       1.3.0
torch                          2.3.0+cu121
torchvision                    0.18.0+cu121
tornado                        6.4
tqdm                           4.66.2
traitlets                      5.14.3
truststore                     0.8.0
types-python-dateutil          2.9.0.20240316
typing_extensions              4.12.1
tzdata                         2024.2
ultralytics                    8.3.55
ultralytics-thop               2.0.13
uri-template                   1.3.0
urllib3                        2.1.0
wcwidth                        0.2.13
webcolors                      1.13
webencodings                   0.5.1
websocket-client               1.8.0
Werkzeug                       3.0.3
wheel                          0.43.0
widgetsnbextension             4.0.11
zstandard                      0.22.0

code:
from ultralytics import YOLO

if __name__ == '__main__':
    # Load a model
    # model = YOLO("yolo11s.yaml")  # build a new model from scratch
    model = YOLO("yolo11s.pt")  # load a pretrained model (recommended for training)
    # Use the model
    model.train(data="PCB.yaml", imgsz=640, batch=16, workers=8, cache=True, epochs=100)  # train the model
    metrics = model.val()  # evaluate model performance on the validation set
    # results = model("ultralytics\\assets\\bus.jpg")  # predict on an image
    path = model.export(format="onnx", opset=13)  # export the model to ONNX format
    
pcb.yaml:

path: /root/autodl-fs/PCB/PCB_DATASET # dataset root dir
train: images/train2017
val: images/val2017 

names:
  0: missing_hole
  1: mouse_bite
  2: open_circuit
  3: short
  4: spur
  5: spurious_copper


### Additional

_No response_

**Comment by UltralyticsAssistant** [comment] 2024-12-28 16:44
👋 Hello @165412152, thank you for your interest in Ultralytics 🚀! We recommend visiting our [Docs](https://docs.ultralytics.com) for detailed guidance and extensive [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples. Many common questions and challenges can often be resolved there.

### 🐛 Bug Report

You seem to have encountered an issue related to `torch` not recognizing the `OutOfMemoryError` attribute. Additionally, the provided logs indicate a CUDA error and device assertion failure during training. To help us address this, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) that includes:
1. Your `yaml` files (e.g., `data.yaml`, `model.yaml`).
2. The code snippet or script you used to trigger the error.
3. Details about your GPU, driver, and CUDA setup.
4. Confirmation that you are using the latest Ultralytics package and supported dependencies (see below for version upgrade instructions).

### Upgrade

Ensure you are using the latest version of the `ultralytics` package, as this might have already resolved your issue. Update everything in a clean Python environment:

```bash
pip install -U ultralytics
```

Verify your setup is compliant with the latest [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml), ensuring you are using **Python>=3.8** and **PyTorch>=1.8**, ideally with the latest CUDA and cuDNN versions.

### Debugging Hints
1. Your logs suggest running with CUDA debugging enabled (`CUDA_LAUNCH_BLOCKING=1`) to help isolate the issue. You can enable it as follows before running your script:
   ```bash
   export CUDA_LAUNCH_BLOCKING=1
   ```
2. Confirm your GPU and its memory are sufficient for your training setup. Consider reducing your `batch` size or `imgsz` if resources are constrained.

### Environments

You can also try YOLO in any of the verified environments below to confirm whether the issue persists:
- **Notebooks** with free GPUs:
  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a>
  <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
  <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Docker Image**: See our [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>.

### Community Support

Join the Ultralytics community for additional help and resources:
- [Discord](https://discord.com/invite/ultralytics) for real-time chat 🎧
- [Discourse](https://community.ultralytics.com) for in-depth discussions 📚
- [Subreddit](https://reddit.com/r/Ultralytics) to engage and share with the community 🤝

---

This is an automated response to help you get started faster 🚀. An Ultralytics engineer will also review your issue shortly. Thank you for your patience and for being part of our community! 😊

**Comment by Y-T-G** [comment] 2024-12-28 16:47
There's an issue with your dataset labels. There's probably a class label that's larger than 5. They should all be between 0-5.

**Comment by Y-T-G** [comment] 2024-12-28 16:48
Duplicate of https://github.com/ultralytics/ultralytics/issues/17660

**Closed by Y-T-G** 2024-12-28 16:48 UTC
Labels: question, dependencies, detect

**Comment by 165412152** [comment] 2024-12-28 16:58
> There's an issue with your dataset labels. There's probably a class label that's larger than 5. They should all be between 0-5.

I looked at that solution carefully, but the categories in my pcb.yaml are indeed 0-5

**Comment by Y-T-G** [comment] 2024-12-28 16:59
Check all your .txt files
