### ISSUE TITLE
Yolo 8  Segment -- invalid generated Image

### ISSUE THREAD

**Issue by Alarmod** [ultralytics/ultralytics#6226] opened 2023-11-09 10:05 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Yolo 8 Segment have bug in predict. 8.0.205 - all OK, 8.0.206 and more new - bug with scaling and last line filling

### Minimal Reproducible Example

model = YOLO("./runs/segment/t2_ishemia/weights/best.pt")
results = model.predict(batch=44, workers=2, source="./datasets/t2_data/ishemia/test/images_big", imgsz=320, save=True, conf=0.25)

205: 
![205](https://github.com/ultralytics/ultralytics/assets/4010688/c3dc600a-62f7-41bd-b90b-b5f04aa8cf7c)

206: 
![206](https://github.com/ultralytics/ultralytics/assets/4010688/04c94d77-f6ca-4d91-96e6-0bf296473e3a)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Alarmod** [comment] 2023-11-09 10:07
Last line diff
![diff_last_line](https://github.com/ultralytics/ultralytics/assets/4010688/73f03717-f2ed-409e-8aab-f1079a8ffbd7)

**Comment by glenn-jocher** [comment] 2023-11-09 12:29
@Alarmod hello,

Thank you for reporting this issue with the segment prediction in YOLOv8 and for providing the comparison between versions 8.0.205 and 8.0.206. From your description, it seems there may have been a regression affecting the scaling and the last line filling in the newer versions.

The images you've provided are quite useful for understanding the problem. The last line difference could be indicative of a padding, scaling, or image processing issue that was introduced in the 8.0.206 update.

We take such issues seriously as they affect the performance and accuracy of the model predictions. As the first step to resolving the bug, our team will attempt to replicate the problem using the information you've provided. Once we have identified the root cause, we will address it as quickly as possible.

Meanwhile, I'd recommend rolling back to version 8.0.205 for the specific segment-related tasks if that version is stable for your current needs. We appreciate your patience and are sorry for any inconvenience this has caused. Please stay tuned for updates on this issue as we work on fixing it.

Your contribution is highly valuable, and we thank you for being proactive in helping us maintain the quality of YOLOv8.

Best regards,
The Ultralytics Team

**Comment by Alarmod** [comment] 2023-12-10 04:36
Bug still exist

**Comment by glenn-jocher** [comment] 2023-12-10 08:01
@Alarmod apologies for the inconvenience, and thank you for the update. We are actively investigating the issue and working towards a resolution. Please continue to monitor the repository for updates. Your understanding is much appreciated. 🛠️👀

**Comment by Alarmod** [comment] 2024-01-11 05:42
:) still actual

**Comment by glenn-jocher** [comment] 2024-01-11 16:50
@Alarmod, the issue is acknowledged and under investigation. Updates will be posted in the repo. Thank you for your patience! 😊🔍

**Comment by glenn-jocher** [comment] 2024-01-25 17:56
@Alarmod thanks for opening a fix PR!

**Closed** 2024-01-26 03:26 UTC
Labels: bug
