### ISSUE TITLE
Nvidia ORIN no GPU on docker 

### ISSUE THREAD

**Issue by pabsan-0** [ultralytics/ultralytics#2025] opened 2023-04-14 11:40 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

No GPU is found using docker image `ultralytics/ultralytics:latest-arm64`.
- `python3 -c 'import torch; print(torch.cuda.is_available())'`: yields False
- `yolo detect`: catches default args then output says using CPU

I've successfully tested these on a different container and the GPU is found [[source](https://forums.developer.nvidia.com/t/nvidia-container-with-gpu/229126/2)]

```
$ sudo docker run -it --rm --runtime nvidia --network host nvcr.io/nvidia/l4t-pytorch:r35.1.0-pth1.12-py3
# python3 -c 'import torch; print(torch.cuda.is_available())'
# cd /usr/local/cuda/samples/1_Utilities/deviceQuery
# make
# ./deviceQuery
```

### Environment

- YOLO: `docker run --rm -it --runtime nvidia ultralytics/ultralytics:latest-arm64`
- OS: Host is Ubuntu 20.04.5 LTS  aarch64, NVIDIA Orin NX developer kit, armv8
- Python: default from docker image (3.10.7)

### Minimal Reproducible Example

```
docker run --rm -it --runtime nvidia ultralytics/ultralytics:latest-arm64

python3 -c 'import torch; print(torch.cuda.is_available())'
yolo detect
```

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by pabsan-0** [comment] 2023-04-14 11:56
Taking a closer look at the Dockerfiles in `docker/` I believe the base layer is the responsible for the GPU capability. The Dockerfile-arm64 does not mention neither the GPU nor CPU keywords and I just assumed it should work out of the box. I'll try swapping the base to make a Dockerfile with GPU for ARM next week. Is it interesting for you to have it PR'd?

**Comment by aurelm95** [comment] 2023-04-14 15:13
@pabsan-0  I guess it is a duplicate of my previous issue: https://github.com/ultralytics/ultralytics/issues/1981

As I commented there, I ended up using the `nvcr.io/nvidia/l4t-pytorch` image and then cloning this repo. I think this could be a starting point.

**Comment by glenn-jocher** [comment] 2023-04-14 23:01
@aurelm95, thank you for letting me know about the potential duplicate issue. I appreciate it. It's great to hear that you were able to find a solution by using the `nvcr.io/nvidia/l4t-pytorch` image and cloning our repository. This is definitely a great starting point. If you have any further questions or concerns, please don't hesitate to let me know.

**Comment by glenn-jocher** [comment] 2023-04-15 11:11
@aurelm95 I've created a PR with a new Dockerfile-jetson file for building YOLOv8 containers for Jetson devices. Could you please review and let me know if it needs any changes. I don't have a Jetson device handy to test myself unfortunately. The PR is https://github.com/ultralytics/ultralytics/pull/2050

**Closed** 2023-04-15 12:08 UTC
Labels: bug, fixed

**Comment by aurelm95** [comment] 2023-04-15 12:21
@glenn-jocher Sure! I will review it on monday and give you feedback.

**Comment by glenn-jocher** [comment] 2023-04-15 18:08
@aurelm95 thank you for your reply. I appreciate your willingness to review the PR on Monday and provide feedback. Our team values contributions to open source projects like YOLOv8 and we believe that collaboration makes our community stronger. If you have any questions or concerns, please don't hesitate to let me know.

**Comment by pabsan-0** [comment] 2023-04-17 07:24
Importing cv2 in a container from the base image yields a different error, but won't work either.

I've researched a bit and want to leave some thoughts regarding Docker for jetson while working on it:
- Base image layer should be decided based on the installed Jetpack version, maybe using an env variable
- Lower Jetpack versions may not reach the ultralytics-required Python version (or other packages), a warning before pulling and running would be nice

**Comment by glenn-jocher** [comment] 2023-04-17 09:58
@pabsan-0 thank you for sharing your thoughts and observations regarding running YOLOv8 on Jetson devices through Docker. Choosing the appropriate base image layer based on the installed Jetpack version seems like a good idea to ensure compatibility. Providing a warning message when lower Jetpack versions cannot meet the required Python version or other package requirements could also be a useful feature. It's important to ensure that users have a smooth experience when working with YOLOv8 on different platforms, and incorporating these considerations could help improve the experience for using YOLOv8 on Jetson devices with Docker.

**Comment by glenn-jocher** [comment] 2023-04-17 18:49
@aurelm95 thank you for letting me know about the PR you submitted to fix the `import cv2` issue and other dependencies issues when running YOLOv8 on Jetson devices through Docker. I appreciate your effort to resolve this issue and your contributions to YOLOv8. It is great to see the community come together to improve the YOLOv8 project and ensure that it provides a smooth experience when used on different platforms.
