### ISSUE TITLE
wandb callback reporting fails if no positive examples in validator

### ISSUE THREAD

**Issue by Jamil** [ultralytics/ultralytics#17543] opened 2024-11-14 23:04 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug

When using the `wandb` callback, the following error occurs if there are no positive examples:
```
Traceback (most recent call last):
  File "pipeline.py", line 97, in <module>
    main()
  File "pipeline.py", line 84, in main
    output_path = train_stage(stage_config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "train_new.py", line 57, in train_stage
    results = model.train(**train_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "site-packages/ultralytics/engine/model.py", line 802, in train
    self.trainer.train()
  File "site-packages/ultralytics/engine/trainer.py", line 207, in train
    self._do_train(world_size)
  File "site-packages/ultralytics/engine/trainer.py", line 477, in _do_train
    self.run_callbacks("on_train_end")
  File "site-packages/ultralytics/engine/trainer.py", line 168, in run_callbacks
    callback(self)
  File "site-packages/ultralytics/utils/callbacks/wb.py", line 141, in on_train_end
    if trainer.args.plots and trainer.validator.metrics.curves and trainer.validator.metrics.curves_results:
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "site-packages/ultralytics/utils/__init__.py", line 221, in __getattr__
    raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")
AttributeError: 'DetMetrics' object has no attribute 'curves_results'. See valid attributes below.
    Utility class for computing detection metrics such as precision, recall, and mean average precision (mAP) of an
    object detection model.
    Args:
        save_dir (Path): A path to the directory where the output plots will be saved. Defaults to current directory.
        plot (bool): A flag that indicates whether to plot precision-recall curves for each class. Defaults to False.
        on_plot (func): An optional callback to pass plots path and data when they are rendered. Defaults to None.
        names (dict of str): A dict of strings that represents the names of the classes. Defaults to an empty tuple.
    Attributes:
        save_dir (Path): A path to the directory where the output plots will be saved.
        plot (bool): A flag that indicates whether to plot the precision-recall curves for each class.
        on_plot (func): An optional callback to pass plots path and data when they are rendered.
        names (dict of str): A dict of strings that represents the names of the classes.
        box (Metric): An instance of the Metric class for storing the results of the detection metrics.
        speed (dict): A dictionary for storing the execution time of different parts of the detection process.
    Methods:
        process(tp, conf, pred_cls, target_cls): Updates the metric results with the latest batch of predictions.
        keys: Returns a list of keys for accessing the computed detection metrics.
        mean_results: Returns a list of mean values for the computed detection metrics.
        class_result(i): Returns a list of values for the computed detection metrics for a specific class.
        maps: Returns a dictionary of mean average precision (mAP) values for different IoU thresholds.
        fitness: Computes the fitness score based on the computed detection metrics.
        ap_class_index: Returns a list of class indices sorted by their average precision (AP) values.
        results_dict: Returns a dictionary that maps detection metric keys to their computed values.
        curves: TODO
        curves_results: TODO
```

### Environment

```
Ultralytics 8.3.30 🚀 Python-3.11.5 torch-2.1.2+cu121 CUDA:0 (NVIDIA GeForce RTX 4090, 24111MiB)
Setup complete ✅ (32 CPUs, 251.5 GB RAM, 6725.0/7096.0 GB disk)

OS                  Linux-6.5.0-45-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.11.5
Install             pip
RAM                 251.52 GB
Disk                6725.0/7096.0 GB
CPU                 AMD Ryzen Threadripper PRO 5955WX 16-Cores
CPU count           32
GPU                 NVIDIA GeForce RTX 4090, 24111MiB
GPU count           3
CUDA                12.1

numpy               ✅ 1.24.3>=1.23.0
matplotlib          ✅ 3.7.2>=3.3.0
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.1>=1.4.1
torch               ✅ 2.1.2>=1.8.0
torchvision         ✅ 0.16.2>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 8.0.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0
numpy               ✅ 1.24.3<2.0.0; sys_platform == "darwin"
torch               ✅ 2.1.2!=2.4.0,>=1.8.0; sys_platform == "win32"
```

### Minimal Reproducible Example

```
import wandb
from ultralytics import YOLO
from wandb.integration.ultralytics import add_wandb_callback

def train_yolo():
    # Initialize wandb
    wandb.init(
        project="yolo-example",
        name="training-run",
        job_type="training"
    )
    
    # Initialize YOLO model
    model = YOLO('yolov8n.yaml')  # or 'yolov8n.pt' for pretrained
    
    # Add wandb callback to log metrics
    add_wandb_callback(model)
    
    # Train the model
    results = model.train(
        data='coco128_negative.yaml',  # path to data config file with negatives
        epochs=3,
        batch=16,
        imgsz=640
    )
    
    # Close wandb run
    wandb.finish()

if __name__ == "__main__":
    train_yolo()
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment] 2024-11-14 23:05
👋 Hello @Jamil, thank you for your interest in Ultralytics 🚀! We recommend a visit to the [Docs](https://docs.ultralytics.com) for new users where you can find many [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples and where many of the most common questions may already be answered.

If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us debug it, though it looks like you've already included a helpful MRE. Thank you! An Ultralytics engineer will review your issue and respond soon.

If this is a custom training ❓ Question, please provide as much information as possible, including dataset image examples and training logs, and verify you are following our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

Join the Ultralytics community where it suits you best. For real-time chat, head to [Discord](https://ultralytics.com/discord) 🎧. Prefer in-depth discussions? Check out [Discourse](https://community.ultralytics.com). Or dive into threads on our [Subreddit](https://reddit.com/r/ultralytics) to share knowledge with the community.

## Upgrade

Upgrade to the latest `ultralytics` package including all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/) to verify your issue is not already resolved in the latest version:

```bash
pip install -U ultralytics
```

## Environments

YOLO may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing. CI tests verify correct operation of all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) on macOS, Windows, and Ubuntu every 24 hours and on every commit. 

Thank you for your patience while we investigate this issue! 😊

**Comment by glenn-jocher** [comment] 2024-11-15 11:51
@Jamil thank you for reporting this issue with the Weights & Biases callback failing when no positive examples are present in validation. This appears to be a known edge case that needs handling. I've created an issue to track this bug and would welcome your PR to add proper error handling when curves_results are not available.

The fix should include a check for the existence of curves_results before attempting to access it in the wandb callback. Feel free to reference our [Contributing Guide](https://docs.ultralytics.com/help/contributing) for PR guidelines and testing requirements.

**Closed** 2024-11-16 19:09 UTC
Labels: bug, devops
