### ISSUE TITLE
YOLOv8 Pose Detection Model fails with MPS (Apple Silicon) backend

### ISSUE THREAD

**Issue by Tathun** [ultralytics/ultralytics#18413] opened 2024-12-26 20:09 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train

### Bug

When training YOLOv8 pose detection model on Apple Silicon using MPS backend, encountering error:

### Environment

- Hardware: M2 MacBook Pro
- OS: macOS
- Python: 3.10
- Ultralytics version: 8.3.55
- PyTorch version: torch-2.5.1 MPS

### Minimal Reproducible Example

- Standard YOLOv8 pose detection setup
- Works correctly with device='cpu'
- Fails with device='mps'
- Using standard YOLO label format (13 values per line)

### Additional

Traceback (most recent call last):
  File "/Users/idom/Projects/me/mtg_yolo_detector/src/train.py", line 89, in <module>
    model, results = train_yolo_corners(
  File "/Users/idom/Projects/me/mtg_yolo_detector/src/train.py", line 68, in train_yolo_corners
    results = model.train(
  File "/Users/idom/miniconda3/envs/mtg-detector/lib/python3.10/site-packages/ultralytics/engine/model.py", line 806, in train
    self.trainer.train()
  File "/Users/idom/miniconda3/envs/mtg-detector/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 207, in train
    self._do_train(world_size)
  File "/Users/idom/miniconda3/envs/mtg-detector/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 388, in _do_train
    self.scaler.scale(self.loss).backward()
  File "/Users/idom/miniconda3/envs/mtg-detector/lib/python3.10/site-packages/torch/_tensor.py", line 581, in backward
    torch.autograd.backward(
  File "/Users/idom/miniconda3/envs/mtg-detector/lib/python3.10/site-packages/torch/autograd/__init__.py", line 347, in backward
    _engine_run_backward(
  File "/Users/idom/miniconda3/envs/mtg-detector/lib/python3.10/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment] 2024-12-26 20:10
👋 Hello @Tathun, thank you for bringing this to our attention and for your interest in Ultralytics 🚀! 

We recommend checking out our [Docs](https://docs.ultralytics.com) for detailed usage guidance and troubleshooting steps. You'll find useful resources such as [Python examples](https://docs.ultralytics.com/usage/python/) and [CLI examples](https://docs.ultralytics.com/usage/cli/) to explore. Many common questions and issues may already be addressed there.

If this is a 🐛 Bug Report (as it appears to be), could you please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) of your error? From the description you provided, it seems you are encountering a runtime issue when training a YOLOv8 pose detection model on an M2 MacBook Pro with the MPS backend. Providing a clear code snippet, as well as specifics about your dataset setup and preprocessing steps, would greatly assist us in reproducing and diagnosing the issue.

For now, we recommend ensuring you are using the latest version of the Ultralytics package since many issues are addressed in recent updates:  
```bash
pip install -U ultralytics
```

We also encourage you to double-check your PyTorch installation and dependencies as detailed in our [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml). If you're using the MPS backend and encounter compatibility issues, it could be related to the PyTorch build.

For real-time support, you can connect with our community on [Discord](https://discord.com/invite/ultralytics) 🎧. For more in-depth discussions, check out [Discourse](https://community.ultralytics.com), or contribute to knowledge sharing on our [Subreddit](https://reddit.com/r/Ultralytics).

## Verified Environments

YOLOv8 has been tested in the following environments, which you might consider using to validate your results:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** or **AWS** instances using deep learning VMs
- **Docker environments**: See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>.

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>  
If this badge is green, it indicates all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are passing for our verified tasks and environments.

This is an automated response to provide initial guidance 😊. An Ultralytics engineer will review and assist you further as soon as possible. Thank you for your patience!

**Comment by Y-T-G** [comment] 2024-12-26 22:39
Duplicate of https://github.com/ultralytics/ultralytics/issues/17168

**Closed** 2024-12-26 22:39 UTC
Labels: pose, devops
