### ISSUE TITLE
Training segmentation objects look different

### ISSUE THREAD

**Issue by rob-safi** [ultralytics/ultralytics#18008] opened 2024-12-04 12:08 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train, Augmentation

### Bug

When I try and run `yolo segment train data=./unity_datasets/config/storage_v1.yaml model=yolo11s-seg.yaml epochs=1 imgsz=1200 mosaic=0.0` on my custom dataset (2 images) the segmentation contour of the objects change. I have exactly one object per image and ploting it before trainnig and during training gives very different objects, example below:
![bales_alu_1207__IMAGE__d6df2b92-55cc-4025-9e09-26807703b775](https://github.com/user-attachments/assets/db0340ec-1f4b-4ab7-a87a-ca064c6ea139)
![bales_alu_1246__IMAGE__6754acc2-d6af-4de9-b763-ce47210816dc](https://github.com/user-attachments/assets/b9e2f5cf-95d2-492c-b160-944914e4a43f)

![train_batch0](https://github.com/user-attachments/assets/ec7796cb-6daa-4965-834d-a33a240eec07)

The corners seemed to be clipped and on the right one masks is missing a section.

### Environment

```
Ultralytics 8.3.20 🚀 Python-3.10.12 torch-2.5.0+cu124 CUDA:0 (NVIDIA GeForce RTX 4060 Laptop GPU, 7933MiB)
Setup complete ✅ (16 CPUs, 30.5 GB RAM, 344.0/364.9 GB disk)

OS                  Linux-6.8.0-49-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             git
RAM                 30.54 GB
Disk                344.0/364.9 GB
CPU                 AMD Ryzen 7 7840HS with Radeon 780M Graphics
CPU count           16
GPU                 NVIDIA GeForce RTX 4060 Laptop GPU, 7933MiB
GPU count           1
CUDA                12.4

numpy               ✅ 1.26.4>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.1>=1.4.1
torch               ✅ 2.5.0>=1.8.0
torchvision         ✅ 0.20.0>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.9>=2.0.0
torch               ✅ 2.5.0!=2.4.0,>=1.8.0; sys_platform == "win32"
```

### Minimal Reproducible Example

Here is an example label that causes this issue (file and image linked below)
```
0 0.999784 0.982501 0.999784 0 0 0 0 0.999712 0.724913 0.999712 0.72859 0.993376 0.730969 0.993376 0.734213 0.994528 0.736808 0.991935 0.739403 0.990495 0.741566 0.990783 0.744593 0.989919 0.745675 0.988767 0.747405 0.982719 0.750865 0.980703 0.75346 0.982431 0.754974 0.982143 0.756704 0.983295 0.759083 0.982719 0.770112 0.985311 0.772059 0.987039 0.772059 0.988479 0.770761 0.988767 0.772491 0.989919 0.772491 0.991935 0.773356 0.993088 0.775303 0.993952 0.77487 0.995104 0.786981 0.99568 0.791522 0.994528 0.795415 0.996832 0.796064 0.999712 0.898789 0.999712 0.893599 0.994816 0.890355 0.993088 0.888625 0.990783 0.887543 0.987039 0.887543 0.984159 0.893166 0.984735 0.897059 0.987615 0.90333 0.987615 0.907223 0.991359 0.91782 0.991647 0.920631 0.993088 0.928633 0.993952 0.931445 0.9928 0.93231 0.991647 0.932742 0.986463 0.93404 0.985023 0.934905 0.985023 0.93577 0.983295 0.937284 0.983295 0.938365 0.985887 0.939446 0.986175 0.942474 0.984447 0.948097 0.983871 0.952422 0.981567 0.95372 0.981567 0.954152 0.982431 0.956315 0.983007 0.958045 0.982143 0.960856 0.982143 0.966912 0.984159 0.970372 0.986463 0.972535 0.986463 0.974913 0.985599 0.977076 0.983583 0.978374 0.978111 0.98032 0.976094 0.985078 0.975806 0.993728 0.978975 0.997405 0.981279 0.999567 0.981567 0.999579 0.982501 0.999784 0.982501
```

[bales_alu_1207__IMAGE__d6df2b92-55cc-4025-9e09-26807703b775.txt](https://github.com/user-attachments/files/18007754/bales_alu_1207__IMAGE__d6df2b92-55cc-4025-9e09-26807703b775.txt)
![bales_alu_1207__IMAGE__d6df2b92-55cc-4025-9e09-26807703b775](https://github.com/user-attachments/assets/fd2580c7-893a-49ed-a011-f04f62daff3b)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment] 2024-12-04 12:09
👋 Hello @rob-safi, thank you for your interest in Ultralytics 🚀! We recommend a visit to the [Docs](https://docs.ultralytics.com) for users where you can find many [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples and where many of the most common questions may already be answered.

If this is a 🐛 Bug Report (as it appears to be), please provide a [minimum reproducible example (MRE)](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us debug it. You've already shared some valuable details and visuals—thank you for being thorough! If possible, please also:

- Confirm that your issue reproduces with the latest `ultralytics` release.
- Clarify if the issue persists with different model settings or data samples.
- Share complete input/output observations, as it will help us pinpoint the issue faster.

To ensure you're running the latest fixes, upgrade to the latest `ultralytics` package, including all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml), in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/):

```bash
pip install -U ultralytics
```

If this is a custom training ❓ Question, please continue providing insights into your dataset, labels, and training process. Including additional examples like your shared labels or analysis of other images in your training pipeline is extremely helpful.

## Train Debugging Suggestions

To address segmentation concerns, ensure you are:
1. Confirming correct label formats for segmentation masks. You may validate your labels with the `yolo data=... val` command to avoid unexpected results.
2. Training with standard or slightly modified models (`yolo11s-seg.yaml` seems compatible, but let us know if there are changes in pretrained weights, if any).
3. Cross-checking visualized intermediate results (e.g., training batch outputs, as you've partly done—this is a great habit).

For further support, you can join the Ultralytics community where it suits you best. For real-time chat, head to [Discord](https://discord.com/invite/ultralytics) 🎧. Prefer in-depth discussions? Check out [Discourse](https://community.ultralytics.com). Or dive into threads on our [Subreddit](https://reddit.com/r/Ultralytics) to share knowledge with the global community.

## Verified Environments

If you need to isolate your issue, YOLO runs seamlessly in verified environments like the following with pre-installed dependencies (including [CUDA](https://developer.nvidia.com/cuda)/[cuDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/), and [PyTorch](https://pytorch.org/)):

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are passing. CI tests validate YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) supported on macOS, Windows, and Ubuntu every 24 hours and on every commit.

This is an automated response to streamline your issue's resolution 🚀. An Ultralytics engineer will review your ticket shortly and provide further assistance! 😊

**Comment by rob-safi** [comment] 2024-12-04 15:04
After a lot of digging it looks like the culprit is `YOLODataset.update_labels_info`, more specifically:
```
segments = np.stack(resample_segments(segments, n=segment_resamples), axis=0)
```


It doesn't do well when we have long straight segments (see bottom corners of the images below, left is before resampling and right after)

![image](https://github.com/user-attachments/assets/6595de8e-f4a1-45c6-8c5e-8d73485705a5)


Here is a code snippet to show the issue:
```
import numpy as np
from ultralytics.utils.ops import resample_segments
import matplotlib.pyplot as plt

data = np.array([[    0.99978,      0.9825],
       [    0.99978,           0],
       [          0,           0],
       [          0,     0.99971],
       [    0.72491,     0.99971],
       [    0.72859,     0.99338],
       [    0.73097,     0.99338],
       [    0.73421,     0.99453],
       [    0.73681,     0.99194],
       [     0.7394,      0.9905],
       [    0.74157,     0.99078],
       [    0.74459,     0.98992],
       [    0.74568,     0.98877],
       [     0.7474,     0.98272],
       [    0.75086,      0.9807],
       [    0.75346,     0.98243],
       [    0.75497,     0.98214],
       [     0.7567,      0.9833],
       [    0.75908,     0.98272],
       [    0.77011,     0.98531],
       [    0.77206,     0.98704],
       [    0.77206,     0.98848],
       [    0.77076,     0.98877],
       [    0.77249,     0.98992],
       [    0.77249,     0.99194],
       [    0.77336,     0.99309],
       [     0.7753,     0.99395],
       [    0.77487,      0.9951],
       [    0.78698,     0.99568],
       [    0.79152,     0.99453],
       [    0.79541,     0.99683],
       [    0.79606,     0.99971],
       [    0.89879,     0.99971],
       [     0.8936,     0.99482],
       [    0.89035,     0.99309],
       [    0.88863,     0.99078],
       [    0.88754,     0.98704],
       [    0.88754,     0.98416],
       [    0.89317,     0.98474],
       [    0.89706,     0.98761],
       [    0.90333,     0.98761],
       [    0.90722,     0.99136],
       [    0.91782,     0.99165],
       [    0.92063,     0.99309],
       [    0.92863,     0.99395],
       [    0.93145,      0.9928],
       [    0.93231,     0.99165],
       [    0.93274,     0.98646],
       [    0.93404,     0.98502],
       [     0.9349,     0.98502],
       [    0.93577,      0.9833],
       [    0.93728,      0.9833],
       [    0.93836,     0.98589],
       [    0.93945,     0.98618],
       [    0.94247,     0.98445],
       [     0.9481,     0.98387],
       [    0.95242,     0.98157],
       [    0.95372,     0.98157],
       [    0.95415,     0.98243],
       [    0.95631,     0.98301],
       [    0.95805,     0.98214],
       [    0.96086,     0.98214],
       [    0.96691,     0.98416],
       [    0.97037,     0.98646],
       [    0.97254,     0.98646],
       [    0.97491,      0.9856],
       [    0.97708,     0.98358],
       [    0.97837,     0.97811],
       [    0.98032,     0.97609],
       [    0.98508,     0.97581],
       [    0.99373,     0.97897],
       [     0.9974,     0.98128],
       [    0.99957,     0.98157],
       [    0.99958,      0.9825],
       [    0.99978,      0.9825]], 
                dtype=np.float32
)
data_resampled = resample_segments([data])


fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(10, 5))
axes[0].plot(data[:,0], data[:,1])
axes[1].plot(data_resampled[0][:,0], data_resampled[0][:,1])
fig.tight_layout()
fig.show()
```

What do you think, what is this function needed for?

**Comment by Y-T-G** [comment] 2024-12-04 15:40
Use latest version. It should be fixed by https://github.com/ultralytics/ultralytics/pull/17810

Also these objects are too big for segmentation. Use a small imgsz like 320 or less during training, otherwise the model wouldn't be able to detect it completely.

**Comment by rob-safi** [comment] 2024-12-04 15:48
@Y-T-G you please detail a bit more why these objects would not 

https://github.com/ultralytics/ultralytics/pull/17810 is for obejcts OUTSIDE the iamge, here you can clearly see all the points are in the iamge. The issue is clearly explained above, as well as the function that causes it, please try the snippet above before claiming it will be fixed by a PR that only changes a function not linked to this.

Pleas try this snippet and let me know if you can reproduce:

```
import numpy as np
from ultralytics.utils.ops import resample_segments
import matplotlib.pyplot as plt

data = np.array([[    0.99978,      0.9825],
       [    0.99978,           0],
       [          0,           0],
       [          0,     0.99971],
       [    0.72491,     0.99971],
       [    0.72859,     0.99338],
       [    0.73097,     0.99338],
       [    0.73421,     0.99453],
       [    0.73681,     0.99194],
       [     0.7394,      0.9905],
       [    0.74157,     0.99078],
       [    0.74459,     0.98992],
       [    0.74568,     0.98877],
       [     0.7474,     0.98272],
       [    0.75086,      0.9807],
       [    0.75346,     0.98243],
       [    0.75497,     0.98214],
       [     0.7567,      0.9833],
       [    0.75908,     0.98272],
       [    0.77011,     0.98531],
       [    0.77206,     0.98704],
       [    0.77206,     0.98848],
       [    0.77076,     0.98877],
       [    0.77249,     0.98992],
       [    0.77249,     0.99194],
       [    0.77336,     0.99309],
       [     0.7753,     0.99395],
       [    0.77487,      0.9951],
       [    0.78698,     0.99568],
       [    0.79152,     0.99453],
       [    0.79541,     0.99683],
       [    0.79606,     0.99971],
       [    0.89879,     0.99971],
       [     0.8936,     0.99482],
       [    0.89035,     0.99309],
       [    0.88863,     0.99078],
       [    0.88754,     0.98704],
       [    0.88754,     0.98416],
       [    0.89317,     0.98474],
       [    0.89706,     0.98761],
       [    0.90333,     0.98761],
       [    0.90722,     0.99136],
       [    0.91782,     0.99165],
       [    0.92063,     0.99309],
       [    0.92863,     0.99395],
       [    0.93145,      0.9928],
       [    0.93231,     0.99165],
       [    0.93274,     0.98646],
       [    0.93404,     0.98502],
       [     0.9349,     0.98502],
       [    0.93577,      0.9833],
       [    0.93728,      0.9833],
       [    0.93836,     0.98589],
       [    0.93945,     0.98618],
       [    0.94247,     0.98445],
       [     0.9481,     0.98387],
       [    0.95242,     0.98157],
       [    0.95372,     0.98157],
       [    0.95415,     0.98243],
       [    0.95631,     0.98301],
       [    0.95805,     0.98214],
       [    0.96086,     0.98214],
       [    0.96691,     0.98416],
       [    0.97037,     0.98646],
       [    0.97254,     0.98646],
       [    0.97491,      0.9856],
       [    0.97708,     0.98358],
       [    0.97837,     0.97811],
       [    0.98032,     0.97609],
       [    0.98508,     0.97581],
       [    0.99373,     0.97897],
       [     0.9974,     0.98128],
       [    0.99957,     0.98157],
       [    0.99958,      0.9825],
       [    0.99978,      0.9825]], 
                dtype=np.float32
)
data_resampled = resample_segments([data])


fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(10, 5))
axes[0].plot(data[:,0], data[:,1])
axes[1].plot(data_resampled[0][:,0], data_resampled[0][:,1])
fig.tight_layout()
fig.show()
```

**Comment by Y-T-G** [comment] 2024-12-04 15:52
You can report if it's still present in the latest version. It takes a few seconds to upgrade the package.

**Comment by Y-T-G** [comment] 2024-12-04 16:24
> @Y-T-G it only takes a few seconds to run this snippet,

If you're reporting a bug, it should be reported on the latest version. It may or may not be present in the latest version.

I am not sure why you don't want to update.

> As far as I am aware `8.3.41` is not publicly available yet.

The PR fix was already part of Ultralytics[ 2 versions ago](https://github.com/ultralytics/ultralytics/releases/tag/v8.3.39) which is still 19 releases newer than the version you're reporting on.

> It would also be great to get your valuable insight on why these objects are too big, I do not understand why a smaller iamge size will lead to better detections?

Because anchors have a limited receptive field. It can't see the whole image especially when you use an image size as large 1200x1200. Increasing image size doesn't increase the receptive field of the anchor. It stays the same, so the problem becomes worse the larger image is.

**Comment by Y-T-G** [comment] 2024-12-04 16:26
I can reproduce the issue with `resample_segments` in your snippet and thank you for providing the snippet and debugging it. It's very helpful. I just need to confirm the image you posted in the OP are also the same in the latest version, especially the second one.

**Comment by rob-safi** [comment] 2024-12-04 16:39
btw I solved the issues in a really ugly way locally by replacing `resample_segments` with.

```
def resample_segments_v2(segments, n=1000):
    """
    Inputs a list of segments (n,2) and returns a list of segments (n,2) up-sampled to n points each.

    Args:
        segments (list): a list of (n,2) arrays, where n is the number of points in the segment.
        n (int): number of points to resample the segment to. Defaults to 1000

    Returns:
        segments (list): the resampled segments.
    """
    for i, s in enumerate(segments):
        if (s[0:1, :] != s[:1, :]).all():
            s = np.concatenate((s, s[0:1, :]), axis=0)
        x = np.linspace(0, len(s) - 1, n)

        # Make sure all points are included if possible
        if len(s) <= n:
            point_id = 1
            for j, _x in enumerate(x):
                if _x > _j:
                    x[j]= point_id
                    point_id += 1
                
        xp = np.arange(len(s))
        segments[i] = (
            np.concatenate([np.interp(x, xp, s[:, i]) for i in range(2)], dtype=np.float32).reshape(2, -1).T
        )  # segment xy
    return segments
```

This is ugly and probably needs to reworked to be merged.

The issue was that if you have <1000 points (or 100 for OBB) there was no guarantee your points would be resampled using the previous function, this lead to corners and edges disappearing. The above snippet ensures all the points are included and solves the issue.

Left original, middle `resample_segments` and right `resample_segments_v2`

![image](https://github.com/user-attachments/assets/c1b551cb-c73e-4a59-9281-4c7225344e6a)

**Comment by Y-T-G** [comment] 2024-12-04 17:35
@Laughing-q I guess `resample_segments` needs to interpolate it differently to preserve the original curve.

**Closed** 2024-12-05 21:21 UTC
Labels: bug, segment

**Comment by tongchangD** [comment] 2025-03-21 09:23
you can change code
```
        segment_resamples = 100 if self.use_obb else 1000
```
with 
```
        segment_resamples = 10000  # tcd change
```

in data/dataset.py

**Comment by glenn-jocher** [comment] 2025-03-22 06:41
Thank you for the suggestion! While we appreciate community contributions, the current segment_resamples values are intentionally set to balance performance and precision for general use cases. For specific needs like preserving complex geometries, you can modify this parameter locally in your implementation. If you'd like to propose this as a configurable option for all users, feel free to open a Pull Request with benchmarks showing maintained performance characteristics.
