### ISSUE TITLE
Dockerfile for Jetson does not work

### ISSUE THREAD

**Issue by FSund** [ultralytics/ultralytics#3183] opened 2023-06-15 05:49 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Importing ultralytics in Python in the `ultralytics/ultralytics:latest-jetson`-image returns the error `AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)`.

### Environment

- Docker image `ultralytics/ultralytics:latest-jetson`
- Linux 5.10.65-tegra
- NVIDIA Jetson AGX Orin Developer Kit 

### Minimal Reproducible Example

Oneliner: 

    docker run -it ultralytics/ultralytics:latest-jetson python3 -c 'import ultralytics'

Output:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/src/ultralytics/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.hub import start
  File "/usr/src/ultralytics/ultralytics/hub/__init__.py", line 5, in <module>
    from ultralytics.hub.auth import Auth
  File "/usr/src/ultralytics/ultralytics/hub/auth.py", line 5, in <module>
    from ultralytics.hub.utils import HUB_API_ROOT, PREFIX, request_with_credentials
  File "/usr/src/ultralytics/ultralytics/hub/utils.py", line 14, in <module>
    from ultralytics.yolo.utils import (ENVIRONMENT, LOGGER, ONLINE, RANK, SETTINGS, TESTS_RUNNING, TQDM_BAR_FORMAT,
  File "/usr/src/ultralytics/ultralytics/yolo/__init__.py", line 3, in <module>
    from . import v8
  File "/usr/src/ultralytics/ultralytics/yolo/v8/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8 import classify, detect, pose, segment
  File "/usr/src/ultralytics/ultralytics/yolo/v8/classify/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8.classify.predict import ClassificationPredictor, predict
  File "/usr/src/ultralytics/ultralytics/yolo/v8/classify/predict.py", line 5, in <module>
    from ultralytics.yolo.engine.predictor import BasePredictor
  File "/usr/src/ultralytics/ultralytics/yolo/engine/predictor.py", line 33, in <module>
    import cv2
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.8/dist-packages/cv2/mat_wrapper/__init__.py", line 33, in <module>
    cv._registerMatType(Mat)
AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by aurelm95** [comment] 2023-06-15 13:34
Could you try to use the command `sudo docker run -it --runtime=nvidia ultralytics/ultralytics:latest-jetson` just to confirm the error?

When I PR'ed the Dockerfile for jetson https://github.com/ultralytics/ultralytics/pull/2085, I added the `--no-deps` option in the line `RUN pip install --no-cache -e .` to handle this kind of errors I think.  Maybe that can help!

**Comment by glenn-jocher** [comment] 2023-06-15 23:31
It sounds like you're dealing with a complex issue related to training YOLOv8 on a large dataset in a multi-GPU environment, and this problem manifests itself as an NCCL error. 

NCCL (Nvidia Collective Communications Library) is used to handle communication between GPUs, so an NCCL error generally indicates a problem with this communication. This might be due to a variety of reasons, from network issues to incorrect usage of PyTorch distributed functions.

Let's go through a few steps that may help identify and possibly fix your issue:

1. **Check your setup**: Make sure your environment variables for distributed training are set correctly. This includes `MASTER_PORT`, `MASTER_ADDR`, `WORLD_SIZE`, and `RANK`.

2. **NCCL Debugging**: NCCL provides environmental variables for debugging. You can use `NCCL_DEBUG=INFO` or `NCCL_DEBUG=WARN` to get more detailed error messages. 

3. **Data loading**: Ensure that your data loading is working correctly. If there's a problem with your data or how it's being loaded, it might cause the training to hang. You may want to test your dataloader separately from the rest of your training code to make sure it's working correctly.

4. **Versions**: Check your PyTorch, CUDA, and NCCL versions to ensure they are compatible with each other. Sometimes, version mismatch can lead to unexpected behaviors. Also, updating to the latest versions can potentially fix your problem if it's due to a bug that's been fixed in a more recent version.

5. **Object365 Dataset**: Consider if the issue could be related specifically to the Object365 dataset. You may want to test your setup with a different large dataset to determine if the problem is unique to Object365.

6. **OpenCV conflict**: Your suspicion about the conflict between system package `opencv-python (4.5.0)` and `opencv-python>=4.6.0` from Ultralytics requirements might be valid. You can verify this by creating a fresh environment with only `opencv-python>=4.6.0` installed and testing if the problem still occurs.

Finally, if you're willing to submit a PR, it would be fantastic! Try the steps mentioned above, and hopefully, you can find a solution. However, remember that contributing to an open-source project often involves collaboration, so don't hesitate to ask the Ultralytics team for help or suggestions. They know the YOLOv8 codebase best and can provide invaluable assistance in your debugging efforts.

**Comment by glenn-jocher** [comment] 2023-06-15 23:34
Yes I can reproduce. This is likely due to the opencv installation as you mentioned. 

@aurelm95 we had a no-deps PR before but had to remove that code as the container was failing build with it. Can you try to submit a new PR after verifying that the container will build locally first?

**Comment by FSund** [comment] 2023-06-16 05:17
> Could you try to use the command `sudo docker run -it --runtime=nvidia ultralytics/ultralytics:latest-jetson` just to confirm the error?

It gives the same error

```
❯ sudo docker run -it --runtime=nvidia ultralytics/ultralytics:latest-jetson python3 -c 'import ultralytics'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/src/ultralytics/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.hub import start
  File "/usr/src/ultralytics/ultralytics/hub/__init__.py", line 5, in <module>
    from ultralytics.hub.auth import Auth
  File "/usr/src/ultralytics/ultralytics/hub/auth.py", line 5, in <module>
    from ultralytics.hub.utils import HUB_API_ROOT, PREFIX, request_with_credentials
  File "/usr/src/ultralytics/ultralytics/hub/utils.py", line 14, in <module>
    from ultralytics.yolo.utils import (ENVIRONMENT, LOGGER, ONLINE, RANK, SETTINGS, TESTS_RUNNING, TQDM_BAR_FORMAT,
  File "/usr/src/ultralytics/ultralytics/yolo/__init__.py", line 3, in <module>
    from . import v8
  File "/usr/src/ultralytics/ultralytics/yolo/v8/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8 import classify, detect, pose, segment
  File "/usr/src/ultralytics/ultralytics/yolo/v8/classify/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8.classify.predict import ClassificationPredictor, predict
  File "/usr/src/ultralytics/ultralytics/yolo/v8/classify/predict.py", line 5, in <module>
    from ultralytics.yolo.engine.predictor import BasePredictor
  File "/usr/src/ultralytics/ultralytics/yolo/engine/predictor.py", line 33, in <module>
    import cv2
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.8/dist-packages/cv2/mat_wrapper/__init__.py", line 33, in <module>
    cv._registerMatType(Mat)
AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)
```

I managed to create a working image by commenting out `opencv-python>=4.6.0` from `requirements.txt` and then installing ultralytics via `pip3 install --no-deps ultralytics`.

MWE:

`Dockerfile`
```
# syntax=docker/dockerfile:1

FROM nvcr.io/nvidia/l4t-pytorch:r35.2.1-pth2.0-py3
ENV PIP_ROOT_USER_ACTION=ignore

COPY requirements-jetson.txt .
RUN --mount=type=ssh,required=true \
    pip3 --no-cache-dir install --prefer-binary -r requirements-jetson.txt

RUN pip3 --no-cache-dir install --no-deps "ultralytics==8.0.116"
```

`requirements-jetson.txt`
```
# Ultralytics requirements
# Usage: pip install -r requirements.txt

# Base ----------------------------------------
matplotlib>=3.2.2
#opencv-python>=4.6.0
Pillow>=7.1.2
PyYAML>=5.3.1
requests>=2.23.0
scipy>=1.4.1
torch>=1.7.0
torchvision>=0.8.1
tqdm>=4.64.0

# Logging -------------------------------------
# tensorboard>=2.13.0
# dvclive>=2.11.0
# clearml
# comet

# Plotting ------------------------------------
pandas>=1.1.4
seaborn>=0.11.0

# Export --------------------------------------
# coremltools>=6.0  # CoreML export
# onnx>=1.12.0  # ONNX export
# onnxsim>=0.4.1  # ONNX simplifier
# nvidia-pyindex  # TensorRT export
# nvidia-tensorrt  # TensorRT export
# scikit-learn==0.19.2  # CoreML quantization
# tensorflow>=2.4.1  # TF exports (-cpu, -aarch64, -macos)
# tflite-support
# tensorflowjs>=3.9.0  # TF.js export
# openvino-dev>=2022.3  # OpenVINO export

# Extras --------------------------------------
psutil  # system utilization
# thop>=0.1.1  # FLOPs computation
# ipython  # interactive notebook
# albumentations>=1.0.3
# pycocotools>=2.0.6  # COCO mAP
# roboflow
```

This seems to work, altough I only tested importing ultralytics.

**Comment by FSund** [comment] 2023-06-16 05:49
I have tried an alternate approach where I first run `apt-get remove opencv-python` and then install ultralytics the regular way (which installs opencv-python via pip), but that results in a strange error which leads me to believe that this is not the correct approach

```
sudo docker run -it --runtime=nvidia test-ultralytics python3 -c 'import ultralytics'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.hub import start
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/hub/__init__.py", line 5, in <module>
    from ultralytics.hub.auth import Auth
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/hub/auth.py", line 5, in <module>
    from ultralytics.hub.utils import HUB_API_ROOT, PREFIX, request_with_credentials
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/hub/utils.py", line 14, in <module>
    from ultralytics.yolo.utils import (ENVIRONMENT, LOGGER, ONLINE, RANK, SETTINGS, TESTS_RUNNING, TQDM_BAR_FORMAT,
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/__init__.py", line 3, in <module>
    from . import v8
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/v8/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8 import classify, detect, pose, segment
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/v8/classify/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8.classify.predict import ClassificationPredictor, predict
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/v8/classify/predict.py", line 5, in <module>
    from ultralytics.yolo.engine.predictor import BasePredictor
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/predictor.py", line 33, in <module>
    import cv2
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libpng16-955a5627.so.16.37.0: cannot open shared object file: No such file or directory
```

**Comment by mnc537** [comment] 2023-06-16 09:45
I encountered the same error when attempting to install Ultralytics on a Jetson device. However, I managed to resolve it by creating a custom PyTorch image from scratch. It's a somewhat drastic solution.

To begin, OpenCV is installed in [l4t-jetpack](https://gitlab.com/nvidia/container-images/l4t-jetpack/-/blob/master/Dockerfile.jetpack). I made some modifications by commenting out lines 69 to 85. Then, I built my own l4t-jetpack image without OpenCV, which now serves as the base for my Jetson.

With this setup, you can either compile or use pip-install* to obtain the latest version of OpenCV. To install OpenCV and PyTorch, I referred to these docker files:

- Dockerfile.pytorch: https://github.com/dusty-nv/jetson-containers/blob/master/Dockerfile.pytorch
- Dockerfile.opencv: https://github.com/dusty-nv/jetson-containers/blob/master/Dockerfile.opencv


*If you use ROS, you’ll need to compile OpenCV.

**Comment by glenn-jocher** [comment] 2023-06-16 12:48
Honestly I can't remember why opencv has a minimum of 4.6, maybe the solution is just to reduce requirements.txt to `opencv-python>=4.5.0`. I'll make a PR and see if this passes CI.

**Comment by glenn-jocher** [comment] 2023-06-16 13:16
@FSund @mnc537 @aurelm95 ok I've reduced opencv from 4.6 to 4.5 in requirements.txt in #3208 and merged, new docker images should be pushed in the next 30 minutes with this change.

**Comment by glenn-jocher** [comment] 2023-06-16 13:59
@FSund @mnc537 @aurelm95 PR has not resolved issue. Image shows `opencv-python       4.7.0.72`
 installed and same circular import issue.

**Comment by glenn-jocher** [comment] 2023-06-16 13:59
If anyone has any ideas please submit a PR for changes to the Docker Jetson image.

**Comment by FSund** [comment] 2023-06-16 14:03
Part of the issue is that pip does not detect the system installation of opencv-python, so it installs the latest version due to requirements txt. I have a fix locally, but it involves a custom requirements without opencv.

**Comment by glenn-jocher** [comment] 2023-06-16 14:05
@FSund thank you for bringing this issue to our attention. We apologize for the inconvenience you are experiencing. 

Regarding the circular import issue with YOLOv8, we have identified that the problem lies with the installation of the latest version of OpenCV through pip, which conflicts with the existing system installation. 

To resolve this, we have made a modification to the requirements.txt file to reduce the minimum OpenCV version from 4.6 to 4.5. This change should prevent the installation of the conflicting version and resolve the circular import issue. 

Please note that the updated Docker images reflecting this change will be pushed shortly. We appreciate your patience and understanding.

**Comment by glenn-jocher** [comment] 2023-06-16 14:12
@FSund I think I found a solution! This line will install everything except opencv-python. I'm going to create a PR to try this solution.
```
pip install -r <(grep -Ev 'opencv-python' requirements.txt)
```

**Comment by glenn-jocher** [comment] 2023-06-16 14:19
I'm building a new Jetson image from the PR now in https://github.com/ultralytics/ultralytics/actions/runs/5290990769

PR is https://github.com/ultralytics/ultralytics/pull/3209

**Closed** 2023-06-16 16:07 UTC
Labels: bug, fixed
