### ISSUE TITLE
YoloV11-cls export to tflite with int8 error

### ISSUE THREAD

**Issue by NazaRik555** [ultralytics/ultralytics#17403] opened 2024-11-07 20:16 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

I'm trying to convert my model with 
'''
model = YOLO("best.pt")
model.export(format = "tflite", int8 = True)
'''
Here's log:
```
Ultralytics 8.3.28 🚀 Python-3.10.12 torch-2.5.0+cu121 CPU (Intel Xeon 2.20GHz)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-11-2fe4f434210d>](https://localhost:8080/#) in <cell line: 1>()
----> 1 model.export(format = "tflite", int8 = True)

3 frames
[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in __getattr__(self, name)
   1929             if name in modules:
   1930                 return modules[name]
-> 1931         raise AttributeError(
   1932             f"'{type(self).__name__}' object has no attribute '{name}'"
   1933         )

AttributeError: 'ClassificationModel' object has no attribute 'end2end'
```

### Environment

Ultralytics 8.3.28 🚀 Python-3.10.12 torch-2.5.0+cu121 CPU (Intel Xeon 2.20GHz)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 42.9/107.7 GB disk)

### Minimal Reproducible Example

'''
model = YOLO("best.pt")
model.export(format = "tflite", int8 = True)
'''

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment] 2024-11-07 20:17
👋 Hello @NazaRik555, thank you for bringing this to our attention 🚀! It seems you are encountering an issue when trying to export your YOLOv11 classification model to TFLite with int8 quantization.

To assist us in resolving this 🐛, please ensure you have provided a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us understand and debug the issue effectively. We've noticed you included your script already—thank you for that!

In the meantime, please make sure your environment is up-to-date. You can upgrade to the latest `ultralytics` package along with all necessary [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml):

```bash
pip install -U ultralytics
```

Also, please verify that your Python environment is **Python>=3.8** and PyTorch is **PyTorch>=1.8** to ensure compatibility.

For community support and further discussion, feel free to join our community on [Discord](https://ultralytics.com/discord) 🎧 or engage in in-depth discussions on [Discourse](https://community.ultralytics.com). You can also explore our [Subreddit](https://reddit.com/r/ultralytics) for more community insights.

One of our Ultralytics engineers will review your issue soon as well. Thank you for offering to submit a PR! Your contribution is valuable to us and the community.

## Upgrade

Make sure to install the latest updates to verify your issue is not already resolved in the latest version:

```bash
pip install -U ultralytics
```

## Environments

YOLO can be run in several verified environments with pre-installed dependencies:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing, ensuring the correct operation of all YOLO modes and tasks across macOS, Windows, and Ubuntu.

Again, thank you for your report, and stay tuned for more updates! 😊

**Comment by Y-T-G** [comment] 2024-11-07 22:40
It's not the full error. Can you post the full error traceback?

**Comment by Y-T-G** [comment] 2024-11-07 22:49
I can't reproduce this with `8.3.28` with both pretrained classification models and custom trained models.

You will have to provide the full error traceback and also the output of `yolo checks` from terminal or running `!yolo checks` in your notebook.

**Comment by NazaRik555** [comment] 2024-11-07 22:49
@Y-T-G 
Yes, sorry

```
Ultralytics 8.3.28 🚀 Python-3.10.12 torch-2.5.0+cu121 CPU (Intel Xeon 2.30GHz)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-5-2fe4f434210d>](https://localhost:8080/#) in <cell line: 1>()
----> 1 model.export(format = "tflite", int8 = True)

3 frames
[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py](https://localhost:8080/#) in export(self, **kwargs)
    732         }  # method defaults
    733         args = {**self.overrides, **custom, **kwargs, "mode": "export"}  # highest priority args on the right
--> 734         return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
    735 
    736     def train(

[/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py](https://localhost:8080/#) in decorate_context(*args, **kwargs)
    114     def decorate_context(*args, **kwargs):
    115         with ctx_factory():
--> 116             return func(*args, **kwargs)
    117 
    118     return decorate_context

[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py](https://localhost:8080/#) in __call__(self, model)
    228             assert self.device.type == "cpu", "optimize=True not compatible with cuda devices, i.e. use device='cpu'"
    229         if self.args.int8 and tflite:
--> 230             assert not model.end2end, "TFLite INT8 export not supported for end2end models, please use half precision."
    231         if edgetpu:
    232             if not LINUX:

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in __getattr__(self, name)
   1929             if name in modules:
   1930                 return modules[name]
-> 1931         raise AttributeError(
   1932             f"'{type(self).__name__}' object has no attribute '{name}'"
   1933         )

AttributeError: 'ClassificationModel' object has no attribute 'end2end'
```

**Comment by Y-T-G** [comment] 2024-11-07 22:54
Actually, this was fixed recently by PR https://github.com/ultralytics/ultralytics/pull/17391

The fix is in the main branch but not in the release yet. It should be fixed in the next release.

**Comment by Y-T-G** [comment] 2024-11-07 22:57
You can try exporting after adding this before your code:

`model.model.end2end = False`

**Closed** 2024-11-14 14:51 UTC
Labels: bug, fixed, classify, exports
