### ISSUE TITLE
pbar only show 5 items except 'Epoch' and 'GPU_mem'

### ISSUE THREAD

**Issue by ZhixiongSun** [ultralytics/ultralytics#6017] opened 2023-10-30 08:17 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hi, I am now usiing Ultralytics YOLOv8.0.161 🚀 Python-3.8.16 torch-1.9.1+cu111 CPU (Intel Xeon Gold 6326 2.90GHz)
and I found in basetrainer you write 
`
                    pbar.set_description(
                        ('%11s' * 2 + '%11.4g' * (2 + loss_len)) %
                        (f'{epoch + 1}/{self.epochs}', mem, *losses, batch['cls'].shape[0], batch['img'].shape[-1]))
`      
but it seems doesn't work in task pose and segment, 
Segment pbar shows as following, seems Size is missing:
    Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
       1/10                 0G        2.413         1.932      14.66      1.587             12   

and Pose shows as following, 
      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
            1/1                0G         3.261         5.765      0.4966       12.11      2.071 

if you need more information of my environment please tell me.

### Environment

Ultralytics YOLOv8.0.161 🚀 Python-3.8.16 torch-1.9.1+cu111 CPU (Intel Xeon Gold 6326 2.90GHz)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment] 2023-10-30 10:33
@ZhixiongSun 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. Console printing for all tasks works correctly and shows the Size column as you can see in the screenshot below from our notebook:
https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb

<img width="2025" alt="Screenshot 2023-10-30 at 11 31 44" src="https://github.com/ultralytics/ultralytics/assets/26833433/01cd473b-0264-404b-ba88-2b0637eeec68">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by ZhixiongSun** [comment] 2023-10-30 10:52
Dear @glenn-jocher , thanks for your quick response. It seems that there are some difference in pycharm console and linux command line console. I ran yolov8 directly in Ubuntu terminal and get same results as you mentioned in the screecshot above. This issue will be closed.

**Closed** 2023-10-30 10:52 UTC
Labels: bug, non-reproducible

**Comment by glenn-jocher** [comment] 2023-10-30 19:48
You're welcome @ZhixiongSun! I'm glad to hear that you've made progress and that the output in the Ubuntu terminal matches the expected results. It seems the differences you observed could be due to the way the PyCharm console handles formatting compared to traditional command line consoles. I'm glad you were able to troubleshoot this issue. Feel free to contact us if you have any more questions or issues. Thanks!
