### ISSUE TITLE
'wanbd' environment variables

### ISSUE THREAD

**Issue by AMX0816** [ultralytics/ultralytics#18332] opened 2024-12-20 12:49 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://github.com/user-attachments/assets/d695339c-418a-4260-985f-537aa874afff)
### **I use kaggle to train my model ,use notebook to code;I find this problem in previous yolov8 issues,but yolov11 failed.**
Changes to your `wandb` environment variables will be ignored because your `wandb' session has already started. For more information
on how to modify vour settings with wandb.inito arguments. please refer to the W&B docs.

**Comment by UltralyticsAssistant** [comment] 2024-12-20 12:50
👋 Hello @AMX0816, thank you for your interest in Ultralytics 🚀! We recommend a visit to the [Docs](https://docs.ultralytics.com) for new users where you can find many [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples and where many of the most common questions may already be answered.

If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us debug it. From your description, it seems related to W&B integration, so ensuring that a detailed setup explanation is included will be valuable for replicating and addressing the issue.

If this is a custom training ❓ Question, please include more details, such as your specific `yolo` commands, environment configurations in Kaggle, and any modifications you made to the default settings. Ensure you're following our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

Join the Ultralytics community where it suits you best. For real-time chat, head to [Discord](https://discord.com/invite/ultralytics) 🎧. Prefer in-depth discussions? Check out [Discourse](https://community.ultralytics.com). Or dive into threads on our [Subreddit](https://reddit.com/r/Ultralytics) to share knowledge with the community.

## Upgrade

Please ensure you're using the latest version of the `ultralytics` package, as this might resolve the issue you're experiencing:

Upgrade all dependencies in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/):

```bash
pip install -U ultralytics
```

## Environments

YOLO can be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing. CI tests verify correct operation of all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) on macOS, Windows, and Ubuntu every 24 hours and on every commit.

---

This is an automated response to ensure you get a prompt reply, but don't worry—a friendly Ultralytics engineer will follow up with additional help soon! 😊

**Comment by Y-T-G** [comment] 2024-12-20 13:08
Can you elaborate on your issue?

What you did and what the issue is?

**Comment by Petros626** [comment] 2024-12-21 13:27
```python
from ultralytics import settings

print(settings)
```
```txt
JSONDict("/home/rlab10/.config/Ultralytics/settings.json"):
{
  "settings_version": "0.0.6",
  "datasets_dir": "/home/rlab10/datasets",
  "weights_dir": "/home/rlab10/ultralytics/weights",
  "runs_dir": "/home/rlab10/ultralytics/runs",
  "uuid": "e9369f04bb10accee4e3dcd4c013419d39402eedc61540f0158125b5aa82cbf9",
  "sync": true,
  "api_key": "",
  "openai_api_key": "",
  "clearml": true,
  "comet": true,
  "dvc": true,
  "hub": true,
  "mlflow": true,
  "neptune": true,
  "raytune": true,
  "tensorboard": true,
  "wandb": false,
  "vscode_msg": true
}
```

after I tried
`settings.update({"wandb": "true"})` the value is saved, but after closing deactivating my conda environment and reactivating it, the parameter `wandb` switched to false again.

**Comment by Y-T-G** [comment] 2024-12-21 13:54
If it requires sudo to edit, then you have wrong permissions on the file.

**Comment by Petros626** [comment] 2024-12-21 14:00
You mean normally after a fresh installation this permissions are given?

**Comment by Y-T-G** [comment] 2024-12-21 14:04
No. The file shouldn't require sudo to edit because ultralytics (or Python packages in general) doesn't require sudo to run. It would only happen if you ran an ultralytics script the first time with sudo, which you shouldn't be doing.

**Comment by Petros626** [comment] 2024-12-21 14:08
I can change the parameter of settings.json without sudo, but to keep the changed value not.All other scripts etc. I didn't run with sudo.

**Comment by Y-T-G** [comment] 2024-12-21 14:10
So after you change it without sudo, does it save?

**Comment by Petros626** [comment] 2024-12-21 14:13
Yes, but after the reacessing the settings the param switched to default value. 😅

**Comment by Y-T-G** [comment] 2024-12-21 14:14
Did you edit with nano?

**Comment by Petros626** [comment] 2024-12-21 14:19
Yes the first time without sudo. It generally works, i was just surprised by the warning

**Comment by Y-T-G** [comment] 2024-12-21 15:29
What's the warning?

**Comment by Petros626** [comment] 2024-12-21 17:08
> What's the warning?

https://github.com/ultralytics/ultralytics/blob/e3c46920e7a5ffed6a49d23daeab3de20f63a5f8/ultralytics/utils/__init__.py#L1229

**Comment by glenn-jocher** [comment] 2024-12-21 17:09
The warning likely comes from the `SettingsManager` validating or resetting the settings file. This can happen if the settings file is modified incorrectly or if the changes don't align with the expected schema. Ensure you update settings using `settings.update()` or `yolo settings` commands to avoid such issues.

**Comment by Y-T-G** [comment] 2024-12-21 17:24
> > What's the warning?
> 
> https://github.com/ultralytics/ultralytics/blob/e3c46920e7a5ffed6a49d23daeab3de20f63a5f8/ultralytics/utils/__init__.py#L1229

This is probably because you're setting it as `"true"` which is a string, when it should be `True`. `settings.update(wandb=True)`

**Comment by Petros626** [comment] 2024-12-21 17:32
@Y-T-G yes I always wrote `true` instead of `True`

**Comment by glenn-jocher** [comment] 2024-12-21 21:38
@AMX0816 @Petros626 you should be able to update your settings in Python using any normal dictionary commands, e.g.:

```python
from ultralytics import settings

settings["wandb"]=False # works
settings.update(wandb=False) # works
settings.update({"wandb": False}) # works
```

**Comment by Petros626** [comment] 2024-12-21 21:44
Thx for me it's solved.

**Comment by UltralyticsAssistant** [comment] 2024-12-22 00:25
Thanks for reporting this issue and helping improve the project! A potential fix for this has been merged in [PR #18337](https://github.com/ultralytics/ultralytics/pull/18337). Here are some of the key changes introduced that may address the problem:

- **Improved Error Handling**: The `update` method for settings now provides clearer error messages for invalid keys or types, potentially resolving settings-related issues.
- **Enhanced Usability**: A new `__setitem__` method has been added to allow direct updates to configuration settings, making it easier to work with.
- **Simplified URL Handling**: The `clean_url` function was refactored to reduce complexity and improve performance, which could address issues tied to URL sanitization.

You can test the latest changes by installing the library from the updated GitHub main branch:

```bash
pip install git+https://github.com/ultralytics/ultralytics.git@main
```

Alternatively, you can wait for the next official release on PyPI if you prefer.

If possible, please test the updated code and let us know if it resolves the issue for you. Your feedback is incredibly valuable to ensure everything is working as expected. Thanks again for your contribution, and feel free to reopen or comment here if the issue persists! 🙏

**Closed** 2024-12-22 00:24 UTC
Labels: question, Notebook

**Comment by Petros626** [comment] 2024-12-30 13:59
Do I have to specifiy twice, where my dataset is? Once in the settings and in the `.yaml`?

```json
JSONDict("/home/rlab10/.config/Ultralytics/settings.json"):
{
  "settings_version": "0.0.6",
  "datasets_dir": "/home/rlab10/ultralytics/ultralytics/cfg/datasets/kitti",
```

`/home/rlab10/ultralytics/ultralytics/cfg/datasets/kitti_bev.yaml`:
```yaml
path: /home/rlab10/ultralytics/ultralytics/cfg/datasets/kitti # dataset root dir
train: images/train/ # train images (relative to 'path') 18560 images (3712 training images extended with data augmentation)
val: images/val/ # val images (relative to 'path') 3769 images
```

**Comment by Y-T-G** [comment] 2024-12-30 14:12
The path in settings is only used when there are no `path:` in the dataset yaml

**Comment by glenn-jocher** [comment] 2024-12-30 15:48
You're welcome! If you have any further questions or need clarification, feel free to ask.
