### ISSUE TITLE
use screenshot sorce error

### ISSUE THREAD

**Issue by bobophp** [ultralytics/ultralytics#4015] opened 2023-07-28 16:48 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

 File "D:\2_yolov8\python_www\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 248, in stream_inference
    im = self.preprocess(im0s)
  File "D:\2_yolov8\python_www\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 123, in preprocess
    im = np.stack(self.pre_transform(im))
  File "D:\2_yolov8\python_www\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 144, in pre_transform
    return [LetterBox(self.imgsz, auto=auto, stride=self.model.stride)(image=x) for x in im]
  File "D:\2_yolov8\python_www\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 144, in <listcomp>
    return [LetterBox(self.imgsz, auto=auto, stride=self.model.stride)(image=x) for x in im]
  File "D:\2_yolov8\python_www\venv\lib\site-packages\ultralytics\yolo\data\augment.py", line 581, in __call__
    img = cv2.resize(img, new_unpad, interpolation=cv2.INTER_LINEAR)
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4065: error: (-215:Assertion failed) inv_scale_x > 0 in function 'cv::resize'

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment] 2023-07-29 02:27
@bobophp hello, thanks for reaching out and providing detailed error logs.

The error message you received seems to originate from OpenCV's resize function. This usually happens when the image passed to the resize function is empty or has zero size. Kindly check your source of images or video frames for any inconsistencies.

The issue could also be due to some discrepancy in your configurations or source files. Perhaps the image size that you defined for the object detection doesn't match with the actual input images, or there are some files in your dataset that are empty or corrupt.

Ensure that all your images are readable and match the defined sizes. Please review your code or dataset and make sure there is no zero-sized or corrupt image passed to this function. I hope this helps! If your issue persists, please do not hesitate to provide further information.

Thank you for being part of the Ultralytics community!

**Comment by glenn-jocher** [comment] 2023-07-29 19:30
We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by glenn-jocher** [comment] 2023-07-29 19:44
@bobophp thanks for the bug report. I'm able to reproduce. I've added a TODO tag to track.

**Comment by glenn-jocher** [comment] 2023-07-29 20:54
@bobophp great news 😃! Your original issue may now be resolved ✅ in PR #4033. This PR is merged to main and should be live in `ultralytics 8.0.145` later this weekend.

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Closed** 2023-07-29 20:53 UTC
Labels: TODO, bug
