### ISSUE TITLE
segment predict error : cuda out of memory

### ISSUE THREAD

**Issue by 1623021453** [ultralytics/ultralytics#14381] opened 2024-07-12 08:05 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

1.when I predict with yolov8x-seg.pt, as the number of test images increases, the memory keeps increasing, and finally cuda out of memory.I can only divide the folder into a few small folders for testing.
2.Then I set stream=True，program Interrupt without any output.

### Environment

Ultralytics YOLOv8.2.54 🚀 Python-3.8.18 torch-2.1.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4080, 16076MiB)
Setup complete ✅ (32 CPUs, 62.5 GB RAM, 267.9/879.1 GB disk)

OS                  Linux-5.4.0-150-generic-x86_64-with-glibc2.17
Environment         Linux
Python              3.8.18
Install             git
RAM                 62.45 GB
CPU                 Intel Xeon Silver 4208 2.10GHz
CUDA                12.1

numpy               ✅ 1.23.5<2.0.0,>=1.23.0
matplotlib          ✅ 3.7.4>=3.3.0
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.1.1>=1.8.0
torchvision         ✅ 0.16.1>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

from ultralytics import YOLO

# Load a pretrained YOLOv8n model
model = YOLO('./models/yolov8x-seg.pt')

# Define path to video file
source = '/media/user/新加卷/zxc_ubuntu/data/bdd100k/images/100k/val_3'

# Run inference on the source
results = model(source,imgsz=640,conf=0.25,iou=0.4,classes=[0,1,2,3,5,7,9,11],save_txt=True)  # generator of Results objects

error:
image 1716/70000 /media/user/新加卷/zxc_ubuntu/data/bdd100k/images/100k/train/049494ac-8dfb2a82.jpg: 384x640 1 person, 8 cars, 1 motorcycle, 5 trucks, 44.3ms
image 1717/70000 /media/user/新加卷/zxc_ubuntu/data/bdd100k/images/100k/train/049494ac-9aa2732a.jpg: 384x640 7 cars, 19.0ms
image 1718/70000 /media/user/新加卷/zxc_ubuntu/data/bdd100k/images/100k/train/049494ac-dfc87990.jpg: 384x640 13 cars, 1 truck, 48.3ms
Traceback (most recent call last):
  File "predict.py", line 28, in <module>
    results = model(source,imgsz=640,conf=0.25,iou=0.4,classes=[0,1,2,3,5,7,9,11],save_txt=True)  # generator of Results objects
  File "/media/user/新加卷/zxc_ubuntu/code/ultralytics/ultralytics/engine/model.py", line 174, in __call__
    return self.predict(source, stream, **kwargs)
  File "/media/user/新加卷/zxc_ubuntu/code/ultralytics/ultralytics/engine/model.py", line 442, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/media/user/新加卷/zxc_ubuntu/code/ultralytics/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/home/user/anaconda3/envs/yolo/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 56, in generator_context
    response = gen.send(request)
  File "/media/user/新加卷/zxc_ubuntu/code/ultralytics/ultralytics/engine/predictor.py", line 254, in stream_inference
    preds = self.inference(im, *args, **kwargs)
  File "/media/user/新加卷/zxc_ubuntu/code/ultralytics/ultralytics/engine/predictor.py", line 142, in inference
    return self.model(im, augment=self.args.augment, visualize=visualize, embed=self.args.embed, *args, **kwargs)
  File "/home/user/anaconda3/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/anaconda3/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/user/新加卷/zxc_ubuntu/code/ultralytics/ultralytics/nn/autobackend.py", line 456, in forward
    y = self.model(im, augment=augment, visualize=visualize, embed=embed)
  File "/home/user/anaconda3/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/anaconda3/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/user/新加卷/zxc_ubuntu/code/ultralytics/ultralytics/nn/tasks.py", line 102, in forward
    return self.predict(x, *args, **kwargs)
  File "/media/user/新加卷/zxc_ubuntu/code/ultralytics/ultralytics/nn/tasks.py", line 120, in predict
    return self._predict_once(x, profile, visualize, embed)
  File "/media/user/新加卷/zxc_ubuntu/code/ultralytics/ultralytics/nn/tasks.py", line 141, in _predict_once
    x = m(x)  # run
  File "/home/user/anaconda3/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/anaconda3/envs/yolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/user/新加卷/zxc_ubuntu/code/ultralytics/ultralytics/nn/modules/block.py", line 240, in forward
    return self.cv2(torch.cat(y, 1))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 24.00 MiB. GPU 0 has a total capacty of 15.70 GiB of which 41.06 MiB is free. Including non-PyTorch memory, this process has 15.24 GiB memory in use. Of the allocated memory 13.09 GiB is allocated by PyTorch, and 156.60 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by 1623021453** [comment] 2024-07-12 08:58
When I set stream=True，program Interrupt without any output.

**Comment by Y-T-G** [comment] 2024-07-12 09:10
> When I set stream=True，program Interrupt without any output.

You have to use it in a loop.

`for i in results: pass`

**Comment by 1623021453** [comment] 2024-07-12 09:24
It works, thank you very much.

**Comment by Skillnoob** [comment] 2024-07-15 18:55
@1623021453 as explained in the docs (which you should read), when passing `stream=True` the predictor returns a generator. A generator is a thing in python on which you have to iterate on for it to in this case begin predicting.
If the problem is resolved you can close this issue.

**Closed** 2024-07-16 01:09 UTC
Labels: bug, fixed
