### ISSUE TITLE
Transformer activation bug.

### ISSUE THREAD

**Issue by saitros** [ultralytics/ultralytics#14874] opened 2024-08-01 09:47 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

![image (4)](https://github.com/user-attachments/assets/e2e6dd8e-2e34-42fc-bbc8-4b64c265dbe4)

AttributeError: 'MLP' object has no attribute 'act'

I don't know why, but it seems that the act declared in the MLP class is not initialized properly.
I don't understand the cause of this, but if you find out why, I would appreciate it if you could let me know.

So I downgraded the version and use it. 8.1.24 (error is on newest version 8.2.70)
In this version, there is no act applied to that part. 
![image (5)](https://github.com/user-attachments/assets/e978e866-9db3-4d36-9c5a-57ac946150aa)

### Environment

Python 3.10.12, torch 2.4.0+cu121, Ubuntu 22.04.3 LTS, Disk RAM is free enough. ultralytics==8.2.70

### Minimal Reproducible Example

detector = RTDETR('redetr-x.pt)

### Additional

Here is error log.

```
  File "/home/work/.local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 173, in __call__
    return self.predict(source, stream, **kwargs)
  File "/home/work/.local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 563, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/work/.local/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/home/work/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 36, in generator_context
    response = gen.send(None)
  File "/home/work/.local/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 234, in stream_inference
    self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
  File "/home/work/.local/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 639, in warmup
    self.forward(im)  # warmup
  File "/home/work/.local/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 456, in forward
    y = self.model(im, augment=augment, visualize=visualize, embed=embed)
  File "/home/work/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/work/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/work/.local/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 102, in forward
    return self.predict(x, *args, **kwargs)
  File "/home/work/.local/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 120, in predict
    return self._predict_once(x, profile, visualize, embed)
  File "/home/work/.local/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 141, in _predict_once
    x = m(x)  # run
  File "/home/work/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/work/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/work/.local/lib/python3.10/site-packages/ultralytics/nn/modules/head.py", line 446, in forward
    embed, refer_bbox, enc_bboxes, enc_scores = self._get_decoder_input(feats, shapes, dn_embed, dn_bbox)
  File "/home/work/.local/lib/python3.10/site-packages/ultralytics/nn/modules/head.py", line 525, in _get_decoder_input
    refer_bbox = self.enc_bbox_head(top_k_features) + top_k_anchors
  File "/home/work/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/work/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/work/.local/lib/python3.10/site-packages/ultralytics/nn/modules/transformer.py", line 189, in forward
    x = self.act(layer(x)) if i < self.num_layers - 1 else layer(x)
  File "/home/work/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'MLP' object has no attribute 'act'
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment] 2024-08-01 10:43
@saitros I'm not able to reproduce the issue within `8.2.70`.
![pic-240801-1842-27](https://github.com/user-attachments/assets/8d58f51d-ff70-4b40-94ef-1928a7f9a09a)

**Comment by felipetobars** [comment] 2024-08-01 18:36
@saitros I'm experiencing the same issue when installing with pip ultralytics, using the RT-DETR model. Last weekend, I did the exact same installation, and I didn't have any problems. Did you figure out how to solve the issue?

**Comment by moyu026** [comment] 2024-08-02 03:17
I have same issue and I just run example [ultralytics](https://docs.ultralytics.com/models/rtdetr/#pre-trained-models) provide:

from ultralytics import RTDETR

# Load a COCO-pretrained RT-DETR-l model
model = RTDETR("rtdetr-l.pt")

# Display model information (optional)
model.info()

# Train the model on the COCO8 example dataset for 100 epochs
# results = model.train(data="coco8.yaml", epochs=100, imgsz=640)

# Run inference with the RT-DETR-l model on the 'bus.jpg' image
results = model("path/to/bus.jpg")

**Comment by Laughing-q** [comment] 2024-08-02 05:42
@saitros @felipetobars @moyu026 Hey guys thanks for reporting! I'm able to reproduce the issue now with:
```python
from ultralytics import RTDETR

model = RTDETR("rtdetr-x.pt")
model.predict()
```
There's some updates about the MLP module recently we made for the SAM integration. And we didn't notice it broke the RTDETR inference pipeline. The issue should be fixed by https://github.com/ultralytics/ultralytics/pull/14901.
BTW a friendly reminder, for bug reporting please come with a `Minimal Reproducible Example` which would be super helpful for us to locate the issue and fix it. Thanks!

**Closed** 2024-08-03 18:03 UTC
Labels: bug, fixed, detect
