### ISSUE TITLE
YOLOv10 export: Setting simplify=True raise exception

### ISSUE THREAD

**Issue by hmasum52** [ultralytics/ultralytics#13868] opened 2024-06-21 19:16 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

![image](https://github.com/ultralytics/ultralytics/assets/55390870/44ee712c-ec56-4199-a8af-5f52c15869fd)

### With simplify enabled true

![image](https://github.com/ultralytics/ultralytics/assets/55390870/22b550a7-0b7c-4e63-816b-49812e09d93f)

### Environment

Kaggle
Ultralytics YOLOv8.2.38 🚀 Python-3.10.13 torch-2.1.2 CUDA:0 (Tesla P100-PCIE-16GB, 16276MiB)
(4 CPUs, 31.4 GB RAM, 5689.3/8062.4 GB disk)

### Minimal Reproducible Example

```
model=YOLO("<path_to_model>.pt")
model.export(format="onnx")
```
and than
```
! yolo val model=<path_to_model>.onnx imgsz=768 data=data.yaml
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment] 2024-06-21 23:19
@hmasum52 hello,

Thank you for reporting this issue and providing the details. To help us investigate further, could you please provide a minimal reproducible code example that includes the exact steps and code you used to encounter this error? This will help us reproduce the issue on our end. You can refer to our guide on creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

Additionally, please ensure that you are using the latest versions of `torch` and `ultralytics`. You can upgrade your packages using the following commands:

```bash
pip install --upgrade torch ultralytics
```

Once you've updated, try running your export again with `simplify=True` and let us know if the issue persists.

If the problem continues, please share any error messages or logs you receive. This will help us diagnose the issue more effectively.

Looking forward to your response!

**Comment by Kayzwer** [comment] 2024-06-22 01:09
@inisis any possible solution?

**Comment by inisis** [comment] 2024-06-22 01:29
Hi @hmasum52 can you provide your onnx and onnxruntime version, I think it's a compatibility bug. I have tested locally and can not produce it.

**Comment by inisis** [comment] 2024-06-22 01:42
Hi @glenn-jocher @Kayzwer , this was a known issue related to https://github.com/inisis/OnnxSlim/issues/10 and was fixed in version 0.1.30, would you mind upgrade version to 0.1.30

**Comment by glenn-jocher** [comment] 2024-06-22 03:53
Hi @inisis,

Thank you for your patience. It looks like the issue you're encountering is related to the `OnnxSlim` library. This was a known issue and has been addressed in version 0.1.30.

To resolve this, please upgrade `OnnxSlim` to the latest version by running:

```bash
pip install onnx-simplifier==0.1.30
```

After upgrading, try exporting your model again with `simplify=True` and let us know if the issue persists.

If you continue to experience problems, please provide a minimal reproducible example following our [guide](https://docs.ultralytics.com/help/minimum_reproducible_example). This will help us investigate further.

Thanks for your cooperation! 😊

**Comment by hmasum52** [comment] 2024-06-22 07:39
Hi @glenn-jocher . Thanks for your reply. I have tried upgrading onnxslim. But it seems like ultralytics attempts to auto install an older version of onnxslim. Here is my code for exporting a trained `yolov10n` model on a custom dataset.
```
best_model=YOLO(f"{result}/weights/best.pt")
best_model.export(format="onnx", simplify=True)
```
This is the output I get running the above code.

```
Ultralytics YOLOv8.2.38 🚀 Python-3.10.13 torch-2.1.2 CPU (Intel Xeon 2.00GHz)
YOLOv10n summary (fused): 285 layers, 2695976 parameters, 0 gradients, 8.2 GFLOPs

PyTorch: starting from '/kaggle/working/runs/detect/yolov10n-run/weights/yolov10n-nht.pt' with input shape (1, 3, 768, 768) BCHW and output shape(s) (1, 300, 6) (5.5 MB)
requirements: Ultralytics requirement ['onnxslim==0.1.28'] not found, attempting AutoUpdate...
Collecting onnxslim==0.1.28
  Downloading onnxslim-0.1.28-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: onnx in /opt/conda/lib/python3.10/site-packages (from onnxslim==0.1.28) (1.16.1)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from onnxslim==0.1.28) (1.12.1)
Requirement already satisfied: packaging in /opt/conda/lib/python3.10/site-packages (from onnxslim==0.1.28) (21.3)
Requirement already satisfied: numpy>=1.20 in /opt/conda/lib/python3.10/site-packages (from onnx->onnxslim==0.1.28) (1.26.4)
Requirement already satisfied: protobuf>=3.20.2 in /opt/conda/lib/python3.10/site-packages (from onnx->onnxslim==0.1.28) (3.20.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.10/site-packages (from packaging->onnxslim==0.1.28) (3.1.1)
Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in /opt/conda/lib/python3.10/site-packages (from sympy->onnxslim==0.1.28) (1.3.0)
Downloading onnxslim-0.1.28-py3-none-any.whl (118 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.3/118.3 kB 4.3 MB/s eta 0:00:00
Installing collected packages: onnxslim
  Attempting uninstall: onnxslim
    Found existing installation: onnxslim 0.1.30
    Uninstalling onnxslim-0.1.30:
      Successfully uninstalled onnxslim-0.1.30
Successfully installed onnxslim-0.1.28

requirements: AutoUpdate success ✅ 11.8s, installed 1 package: ['onnxslim==0.1.28']
requirements: ⚠️ Restart runtime or rerun command for updates to take effect


ONNX: starting export with onnx 1.16.1 opset 17...
ONNX: slimming with onnxslim 0.1.28...
ONNX: export success ✅ 14.0s, saved as '/kaggle/working/runs/detect/yolov10n-run/weights/yolov10n-nht.onnx' (9.0 MB)

Export complete (16.2s)
Results saved to /kaggle/working/runs/detect/yolov10n-run/weights
Predict:         yolo predict task=detect model=/kaggle/working/runs/detect/yolov10n-run/weights/yolov10n-nht.onnx imgsz=768  
Validate:        yolo val task=detect model=/kaggle/working/runs/detect/yolov10n-run/weights/yolov10n-nht.onnx imgsz=768 data=train.yaml  
Visualize:       https://netron.app/
```

This is the command I am using  for validation
```
! yolo val model={result}/weights/best.onnx imgsz=768 data=train.yaml split=test name=test
```
I get this traceback after running the above command
```
Ultralytics YOLOv8.2.38 🚀 Python-3.10.13 torch-2.1.2 CPU (Intel Xeon 2.00GHz)
Loading /kaggle/working/runs/detect/yolov10n-run/weights/yolov10n-nht.onnx for ONNX Runtime inference...
Traceback (most recent call last):
  File "/opt/conda/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 591, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/model.py", line 528, in val
    validator(model=self.model)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/validator.py", line 124, in __call__
    model = AutoBackend(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 192, in __init__
    session = onnxruntime.InferenceSession(w, providers=providers)
  File "/opt/conda/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/opt/conda/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /kaggle/working/runs/detect/yolov10n-run/weights/yolov10n-nht.onnx failed:Node (/model.23/Tile_1) Op (Tile) [ShapeInferenceError] 'Repeats' input has incorrect number of values. The number of values in 'repeats' must be equal to the number of input dimensions.
Sentry is attempting to send 1 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit
```

I am doing this on a kaggle notebook.

**Comment by hmasum52** [comment] 2024-06-22 07:42
Hi @glenn-jocher . Thanks for your reply. I have tried upgrading onnxslim. But it seems like ultralytics attempts to auto install an older version of onnxslim. Here is my code for exporting a trained `yolov10n` model on a custom dataset.
```
best_model=YOLO(f"{result}/weights/best.pt")
best_model.export(format="onnx", simplify=True)
```
This is the output I get running the above code.

```
Ultralytics YOLOv8.2.38 🚀 Python-3.10.13 torch-2.1.2 CPU (Intel Xeon 2.00GHz)
YOLOv10n summary (fused): 285 layers, 2695976 parameters, 0 gradients, 8.2 GFLOPs

PyTorch: starting from '/kaggle/working/runs/detect/yolov10n-run/weights/best.pt' with input shape (1, 3, 768, 768) BCHW and output shape(s) (1, 300, 6) (5.5 MB)
requirements: Ultralytics requirement ['onnxslim==0.1.28'] not found, attempting AutoUpdate...
Collecting onnxslim==0.1.28
  Downloading onnxslim-0.1.28-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: onnx in /opt/conda/lib/python3.10/site-packages (from onnxslim==0.1.28) (1.16.1)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from onnxslim==0.1.28) (1.12.1)
Requirement already satisfied: packaging in /opt/conda/lib/python3.10/site-packages (from onnxslim==0.1.28) (21.3)
Requirement already satisfied: numpy>=1.20 in /opt/conda/lib/python3.10/site-packages (from onnx->onnxslim==0.1.28) (1.26.4)
Requirement already satisfied: protobuf>=3.20.2 in /opt/conda/lib/python3.10/site-packages (from onnx->onnxslim==0.1.28) (3.20.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.10/site-packages (from packaging->onnxslim==0.1.28) (3.1.1)
Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in /opt/conda/lib/python3.10/site-packages (from sympy->onnxslim==0.1.28) (1.3.0)
Downloading onnxslim-0.1.28-py3-none-any.whl (118 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.3/118.3 kB 4.3 MB/s eta 0:00:00
Installing collected packages: onnxslim
  Attempting uninstall: onnxslim
    Found existing installation: onnxslim 0.1.30
    Uninstalling onnxslim-0.1.30:
      Successfully uninstalled onnxslim-0.1.30
Successfully installed onnxslim-0.1.28

requirements: AutoUpdate success ✅ 11.8s, installed 1 package: ['onnxslim==0.1.28']
requirements: ⚠️ Restart runtime or rerun command for updates to take effect


ONNX: starting export with onnx 1.16.1 opset 17...
ONNX: slimming with onnxslim 0.1.28...
ONNX: export success ✅ 14.0s, saved as '/kaggle/working/runs/detect/yolov10n-run/weights/best.onnx' (9.0 MB)

Export complete (16.2s)
Results saved to /kaggle/working/runs/detect/yolov10n-run/weights
Predict:         yolo predict task=detect model=/kaggle/working/runs/detect/yolov10n-run/weights/best.onnx imgsz=768  
Validate:        yolo val task=detect model=/kaggle/working/runs/detect/yolov10n-run/weights/best.onnx imgsz=768 data=train.yaml  
Visualize:       https://netron.app/
```

This is the command I am using  for validation
```
! yolo val model={result}/weights/best.onnx imgsz=768 data=train.yaml split=test name=test
```
I get this traceback after running the above command
```
Ultralytics YOLOv8.2.38 🚀 Python-3.10.13 torch-2.1.2 CPU (Intel Xeon 2.00GHz)
Loading /kaggle/working/runs/detect/yolov10n-run/weights/best.onnx for ONNX Runtime inference...
Traceback (most recent call last):
  File "/opt/conda/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 591, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/model.py", line 528, in val
    validator(model=self.model)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/validator.py", line 124, in __call__
    model = AutoBackend(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 192, in __init__
    session = onnxruntime.InferenceSession(w, providers=providers)
  File "/opt/conda/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/opt/conda/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /kaggle/working/runs/detect/yolov10n-run/weights/best.onnx failed:Node (/model.23/Tile_1) Op (Tile) [ShapeInferenceError] 'Repeats' input has incorrect number of values. The number of values in 'repeats' must be equal to the number of input dimensions.
Sentry is attempting to send 1 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit
```

I am doing this on a kaggle notebook.

**Comment by inisis** [comment] 2024-06-22 07:46
Hi @hmasum52 , we are working on it, and a new pr if created. and you can try this
```
pip install onnxslim==0.1.31

best_model=YOLO(f"{result}/weights/best.pt")
best_model.export(format="onnx", simplify=False)

onnxslim best.onnx best.onnx  # single call
yolo val model={result}/weights/best.onnx imgsz=768 data=train.yaml split=test name=test

```

**Comment by glenn-jocher** [comment] 2024-06-22 10:43
I'll update the min requirement then to patch version 31!

**Closed** 2024-06-22 11:41 UTC
Labels: bug, fixed
