### ISSUE TITLE
Yolov10 training fails for imgsz=32 and imgsz=64

### ISSUE THREAD

**Issue by richardverheyen** [ultralytics/ultralytics#15887] opened 2024-08-29 09:49 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train

### Bug

with `ultralytics==8.2.83` I can't progress past the first loop in training when my imgsz=32. 

`ultralytics==8.1.34` lets me train my teensy tiny model and it works great, but I can't export it to CoreML!

### Environment

Ultralytics YOLOv8.2.83 🚀 Python-3.10.12 torch-2.4.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 33.1/78.2 GB disk)

OS                  Linux-6.1.85+-x86_64-with-glibc2.35
Environment         Colab
Python              3.10.12
Install             pip
RAM                 12.67 GB
CPU                 Intel Xeon 2.20GHz
CUDA                12.1

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.7.1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 9.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.4.0+cu121>=1.8.0
torchvision         ✅ 0.19.0+cu121>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.1.4>=1.1.4
seaborn             ✅ 0.13.1>=0.11.0
ultralytics-thop    ✅ 2.0.5>=2.0.0

### Minimal Reproducible Example

**updated**
```
yolo train imgsz=32 max_det=1 model=yolov10n.pt data=brain-tumor.yaml
```

### Training output with error logs
```
Ultralytics YOLOv8.2.83 🚀 Python-3.10.12 torch-2.4.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
engine/trainer: task=detect, mode=train, model=/content/weights/yolov10n.pt, data=/content/datasets/Beach-Volleyballs-32p-2/data.yaml, epochs=50, time=None, patience=100, batch=1024, imgsz=32, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train7, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=1, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train7
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]             
  5                  -1  1      9856  ultralytics.nn.modules.block.SCDown          [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  7                  -1  1     36096  ultralytics.nn.modules.block.SCDown          [128, 256, 3, 2]              
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]           
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]                 
 10                  -1  1    249728  ultralytics.nn.modules.block.PSA             [256, 256]                    
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 13                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]                 
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 16                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]                  
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]                
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 19                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]                 
 20                  -1  1     18048  ultralytics.nn.modules.block.SCDown          [128, 128, 3, 2]              
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 22                  -1  1    282624  ultralytics.nn.modules.block.C2fCIB          [384, 256, 1, True, True]     
 23        [16, 19, 22]  1    861718  ultralytics.nn.modules.head.v10Detect        [1, [64, 128, 256]]           
YOLOv10n summary: 385 layers, 2,707,430 parameters, 2,707,414 gradients, 8.4 GFLOPs

Transferred 493/595 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py:268: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = torch.cuda.amp.GradScaler(enabled=self.amp)
train: Scanning /content/datasets/Beach-Volleyballs-32p-2/train/labels... 13509 images, 10869 backgrounds, 0 corrupt: 100% 13509/13509 [00:03<00:00, 3394.85it/s]
train: New cache created: /content/datasets/Beach-Volleyballs-32p-2/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
val: Scanning /content/datasets/Beach-Volleyballs-32p-2/valid/labels... 1312 images, 1046 backgrounds, 0 corrupt: 100% 1312/1312 [00:00<00:00, 1811.58it/s]
val: New cache created: /content/datasets/Beach-Volleyballs-32p-2/valid/labels.cache
Plotting labels to runs/detect/train7/labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 95 weight(decay=0.0), 108 weight(decay=0.008), 107 bias(decay=0.0)
Image sizes 32 train, 32 val
Using 2 dataloader workers
Logging results to runs/detect/train7
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/50      1.44G      6.136      7.122      2.747        100         32: 100% 14/14 [00:17<00:00,  1.28s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0% 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 830, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 813, in train
    self.trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 206, in train
    self._do_train(world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 430, in _do_train
    self.metrics, self.fitness = self.validate()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 575, in validate
    metrics = self.validator(self)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/validator.py", line 176, in __call__
    preds = model(batch["img"], augment=augment)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py", line 106, in forward
    return self.predict(x, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py", line 124, in predict
    return self._predict_once(x, profile, visualize, embed)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py", line 145, in _predict_once
    x = m(x)  # run
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/modules/head.py", line 54, in forward
    return self.forward_end2end(x)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/modules/head.py", line 84, in forward_end2end
    y = self.postprocess(y.permute(0, 2, 1), self.max_det, self.nc)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/modules/head.py", line 152, in postprocess
    scores, index = scores.flatten(1).topk(max_det)
RuntimeError: selected index k out of range
```

### Additional

I have tested a few variations, and imgsz=32,64 both fail on `8.2.83`, I'm not sure which version it stopped working on.

The latest version I've successfully trained yolov10 on with my 32x32 dataset is `8.1.34`

I'd like to be able to export my model to CoreML, and models trained on older versions of ultralytics can't be exported to CoreML by `ultralytics==8.2.83`.

My 32p labelled dataset is here: https://app.roboflow.com/cutshot-vxnxp/beach-volleyballs-32p/2

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ambitious-octopus** [comment] 2024-08-29 10:25
Hey @richardverheyen, Your Minimal Reproducible Example seems wrong, I tried this command and I can't reproduce your error (using `Ultralytics v8.2.83`): 
```
yolo train imgsz=32 max_det=1 model=yolov10n.pt data=coco8.yaml
```
I also cannot access the dataset you provided.

**Comment by Y-T-G** [comment] 2024-08-29 11:26
I suppose by `8.1.34`, you're referring to the code in YOLOv10 repository. That is a fork of ultralytics and not the official ultralytics.

Official support for YOLOv10 was introduced in v8.2.38

https://github.com/ultralytics/ultralytics/releases/tag/v8.2.38

**Comment by richardverheyen** [comment] 2024-08-29 13:41
> I suppose by `8.1.34`, you're referring to the code in YOLOv10 repository. That is a fork of ultralytics and not the official ultralytics.
> 
> Official support for YOLOv10 was introduced in v8.2.38
> 
> https://github.com/ultralytics/ultralytics/releases/tag/v8.2.38

I think you're referring to when the models became available to reference as model=yolov10n etc. I'm still able to train on ultralytics==8.1.34 based on the colab notebook linked/followed in this tutorial: https://blog.roboflow.com/yolov10-how-to-train/

Currently this is the only way I can train yolov10 with my dataset

**Comment by richardverheyen** [comment] 2024-08-29 14:06
> Hey @richardverheyen, Your Minimal Reproducible Example seems wrong, I tried this command and I can't reproduce your error (using `Ultralytics v8.2.83`):
> 
> ```
> yolo train imgsz=32 max_det=1 model=yolov10n.pt data=coco8.yaml
> ```
> 
> I also cannot access the dataset you provided.

@ambitious-octopus thanks for your quick reply, I have validated that I can run `yolo train imgsz=32 max_det=1 model=yolov10n.pt data=coco8.yaml`. Clearly the title of my ticket is slightly wrong in this case.

I am a bit of a klutz, and only just learned about yolov8's inbuilt example datasets. I found a way of reproducing my error with 32p images on the brain-tumor.yaml dataset, which is the same yolov8 format as my dataset and seems to fail in exactly the same way:

```yolo train imgsz=32 max_det=1 model=yolov10n.pt data=brain-tumor.yaml```

Does this fail for you on `8.2.83`?

**Comment by richardverheyen** [comment] 2024-08-29 14:21
@Y-T-G thanks for replying on my ticket, apologies I don't have a lot of experience in creating minimal reproducible examples, but I've created one which fails for me. Can you reproduce my bug with this?
```yolo train imgsz=32 max_det=1 model=yolov10n.pt data=brain-tumor.yaml```

**Comment by Y-T-G** [comment] 2024-08-29 14:50
Yes, it's reproducible.

You can workaround the issue by training using Python for now:

```python
from ultralytics.nn.modules.head import Detect
from ultralytics import YOLO
Detect.max_det = 1
model = YOLO("yolov10n.pt")
results = model.train(data="brain-tumor.yaml", imgsz=32)
```

**Comment by Laughing-q** [comment] 2024-08-31 14:11
@richardverheyen Thanks for reporting the issue!
The issue is because the image size is too small hence the total number of anchor is less than the `max_det=300`, then an error raised from torch.topk operation, and plus we don't support setting max_det for e2e models so the max_det=1 from the user didn't work as expected.
The issue should be fixed in this [PR](https://github.com/ultralytics/ultralytics/pull/15917) that @ambitious-octopus submitted. :)

**Closed** 2024-09-01 00:04 UTC
Labels: bug, fixed, detect
