### ISSUE TITLE
Got PosixPath Error when loading pt file

### ISSUE THREAD

**Issue by ZeroAct** [ultralytics/ultralytics#1900] opened 2023-04-08 01:57 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I've trained a model on Linux.
But, I can not load the model on Windows..
```
File "C:\Users\zero\anaconda3\envs\waffle\lib\site-packages\ultralytics\nn\tasks.py", line 347, in torch_safe_load
    return torch.load(file, map_location='cpu'), file  # load
  File "C:\Users\zero\anaconda3\envs\waffle\lib\site-packages\torch\serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\zero\anaconda3\envs\waffle\lib\site-packages\torch\serialization.py", line 1131, in _load
    result = unpickler.load()
  File "C:\Users\zero\anaconda3\envs\waffle\lib\pathlib.py", line 1084, in __new__
    raise NotImplementedError("cannot instantiate %r on your system"
NotImplementedError: cannot instantiate 'PosixPath' on your system
```

It is okay with loading model from windows training.

I could not find a reason for this issue.
Help me.

### Environment

- YOLO : Ultralytics 8.0.70
- OS : windows 11

### Minimal Reproducible Example

```
from ultralytics import YOLO

# Does not work
YOLO("weights/from_linux.pt")

# Does work
YOLO("weights/from_windows.pt")
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment] 2023-04-08 04:07
@ZeroAct it looks like you are encountering an error when trying to load a YOLOv8 model trained on Linux into a Windows environment. The error message seems to indicate that the `PosixPath` module is not instantiated in your Windows system. Although it is difficult to determine the root cause without more information, it might be valuable to ensure that you are using the latest version of PyTorch in your Windows environment. Additionally, you could try to load and save your model with `torch.load` and `torch.save` instead of the `load` and `save` methods in `tasks.py`, respectively. If you are still encountering issues, please provide more details about how you trained the model and any additional error messages that might be helpful in pinpointing the problem.

**Comment by glenn-jocher** [comment] 2023-04-08 17:43
@ZeroAct all official models are trained on Linux and loaded correctly on any operating system. We are not able to reproduce any issues with the official models loading in any environment.

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Closed** 2023-04-20 00:32 UTC
Labels: bug, non-reproducible

**Comment by srishti-buyume** [comment] 2023-10-11 13:15
@glenn-jocher Hello Glenn, I am getting a similar issue, actually the exact issue in op, I have trained my models on GCP/Linux system, I am having no issues when loading and running prediction using custom model files for detection and segmentation task. But only when i try to run predict on a custom model file(best.pt) from a classification problem I get this error.
I have literally spend 2 days trying various solutions from stackoverflow, testing on Jupyter notebooks, colab notebook, with/without virtual environment. using a python script file or CLI command I keep getting path errors.

If you want, I can provide the model file and please let me know if you get the prediction result on a Windows system using this file.

**Comment by glenn-jocher** [comment] 2023-10-11 23:17
@srishti-buyume hello, thank you for reaching out. 

Your error seems to be related to the different path structures between Linux-based and Windows-based systems. Specifically, Windows may not correctly interpret the 'PosixPath' associated with Linux systems. When a model is saved in a Linux environment it also saves the file paths associated with it, which can make cross-platform usage challenging.

Let's try a couple of simple troubleshooting steps:

1. **Try to use the latest version of the YOLOv8 repository.** We continuously improve the repo and it's likely that the problem you are encountering may have already been addressed in the latest updates.

2. **Cross-platform compatibility check:**
    - For models trained on Linux and used on Windows, you may need to modify the saved file paths in the model's state dictionary to convert them to Windows paths.
    - Alternatively, if you have access to your Linux environment, try to work with the model loading and saving paths. Use relative paths instead of absolute paths while saving/loading the models.

Please note that providing the problematic model file or full details of the error messages would indeed be helpful for a deeper investigation. You may need to open a new issue specifically about this, carefully following the issue template, and including all the relevant details.

Hope this helps, and don't hesitate to return for any further questions or issues.

**Comment by srishti-buyume** [comment] 2023-10-12 11:41
@glenn-jocher thanks for your response Glenn, I will try the troubleshooting steps you have mentioned, and if the problem persists I will create a new issue with all the required details.

**Comment by glenn-jocher** [comment] 2023-10-12 21:04
You're welcome @srishti-buyume, and thank you for your understanding! Yes, please take your time trying the troubleshooting steps that we've discussed. These types of cross-platform issues can be quite tricky sometimes. If after trying these steps the problem still exists, do not hesitate to create a new issue. There, you could provide all the pertinent details related to this specific problem which will be really helpful for us to assist you better and possibly diagnose the issue. Good luck, and I hope the issue gets resolved soon. Let us know if you have any more questions or concerns.

**Comment by lonngxiang** [comment] 2023-12-07 06:18
> @srishti-buyume hello, thank you for reaching out.
> 
> Your error seems to be related to the different path structures between Linux-based and Windows-based systems. Specifically, Windows may not correctly interpret the 'PosixPath' associated with Linux systems. When a model is saved in a Linux environment it also saves the file paths associated with it, which can make cross-platform usage challenging.
> 
> Let's try a couple of simple troubleshooting steps:
> 
> 1. **Try to use the latest version of the YOLOv8 repository.** We continuously improve the repo and it's likely that the problem you are encountering may have already been addressed in the latest updates.
> 2. **Cross-platform compatibility check:**
>    
>    * For models trained on Linux and used on Windows, you may need to modify the saved file paths in the model's state dictionary to convert them to Windows paths.
>    * Alternatively, if you have access to your Linux environment, try to work with the model loading and saving paths. Use relative paths instead of absolute paths while saving/loading the models.
> 
> Please note that providing the problematic model file or full details of the error messages would indeed be helpful for a deeper investigation. You may need to open a new issue specifically about this, carefully following the issue template, and including all the relevant details.
> 
> Hope this helps, and don't hesitate to return for any further questions or issues.

how to modify the saved file paths in the model's state dictionary to convert them to Windows paths?

**Comment by MiaMa0914** [comment] 2024-07-24 07:03
I got a same issue. I trained on Linux, and predicted on Windows. The file "weights/from_linux.pt" (around 80M) is larger than "weights/from_windows.pt" (around 15M). I don't know what happened. I try to convert Linux file paths to Windows paths, but it doesn't work. Please help!

**Comment by pderrenger** [comment] 2024-07-24 11:41
Thank you for your message. Please ensure you are using the latest version of the YOLOv8 repository, as updates may resolve your issue. The size discrepancy between the models suggests there might be additional data or different configurations saved in the Linux-trained model. To address the path issue, you can try re-saving the model on Linux with relative paths and then loading it on Windows. If the problem persists, please open a new issue with detailed information for further assistance.
