### ISSUE TITLE
Export Fails with DLA Device

### ISSUE THREAD

**Issue by giulio333** [ultralytics/ultralytics#17415] opened 2024-11-08 09:55 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

The export fails with the following message:

```shell
Ultralytics 8.3.27 🚀 Python-3.10.12 torch-2.3.0 
Traceback (most recent call last):
  File "/workspaces/idf-engine/plugin/export.py", line 44, in <module>
    model.export(format="engine", device="dla:1", half=True)
  File "/ultralytics/ultralytics/engine/model.py", line 734, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/ultralytics/ultralytics/engine/exporter.py", line 210, in __call__
    self.device = select_device("cpu" if self.args.device is None else self.args.device)
  File "/ultralytics/ultralytics/utils/torch_utils.py", line 192, in select_device
    raise ValueError(
ValueError: Invalid CUDA 'device=dla:1' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): False
torch.cuda.device_count(): 0
os.environ['CUDA_VISIBLE_DEVICES']: None
See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no CUDA devices are seen by torch.
``` 

The command I execute is as follows, according to the documentation:

```python
model.export(format="engine", device="dla:1", half=True)
``` 

The logs indicate that CUDA is not visible to Torch, but I believe this is an error. I have manually executed the command and it returns True. Furthermore, exporting with:

```python
out = model.export(
    format="engine",
    imgsz=640,
    dynamic=False,
    verbose=False,
    batch=4,
    workspace=2,
    int8=True,
    data="coco8.yaml",
)
``` 
works fine, so there is something I am missing.

### Orin NX 16 GB

Working inside official Ultralytics Container for Jetpack 6 

Ultralytics 8.3.27 🚀 Python-3.10.12 torch-2.3.0 CUDA:0 (Orin, 16013MiB)
Setup complete ✅ (8 CPUs, 15.6 GB RAM, 66.3/115.4 GB disk)

OS                  Linux-5.15.148-tegra-aarch64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             git
RAM                 15.64 GB
Disk                66.3/115.4 GB
CPU                 ARMv8 Processor rev 1 (v8l)
CPU count           8
GPU                 Orin, 16013MiB
GPU count           1
CUDA                12.2

numpy               ✅ 1.23.5>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.1>=1.4.1
torch               ✅ 2.3.0>=1.8.0
torchvision         ✅ 0.18.0a0+6043bc2>=0.9.0
tqdm                ✅ 4.66.6>=4.64.0
psutil              ✅ 6.1.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.10>=2.0.0
numpy               ✅ 1.23.5<2.0.0; sys_platform == "darwin"
torch               ✅ 2.3.0!=2.4.0,>=1.8.0; sys_platform == "win32"

### Minimal Reproducible Example

```python
from ultralytics import YOLO

model = YOLO("yolo11n.pt")
model.export(format="engine", device="dla:1", half=True)
``` 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment] 2024-11-08 09:56
👋 Hello @giulio333, thank you for your interest in Ultralytics 🚀! We appreciate your detailed report on the `Export Fails with DLA Device` issue you're experiencing. This is an automated response, and an Ultralytics engineer will also assist you soon.

To assist us in understanding this issue better, please ensure you have included a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) with your report, which you have expertly done. This will significantly aid in debugging the problem you're encountering.

Meanwhile, you might find some helpful insights by visiting our [Docs](https://docs.ultralytics.com) for various usage guidelines, or exploring the [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) examples, where many of the most common questions might already be addressed.

For real-time support from the community, please join our [Discord](https://ultralytics.com/discord) 🎧. Alternatively, for more extensive discussions, visit [Discourse](https://community.ultralytics.com) or explore knowledge threads on our [Subreddit](https://reddit.com/r/ultralytics).

## Upgrade

Please make sure to upgrade to the latest `ultralytics` package, including all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml), in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/):

```bash
pip install -U ultralytics
```

## Environments

YOLO should be executed in one of the following up-to-date verified environments, where all dependencies, including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/), and [PyTorch](https://pytorch.org/), come preinstalled:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM: See the [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI: See the [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**: See the [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing. These tests verify the correct operation of all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) on macOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by Y-T-G** [comment] 2024-11-08 10:36
Did you try `dla:0`?

**Comment by Y-T-G** [comment] 2024-11-08 11:23
You can try running this in terminal and then try exporting again:

`sed -i '209i            self.args.device = "0"' /ultralytics/ultralytics/engine/exporter.py`

**Comment by Y-T-G** [comment] 2024-11-08 12:56
Can you provide the output after running this command in terminal: `yolo checks`?

**Comment by Y-T-G** [comment] 2024-11-08 13:01
What does catting this print?

https://github.com/ultralytics/ultralytics/blob/84bfe3c2e4fd5881c33d0f1264b94c6e62edeb43/ultralytics/utils/__init__.py#L530

`cat /proc/device-tree/model`

**Comment by Y-T-G** [comment] 2024-11-08 13:15
> Jetson AGX Orin as NX-16GB

This would also fail because the code is looking for NVIDIA.

https://github.com/ultralytics/ultralytics/blob/84bfe3c2e4fd5881c33d0f1264b94c6e62edeb43/ultralytics/utils/__init__.py#L616

**Comment by Y-T-G** [comment] 2024-11-08 13:17
You could try some of these

https://stackoverflow.com/a/79076621/8061030

**Comment by glenn-jocher** [comment] 2024-11-08 14:21
Thank you for sharing your solution. We'll review this internally to address the issue in future updates.

**Comment by Y-T-G** [comment] 2024-11-08 14:50
https://forums.developer.nvidia.com/t/does-dla-work-faster-than-gpu-in-fp16-model/214505

**Comment by glenn-jocher** [comment] 2024-11-08 15:23
Yes, DLA should be slower than a standard TRT Engine export. It does not run on the GPU.

@lakshanthad can you review our `is_jetson()` implementation? User is saying that it fails in Docker container, but also fails outside Docker container in https://github.com/ultralytics/ultralytics/issues/17415#issuecomment-2464718510

**Comment by lakshanthad** [comment] 2024-11-25 08:40
@giulio333 Can you confirm the exact NVIDIA Jetson Orin NX 16GB you are using? Are you using an official board or a Jetson SoM with 3rd party carrier board?
Also, please tell me the JetPack version you are using.

I am using JetPack 6.0 with reComputer J4012 powered by Jetson Orin NX 16GB and my output for `/proc/device-tree/model` is as follows:

```sh
nvidia@nvidia-desktop:~/YOLO11/ultralytics$ cat /proc/device-tree/model
NVIDIA Jetson Orin NX Engineering Reference Developer Kit(env)
```

So for me, both inside and outside Docker works. In your situation, I could add a fix by checking for both "NVIDIA" and "Jetson". But please help me with the above queries first.

Thank you!

**Comment by lakshanthad** [comment] 2024-11-25 10:49
@giulio333 I have done the necessary PRs for this. They will be merged soon.

**Comment by lakshanthad** [comment] 2024-11-25 10:50
> I take this opportunity to inform you that the new updated container does not include Python 3.11 as stated in your new release but rather v3.10.12.

@giulio333  JetPack6 container already has Python3.10 inside. This is not something that we controlled inside the container. Thanks.

**Closed** 2024-11-25 15:45 UTC
Labels: bug, embedded, exports

**Comment by lakshanthad** [comment] 2024-11-25 15:59
> I founded this on release [v8.3.35](https://github.com/ultralytics/ultralytics/releases/tag/v8.3.35)
> 
> >

This applied to only `Dockerfile-cpu` as stated in [this PR](https://github.com/ultralytics/ultralytics/pull/17670).
