### ISSUE TITLE
runs/best.pt appears to require 'ultralytics.nn.modules.conv', which is not in ultralytics requirements.

### ISSUE THREAD

**Issue by moyu026** [ultralytics/ultralytics#2947] opened 2023-06-01 03:30 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

WARNING  runs/best.pt appears to require 'ultralytics.nn.modules.conv', which is not in ultralytics requirements.
AutoInstall will run now for 'ultralytics.nn.modules.conv' but this feature will be removed in the future.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'
requirements: YOLOv8 requirement "ultralytics.nn.modules.conv" not found, attempting AutoUpdate...
WARNING: Ignore distutils configs in setup.cfg due to encoding errors.
ERROR: Could not find a version that satisfies the requirement ultralytics.nn.modules.conv (from versions: none)
ERROR: No matching distribution found for ultralytics.nn.modules.conv
requirements:  Command 'pip install "ultralytics.nn.modules.conv"  ' returned non-zero exit status 1.
Traceback (most recent call last):
  File "F:/PythonWork/1/ultralytics-main/test_seg_fire.py", line 6, in <module>
    model = YOLO(r'runs/best.pt')  # load an official model
  File "F:\PythonWork\1\ultralytics-main\ultralytics\yolo\engine\model.py", line 106, in __init__
    self._load(model, task)
  File "F:\PythonWork\1\ultralytics-main\ultralytics\yolo\engine\model.py", line 145, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "F:\PythonWork\1\ultralytics-main\ultralytics\nn\tasks.py", line 396, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "F:\PythonWork\1\ultralytics-main\ultralytics\nn\tasks.py", line 351, in torch_safe_load
    return torch.load(file, map_location='cpu'), file  # load
  File "E:\ProgramData\anaconda3\envs\py38torch17\lib\site-packages\torch\serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "E:\ProgramData\anaconda3\envs\py38torch17\lib\site-packages\torch\serialization.py", line 853, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'ultralytics.nn.modules.conv'; 'ultralytics.nn.modules' is not a package

### Additional

 I finish my training and predict the best.pt, it has this bug

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment] 2023-06-01 03:51
@moyu026 what the version of your package? could you attach the best.pt here then I'm able to check on it? if you don't mind.

**Comment by moyu026** [comment] 2023-06-01 04:21
> @moyu026 what the version of your package? could you attach the best.pt here then I'm able to check on it? if you don't mind.

thank you for your reply, here's my package:
absl-py                 1.4.0
cachetools              5.3.0
certifi                 2022.12.7
charset-normalizer      3.1.0
colorama                0.4.6
contourpy               1.0.7
cycler                  0.11.0
exceptiongroup          1.1.1
fonttools               4.39.3
gitdb                   4.0.10
GitPython               3.1.31
google-auth             2.17.3
google-auth-oauthlib    1.0.0
grpcio                  1.54.0
idna                    3.4
importlib-metadata      6.6.0
importlib-resources     5.12.0
iniconfig               2.0.0
kiwisolver              1.4.4
lxml                    4.9.2
Markdown                3.4.3
MarkupSafe              2.1.2
matplotlib              3.7.1
numpy                   1.24.2
oauthlib                3.2.2
opencv-python           4.7.0.72
packaging               23.0
pandas                  2.0.0
Pillow                  9.5.0
pip                     23.1.2
pluggy                  1.0.0
protobuf                4.22.3
psutil                  5.9.5
pyasn1                  0.5.0
pyasn1-modules          0.3.0
pyparsing               3.0.9
pytest                  7.3.1
python-dateutil         2.8.2
pytz                    2023.3
PyYAML                  6.0
requests                2.29.0
requests-oauthlib       1.3.1
rsa                     4.9
scipy                   1.10.1
seaborn                 0.12.2
setuptools              67.7.2
six                     1.16.0
smmap                   5.0.0
tensorboard             2.12.2
tensorboard-data-server 0.7.0
tensorboard-plugin-wit  1.8.1
thop                    0.1.1.post2209072238
tomli                   2.0.1
torch                   1.7.1+cu110
torchvision             0.8.2+cu110
tqdm                    4.65.0
typing_extensions       4.5.0
tzdata                  2023.3
urllib3                 1.26.15
Werkzeug                2.2.3
wheel                   0.40.0
zipp                    3.15.0

**Comment by Laughing-q** [comment] 2023-06-01 06:05
@moyu026 I meant the version ultralytics package. BTW I just tested the training with the latest version and I'm able to load the trained model successfully and do inference. I'm not able to reproduce the issue.
Training first:
```python
from ultralytics import YOLO
model = YOLO("yolov8n.pt")
model.train(data="coco128.yaml", epochs=1)
```
then load the trained model and do inference:
```python
model = YOLO("runs/detect/train/weights/best.pt")
model.predict()
```
![image](https://github.com/ultralytics/ultralytics/assets/61612323/5bd400cf-ffa4-44ec-8350-db6ee2ea2a6a)

**Comment by moyu026** [comment] 2023-06-01 06:40
> @moyu026 I meant the version ultralytics package. BTW I just tested the training with the latest version and I'm able to load the trained model successfully and do inference. I'm not able to reproduce the issue. Training first:
> 
> ```python
> from ultralytics import YOLO
> model = YOLO("yolov8n.pt")
> model.train(data="coco128.yaml", epochs=1)
> ```
> 
> then load the trained model and do inference:
> 
> ```python
> model = YOLO("runs/detect/train/weights/best.pt")
> model.predict()
> ```
> 
> ![image](https://user-images.githubusercontent.com/61612323/242495701-5bd400cf-ffa4-44ec-8350-db6ee2ea2a6a.png)

thank you,I download code zip and pip install ultralytics package again, it works.

**Comment by Laughing-q** [comment] 2023-06-01 06:42
@moyu026 Good to hear you solved the issue. Then I'm closing the issue, please feel free to reopen it if you have any related issues. :)

**Closed by Laughing-q** 2023-06-01 06:42 UTC
Labels: bug, non-reproducible
