### ISSUE TITLE
Why can't I always predict the left boundary when performing instance segmentation?

### ISSUE THREAD

**Issue by zwf159** [ultralytics/ultralytics#15611] opened 2024-08-15 08:19 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Why does the prediction always leave some residuals on the left side when I turn off the bounding box during inference? This issue only occurs on the left side.
![image_2457](https://github.com/user-attachments/assets/33d6190e-79be-45c2-97ae-741e1baa33cf)
![image_2458](https://github.com/user-attachments/assets/427eb788-3712-49fd-b481-259ee52b08bc)

**Comment by Skillnoob** [comment] 2024-08-15 13:05
Duplicate of https://github.com/ultralytics/ultralytics/issues/15610

**Closed** 2024-08-15 22:17 UTC
Labels: duplicate, question, segment
