### ISSUE TITLE
cli training from documentation command not working

### ISSUE THREAD

**Issue by wvalcke** [ultralytics/ultralytics#241] opened 2023-01-11 09:08 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Using the command (as described in the cli documentation):
yolo task=detect mode=train --cfg default.yaml
Gives 
usage: yolo [--help] [--hydra-help] [--version] [--cfg {job,hydra,all}] [--resolve] [--package PACKAGE] [--run] [--multirun] [--shell-completion] [--config-path CONFIG_PATH]
            [--config-name CONFIG_NAME] [--config-dir CONFIG_DIR] [--experimental-rerun EXPERIMENTAL_RERUN] [--info [{all,config,defaults,defaults-tree,plugins,searchpath}]]
            [overrides [overrides ...]]
yolo: error: argument --cfg/-c: invalid choice: 'default.yaml' (choose from 'job', 'hydra', 'all')

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment] 2023-01-11 09:55
@wvalcke hi! can you try `--config-name default.yaml` and let me know if the issue still exisists? Thanks!

**Comment by wvalcke** [comment] 2023-01-11 20:27
Hi Ayush,

Yes this fixes the problem,the documentation on https://docs.ultralytics.com/cli/ is not correct, so please fix it, good documentation is important.
Thanks for the reply.

**Comment by AyushExel** [comment] 2023-01-11 20:33
@wvalcke yes its been fixed in the main. The docs will be updated tonight

**Comment by Robotatron** [comment] 2023-01-12 01:48
> @wvalcke hi! can you try `--config-name default.yaml` and let me know if the issue still exisists? Thanks!

For me it ignores my custom "default.yaml" and loads your default settings. I.e. my default.yaml is for segmentation, but executing 
```
Successfully installed ultralytics-8.0.4
(oneformer) jupyter@yolact-eu-for-object-detection-1:~/yolov8$ yolo --config-name=default.yaml 
```
still does classification on the coco128 dataset. It ignores my config

**Comment by Robotatron** [comment] 2023-01-12 01:56
@AyushExel I renamed my custom config to "custom.yaml", it now shows a different error message:

```
(oneformer) jupyter@yolact-eu-for-object-detection-1:~/yolov8$ yolo task=detect mode=train --config-name=home/jupyter/yolov8/custom.yaml
Cannot find primary config 'home/jupyter/yolov8/custom.yaml'. Check that it's in your config search path.

Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=pkg://ultralytics.yolo.configs
        provider=schema, path=structured://

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

My config file is in the same directory as the terminal, I tried as well `--config-name=custom.yaml`

**Comment by wvalcke** [comment] 2023-01-12 07:57
Updated to 8.0.4 (via pip)

Indeed , it still has issues, if you type 
yolo --config-name=default.yaml 
it completely ignores the content. 
And using : yolo --config-name=./default.yaml gives the following error

Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/wim/.virtualenvs/pytorch1.12.1/lib/python3.8/site-packages/ultralytics/yolo/cli.py", line 24, in cli
    if cfg.cfg:
omegaconf.errors.ConfigAttributeError: Key 'cfg' is not in struct
    full_key: cfg
    object_type=dict

**Comment by Robotatron** [comment] 2023-01-12 18:07
Is there a way to train YOLO8 same way we trained YOLO5 with:
`python segment/train.py --weights 'yolov5l-seg.pt' --cfg yolov5l-seg.yaml --img 600 --epochs 200 --data data/sagemaker.yaml --hyp hyp.scratch-high.yaml --batch 48 --project runs/SageMaker/train --name 02-L-600-hyphigh` ?

**Comment by AyushExel** [comment] 2023-01-12 19:42
Hey guys, if you update to the latest version you can simply pass any config file like this:
`yolo cfg=file.yaml`
see example https://docs.ultralytics.com/cli/#overriding-default-config-file
Can you confirm if your issue has been resolved? Thanks!

**Comment by wvalcke** [comment] 2023-01-12 20:12
Hi Ayush,

I've just started training (using version 8.0.5), now the cfg=fileyaml works, it does take the options inside the yaml file now. 
Thanks for such speedy replies and reactions!

**Comment by AyushExel** [comment] 2023-01-12 20:40
You're welcome! ☺️  Please let us know if you face any more problems. I'm closing this issue

**Closed by AyushExel** 2023-01-12 20:40 UTC
Labels: bug

**Comment by Robotatron** [comment] 2023-01-13 20:56
> You're welcome! ☺️ Please let us know if you face any more problems. I'm closing this issue

I am still getting errors with `Ultralytics YOLOv8.0.5 🚀 Python-3.8.15 torch-1.10.1`
Using `yolo cfg=custom.yaml` I am getting an error:

```
 19                  -1  1   3687680  ultralytics.nn.modules.Conv                  [640, 640, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.Concat                [1]                           
 21                  -1  3   7379200  ultralytics.nn.modules.C2f                   [1280, 640, 3]                
 22        [15, 18, 21]  1  12345098  ultralytics.nn.modules.Segment               [30, 32, 320, [320, 640, 640]]
YOLOv8x-seg summary: 401 layers, 71779738 parameters, 71779722 gradients, 344.7 GFLOPs

ClearML Task: created new task id=1f7a10ac7b631482695d494d963359c445
2023-01-13 20:54:48,991 - clearml.Task - INFO - No repository found, storing script code instead
ClearML results page: https://app.clear.ml/projects/927asdb87cc/experiments/1f7a10ac7basdc445/output/log
2023-01-13 20:54:53,754 - clearml.Task - WARNING - Parameters must be of builtin type (General/hydra[DictConfig])
AutoBatch: Computing optimal batch size for --imgsz 600
AutoBatch: CUDA:0 (A100-SXM4-40GB) 39.59G total, 0.56G reserved, 0.55G allocated, 38.48G free
      Params      GFLOPs  GPU_mem (GB)  forward (ms) backward (ms)                   input                  output
Sizes of tensors must match except in dimension 1. Expected size 76 but got size 75 for tensor number 1 in the list.
Sizes of tensors must match except in dimension 1. Expected size 76 but got size 75 for tensor number 1 in the list.
Sizes of tensors must match except in dimension 1. Expected size 76 but got size 75 for tensor number 1 in the list.
Sizes of tensors must match except in dimension 1. Expected size 76 but got size 75 for tensor number 1 in the list.
Sizes of tensors must match except in dimension 1. Expected size 76 but got size 75 for tensor number 1 in the list.
Error executing job with overrides: ['cfg=custom.yaml']
An error occurred during Hydra's exception formatting:
AssertionError()
Traceback (most recent call last):
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/_internal/utils.py", line 254, in run_and_report
    assert mdl is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/oneformer/bin/yolo", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/_internal/utils.py", line 389, in _run_hydra
    _run_app(
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/_internal/utils.py", line 452, in _run_app
    run_and_report(
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/_internal/utils.py", line 296, in run_and_report
    raise ex
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/_internal/utils.py", line 453, in <lambda>
    lambda: hydra.run(
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/cli.py", line 56, in cli
    func(cfg)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/main.py", line 79, in decorated_main
    return task_function(cfg_passthrough)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/v8/segment/train.py", line 152, in train
    model.train(**cfg)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 193, in train
    self.trainer.train()
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 185, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 247, in _do_train
    self._setup_train(rank, world_size)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 210, in _setup_train
    self.batch_size = check_train_batch_size(self.model, self.args.imgsz, self.amp)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/utils/autobatch.py", line 18, in check_train_batch_size
    return autobatch(deepcopy(model).train(), imgsz)  # compute optimal batch size
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/utils/autobatch.py", line 60, in autobatch
    p = np.polyfit(batch_sizes[:len(y)], y, deg=1)  # first degree polynomial fit
  File "<__array_function__ internals>", line 180, in polyfit
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/numpy/lib/polynomial.py", line 638, in polyfit
    raise TypeError("expected non-empty vector for x")
TypeError: expected non-empty vector for x
```

**Comment by AyushExel** [comment] 2023-01-14 18:29
@Robotatron can please confirm if this issue is reproducible in the colab example? thanks!

**Comment by Robotatron** [comment] 2023-01-15 16:10
> @Robotatron can please confirm if this issue is reproducible in the colab example? thanks!

Yes, it is reproducible if using `imgsz=600` in Colab, same error and workaround as here https://github.com/ultralytics/ultralytics/issues/365

(the workaround being using an image size % 32 == 0)

**Comment by AyushExel** [comment] 2023-01-15 17:12
@Robotatron okay yeah now I think I know the reason..We'll fix it soon

**Comment by AyushExel** [comment] 2023-01-16 09:22
https://github.com/ultralytics/ultralytics/pull/398

**Comment by Robotatron** [comment] 2023-01-16 09:25
Thanks for a prompt fix!

**Comment by gabriel-joy** [comment] 2023-02-21 02:55
I guess cli works only in windows, tried in ubuntu 20.04 and 22.04 and I've got yolo command was not found.
