### ISSUE TITLE
What's the reason for the different results?

### ISSUE THREAD

**Issue by dh031200** [ultralytics/ultralytics#1781] opened 2023-04-03 06:03 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I uncomment `detect_results = detect_model.track(source=src, verbose=False, tracker="botsort.yaml", stream=True)`
I got different results.
Also, the seg_model does not use a tracker, but tracking is enabled. You can check the tracking id as shown in the picture below.
Do the two instances(detect_model, seg_model) share memory or parameters?

```python
import cv2
from ultralytics import YOLO


src = 'sample_video.mp4'

detect_model = YOLO('yolov8n')
seg_model = YOLO('yolov8n-seg')

# detect_results = detect_model.track(source=src, verbose=False, tracker="botsort.yaml", stream=True) # This line
seg_results = seg_model.predict(source=src, verbose=False, retina_masks=True, stream=True)

save_path = 'output.mp4'
writer = cv2.VideoWriter(save_path, cv2.VideoWriter_fourcc(*'mp4v'), 60, (1920, 1080))

for seg in seg_results:
    writer.write(seg.plot())
writer.release()
```

### Case 1 (yolov8n-seg):
seg model only:
![image](https://user-images.githubusercontent.com/66017052/229416625-add4475b-4081-4a20-bd42-d62df7964ed4.png)
load two models:
![image](https://user-images.githubusercontent.com/66017052/229416707-7c00c3a9-3788-45c9-b215-035a2de53eeb.png)

### Case 2 (Custom model):
seg model only:
![image](https://user-images.githubusercontent.com/66017052/229418510-e257b922-1b97-441b-9fb7-8635735631d8.png)
load two models:
![image](https://user-images.githubusercontent.com/66017052/229418491-3e7c700f-b40f-4c92-9b70-f9bb5937399f.png)

### Additional

I checked the `seg_model.predictor.args` in both cases, but there was no difference. 
When I use the code below, I get the desired result, but the tracking of the `detect_model` is not activated. Probably because the callback is not added.
```python
import cv2
from ultralytics.yolo.v8 import segment, detect

src = 'sample_video.mp4'

detect_predictor = detect.DetectionPredictor(overrides=dict(verbose=False, tracker="botsort.yaml"))
detect_predictor.setup_model(model='yolov8n.pt')
detect_results = detect_predictor(source=src, stream=True)

seg_predictor = segment.SegmentationPredictor(overrides=dict(verbose=False, retina_masks=True))
seg_predictor.setup_model(model='yolov8n-seg.pt')
seg_results = seg_predictor(source=src, stream=True)

save_path = 'output.mp4'
writer = cv2.VideoWriter(save_path, cv2.VideoWriter_fourcc(*'mp4v'), 60, (3840, 1080))

for detect, seg in zip(detect_results, seg_results):
    writer.write(cv2.hconcat([detect.plot(), seg.plot()]))
writer.release()
```
-----

I guess this is happening because they share callbacks, right?

```python
detect_model = YOLO('yolov8n.pt')
seg_model = YOLO('yolov8n-seg.pt')

detect_results = detect_model.track(source=src, verbose=False, tracker="botsort.yaml", stream=True) # This line
seg_results = seg_model.predict(source=src, verbose=False, retina_masks=True, stream=True)

print('detect_model.predictor.callbacks')
print(detect_model.predictor.callbacks)
print('----------------------------------------------------------------------------')
print('seg_model.predictor.callbacks')
print(seg_model.predictor.callbacks)
```

Output: 
```
detect_model.predictor.callbacks
defaultdict(<class 'list'>, {'on_pretrain_routine_start': [<function on_pretrain_routine_start at 0x7f64821e2f80>, <function on_pretrain_routine_start at 0x7f6474235900>], 'on_pretrain_routine_end': [<function on_pretrain_routine_end at 0x7f64821e31c0>, <function on_pretrain_routine_end at 0x7f6474234ee0>], 'on_train_start': [<function on_train_start at 0x7f64821e3250>, <function on_train_start at 0x7f6474235120>], 'on_train_epoch_start': [<function on_train_epoch_start at 0x7f64821e32e0>], 'on_train_batch_start': [<function on_train_batch_start at 0x7f64821e3370>], 'optimizer_step': [<function optimizer_step at 0x7f64821e3400>], 'on_before_zero_grad': [<function on_before_zero_grad at 0x7f64821e3490>], 'on_train_batch_end': [<function on_train_batch_end at 0x7f64821e3520>], 'on_train_epoch_end': [<function on_train_epoch_end at 0x7f64821e35b0>], 'on_fit_epoch_end': [<function on_fit_epoch_end at 0x7f64821e3640>, <function on_fit_epoch_end at 0x7f6474234f70>, <function on_fit_epoch_end at 0x7f6474235750>], 'on_model_save': [<function on_model_save at 0x7f64821e36d0>, <function on_model_save at 0x7f6474235000>], 'on_train_end': [<function on_train_end at 0x7f64821e3760>, <function on_train_end at 0x7f6474235090>], 'on_params_update': [<function on_params_update at 0x7f64821e37f0>], 'teardown': [<function teardown at 0x7f64821e3880>], 'on_val_start': [<function on_val_start at 0x7f64821e3910>, <function on_val_start at 0x7f64742351b0>], 'on_val_batch_start': [<function on_val_batch_start at 0x7f64821e39a0>], 'on_val_batch_end': [<function on_val_batch_end at 0x7f64821e3a30>], 'on_val_end': [<function on_val_end at 0x7f64821e3ac0>], 'on_predict_start': [<function on_predict_start at 0x7f64821e3b50>, <function on_predict_start at 0x7f6482099f30>, <function on_predict_start at 0x7f6474235240>], 'on_predict_batch_start': [<function on_predict_batch_start at 0x7f64821e3be0>], 'on_predict_postprocess_end': [<function on_predict_postprocess_end at 0x7f64821e3d00>, <function on_predict_postprocess_end at 0x7f648209a170>], 'on_predict_batch_end': [<function on_predict_batch_end at 0x7f64821e3c70>], 'on_predict_end': [<function on_predict_end at 0x7f64821e3d90>], 'on_export_start': [<function on_export_start at 0x7f64821e3e20>, <function on_export_start at 0x7f64742352d0>], 'on_export_end': [<function on_export_end at 0x7f64821e3eb0>], 'on_batch_end': [<function on_batch_end at 0x7f64742357e0>]})
----------------------------------------------------------------------------
seg_model.predictor.callbacks
defaultdict(<class 'list'>, {'on_pretrain_routine_start': [<function on_pretrain_routine_start at 0x7f64821e2f80>, <function on_pretrain_routine_start at 0x7f6474235900>], 'on_pretrain_routine_end': [<function on_pretrain_routine_end at 0x7f64821e31c0>, <function on_pretrain_routine_end at 0x7f6474234ee0>], 'on_train_start': [<function on_train_start at 0x7f64821e3250>, <function on_train_start at 0x7f6474235120>], 'on_train_epoch_start': [<function on_train_epoch_start at 0x7f64821e32e0>], 'on_train_batch_start': [<function on_train_batch_start at 0x7f64821e3370>], 'optimizer_step': [<function optimizer_step at 0x7f64821e3400>], 'on_before_zero_grad': [<function on_before_zero_grad at 0x7f64821e3490>], 'on_train_batch_end': [<function on_train_batch_end at 0x7f64821e3520>], 'on_train_epoch_end': [<function on_train_epoch_end at 0x7f64821e35b0>], 'on_fit_epoch_end': [<function on_fit_epoch_end at 0x7f64821e3640>, <function on_fit_epoch_end at 0x7f6474234f70>, <function on_fit_epoch_end at 0x7f6474235750>], 'on_model_save': [<function on_model_save at 0x7f64821e36d0>, <function on_model_save at 0x7f6474235000>], 'on_train_end': [<function on_train_end at 0x7f64821e3760>, <function on_train_end at 0x7f6474235090>], 'on_params_update': [<function on_params_update at 0x7f64821e37f0>], 'teardown': [<function teardown at 0x7f64821e3880>], 'on_val_start': [<function on_val_start at 0x7f64821e3910>, <function on_val_start at 0x7f64742351b0>], 'on_val_batch_start': [<function on_val_batch_start at 0x7f64821e39a0>], 'on_val_batch_end': [<function on_val_batch_end at 0x7f64821e3a30>], 'on_val_end': [<function on_val_end at 0x7f64821e3ac0>], 'on_predict_start': [<function on_predict_start at 0x7f64821e3b50>, <function on_predict_start at 0x7f6482099f30>, <function on_predict_start at 0x7f6474235240>], 'on_predict_batch_start': [<function on_predict_batch_start at 0x7f64821e3be0>], 'on_predict_postprocess_end': [<function on_predict_postprocess_end at 0x7f64821e3d00>, <function on_predict_postprocess_end at 0x7f648209a170>], 'on_predict_batch_end': [<function on_predict_batch_end at 0x7f64821e3c70>], 'on_predict_end': [<function on_predict_end at 0x7f64821e3d90>], 'on_export_start': [<function on_export_start at 0x7f64821e3e20>, <function on_export_start at 0x7f64742352d0>], 'on_export_end': [<function on_export_end at 0x7f64821e3eb0>], 'on_batch_end': [<function on_batch_end at 0x7f64742357e0>]})
```

**Comment by dh031200** [comment] 2023-04-03 06:38
@glenn-jocher Is it against the author's intention that each instance has its own callback?

**Comment by glenn-jocher** [comment] 2023-04-03 08:00
@dh031200 that's strange. Multiple instances of YOLO models should be behaving independently. I wonder if this is caused by stream=True. If you use stream=False do you get the expected independent behavior?

**Comment by dh031200** [comment] 2023-04-03 08:07
@glenn-jocher Can you check this PR if you are ready? #1782

**Comment by glenn-jocher** [comment] 2023-04-03 08:12
@dh031200 I'm not an Ultralytics YOLOv8 maintainer, but I can assure you that the PR you mentioned hasn't been merged yet. You'll have to wait for an official response from the Ultralytics team. In the meantime, you can follow up on the PR or try testing it yourself.

**Comment by glenn-jocher** [comment] 2023-04-03 08:16
@dh031200 thanks! Will review.

**Comment by Sasek-11** [comment] 2023-04-03 12:38
Thanks for your great work and activate help alwasys!
Could I know how to save the tacking results ? I added the save_txt= true, but the output txt.files don't have the ID infromation for each frame/image. Sorry, my question may be not elegent, since I am just new to yolov8. I would appreciate to your kind help.

**Comment by dh031200** [comment] 2023-04-04 00:59
@Sasek-11 
You can get tracking results like this:
```python
from ultralytics import YOLO

# Python
model = YOLO('yolov8n.pt')
results = detect_model.track(source=src, tracker="botsort.yaml", save_txt=True)

# CLI
yolo predict model=yolov8n.pt source=sample.mp4 mode=track tracker=botsort.yaml save_txt=True
```

When complete, the following text will appear.
```
Speed: 1.2ms preprocess, 13.6ms inference, 2.2ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/track
600 labels saved to runs/detect/track/labels
```

And you can find each frame result as a text file.
```bash
# Class    Center_X        Center_Y         Width              Height           Tracking ID
# ---------------------------------------------------------------------------------------------
  29       0.339246        0.640001         0.0464199          0.219422         5
  17       0.37148         0.352645         0.045882           0.701325         4
  5        0.023913        0.763454         0.047826           0.139489         3
  5        0.15741         0.737927         0.127599           0.115596         2
  15       0.688872        0.663878         0.0646999          0.247534         1
```

**Closed** 2023-04-04 04:34 UTC
Labels: question

**Comment by Sasek-11** [comment] 2023-04-05 07:38
> @Sasek-11 You can get tracking results like this:
> 
> ```python
> from ultralytics import YOLO
> 
> # Python
> model = YOLO('yolov8n.pt')
> results = detect_model.track(source=src, tracker="botsort.yaml", save_txt=True)
> 
> # CLI
> yolo predict model=yolov8n.pt source=sample.mp4 mode=track tracker=botsort.yaml save_txt=True
> ```
> 
> When complete, the following text will appear.
> 
> ```
> Speed: 1.2ms preprocess, 13.6ms inference, 2.2ms postprocess per image at shape (1, 3, 640, 640)
> Results saved to runs/detect/track
> 600 labels saved to runs/detect/track/labels
> ```
> 
> And you can find each frame result as a text file.
> 
> ```shell
> # Class    Center_X        Center_Y         Width              Height           Tracking ID
> # ---------------------------------------------------------------------------------------------
>   29       0.339246        0.640001         0.0464199          0.219422         5
>   17       0.37148         0.352645         0.045882           0.701325         4
>   5        0.023913        0.763454         0.047826           0.139489         3
>   5        0.15741         0.737927         0.127599           0.115596         2
>   15       0.688872        0.663878         0.0646999          0.247534         1
> ```

Thank you so much for your kind help !!! But  I am using yolov8 segment model. It seems 'save_txt' shown above only works with detect model. I tried with same cmd but the output.file are like : Classed iD /// Mask coordinate . The last column does not show track_id. I am sorry for my clumsy question. For segment model, how should I do with it ?

**Comment by dh031200** [comment] 2023-04-05 08:08
@Sasek-11 
When I run below code, the result was saved including track_id.
```python
from ultralytics import YOLO

# Python
src = 'sample.mp4'
model = YOLO('yolov8n-seg.pt')
results = model.track(source=src, tracker="botsort.yaml", save_txt=True, project='run')

# CLI
yolo predict model=yolov8n-seg.pt source=sample.mp4 mode=track tracker=botsort.yaml save_txt=True
```

What version of `ultralytics` are you on?
If not latest, how about updating ultralytics?

`pip install -U ultralytics`

These are some of my results.:
[sample_1.txt](https://github.com/ultralytics/ultralytics/files/11156490/sample_1.txt)
[sample_2.txt](https://github.com/ultralytics/ultralytics/files/11156491/sample_2.txt)
[sample_3.txt](https://github.com/ultralytics/ultralytics/files/11156492/sample_3.txt)

**Comment by glenn-jocher** [comment] 2023-04-05 10:27
@dh031200 the user wants to save tracking results for YOLOv8 segment models. Using `save_txt` flag in `model.track()` method should be enough to save results including tracking ID. However, their results do not include tracking ID in the output file. Updating `ultralytics` package to the latest version could potentially fix the issue.
