### ISSUE TITLE
always data=coco8.yaml

### ISSUE THREAD

**Issue by DnEcing** [ultralytics/ultralytics#6914] opened 2023-12-11 09:40 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

When I modify the parameter configuration with default.yaml, the 'data' item cannot be overwritten, it always data=coco8.yaml
Custom dataset training can only be implemented with model.train(data=mydata.yaml)
Is this a bug?
![image](https://github.com/ultralytics/ultralytics/assets/114732610/2d3910bc-7e10-4867-b284-812f1d9b0c2c)

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment] 2023-12-11 20:31
@DnEcing hello! 👋 It sounds like you're experiencing an issue where the `data` parameter from `default.yaml` is not being overwritten as expected. This definitely shouldn't be the case, as you should be able to specify a custom data configuration file for your training.

When using `train()`, passing the `data` argument with your custom `.yaml` file should indeed overwrite the default set in `default.yaml`. If that's not happening, it could indeed be indicative of a bug.

I recommend ensuring that your custom configuration file is properly formatted and located in the correct directory. If the problem persists after verifying this, it would be helpful if you could raise an issue on our [issues page](https://github.com/ultralytics/ultralytics/issues) with detailed steps to reproduce it, so we can investigate further.

Thanks for offering to submit a PR! If you manage to identify the cause and a fix, we would highly appreciate your contribution to the YOLOv8 community. If any more guidance is needed, please refer to our documentation or reach out again. Happy coding! 😊

**Comment by glenn-jocher** [comment] 2023-12-11 23:08
@DnEcing hey I'm able to reproduce the problem, thanks for raising this bug report! I don't know the exact cause but I've added a TODO tag to track this for a fix.

**Comment by glenn-jocher** [comment] 2023-12-12 00:26
@DnEcing resolved in #6935

**Closed** 2023-12-12 00:40 UTC
Labels: bug, fixed

**Comment by DnEcing** [comment] 2023-12-12 01:42
@glenn-jocher Thank you for your positive reply and efficient repair！

**Comment by glenn-jocher** [comment] 2023-12-12 13:06
@DnEcing you're welcome! The YOLOv8 community is always our top priority. Happy to help and keep the feedback coming! 😄🚀
