### ISSUE TITLE
Cannot use Yolo models converted to EdgeTPU.

### ISSUE THREAD

**Issue by saradaman** [ultralytics/ultralytics#4869] opened 2023-09-13 02:33 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am planning to convert yolov5s.pt to EdgeTPU.
The conversion will be used for object detection using Coral's external TPU and Raspberry Pi.

The following program was used to perform the conversion, based on the official page below.
[ultralytics:Export](https://docs.ultralytics.com/modes/export/)

```
from ultralytics import YOLO

# Load a model
model = YOLO('/content/yolov5s.pt')  # The production will use the transition-trained model.

# Export the model
model.export(format='edgetpu')
```
When this code is executed, the edgetpu model is output without any errors.

However, when I try to run the program with EdgeTPU, the TPU is not used.
Is the conversion working in the first place...

Just to be sure, we converted once to tflite and further converted using the Edge compiler provided by Coral, with the same result.
Incidentally, at this time I passed int8 as an argument to perform the conversion.
[Coral:Edge compiler](https://coral.ai/docs/edgetpu/compiler/#system-requirements)

As can be seen from the log output during the conversion, the allocation to the TPU is set to 0.
```
Number of operations that will run on Edge TPU: 0
Number of operations that will run on CPU: 348
```
Therefore, even with the converted model and TPU, object detection using TPU is still not possible.
Is there anything missing?

Thank you in advance for your response.

### Additional

The conversion to EdgeTPU was done by GoogleColaboratory.

**Comment by RizwanMunawar** [comment] 2023-09-13 06:15
@saradaman! The export conversion appears to be finished, but the TFLite file hasn't undergone full quantization for TPU. To achieve this, make sure to include the `int8=True` option during export. For effortless conversion of the model to Edge TPU with TPU support, utilize the [ultralytics-notebook](https://colab.research.google.com/drive/1TSAOjMDtHhGE39tHotul7vlK6eu9hh5F?usp=sharing)

I used the mentioned steps for exporting the model to tflite and then converted the model to TPU with the edgeTPU module.

```
from ultralytics import YOLO

model = YOLO('yolov5s.pt') 

model.export(format='tflite',int8=True)
```
The above code will provide a file name "yolov5su_full_integer_quant.tflite", you can use that file with the mentioned command to convert the model to edgeTPU and it will support TPU operations.

```
edgetpu_compiler "/content/yolov5su_saved_model/yolov5su_full_integer_quant.tflite"
```
### Export Output
```
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.

Model compiled successfully in 21747 ms.

Input model: /content/yolov5su_saved_model/yolov5su_full_integer_quant.tflite
Input size: 8.85MiB
Output model: yolov5su_full_integer_quant_edgetpu.tflite
Output size: 10.12MiB
On-chip memory used for caching model parameters: 6.36MiB
On-chip memory remaining for caching model parameters: 0.00B
Off-chip memory used for streaming uncached model parameters: 2.44MiB
Number of Edge TPU subgraphs: 1
Total number of operations: 278
Operation log: yolov5su_full_integer_quant_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 252
Number of operations that will run on CPU: 26
See the operation log file for individual operation details.
Compilation child process completed within timeout period.
Compilation succeeded! 
```

**Comment by saradaman** [comment] 2023-09-13 06:35
@RizwanMunawar 
Thank you for your response.
The following identically named .tflite file was output when using ultralytics' Export and when using Coral's Edge compiler.
`yolov5su_full_integer_quant.tflite`
I looked at the file size and there was only a 1KB difference between both, are these the exact same thing?

We also loaded the converted model with the following program.
```
import numpy as np
from PIL import Image, ImageDraw, ImageFont
import tflite_runtime.interpreter as tflite
import time

model_path = 'yolov5su_integer_full_quant_edgetpu.tflite'
interpreter = tflite.Interpreter(model_path=model_path,experimental_delegates=[tflite.load_delegate('libedgetpu.so.1')])
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
print(input_details)
print('----------------------------------------------------------------------')
print(output_details)
```
Then, the following output was obtained.
```
[{'name': 'serving_default_images:0', 'index': 0, 'shape': array([  1, 640, 640,   3]), 'shape_signature': array([  1, 640, 640,   3]), 'dtype': <class 'numpy.int8'>, 'quantization': (0.01865844801068306, -14), 'quantization_parameters': {'scales': array([0.01865845], dtype=float32), 'zero_points': array([-14]), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
----------------------------------------------------------------------
[{'name': 'PartitionedCall:0', 'index': 48, 'shape': array([   1,    5, 8400]), 'shape_signature': array([   1,    5, 8400]), 'dtype': <class 'numpy.int8'>, 'quantization': (0.004384140018373728, -119), 'quantization_parameters': {'scales': array([0.00438414], dtype=float32), 'zero_points': array([-119]), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
```
Is this normal?
The shape of the output tensor is `(1,5,8400)`, does it sound like the inference result is included in this?
(Bounding box coordinates, class ID, estimated value, etc...)

**Comment by RizwanMunawar** [comment] 2023-09-13 06:52
@saradaman `yolov5su_full_integer_quant.tflite` is a TFLite file that has undergone complete `int8` quantization. If you export a TFLite model without int8 quantization, it will be in the fp32 format, which is not supported by the EdgeTPU.

It seems that the conversion is precise, and the model should effectively identify objects. Regarding the YOLOv5s COCO model, it yields an output tensor of (1,84,8400), which corresponds to 80 classes. However, in your scenario, I presume you intend to detect a single class, correct?

You can further inspect the layers and output format by using the [Netron](https://netron.app/).

**Comment by saradaman** [comment] 2023-09-13 08:56
Thank you for your response.
I apologize for the explanation.
Currently, yolov5s is being trained to transition and detect certain objects.
We have training data that can annotate an image and recognize the object as, for example, a car.
We used that dataset to train on and then converted it to edgeTPU.
The results using that converted EdgeTPU are shown above.
I just assumed that an output tensor of (1,84,8400) would be generated, but I was wondering if the shape of the output tensor changes when the transition is learned?
(I apologize for my complete lack of knowledge in this area.)
By the way, I looked at it using the Netron you just shared, and the final output was still (1, 5, 8400).

**Comment by RizwanMunawar** [comment] 2023-09-13 09:12
@saradaman If you trained the model to detect car than the output format `(1,5,8400)` is fine.

**Comment by saradaman** [comment] 2023-09-15 06:55
@RizwanMunawar 
Thank you for your thoughtful response.
I am relieved that the conversion seems to be working for now.
From here, we will look a little further into how to successfully perform object detection.
Thank you so much.

**Comment by RizwanMunawar** [comment] 2023-09-15 07:16
@saradaman Great News! I wish you the best of luck for your project.

**Comment by RizwanMunawar** [comment] 2023-09-22 13:04
I am closing this issue. Please reopen if the issue persists

**Closed by RizwanMunawar** 2023-09-22 13:04 UTC
Labels: question, fixed

**Comment by FoxieK** [comment] 2024-01-17 11:22
Hello! sorry for reopening this issue, but i think i think my problem is quite related to this one.

I've trained and exported successfully a YOLOv8 model using `yolo export model={MODEL_PATH} format=edgetpu int8=True imgsz=192` into a quantized compatible model for my coral edgetpu.
![image](https://github.com/ultralytics/ultralytics/assets/92261030/4e973583-e799-4dd3-847e-cc6733a362d0)
which it looks like this in netron: 
![image](https://github.com/ultralytics/ultralytics/assets/92261030/0197d6af-8534-4ecd-9f83-a195a2331d25)
![image](https://github.com/ultralytics/ultralytics/assets/92261030/23922273-fb09-445d-bb0a-c593a6ef1064)
So my output tensor has a shape of `(1,5,756)` because i down scaled the images to 192x192px and detect only 1 class.

The problem is when i use this model to do inference using pycoral libraries, i encountered the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "webstream_edgetpu.py", line 157, in detect_motion
    objs = get_objects(interpreter, 0.25)
  File "/opt/plcnext/.local/lib/python3.8/site-packages/pycoral/adapters/detect.py", line 214, in get_objects
    elif common.output_tensor(interpreter, 3).size == 1:
  File "/opt/plcnext/.local/lib/python3.8/site-packages/pycoral/adapters/common.py", line 29, in output_tensor
    return interpreter.tensor(interpreter.get_output_details()[i]['index'])()
IndexError: list index out of range
```
The error is generated by this piece of code:
```
run_inference(interpreter, cv2_im_rgb.tobytes())
objs = get_objects(interpreter, 0.25) <--- The error is here
cv2_im = append_objs_to_img(cv2_im, inference_size, objs, labels)
```
I think the problem here is that the `get_objects()` function tries to iterate on the output data but i only got one index:
```
[{'name': 'PartitionedCall:0', 'index': 1, 'shape': array([  1,   5, 756], dtype=int32), 'shape_signature': array([  1,   5, 756], dtype=int32), 'dtype': <class 'numpy.int8'>, 'quantization': (0.013924574479460716, -117), 'quantization_parameters': {'scales': array([0.01392457], dtype=float32), 'zero_points': array([-117], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
```

So i tried something else:
```
output_data = interpreter.get_tensor(output_details[0]['index'])[0]
```
and the `output_data` tensor looks like this:
```
[[-113 -109 -107 ...  -92  -76  -69]
 [-112 -111 -113 ...  -51  -52  -51]
 [-108 -102  -97 ...   46   67   15]
 [-107 -105 -109 ...   24   23   36]
 [-117 -117 -117 ... -117 -117 -117]]
```

Now the fact is i don't know how to decode the bounding box coordinates, class score, and other relevant information from that tensor which row is the bboxes, scores etc..?
How did you manage to read the data and draw the bboxes and scores? @saradaman 

If someone knows please let me know, thank you!

**Comment by pvtoan** [comment] 2025-01-17 01:08
Hi @FoxieK, 

I have the same issue, so, I'd like to know if you have already resolved this issue?

Also, appreciate if anyone know how to fix this issue?
