### ISSUE TITLE
YoloV8, SAHI, and PyQT crashes in Windows, but it works fine on Ubuntu

### ISSUE THREAD

**Issue by gguzzy** [ultralytics/ultralytics#16036] opened 2024-09-05 13:12 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Other

### Bug

Hi dear all,
when using pyqt, sahi and ultralytics, when running inference on Ubuntu, all goes smoothly, no exceptions or errors arise; whereas using the same version of YoloV8 on Windows does not work properly i.e. giving back an error of the form:

```
 '<qt_gui_utils.Capture object at 0x0000026366159AB0> < cv2.VideoCapture 0000026366039BF0>
Performing prediction on 1 slices.
save 0: ./acquisitions\2024-09-05\034_ZekqQkMT\0000_label_ZekqQkMT.png

Process finished with exit code -1073741819 (0xC0000005)'
```

As you can see, it performs the prediction correctly, but somehow when it should open and capture another frame, the new detection window (the window where the predictions are visualized) lags and eventually crashes reporting the aforementioned problem.

What is even weirder, is that changing version from yolov8 to yolov5 (I used AutoDetectionModel) works on both operating systems (Ubuntu and Windows 11). 

I tried to change dimensions of windows, recreate an ad hoc environment, but still it gives me back the exact same error and crashes. 

I hope you can help me find the reason why. 

### Environment

Ultralytics YOLOv8.2.87 🚀 Python-3.10.0 torch-2.3.1+cpu CPU (13th Gen Intel Core(TM) i7-13700H)
Setup complete ✅ (20 CPUs, 15.7 GB RAM, 281.3/293.0 GB disk)

### Minimal Reproducible Example

```python
    def init_camera(self):
        self.capture = Capture()
        self.converter = Converter()

        self.captureThread = QtCore.QThread(self)
        self.converterThread = QtCore.QThread(self)
        self.converter.setProcessAll(False)

        self.captureThread.start()
        self.converterThread.start()

        # move obj to thread
        self.capture.moveToThread(self.captureThread)
        self.converter.moveToThread(self.converterThread)

        # connect signals
        self.capture.frameReady.connect(self.converter.processFrame)
        self.converter.imageReady.connect(self.set_image)
        self.capture.error.connect(self.alert)
        self.capture.started.connect(self.capture_started)

        # connect btn signals
        self.btn_camStart.clicked.connect(self.capture.start)
        # self.btn_cam_start.clicked.connect(self.local_start) # non si puo fare con i timer e i thread
        self.btn_camStop.clicked.connect(self.capture.stop)
        self.cmb_camType.currentTextChanged.connect(self.set_video_capture)
        
        ----

    def capturePhoto(self, save_type, jpeg=False):
        self.overlay.setVisible(True)
        QTimer.singleShot(2000, self.hideOverlay)

        # create folder if not exist
        if not os.path.exists(self.out_folder):
            os.makedirs(self.out_folder, exist_ok=True)

        ext = 'jpg' if jpeg else 'png'
        out = os.path.join(
            self.out_folder, f"{self.save_counter:04d}_{save_type}_{self.task_name}.{ext}")
        self.imageLabel.pixmap().save(out, format=ext, quality=75)
        self.led_acquisitionReady.setChecked(True)
        if self.btn_enableDetection.isChecked():
            window_name = 'Detection'
            cv2.namedWindow(window_name, cv2.WINDOW_KEEPRATIO)
            cv2.resizeWindow(window_name, 800, 612)

            sliced_pred_result = get_sliced_prediction(
                out,
                self.detection_model,
                overlap_height_ratio=0.45,
                overlap_width_ratio=0.45,
                slice_width=640,
                slice_height=640,
                postprocess_match_threshold=0.3,
                postprocess_class_agnostic=True,
                postprocess_type='NMS',
            )

            img_detected = self.visualize_object_predictions(
                image=np.ascontiguousarray(sliced_pred_result.image),
                object_prediction_list=sliced_pred_result.object_prediction_list,
                rect_th=3,
                text_size=1,
                text_th=2,
                # color=(0, 0, 255),
                output_dir=os.path.join('acquisitions_pred', datetime.datetime.now().strftime('%Y-%m-%d')),
                file_name=f"{self.save_counter:04d}_{save_type}_{self.task_name}"+"_pred",
                export_format='png'
            )

            cv2.imshow(window_name, cv2.cvtColor(
                img_detected['image'], cv2.COLOR_BGR2RGB))

            print(f"save {self.save_counter}: {out}")


    def capturePhoto(self, save_type, jpeg=False):
        self.overlay.setVisible(True)
        QTimer.singleShot(2000, self.hideOverlay)

        # create folder if not exist
        if not os.path.exists(self.out_folder):
            os.makedirs(self.out_folder, exist_ok=True)

        ext = 'jpg' if jpeg else 'png'
        out = os.path.join(
            self.out_folder, f"{self.save_counter:04d}_{save_type}_{self.task_name}.{ext}")
        self.imageLabel.pixmap().save(out, format=ext, quality=75)
        self.led_acquisitionReady.setChecked(True)
        if self.btn_enableDetection.isChecked():
            window_name = 'Detection'
            cv2.namedWindow(window_name, cv2.WINDOW_KEEPRATIO)
            cv2.resizeWindow(window_name, 800, 612)

            sliced_pred_result = get_sliced_prediction(
                out,
                self.detection_model,
                overlap_height_ratio=0.45,
                overlap_width_ratio=0.45,
                slice_width=640,
                slice_height=640,
            )

            # print("sliced_pred_result ottenute:", sliced_pred_result)

            img_detected = self.visualize_object_predictions(
                image=np.ascontiguousarray(sliced_pred_result.image),
                object_prediction_list=sliced_pred_result.object_prediction_list,
                rect_th=3,
                text_size=1,
                text_th=2,
                # color=(0, 0, 255),
                output_dir=os.path.join('acquisitions_pred', datetime.datetime.now().strftime('%Y-%m-%d')),
                file_name=f"{self.save_counter:04d}_{save_type}_{self.task_name}"+"_pred",
                export_format='png'
            )

            # im_fake_pred=cv2.imread('0000_label_NyI5IDMS_pred.png')
            # print("img_detected ottenute:", img_detected)

            cv2.imshow(window_name, cv2.cvtColor(
                img_detected['image'], cv2.COLOR_BGR2RGB))

            print(f"save {self.save_counter}: {out}")
```

### Additional

When I used those pieces of code, when running capturePhoto, it fails on set_image on the setPixMap and crashes.

I cannot understand why, the code seems fine in Ubutu, I think there is some issues on Ultralytics library.

I hope you can help me out solving this issue. 

Thanks.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by gguzzy** [comment] 2024-09-05 13:16
Please report only serious answers. How can you even answer before I published the question?

**Comment by ambitious-octopus** [comment] 2024-09-05 13:48
Ciao @gguzzy, can you please provide a Minimal Reproducible Example, the code you provided seems to be partial.

**Comment by gguzzy** [comment] 2024-09-05 13:57
Ciao caro,
I will try my best to publish a smaller version, I ask you to wait some time to do so.

Thanks.

**Comment by glenn-jocher** [comment] 2024-09-05 20:12
Sure, take your time. When you're ready, please provide the smaller version, and we'll assist you further.

**Comment by gguzzy** [comment] 2024-09-10 09:56
Hi guys, I cannot share the code here, but what I found is that the thread on the button was stopping the normal execution of the flow in the prediction (what I think is that yolov8 wrt yolov5, forces to close or handles the cv window), whereas forcing to close the capture of the photo everytime when the execution button is it, and closing an additional cv window, allows to work the code smoothly.

So for anyone working with Sahi, YoloV8, Ultralytics and pyqt6 I want to share that the thread has to be close before the new capture, wrt the yolov5 version. This worked for me.

Thanks.

**Comment by glenn-jocher** [comment] 2024-09-10 19:20
Thank you for sharing your findings. It's great to hear that closing the thread before a new capture resolved the issue for you. If you have any further questions or need assistance, feel free to ask.

**Comment by gguzzy** [comment] 2024-09-11 10:18
Yeah thanks, as references this issue was shared with this manners:

[https://github.com/ultralytics/ultralytics/issues/9163#issuecomment-2332258528](url)

I think the error comes from get_sliced_prediction, which now (wrt YoloV5 version) handles the cv windows differently (maybe due to multiprocessing) 

I think this can be referenced as a workaround for this error 'Process finished with exit code -1073741819 (0xC0000005)' which I recall is not present running the same exact code in a Ubuntu (linux alike) operating systems, whereas the YoloV5 version works for both operating systems. 

Thanks again still for the help, I think it is now working because I forced the detector to make predictions one capture at a time.

**Comment by glenn-jocher** [comment] 2024-09-13 01:23
@gguzzy thank you for sharing your insights. It seems like handling predictions one capture at a time has resolved the issue. If you need further assistance, feel free to reach out.

**Closed** 2024-09-16 08:31 UTC
Labels: bug, dependencies, detect
