### ISSUE TITLE
How to control tracker parameter for better performance?

### ISSUE THREAD

**Issue by dedoogong** [ultralytics/ultralytics#4473] opened 2023-08-21 08:48 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello. Thank you for sharing this art work.
I'm trying to use your code and I wonder what paramters are the nice options for better tracking performance.
I think below params in cfg bottrack.yaml and self.std_xxx params in kalman_filter.py is all. 
tracker_type: botsort  # tracker type, ['botsort', 'bytetrack']
track_high_thresh: 0.5  # threshold for the first association
track_low_thresh: 0.1  # threshold for the second association
new_track_thresh: 0.6  # threshold for init new track if the detection does not match any tracks
track_buffer: 30  # buffer to calculate the time when to remove tracks
match_thresh: 0.8  # threshold for matching tracks

self._std_weight_position = 1. / 20
self._std_weight_velocity = 1. / 160

Can you please add more guide or explanation what is the meaning of each? and what is the impact?
plus I think to control the kalman filter performance, Q, R matrix or other variance matrix are the usual key factor but I can't find it. 
Can you help me?

**Comment by glenn-jocher** [comment] 2023-08-21 13:24
@dedoogong hello,

Thank you for your kind words and for reaching out with your question. I'd be happy to provide further explanation on the parameters you've listed as they significantly impact tracking performance in YOLOv8.

1. `tracker_type`: This specifies the type of tracker to be used, options are `botsort` and `bytetrack`.

2. `track_high_thresh`: This is the threshold used for initial association of a detection with a track. If the detection's score is above this threshold, it could be associated in the first round.

3. `track_low_thresh`: This is the threshold used for secondary association. If a detection wasn't associated in the first round and its score is higher than this, it might still be associated in a second round.

4. `new_track_thresh`: This is the threshold used for starting a new track. If a detection doesn't match any existing tracks and its score is above this threshold, a new track will be initialized.

5. `track_buffer`: This is the amount of time allowed to pass without receiving updates from a track before it will be removed. Higher values allow tracks to remain active longer without updates, which might help with intermittent detections but could increase the risk of tracking errors.

6. `match_thresh`: This threshold is used for matching tracks between consecutive frames. Only tracks with a score above this threshold are considered for matching.

7. `_std_weight_position`: This factor is used to weight position information in the Kalman filter. Lower values give more weight to position in predictions and updates.

8. `_std_weight_velocity`: This factor is used to weight velocity in the Kalman filter. Similar to position, lower values give more weight to velocity.

Regarding the Kalman filter parameters, you're right that the Q and R matrices typically control the filter's performance. In our current implementation, however, these matrices are not exposed for configuration. Alternatives would involve adjusting `_std_weight_position` and `_std_weight_velocity` as they indirectly influence the behavior of the Kalman filter within the tracking process.

I hope this helps you understand these parameters better for tuning the tracking performance of YOLOv8. If you have further questions, don't hesitate to ask.

Best,
Glenn

**Comment by marco-monforte** [comment] 2023-08-23 09:22
Hi @glenn-jocher , is ```track_buffer``` expressed in milliseconds, seconds or which scale? Thanks!

**Comment by dedoogong** [comment] 2023-08-24 09:02
Thanks for your answer~!
I wonder, yolo tracker results not only bbox but masks so that I think yolov8n-seg model run for every frame. right?
I thought, the model gives detection and segmentation for the first frame and every 30 frames(or some thing like that) periodically and then tracker is used for the other frames like a common visual odometry. But now I think it's wrong and detection is alro run for the every frame. Am I right?
Howevery, regarding inference time, when I actiavete verbose mode, it shows, around 5ms every frame and every 20~40 frames the time get much bigger like 45ms~80ms. 
I'm confused. Please please give me some hint about the process.

**Comment by glenn-jocher** [comment] 2023-08-24 17:20
Hello @dedoogong,

Your understanding is partially correct. YOLOv8 indeed runs on every frame delivering both detection and segmentation results. The tracker does not take over for intermediary frames, rather, it's utilized in conjunction with the model's predictions on every frame to maintain the identity of the objects across frames over time.

As for your observed inference times, the fluctuation you're seeing (from 5ms to greater times) most likely arises from the varying complexity of the frames. More complex frames with more objects or more detailed segmentation tasks will take longer to process, hence the larger inference times. However, note that this does not imply that the model works only on these frames, it continues to infer every frame, but varying computational effort may cause the time discrepancies you observe.

I hope this clears up the tracking process a bit more. Let me know if you have any more questions.

Best,
Glenn

**Closed** 2023-08-29 05:47 UTC
Labels: question

**Comment by mattiasospetti** [comment] 2024-04-24 09:58
> Hi @glenn-jocher , is `track_buffer` expressed in milliseconds, seconds or which scale? Thanks!

`self.buffer_size = int(frame_rate / 30.0 * args.track_buffer)` (from [BoTSort python tracker](https://github.com/NirAharon/BoT-SORT/blob/main/tracker/bot_sort.py)).
So I guess it is the number of precedent frames.

**Comment by glenn-jocher** [comment] 2024-04-24 20:22
Hello there! 👋 You're correct, the `track_buffer` is essentially expressed in terms of frames, not time units like seconds or milliseconds. It represents the maximum number of frames that a track can be kept without being updated with new detections. So, if your video is 30 fps and you set `track_buffer` to 30, it means the tracker can keep an inactive track for about 1 second. Hope this helps clear things up! 😊

**Comment by marco-monforte** [comment] 2024-04-25 12:57
Thanks, both of you! :) @mattiasospetti @glenn-jocher

**Comment by glenn-jocher** [comment] 2024-04-25 14:34
You're welcome! 😊 If you have any more questions or need further assistance, feel free to ask. Happy coding!

**Comment by Moizcode** [comment] 2024-06-20 05:44
Hii,
My question is that I am using the Yolov8n tracker for face tracking, and sometimes the track ID of the same person changes. I am trying to figure out why this happening. The problem is that Detection happens but it can't able to associate it with the existing track ID and assign a new track ID. 
Also, I checked that processed video and found out that the ID suddenly changed, it is not a case of "Track_buffer".
I understand all your parameters, can you please describe how "match_thresh" works between frames to match the same person with the same track ID?

Thank you.

**Comment by Moizcode** [comment] 2024-06-20 06:12
My second question is where we change the parameter of this tracker. For example, if we want to change "track_buffer, " then where we pass the new value.

**Comment by cacaluote** [comment] 2024-07-10 02:21
> Hello there! 👋 You're correct, the `track_buffer` is essentially expressed in terms of frames, not time units like seconds or milliseconds. It represents the maximum number of frames that a track can be kept without being updated with new detections. So, if your video is 30 fps and you set `track_buffer` to 30, it means the tracker can keep an inactive track for about 1 second. Hope this helps clear things up! 😊

If detect one frame per second in 30 fps video，what should `track_buffer` be set

**Comment by glenn-jocher** [comment] 2024-07-10 09:45
@cacaluote hello! 👋

If you're detecting one frame per second in a 30 fps video, you'll want to set the `track_buffer` to a value that accommodates the 29 frames in between detections. In this case, setting `track_buffer` to 30 should work well, as it allows the tracker to maintain the track for approximately one second (30 frames) without an update.

Here's a quick example:
```yaml
track_buffer: 30  # Keeps the track for 1 second in a 30 fps video
```

This setting ensures that even if detections are only made once per second, the tracker will still maintain the object IDs consistently. If you have any more questions or need further assistance, feel free to ask! 😊

**Comment by 0xzre** [comment] 2025-02-23 11:46
HI, is there a way to select args for ultralytics tracker without specifying on outside file (.yaml) ? like args as param?

**Comment by glenn-jocher** [comment] 2025-02-26 19:24
Hi @0xzre,

Yes, you can pass tracker parameters directly in Python without a YAML file. Use a `Namespace` object to set your desired parameters programmatically:

```python
from types import SimpleNamespace
from ultralytics import YOLO

args = SimpleNamespace(track_high_thresh=0.5, track_buffer=30, match_thresh=0.8)  # your params
model = YOLO("yolov8n.pt").track(source="video.mp4", tracker=args)
```

This approach avoids external config files while letting you customize tracking behavior. For parameter details, see the [tracker configuration docs](https://docs.ultralytics.com/modes/track/#tracker-selection).

**Comment by ramelito** [comment] 2025-05-01 19:41
SimpleNamespace not working any more

File [~/dev/ultralytics/.venv/lib/python3.9/site-packages/ultralytics/engine/model.py:593](http://localhost:8890/lab/tree/~/dev/ultralytics/.venv/lib/python3.9/site-packages/ultralytics/engine/model.py#line=592), in Model.track(self, source, stream, persist, **kwargs)
    591 kwargs["batch"] = kwargs.get("batch") or 1  # batch-size 1 for tracking in videos
    592 kwargs["mode"] = "track"
--> 593 return self.predict(source=source, stream=stream, **kwargs)

File [~/dev/ultralytics/.venv/lib/python3.9/site-packages/ultralytics/engine/model.py:549](http://localhost:8890/lab/tree/~/dev/ultralytics/.venv/lib/python3.9/site-packages/ultralytics/engine/model.py#line=548), in Model.predict(self, source, stream, predictor, **kwargs)
    547 if prompts and hasattr(self.predictor, "set_prompts"):  # for SAM-type models
    548     self.predictor.set_prompts(prompts)
--> 549 return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)

File [~/dev/ultralytics/.venv/lib/python3.9/site-packages/ultralytics/engine/predictor.py:218](http://localhost:8890/lab/tree/~/dev/ultralytics/.venv/lib/python3.9/site-packages/ultralytics/engine/predictor.py#line=217), in BasePredictor.__call__(self, source, model, stream, *args, **kwargs)
    216     return self.stream_inference(source, model, *args, **kwargs)
    217 else:
--> 218     return list(self.stream_inference(source, model, *args, **kwargs))

File [~/dev/ultralytics/.venv/lib/python3.9/site-packages/torch/utils/_contextlib.py:36](http://localhost:8890/lab/tree/~/dev/ultralytics/.venv/lib/python3.9/site-packages/torch/utils/_contextlib.py#line=35), in _wrap_generator.<locals>.generator_context(*args, **kwargs)
     33 try:
     34     # Issuing `None` to a generator fires it up
     35     with ctx_factory():
---> 36         response = gen.send(None)
     38     while True:
     39         try:
     40             # Forward the response to our caller and get its next request

File [~/dev/ultralytics/.venv/lib/python3.9/site-packages/ultralytics/engine/predictor.py:318](http://localhost:8890/lab/tree/~/dev/ultralytics/.venv/lib/python3.9/site-packages/ultralytics/engine/predictor.py#line=317), in BasePredictor.stream_inference(self, source, model, *args, **kwargs)
    312 self.seen, self.windows, self.batch = 0, [], None
    313 profilers = (
    314     ops.Profile(device=self.device),
    315     ops.Profile(device=self.device),
    316     ops.Profile(device=self.device),
    317 )
--> 318 self.run_callbacks("on_predict_start")
    319 for self.batch in self.dataset:
    320     self.run_callbacks("on_predict_batch_start")

File [~/dev/ultralytics/.venv/lib/python3.9/site-packages/ultralytics/engine/predictor.py:497](http://localhost:8890/lab/tree/~/dev/ultralytics/.venv/lib/python3.9/site-packages/ultralytics/engine/predictor.py#line=496), in BasePredictor.run_callbacks(self, event)
    495 """Run all registered callbacks for a specific event."""
    496 for callback in self.callbacks.get(event, []):
--> 497     callback(self)

File [~/dev/ultralytics/.venv/lib/python3.9/site-packages/ultralytics/trackers/track.py:41](http://localhost:8890/lab/tree/~/dev/ultralytics/.venv/lib/python3.9/site-packages/ultralytics/trackers/track.py#line=40), in on_predict_start(predictor, persist)
     38 if hasattr(predictor, "trackers") and persist:
     39     return
---> 41 tracker = check_yaml(predictor.args.tracker)
     42 cfg = IterableSimpleNamespace(**yaml_load(tracker))
     44 if cfg.tracker_type not in {"bytetrack", "botsort"}:

File [~/dev/ultralytics/.venv/lib/python3.9/site-packages/ultralytics/utils/checks.py:559](http://localhost:8890/lab/tree/~/dev/ultralytics/.venv/lib/python3.9/site-packages/ultralytics/utils/checks.py#line=558), in check_yaml(file, suffix, hard)
    547 def check_yaml(file, suffix=(".yaml", ".yml"), hard=True):
    548     """
    549     Search[/download](http://localhost:8890/download) YAML file (if necessary) and return path, checking suffix.
    550 
   (...)
    557         (str): Path to the YAML file.
    558     """
--> 559     return check_file(file, suffix, hard=hard)

File [~/dev/ultralytics/.venv/lib/python3.9/site-packages/ultralytics/utils/checks.py:521](http://localhost:8890/lab/tree/~/dev/ultralytics/.venv/lib/python3.9/site-packages/ultralytics/utils/checks.py#line=520), in check_file(file, suffix, download, download_dir, hard)
    507 def check_file(file, suffix="", download=True, download_dir=".", hard=True):
    508     """
    509     Search[/download](http://localhost:8890/download) file (if necessary) and return path.
    510 
   (...)
    519         (str): Path to the file.
    520     """
--> 521     check_suffix(file, suffix)  # optional
    522     file = str(file).strip()  # convert to string and strip spaces
    523     file = check_yolov5u_filename(file)  # yolov5n -> yolov5nu

File [~/dev/ultralytics/.venv/lib/python3.9/site-packages/ultralytics/utils/checks.py:458](http://localhost:8890/lab/tree/~/dev/ultralytics/.venv/lib/python3.9/site-packages/ultralytics/utils/checks.py#line=457), in check_suffix(file, suffix, msg)
    456     suffix = (suffix,)
    457 for f in file if isinstance(file, (list, tuple)) else [file]:
--> 458     s = Path(f).suffix.lower().strip()  # file suffix
    459     if len(s):
    460         assert s in suffix, f"{msg}{f} acceptable suffix is {suffix}, not {s}"

File [/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/pathlib.py:1072](http://localhost:8890/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/pathlib.py#line=1071), in Path.__new__(cls, *args, **kwargs)
   1070 if cls is Path:
   1071     cls = WindowsPath if os.name == 'nt' else PosixPath
-> 1072 self = cls._from_parts(args, init=False)
   1073 if not self._flavour.is_supported:
   1074     raise NotImplementedError("cannot instantiate %r on your system"
   1075                               % (cls.__name__,))

File [/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/pathlib.py:697](http://localhost:8890/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/pathlib.py#line=696), in PurePath._from_parts(cls, args, init)
    692 @classmethod
    693 def _from_parts(cls, args, init=True):
    694     # We need to call _parse_args on the instance, so as to get the
    695     # right flavour.
    696     self = object.__new__(cls)
--> 697     drv, root, parts = self._parse_args(args)
    698     self._drv = drv
    699     self._root = root

File [/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/pathlib.py:681](http://localhost:8890/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/pathlib.py#line=680), in PurePath._parse_args(cls, args)
    679     parts += a._parts
    680 else:
--> 681     a = os.fspath(a)
    682     if isinstance(a, str):
    683         # Force-cast str subclasses to str (issue #21127)
    684         parts.append(str(a))

TypeError: expected str, bytes or os.PathLike object, not SimpleNamespace
