### ISSUE TITLE
After setting `set_classes`, the `device` parameter is no longer valid.

### ISSUE THREAD

**Issue by SWHL** [ultralytics/ultralytics#17731] opened 2024-11-23 12:41 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug

When I am inferring the YOLOV8X-Worldv2 model, I cannot specify GPU inference.

### Environment

```bash
$ yolo checks
Ultralytics 8.3.36 🚀 Python-3.10.15 torch-2.5.1+cu118 CUDA:0 (NVIDIA A800-SXM4-80GB, 81251MiB)
Setup complete ✅ (128 CPUs, 2015.3 GB RAM, 335.0/391.7 GB disk)

OS                  Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.31
Environment         Docker
Python              3.10.15
Install             pip
RAM                 2015.28 GB
Disk                335.0/391.7 GB
CPU                 Intel Xeon Platinum 8369C 2.90GHz
CPU count           128
GPU                 NVIDIA A800-SXM4-80GB, 81251MiB
GPU count           2
CUDA                11.8

numpy               ✅ 1.26.3>=1.23.0
numpy               ✅ 1.26.3<2.0.0; sys_platform == "darwin"
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ❌ (not installed)>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.14.1>=1.4.1
torch               ✅ 2.5.1+cu118>=1.8.0
torch               ✅ 2.5.1+cu118!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision         ✅ 0.20.1+cu118>=0.9.0
tqdm                ✅ 4.66.6>=4.64.0
psutil              ✅ 6.1.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.10>=2.0.0
```

### Normal Code

```python
from ultralytics import YOLO

model = YOLO("yolov8x-worldv2.pt")  # load an official model
for i in range(1000):
    results = model("https://ultralytics.com/images/bus.jpg", device="cuda:1") 
```

### Error Code

After setting set_classes, the device parameter is no longer valid. Each inference will only call `cuda:0`

```python
from ultralytics import YOLO

model = YOLO("yolov8x-worldv2.pt")  # load an official model
model.set_classes(["person"])
for i in range(1000):
    results = model("https://ultralytics.com/images/bus.jpg", device="cuda:1") 
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment] 2024-11-23 12:43
👋 Hello @SWHL, thank you for reporting this issue with Ultralytics 🚀! We recommend first checking our comprehensive [Docs](https://docs.ultralytics.com) for guidance, as they might already contain an answer to this query, especially in the context of device settings or class configurations during inference.

Regarding the behavior you're encountering with the device parameter after using `set_classes`, could you please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/)? This will help us better investigate the issue.

For bug reports like this one 🐛, a detailed explanation including any error messages or logs would be greatly beneficial.

In the meantime, ensure you're using the latest version of the `ultralytics` package to see if the issue persists:

```bash
pip install -U ultralytics
```

Check that all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) are met in a **Python>=3.8** environment and that you're running an updated version of [PyTorch>=1.8](https://pytorch.org/get-started/locally/). You might also find it helpful to test your setup in one of our verified environments, such as [Google Colab](https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb) or [Kaggle](https://www.kaggle.com/models/ultralytics/yolo11), which have all necessary dependencies preinstalled.

If you have any more questions or need help, join our lively [Discord community](https://ultralytics.com/discord) 🎧, where you can engage with fellow users and developers. Alternatively, our [Discourse forum](https://community.ultralytics.com) and [Subreddit](https://reddit.com/r/ultralytics) are also great places for discussions and troubleshooting.

This is an automated response, but rest assured, an Ultralytics engineer will review your issue and provide additional guidance soon. Thank you for your patience and for helping us improve our products! 💡

**Comment by Y-T-G** [comment] 2024-11-23 19:25
YOLO Wolrd model are supposed to be loaded using `YOLOWorld` function, not `YOLO`.

https://docs.ultralytics.com/models/yolo-world/

And to select a different CUDA device during inference, you should pass `device=torch.device("cuda:1")`.

**Comment by SWHL** [comment] 2024-11-23 23:18
But in the [docs](https://docs.ultralytics.com/models/yolo-world/#track-usage:~:text=setup%20or%20customization.-,Set%20prompts,-The%20YOLO%2DWorld), it shows to use the YOLO class.
```python
from ultralytics import YOLO

# Create a YOLO-World model
model = YOLO("yolov8s-world.pt")  # or select yolov8m/l-world.pt for different sizes

# Conduct model validation on the COCO8 example dataset
metrics = model.val(data="coco8.yaml")
```

Even if I use the `YOLOWorld` class, the above issues still exist.

**Comment by Y-T-G** [comment] 2024-11-24 06:05
> the above issues still exist.

Did you try passing `device=torch.device("cuda:1")` like I said?

**Comment by SWHL** [comment] 2024-11-25 00:32
I tried, but get another question: The program will occupy both `cuda:0` and `cuda:1` memory simultaneously.

![Nov-25-2024 08-30-12](https://github.com/user-attachments/assets/5abe1188-3097-4f87-8b87-787372ff79ce)

**Comment by Laughing-q** [comment] 2024-11-25 05:22
@SWHL Hi, this is a known issue because CLIP package is calling `torch.cuda.is_available()` which prevents users specify another device. And we fixed by forking CLIP and remove the `torch.cuda.is_available()`. Try to install CLIP by:
```bash
pip install git+https://github.com/ultralytics/CLIP.git
```

**Comment by SWHL** [comment] 2024-11-25 06:05
@Laughing-q L Thanks

In this [document](https://docs.ultralytics.com/models/yolo-world/#track-usage:~:text=setup%20or%20customization.-,Set%20prompts,-The%20YOLO%2DWorld), the example code provided by YOLO World is not consistent. Some are loaded using YOLO, while others are loaded using YOLOWorld. I'm too sure if this is a document issue.

**Comment by Laughing-q** [comment] 2024-11-25 06:36
@SWHL @Y-T-G Actually we can also use YOLO class to load YOLO-world models. We have a wrapper in the code to handle this. No worries you could directly use YOLO class for YOLO-World models. :)

**Closed** 2024-11-26 06:06 UTC
Labels: detect
