### ISSUE TITLE
weird obb result and train batch

### ISSUE THREAD

**Issue by kwang19113** [ultralytics/ultralytics#13202] opened 2024-05-29 10:05 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi so im trying to make a license plate detection using obb model. 
When i check the label using my own drawing script the bounding box is fine 
![output_image](https://github.com/ultralytics/ultralytics/assets/73984694/998cb450-aefc-463c-aa11-dd056c995d97)
But when i check on the training batch you can see the bottom left corner is a bit off:
![image](https://github.com/ultralytics/ultralytics/assets/73984694/f4cc5ae4-92b9-42eb-8ebc-a3a3c5807818)
After training for a while with good mAP metrics i took the best model to predict 
![image](https://github.com/ultralytics/ultralytics/assets/73984694/e93145a9-52e2-4d2c-b8c4-5f8176ddc45e)
The result is kinda look like the batch image:
![image](https://github.com/ultralytics/ultralytics/assets/73984694/c7d86ba3-70fb-4367-aebe-44fdb969bc1c)

Any idea how can i deal with this issue?
Training command:
`yolo obb train data=custom.yaml epochs=100 imgsz=640 workers=2 batch=64 project=obb_project/ device=0 cache='True' degrees=20 mosaic=0 fliplr=0 erasing=0.2 shear=0.2 flipud=0 translate=0 `

**Comment by glenn-jocher** [comment] 2024-05-29 13:11
Hello!

Thank you for providing detailed information and images regarding your issue with the OBB model for license plate detection. It seems like the misalignment in the bounding boxes during training might be affecting your final results.

Given the settings you've used, here are a couple of suggestions:

1. **Augmentation Adjustments**: The `degrees=20` setting for rotation might be too aggressive, causing some bounding boxes to misalign. Try reducing this value to see if it improves the bounding box accuracy during training.

2. **Batch Size**: A batch size of 64 is quite large, especially if your GPU memory allows. Sometimes, reducing the batch size can lead to more stable training, particularly for complex tasks like OBB. Consider experimenting with smaller batch sizes if feasible.

3. **Post-Processing**: Ensure that your post-processing steps during prediction align with how your training labels are formatted and processed. Any discrepancies here could lead to results like those you're seeing.

If these adjustments don't resolve the issue, it might be helpful to look into the specific transformations applied to your training data and ensure they are correctly handled during the bounding box calculations.

Keep us updated on your progress, and feel free to reach out if you have more questions!

**Comment by farhanrw** [comment] 2024-05-29 15:26
@kwang19113 could be related to this issue I reported a while back [https://github.com/ultralytics/ultralytics/issues/10181](url)

**Comment by kwang19113** [comment] 2024-05-31 03:32
> @kwang19113 could be related to this issue I reported a while back [https://github.com/ultralytics/ultralytics/issues/10181](url)

yea i think that's the one i set all augment value to 0 but the problem still persists

**Comment by glenn-jocher** [comment] 2024-05-31 07:01
Hello @kwang19113,

Thank you for pointing out the similarity to the issue you've encountered before. It's helpful to cross-reference these cases to better understand potential underlying patterns or recurring problems.

Since setting all augmentation values to zero didn't resolve the issue, it might be worth exploring other aspects such as the data preprocessing steps or the model configuration. Sometimes, subtle nuances in how data is prepared or how the model is set up can lead to unexpected behaviors.

If you have any more insights or specific settings that you've tried since then, sharing those could be beneficial for further troubleshooting.

**Comment by kwang19113** [comment] 2024-05-31 07:09
Hi @glenn-jocher 

I'll try to look into it. and provided any helpful information for the team. I think I've encountered this problem with another task but Im not sure which one. I'll get back to you when i have any other relevant information.

Cheers

**Comment by glenn-jocher** [comment] 2024-05-31 10:45
Hi @kwang19113,

Thank you for looking into this and for your willingness to share any relevant information. Your insights could be invaluable in resolving this issue. We appreciate your efforts and look forward to your update.

**Comment by jiangzhiwei2018** [comment] 2024-06-07 10:07
@kwang19113 hi
Based on the results you provided, it seems like your results are already the best that the algorithm can do. 
This is because the output of OBB is a standard rectangle with a rotation angle, while the license plate in the image is not a standard rectangle due to the perspective, it is more likely to be a parallelogram.

**Comment by glenn-jocher** [comment] 2024-06-07 12:19
Hi @jiangzhiwei2018,

Thank you for your insights! You've raised an excellent point about the limitations of the `OBB` model due to the perspective distortion in license plates, which often appear more like parallelograms than standard rectangles.

Exploring the `Pose` model for this specific use case is a great suggestion, as it could indeed provide the precision needed by outputting the four corner points of the license plate.

We appreciate your understanding regarding the precision issues noted in [#10181](https://github.com/ultralytics/ultralytics/issues/10181). Your feedback is invaluable as we continue to improve our models.

**Closed** 2024-06-10 08:43 UTC
Labels: question

**Comment by glenn-jocher** [comment] 2024-06-10 10:22
Hi @kwang19113,

Thank you for your understanding and for sharing your experience with the `Pose` model! It's great to hear that you've already experimented with the four-point pose approach. Comparing different methods is always a valuable exercise to find the most accurate solution for your specific use case.

If you have any further questions or need additional support as you continue with your current model, please don't hesitate to reach out. We're here to help!

Best of luck with your project, and thank you for being an active member of the YOLO community! 😊
