### ISSUE TITLE
cannot initialize type "StatusCode": an object with that name is already defined

### ISSUE THREAD

**Issue by zjtxxjd** [ultralytics/ultralytics#6003] opened 2023-10-29 07:57 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I trained the model in Google's Collab and exported it as a tfjs model, the error "TensorFlow SavedModel: export failure ❌ 42.4s: generic_ Type: cannot initialize type "StatusCode": an object with that name is already defined. What should I do?

**Comment by glenn-jocher** [comment] 2023-10-29 15:36
@zjtxxjd hello, thank you for reaching out and detailing the issue you're encountering.

The error message you're seeing seems to come from a naming conflict in the TensorFlow SavedModel. This typically happens when you try to create an object with a name that already exists in the TensorFlow memory space. The object in question here is "StatusCode".

A common reason for this kind of error is if you run the code that initializes the StatusCode object more than once in the same session, or if a model or layer within your neural network has the same name as a previously defined or used one.

The solution to this problem may necessitate better management of your training script and TensorFlow sessions or making sure there are no duplicate named models or layers in your network. In your case, since you're using Google Colab, it is recommended that you ensure to reset the environment (Runtime -> Restart Runtime) before starting a new session to avoid such conflicts.

If the issue persists, please consider sharing more details about your implementation, such as the model architecture and how you're initializing and running your TensorFlow session. This will allow us to provide a more precise solution.

We really value your contribution to the YOLOv8 project and look forward to helping you more effectively use the model.

**Comment by glenn-jocher** [comment] 2023-10-29 19:11
@zjtxxjd duplicate of https://github.com/ultralytics/ultralytics/issues/5161

**Comment by zjtxxjd** [comment] 2023-10-29 23:32
@glenn-jocher Thank you for your useful information. My problem has been resolved!

**Closed** 2023-10-29 23:32 UTC
Labels: duplicate, question

**Comment by glenn-jocher** [comment] 2023-11-15 01:11
@zjtxxjd you're very welcome! I'm delighted to hear that your issue has been resolved. Should you have any more questions or encounter further issues, please feel free to reach out. We are here to help. Happy detecting with YOLOv8!

**Comment by zaidworks515** [comment] 2023-12-28 12:38
> please tell me how did your problem solved? I'm facing the same error and it is not going by restarting the session of colab

model.export(format='saved_model', imgsz=640)

TensorFlow SavedModel: export failure  29.8s: generic_type: cannot initialize type "StatusCode": an object with that name is already defined

**Comment by glenn-jocher** [comment] 2023-12-28 17:43
@zaidworks515 it sounds like there might be a persistent naming conflict issue with TensorFlow in your Colab environment. Try completely resetting the environment by using 'Factory reset runtime' under the 'Runtime' menu, then rerun your export code. If the issue persists, double-check that the model architecture and session are initialized properly, with no duplicate names. For more detailed guidance, refer to the YOLOv8 documentation on our 'Export' mode.
