### ISSUE TITLE
Inference time while using ONNX taking more time with respect to pytorch model 

### ISSUE THREAD

**Issue by hvmatrix** [ultralytics/ultralytics#17147] opened 2024-10-25 04:19 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

My question is after converting pytorch model to ONNX, I am getting different inference time Which means while using pytorch model for example inference time is 2.3 ms while using onnx we got 7.3 ms. So, my query is why it is higher than PT model?
The code I'm using for evaluating pt model is given below:
from ultralytics import YOLO
model = YOLO("trains/weights/last.pt")  # load a custom model
metrics = model.val() 

Evaluation using ONNX model
from ultralytics import YOLO
model = YOLO("last.onnx") 
metrics = model.val(data='data.yaml')
Can you guide me how can I reduce inference time of onnx and what is the actual issue.? I have tried onnxruntime also but there is no improvement.

**Comment by UltralyticsAssistant** [comment] 2024-10-25 04:20
👋 Hello @hvmatrix, thank you for bringing this up with the Ultralytics community 🚀! Our documentation is a great resource for issues like this, so be sure to check out the [Docs](https://docs.ultralytics.com), which contain insights on [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage that might help you optimize your ONNX model performance.

Since this appears to be a 🐛 Bug Report, it would be very helpful if you could provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us understand the issue better. This way, we can efficiently investigate if there's a discrepancy between the PyTorch and ONNX inference times.

You're also encouraged to participate in our community platforms. Whether it's chatting with others on [Discord](https://ultralytics.com/discord) 🎧, engaging in in-depth discussions on [Discourse](https://community.ultralytics.com), or exploring threads on our [Subreddit](https://reddit.com/r/ultralytics), you'll find others who can share relevant insights.

## Upgrade

Make sure your `ultralytics` package is up-to-date as improvements and bug fixes are continuously integrated. Update your environment (Python>=3.8, PyTorch>=1.8) with:

```bash
pip install -U ultralytics
```

## Environments

Consider testing your models in one of our verified environments, which are set up for performance and compatibility:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. Refer to the [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. Refer to the [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image** for scalability and ease of use. See the [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

You can monitor the status of our CI tests, which verify the functionality of all YOLO modes across platforms, through this badge. If it’s green, it means all tests are currently passing:

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

Please note this is an automated response and an Ultralytics engineer will assist you with the specifics of your issue soon. Thank you for your patience! 😊

**Comment by Y-T-G** [comment] 2024-10-25 04:30
Duplicate of #17127

**Closed by Y-T-G** 2024-10-25 04:30 UTC
Labels: question, exports
