### ISSUE TITLE
RT-DETR

### ISSUE THREAD

**Issue by universeliang** [ultralytics/ultralytics#2611] opened 2023-05-15 04:59 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

The following error occurs when running RT-DETR:
AttributeError: 'DetectionModel' object has no attribute 'stride'
Running other yaml files is normal, only problem occurs with RT-DETR.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Kayzwer** [comment] 2023-05-15 06:16
the forward function of RT-DETR head is not complete yet, please wait for the team to complete the implementation

**Comment by universeliang** [comment] 2023-05-15 06:42
> the forward function of RT-DETR head is not complete yet, please wait for the team to complete the implementation

Ok. Thank you.

**Comment by Kayzwer** [comment] 2023-05-15 07:05
close the issue if you dont have any question

**Closed** 2023-05-15 07:20 UTC
Labels: bug

**Comment by AyushExel** [comment] 2023-05-15 08:42
@universeliang Please provide the command to reproduce. You should not have any problem running rtdetr model. The head is complete only the trainer is not complete.

**Comment by universeliang** [comment] 2023-05-15 09:31
> @universeliang Please provide the command to reproduce. You should not have any problem running rtdetr model. The head is complete only the trainer is not complete.
yolo cfg=ultralytics/yolo/cfg/default.yaml

**Comment by glenn-jocher** [comment] 2023-05-15 20:32
@universeliang, thank you for the information. According to our development team, the issue seems to be related to the training process. RT-DETR head in YOLOv8 should be complete and work without problems for inference. The problem you are encountering seems to be related to training, and our team is working to finalize the training implementation. Please ensure you're following our RT-DETR training guidelines strictly and avoid using configurations that might raise errors during the training process.

**Comment by universeliang** [comment] 2023-05-16 00:27
> @universeliang, thank you for the information. According to our development team, the issue seems to be related to the training process. RT-DETR head in YOLOv8 should be complete and work without problems for inference. The problem you are encountering seems to be related to training, and our team is working to finalize the training implementation. Please ensure you're following our RT-DETR training guidelines strictly and avoid using configurations that might raise errors during the training process.

![image](https://github.com/ultralytics/ultralytics/assets/91270010/4da9d58a-e33a-4724-a3f5-7ab4d0431b1c)
I tried to train rt-detr again, still reporting an error.
I use the following command：
yolo task=detect mode=train model=E:\abandon\YOLOv8-0516-103\ultralytics-main\ultralytics\models\rt-detr\rt-detr-l.yaml data=E:\abandon\YOLOv8-0516-103\ultralytics-main\ultralytics\datasets\CCTSDB.yaml epochs=200 batch=16

**Comment by universeliang** [comment] 2023-05-16 00:30
> @universeliang, thank you for the information. According to our development team, the issue seems to be related to the training process. RT-DETR head in YOLOv8 should be complete and work without problems for inference. The problem you are encountering seems to be related to training, and our team is working to finalize the training implementation. Please ensure you're following our RT-DETR training guidelines strictly and avoid using configurations that might raise errors during the training process.


I tried to train rt-detr again, still reporting an error. I use the following command for training.
command: yolo task=detect mode=train model=E:\abandon\YOLOv8-0516-103\ultralytics-main\ultralytics\models\rt-detr\rt-detr-l.yaml data=E:\abandon\YOLOv8-0516-103\ultralytics-main\ultralytics\datasets\data.yaml epochs=200 batch=16
An error will occur：
![image](https://github.com/ultralytics/ultralytics/assets/91270010/a28ffa98-72bd-4ae4-9755-b9130956f478)

**Comment by universeliang** [comment] 2023-05-16 00:31
> @universeliang, thank you for the information. According to our development team, the issue seems to be related to the training process. RT-DETR head in YOLOv8 should be complete and work without problems for inference. The problem you are encountering seems to be related to training, and our team is working to finalize the training implementation. Please ensure you're following our RT-DETR training guidelines strictly and avoid using configurations that might raise errors during the training process.

I tried to train rt-detr again, still reporting an error. I use the following command for training.
command: yolo task=detect mode=train model=E:\abandon\YOLOv8-0516-103\ultralytics-main\ultralytics\models\rt-detr\rt-detr-l.yaml data=E:\abandon\YOLOv8-0516-103\ultralytics-main\ultralytics\datasets\data.yaml epochs=200 batch=16
An error will occur：
![image](https://github.com/ultralytics/ultralytics/assets/91270010/e6ed0717-b6e4-4f4a-8474-2ec7f3de298a)

**Comment by glenn-jocher** [comment] 2023-05-16 01:14
@Kayzwer, thank you for the update and the additional details. Based on the error you provided, it seems that there is an issue with one or more of your image files. Please ensure that all images in your dataset are in a proper format and can be read by YOLOv8. You may also want to verify that you're running the latest version of YOLOv8 from the main branch of our GitHub repository and that you have all the necessary dependencies installed. If the problem persists after checking these things, please create a new issue with all the relevant details, and we will investigate further to resolve the issue.

**Comment by universeliang** [comment] 2023-05-16 01:21
I can train other yolov8 models normally, only RT-DETR cannot train normally. I guess, the training configuration should be fine. If there is a problem with the image or training configuration, then other models should not be able to be trained.

**Comment by Laughing-q** [comment] 2023-05-16 01:37
@universeliang hi, thanks for your attention! we have not supported training for RT-DETR yet and we only support inference and evaluation for now. We'll implement the training soon! :) [https://docs.ultralytics.com/models/rtdetr/#supported-modes](https://docs.ultralytics.com/models/rtdetr/#supported-modes)
![image](https://github.com/ultralytics/ultralytics/assets/61612323/f0cbe914-b989-47ef-a778-962e0feb4deb)
