### ISSUE TITLE
Model not accepting numpy / PIL inputs

### ISSUE THREAD

**Issue by QwerMotion** [ultralytics/ultralytics#456] opened 2023-01-17 19:52 UTC
I tried to use an image as input that is in ndarray-format. According to the docs this should work. 

```from ultralytics import YOLO
import numpy
import cv2


model = YOLO("best.pt")
image2 = cv2.imread("zidane.jpg")
model.predict(source=image2, show="True")
```

I'm getting the following Output when running this script:

```
Ultralytics YOLOv8.0.6  Python-3.7.6 torch-1.10.1+cu102 CUDA:0 (NVIDIA GeForce RTX 2080, 8192MiB)
Fusing layers... 
Model summary: 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
Traceback (most recent call last):
  File "D:\Desktop\yolov8\ultralytics\Sohmlord.py", line 8, in <module>
    model.predict(source=image2, show="True")
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "D:\Desktop\yolov8\ultralytics\ultralytics\yolo\engine\model.py", line 130, in predict
    predictor.setup(model=self.model, source=source, return_outputs=return_outputs)
  File "D:\Desktop\yolov8\ultralytics\ultralytics\yolo\engine\predictor.py", line 150, in setup
    vid_stride=self.args.vid_stride)
  File "D:\Desktop\yolov8\ultralytics\ultralytics\yolo\data\dataloaders\stream_loaders.py", line 163, in __init__
    p = str(Path(p).resolve())
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1161, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 205, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 123] Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch: '[[[38 48 72]\n  [40 50 74]\n  [40 51 73]\n  ...\n  [25 21 56]\n  [21 19 55]\n  [17 15 51]]\n\n [[37 47 71]\n  [37 47 71]\n  [37 48 70]\n  ...\n  [24 20 55]\n  [18 16 52]\n  [13 11 47]]\n\n [[41 51 75]\n  [39 49 73]\n  [37 48 70]\n  ...\n  [24 20 56]\n  [20 16 52]\n  [16 12 48]]\n\n ...\n\n [[48 43 40]\n  [49 44 41]\n  [48 43 40]\n  ...\n  [49 49 35]\n  [49 49 35]\n  [50 50 36]]\n\n [[49 42 39]\n  [49 42 39]\n  [49 42 39]\n  ...\n  [50 49 35]\n  [50 49 35]\n  [51 50 36]]\n\n [[48 41 38]\n  [48 41 38]\n  [48 41 38]\n  ...\n  [50 49 35]\n  [50 49 35]\n  [51 50 36]]]'
```

it seems that it is trying to interpret that ndarray as a filename.

**Comment by knoppmyth** [comment] 2023-01-17 21:53
This is being worked on and should be in a release soon. #314 #251

**Comment by Laughing-q** [comment] 2023-01-18 02:25
@QwerMotion @knoppmyth hi guys, the PRs are merged, please using the latest version then the usage of PIL/numpy should work.
```bash
pip install --upgrade ultralytics
```

**Comment by Yusepp** [comment] 2023-01-18 15:16
> ```shell
> pip install --upgrade ultralytics
> ```

I have recently updated and I am now running inference directly on numpy arrays. However, I am experiencing empty tensors as a result with the new Results interface. Has anyone else encountered this behavior?

**Comment by AyushExel** [comment] 2023-01-18 15:19
@Yusepp can you provide command to reproduce?

**Comment by Yusepp** [comment] 2023-01-18 15:24
> @Yusepp can you provide command to reproduce?

I'm running the following python code

```python
from ultralytics import YOLO
import torch
import cv2

input= ['test_input.jpg', 'test_input_2.jpg']
output = ['test_output.jpg', 'test_output_2.jpg']
# select device
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# set threshold
threshold = 0.5

# load a pretrained model (recommended for best training results)
model = YOLO(r'..\\runs\detect\\train\weights\best.pt')                
model.to(device)

# predict on an image
img = cv2.cvtColor(cv2.imread(input[0]), cv2.COLOR_BGR2RGB)
results = model.predict(img)
print(results[0].boxes)
```

The output is:

```
Ultralytics YOLOv8.0.9  Python-3.9.12 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce GTX 1650 with Max-Q Design, 4096MiB)
Fusing layers... 
Model summary: 218 layers, 25840339 parameters, 0 gradients, 78.7 GFLOPs
Ultralytics YOLO <class 'ultralytics.yolo.engine.results.Boxes'> masks
type: <class 'torch.Tensor'>
shape: torch.Size([0, 6])
dtype: torch.float32
```

**Comment by glenn-jocher** [comment] 2023-01-18 16:35
@Yusepp also note that numpy inputs are assumed to be in BGR order, i.e. see Python docs:
https://docs.ultralytics.com/python/

**Comment by Yusepp** [comment] 2023-01-18 17:13
> @Yusepp empty results indicate no detections, there is no error.
> 
> If you can show no detections on bus.jpg or zidane.jpg please let us know, otherwise this issue is non-actionable.

My weights
```python
model = YOLO(r'..\\runs\detect\\train\weights\best.pt')                

```
 are pretrained for face detection, I also checked zidane.jpg but i'm getting empty results. I tried realtime detection with webcam and it works perfectly detecting my face. My version is 8.0.9.

**Closed** 2023-01-18 19:32 UTC

**Comment by aalling93** [comment] 2023-02-20 17:31
Hi.

Is it suppose to work with numpy array currently? 
I can do inference on numpy arrays, but I can not train the model on .npy. Version is '8.0.24'

With Python:
        Like with, e.g., .png files, I call the yaml file as so:
 ```python
  model.train(data="vv_own_npy/data.yaml", 
              .....
 ```
or cli
```python
yolo detect train data=vv_own_npy/data.yaml optimizer=Adam model="yolov8n.yaml" epochs=100 imgsz=250 name=test_model
```
Both works with .png images. Neither work with .npy images.


The folder structure:
```python
    -vv_own_npy
        - train
            - images
                - 000fe338-5af2-448d-aef6-2fd38ad236fc.npy
                - ...
            - labels
                - 000fe338-5af2-448d-aef6-2fd38ad236fc.txt
                - ...
        - test 
            - ....
        - valid 
            - ....
```
Each .npy file is 256x256x2, and the .txt are in yolo format (same labels works with .png format)











I get the following error:
```python

AssertionError                            Traceback (most recent call last)
File /work3/kaaso/phd/git/ship_object_detection/yolov8/ultralytics/yolo/data/base.py:94, in BaseDataset.get_img_files(self, img_path)
     93     # self.img_files = sorted([x for x in f if x.suffix[1:].lower() in IMG_FORMATS])  # pathlib
---> 94     assert im_files, f"{self.prefix}No images found"
     95 except Exception as e:

AssertionError: train: No images found

The above exception was the direct cause of the following exception:


.
.
.
.
.
.
.

yolov8/ultralytics/yolo/engine/model.py:206, in YOLO.train(self, **kwargs)
    204     self.trainer.model = self.trainer.get_model(weights=self.model if self.ckpt else None, cfg=self.model.yaml)
    205     self.model = self.trainer.model
--> 206 self.trainer.train()
    207 # update model and cfg after training
    208 if RANK in {0, -1}:

yolov8/ultralytics/yolo/engine/trainer.py:182, in BaseTrainer.train(self)
    180         ddp_cleanup(command, self)
    181 else:
--> 182     self._do_train(int(os.getenv("RANK", -1)), world_size)

yolov8/ultralytics/yolo/engine/trainer.py:247, in BaseTrainer._do_train(self, rank, world_size)
    244 if world_size > 1:
    245     self._setup_ddp(rank, world_size)
--> 247 self._setup_train(rank, world_size)
    249 self.epoch_time = None
    250 self.epoch_time_start = time.time()

yolov8/ultralytics/yolo/engine/trainer.py:233, in BaseTrainer._setup_train(self, rank, world_size)
    231 # dataloaders
    232 batch_size = self.batch_size // world_size if world_size > 1 else self.batch_size
--> 233 self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=rank, mode="train")
    234 if rank in {0, -1}:
    235     self.test_loader = self.get_dataloader(self.testset, batch_size=batch_size * 2, rank=-1, mode="val")

yolov8/ultralytics/yolo/v8/detect/train.py:43, in DetectionTrainer.get_dataloader(self, dataset_path, batch_size, mode, rank)
     24 def get_dataloader(self, dataset_path, batch_size, mode="train", rank=0):
     25     # TODO: manage splits differently
     26     # calculate stride - check if model is initialized
     27     gs = max(int(de_parallel(self.model).stride.max() if self.model else 0), 32)
     28     return create_dataloader(path=dataset_path,
     29                              imgsz=self.args.imgsz,
     30                              batch_size=batch_size,
     31                              stride=gs,
     32                              hyp=vars(self.args),
     33                              augment=mode == "train",
     34                              cache=self.args.cache,
     35                              pad=0 if mode == "train" else 0.5,
     36                              rect=self.args.rect,
     37                              rank=rank,
     38                              workers=self.args.workers,
     39                              close_mosaic=self.args.close_mosaic != 0,
     40                              prefix=colorstr(f'{mode}: '),
     41                              shuffle=mode == "train",
     42                              seed=self.args.seed)[0] if self.args.v5loader else \
---> 43         build_dataloader(self.args, batch_size, img_path=dataset_path, stride=gs, rank=rank, mode=mode)[0]

yolov8/ultralytics/yolo/data/build.py:71, in build_dataloader(cfg, batch_size, img_path, stride, label_path, rank, mode)
     69     shuffle = False
     70 with torch_distributed_zero_first(rank):  # init dataset *.cache only once if DDP
---> 71     dataset = YOLODataset(
     72         img_path=img_path,
     73         label_path=label_path,
     74         imgsz=cfg.imgsz,
     75         batch_size=batch_size,
     76         augment=mode == "train",  # augmentation
     77         hyp=cfg,  # TODO: probably add a get_hyps_from_cfg function
     78         rect=cfg.rect if mode == "train" else True,  # rectangular batches
     79         cache=cfg.cache or None,
     80         single_cls=cfg.single_cls or False,
     81         stride=int(stride),
     82         pad=0.0 if mode == "train" else 0.5,
     83         prefix=colorstr(f"{mode}: "),
     84         use_segments=cfg.task == "segment",
     85         use_keypoints=cfg.task == "keypoint")
     87 batch_size = min(batch_size, len(dataset))
     88 nd = torch.cuda.device_count()  # number of CUDA devices

yolov8/ultralytics/yolo/data/dataset.py:45, in YOLODataset.__init__(self, img_path, imgsz, label_path, cache, augment, hyp, prefix, rect, batch_size, stride, pad, single_cls, use_segments, use_keypoints)
     43 self.use_keypoints = use_keypoints
     44 assert not (self.use_segments and self.use_keypoints), "Can not use both segments and keypoints."
---> 45 super().__init__(img_path, imgsz, label_path, cache, augment, hyp, prefix, rect, batch_size, stride, pad,
     46                  single_cls)

yolov8/ultralytics/yolo/data/base.py:50, in BaseDataset.__init__(self, img_path, imgsz, label_path, cache, augment, hyp, prefix, rect, batch_size, stride, pad, single_cls)
     47 self.single_cls = single_cls
     48 self.prefix = prefix
---> 50 self.im_files = self.get_img_files(self.img_path)
     51 self.labels = self.get_labels()
     52 if self.single_cls:

yolov8/ultralytics/yolo/data/base.py:96, in BaseDataset.get_img_files(self, img_path)
     94     assert im_files, f"{self.prefix}No images found"
     95 except Exception as e:
---> 96     raise FileNotFoundError(f"{self.prefix}Error loading data from {img_path}\n{HELP_URL}") from e
     97 return im_files

FileNotFoundError: train: Error loading data from yolov8/vv_own_npy/train/images
See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data

```

Meaning that the problem is at line 50.
```python
    50 self.im_files = self.get_img_files(self.img_path)
```

**Comment by Laughing-q** [comment] 2023-02-21 03:18
@aalling93 hi, yeah we need images as original training sources. You can add `cache=disk` amd it'll automatically generate `.npy` files in your images folder then the training will use the generated `.npy` file.
