### ISSUE TITLE
arg view_img not working as well as other args like vid_writer not working

### ISSUE THREAD

**Issue by udayzee05** [ultralytics/ultralytics#190] opened 2023-01-10 10:47 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

-  (D:\YOLOv8\venv) PS D:\YOLOv8\ultralytics> yolo task=detect mode=predict model=yolov8s.pt source=D:\YOLOv8\ultralytics\AL_line_25.mp4 view_img=True

view_img is not a valid key. Similar keys: []

- (D:\YOLOv8\venv) PS D:\YOLOv8\ultralytics> yolo task=detect mode=predict model=yolov8s.pt source=D:\YOLOv8\ultralytics\AL_line_25.mp4 view_img     

Error parsing override 'view_img'
missing EQUAL at '<EOF>'
See https://hydra.cc/docs/1.2/advanced/override_grammar/basic for details

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
(D:\YOLOv8\venv) PS D:\YOLOv8\ultralytics> yolo task=detect mode=predict model=yolov8s.pt source=D:\YOLOv8\ultralytics\AL_line_25.mp4 vid_writer
Error parsing override 'vid_writer'
missing EQUAL at '<EOF>'
See https://hydra.cc/docs/1.2/advanced/override_grammar/basic for details

### Environment

Win 11 64 bit ,11th gen i7, 16 GB DDR 5 RAM
NVIDIA RTX 3070 8 GB

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment] 2023-01-10 10:52
@udayzee05 oh we're using show=True now instead of view_img.

**Comment by udayzee05** [comment] 2023-01-10 10:54
where are the list of all args ?

**Comment by Laughing-q** [comment] 2023-01-10 10:58
oh I think we forget to update the docs of args. have you tried show=True?

**Comment by udayzee05** [comment] 2023-01-10 11:04
Yes, show is working fine, please Update docs, thank you

**Comment by Laughing-q** [comment] 2023-01-10 11:07
@udayzee05 sure

**Comment by AyushExel** [comment] 2023-01-10 11:08
@udayzee05 @Laughing-q https://docs.ultralytics.com/config/#prediction here I see its `show`..Can you point me where its still outdated?

**Comment by Laughing-q** [comment] 2023-01-10 11:09
@AyushExel 
[https://github.com/ultralytics/ultralytics/blob/a8a70390ab592ad2653e1c5f38c8320124508835/ultralytics/yolo/engine/predictor.py#L60](https://github.com/ultralytics/ultralytics/blob/a8a70390ab592ad2653e1c5f38c8320124508835/ultralytics/yolo/engine/predictor.py#L60)

**Comment by AyushExel** [comment] 2023-01-10 11:11
ohh in the docstrings.. Okay got it

**Comment by glenn-jocher** [comment] 2023-01-10 11:26
`view_img` renamed to `show` for entire repo in https://github.com/ultralytics/ultralytics/pull/169/commits/cf40c5a2ac599cf2d28bfc2b71aa80ff8517fe98

**Comment by kadirnar** [comment] 2023-01-10 11:40
@AyushExel 
I want to add yolov8 to [TorchYolo](https://github.com/kadirnar/torchyolo) library but I am getting this error.
```
size is not a valid key. Similar keys: ['visualize']
```

**Comment by AyushExel** [comment] 2023-01-10 11:42
@kadirnar I'm not sure. Can you provide command to reprouce? You'll probably need to add ultralytics in your requirements.txt file..ultralytics repo now supports v3,v5,v8 with more versions to come

**Comment by kadirnar** [comment] 2023-01-10 11:49
> @kadirnar I'm not sure. Can you provide command to reprouce? You'll probably need to add ultralytics in your requirements.txt file..ultralytics repo now supports v3,v5,v8 with more versions to come

ultralytics: 8.0.1
I don't know which line has the error. I don't understand the error message. How can I add the image_size and device parameters?
Code:
```
class Yolov8DetectionModel(YoloDetectionModel):
    def load_model(self):
        model = YOLO(self.model_path)
        self.model = model

    def predict(self, image, yaml_file=None):
        prediction = self.model(image)
        object_prediction_list = []
        for _, image_predictions_in_xyxy_format in enumerate(prediction):
            for pred in image_predictions_in_xyxy_format.cpu().detach().numpy():
                x1, y1, x2, y2 = (
                    int(pred[0]),
                    int(pred[1]),
                    int(pred[2]),
                    int(pred[3]),
                )
                bbox = [x1, y1, x2, y2]
                score = pred[4]
                category_name = self.model.names[int(pred[5])]
                category_id = pred[5]
```

**Comment by kadirnar** [comment] 2023-01-10 11:59
> @AyushExel I want to add yolov8 to [TorchYolo](https://github.com/kadirnar/torchyolo) library but I am getting this error.
> 
> ```
> size is not a valid key. Similar keys: ['visualize']
> ```

I solved this error. The cause of the error is due to packet conflict.

**Comment by glenn-jocher** [comment] 2023-01-10 14:13
@kadirnar are all your issues resolved now?

**Comment by kadirnar** [comment] 2023-01-10 14:25
> 

Yes, I got it working. Thank you.

**Comment by glenn-jocher** [comment] 2023-01-10 14:25
Great! Closing issue 😃

**Closed by glenn-jocher** 2023-01-10 14:25 UTC
Labels: bug
