### ISSUE TITLE
Yolov8 coco training on the latest version of ultralytics (8.3.x)

### ISSUE THREAD

**Issue by maro-jeon** [ultralytics/ultralytics#17002] opened 2024-10-18 03:55 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train

### Bug

In Ultralytics 8.3.x versions,

The `yolov8s.pt` model was trained with coco128.yaml data. 
The results confirmed that mAP50:95 starts around 0.

This is a different trend than in Ultralytics 8.2.x versions. 
This is because in v8.2.x mAP50:95 starts from 0.46.

Does anyone know why this is happening?

### Environment

bug: ultralytics v8.3.x
no bug: ultralytics v8.2.0 ~ v8.2.103

### Minimal Reproducible Example

from ultralytics import YOLO

# Load a model
model = YOLO("yolov8s.pt")
# model.val(data="coco128.yaml")
train_results = model.train(
    data="coco128.yaml",  # path to dataset YAML
    epochs=20,  # number of training epochs
    imgsz=640,  # training image size
    device=0,
    cos_lr=False,
    amp=False,
    lr0=0.01,
    lrf=0.01,
    workers=16,
    warmup_epochs=0.0,
)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment] 2024-10-18 04:39
Duplicate of https://github.com/ultralytics/ultralytics/issues/16678

**Comment by Y-T-G** [comment] 2024-10-18 04:40
You will have to use an older version of `ultralytics` to use pretrained weights completely.

https://github.com/ultralytics/ultralytics/issues/16678#issuecomment-2393099959

**Closed by Y-T-G** 2024-10-18 04:39 UTC
Labels: bug
