### ISSUE TITLE
size mismatch error when finetuning a model with multiprocessing

### ISSUE THREAD

**Issue by davegrays** [ultralytics/ultralytics#9419] opened 2024-03-29 22:38 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

Using 8.1.27

I train a model from yolov8s.pt --> model1.pt. THEN,
I want to train a new model from model1.pt, but with a different number of classes

This works fine if using device="cpu" or device=0

When using multi-gpu, I get the following error before training begins:
```
optimizer: AdamW(lr=0.000714, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Traceback (most recent call last):
  File "/home/david/.config/Ultralytics/DDP/_temp_h9a53u9r139976720501584.py", line 12, in <module>
    results = trainer.train()
  File "/home/david/ultralytics/ultralytics/engine/trainer.py", line 213, in train
    self._do_train(world_size)
  File "/home/david/ultralytics/ultralytics/engine/trainer.py", line 327, in _do_train
    self._setup_train(world_size)
  File "/home/david/ultralytics/ultralytics/engine/trainer.py", line 319, in _setup_train
    self.resume_training(ckpt)
  File "/home/david/ultralytics/ultralytics/engine/trainer.py", line 669, in resume_training
    self.ema.ema.load_state_dict(ckpt["ema"].float().state_dict())  # EMA
  File "/opt/conda/envs/bumlo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DetectionModel:
	size mismatch for model.22.cv3.0.2.weight: copying a param with shape torch.Size([9, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([11, 128, 1, 1]).
	size mismatch for model.22.cv3.0.2.bias: copying a param with shape torch.Size([9]) from checkpoint, the shape in current model is torch.Size([11]).
	size mismatch for model.22.cv3.1.2.weight: copying a param with shape torch.Size([9, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([11, 128, 1, 1]).
	size mismatch for model.22.cv3.1.2.bias: copying a param with shape torch.Size([9]) from checkpoint, the shape in current model is torch.Size([11]).
	size mismatch for model.22.cv3.2.2.weight: copying a param with shape torch.Size([9, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([11, 128, 1, 1]).
	size mismatch for model.22.cv3.2.2.bias: copying a param with shape torch.Size([9]) from checkpoint, the shape in current model is torch.Size([11]).
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 21516 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 21517 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 21518 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 21515) of binary: /opt/conda/envs/bumlo/bin/python3.10
```

The full command I used for training looks like this:
```
yolo detect train  model=/path/to/pretrained-model/weights/best.pt data=/path/to/my_yaml.yaml epochs=100 batch=16 imgsz=1184 device=0,1,2,3 seed=0 patience=0
```

### Environment

Ultralytics YOLOv8.1.27 🚀 Python-3.10.12 torch-1.13.1+cu117 CUDA:0 (Tesla T4, 14910MiB)
Setup complete ✅ (16 CPUs, 102.3 GB RAM, 210.8/393.5 GB disk)

OS                  Linux-4.19.0-25-cloud-amd64-x86_64-with-glibc2.28
Environment         Linux
Python              3.10.12
Install             git
RAM                 102.29 GB
CPU                 Intel Xeon 2.30GHz
CUDA                11.7

matplotlib          ✅ 3.6.3>=3.3.0
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 9.5.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.3>=1.4.1
torch               ✅ 1.13.1+cu117>=1.8.0
torchvision         ✅ 0.14.1+cu117>=0.9.0
tqdm                ✅ 4.64.1>=4.64.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 1.5.3>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0

### Minimal Reproducible Example

```
yolo detect train  model=yolov8s.pt data=/path/to/first_yaml.yaml epochs=100 batch=16 imgsz=1184 device=0,1,2,3 seed=0 patience=0
```
```
yolo detect train  model=/path/to/pretrained-model/weights/best.pt data=/path/to/next_yaml.yaml epochs=100 batch=16 imgsz=1184 device=0,1,2,3 seed=0 patience=0
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment] 2024-03-30 09:54
@davegrays hey there! 🌟 It seems you're encountering a size mismatch error due to changing the number of classes between trainings. When finetuning on a different number of classes with multi-GPU, you should adjust the model's `nc` (number of classes) in the model's `.yaml` configuration file to match your new dataset's classes before the second training session.

Here's a quick step you can take:
1. Ensure the `nc` in the `.yaml` file for your model architecture (e.g., `yolov8s.yaml`) matches the number of classes in `/path/to/next_yaml.yaml`.

Example tweak in `yolov8s.yaml` if your new dataset has 5 classes:
```yaml
nc: 5  # number of classes
```

Then you can rerun your training command. This should help resolve the size mismatch issue. 🚀

**Comment by davegrays** [comment] 2024-03-31 03:15
@glenn-jocher thanks for the prompt response, but this seems like an incorrect answer.

I shouldn't have to have the same number of classes between training model1 and training model 2. My goal is to use most of model 1's weights and have a different number of classes when training model 2. If that wasn't actually feasible, then that shouldn't work when device is multi-gpu mode, single gpu, or cpu. But like I said, the error only occurs during multi-gpu, which points to something else going on.

**Comment by glenn-jocher** [comment] 2024-03-31 09:07
Hey @davegrays! 😊 You're right, the flexibility to change the number of classes and utilize pre-trained weights is indeed a core feature of fine-tuning in object detection models like YOLOv8. If it works seamlessly on single GPU or CPU but not on multi-GPU setups, it suggests there might be a specific issue related to the distribution strategy or model initialization across multiple GPUs.

A quick workaround would be ensuring the model architecture defined for the second training session (model 2), where you change the number of classes, is correctly set up to match these changes before initializing the training process. Here’s a small pointer: before starting the second training session, double-check your dataset's YAML file for the correct number of classes and ensure it aligns with the model's configuration being loaded. 

If the issue persists, it's useful to look at how your model handles multi-GPU synchronization, specifically around the layers responsible for class predictions. Sometimes, explicit handling or model adjustments are needed when scaling from single to multi-GPU to maintain consistency in layer dimensions, especially for the output layers tied to class predictions.

Hope this nudges you in the right direction! Let us know how it goes.

**Comment by glenn-jocher** [comment] 2024-03-31 16:06
@Laughing-q can you try to reproduce this on the server? I think launching a new training for any dataset with a different class count is what the user is saying, but this is a standard use case so I don't think there can be any issue here.

**Comment by glenn-jocher** [comment] 2024-03-31 16:19
@davegrays I'm unable to reproduce any issue training VOC.yaml (10 classes) from COCO (80 classes) pretrained-YOLOv8n.pt:

<img width="1613" alt="Screenshot 2024-03-31 at 18 18 43" src="https://github.com/ultralytics/ultralytics/assets/26833433/24110277-606d-4b27-bfb6-e3bf492d9ca7">

**Comment by davegrays** [comment] 2024-03-31 18:59
Yeah that works fine for me as well. In your example, the model you’re training would correspond to the “model 1” I was referring to. The error appears when I try to finetune a second model with additional classes using the first model’s weights. I also was interrupting the first model training before doing so, but not sure yet if that matters. 

For example if you were now to take VOC.yaml, add a couple new classes, and train yet another model using model=/usr/src/ultralytics/runs/detect/train2/weights/last.pt

**Comment by glenn-jocher** [comment] 2024-03-31 19:17
@davegrays the code below works correctly for me:

```bash
yolo train data=coco8.yaml epochs=10
yolo train data=VOC.yaml model=/usr/src/ultralytics/runs/detect/train/weights/best.pt device=0,1
```

<img width="1522" alt="Screenshot 2024-03-31 at 21 17 23" src="https://github.com/ultralytics/ultralytics/assets/26833433/0edf9954-f8a4-4437-ae3d-02ee7da7bb7d">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by glenn-jocher** [comment] 2024-03-31 20:24
@davegrays was able to reproduce on a partially trained checkpoint. Should be resolved now in #9453 that will publish soon as ultralytics version 8.1.40.

Let us know if this fixes your problem and please let us know if you run into any other problem!

**Comment by davegrays** [comment] 2024-04-01 00:06
@glenn-jocher Thats awesome! Thanks for looking into it!

**Closed** 2024-04-01 17:46 UTC
Labels: bug, fixed

**Comment by glenn-jocher** [comment] 2024-05-21 05:55
Hey @davegrays! You're welcome! 🚀 We're always here to help. Keep an eye out for the update in the next release. If you have any more questions or run into other issues, feel free to reach out. Happy coding!
