### ISSUE TITLE
 'clip_model'

### ISSUE THREAD

**Issue by Pandaliaojing** [ultralytics/ultralytics#9250] opened 2024-03-23 11:19 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

AttributeError: 'WorldModel' object has no attribute 'clip_model'

### Additional

AttributeError: 'WorldModel' object has no attribute 'clip_model'

**Comment by Pandaliaojing** [comment] 2024-03-23 12:05
from ultralytics import YOLO

model = YOLO(r'D:\yolo\ultralytics-YOLOWORLD\yolov8s-worldv2.pt')  # or choose yolov8m/l-world.pt

# Define custom classes
model.set_classes(["person"])

# Execute prediction for specified categories on an image
results = model.predict('1.png')

# Show results
results[0].show()

AttributeError: 'WorldModel' object has no attribute 'clip_model'

**Comment by Pandaliaojing** [comment] 2024-03-23 12:06
from ultralytics import YOLO

model = YOLO(r'D:\yolo\ultralytics-YOLOWORLD\yolov8s-worldv2.pt')  # or choose yolov8m/l-world.pt
model.set_classes(["person"])
results = model.predict('1.png')
results[0].show()

AttributeError: 'WorldModel' object has no attribute 'clip_model'

**Comment by Pandaliaojing** [comment] 2024-03-23 12:28
<img width="436" alt="屏幕截图 2024-03-23 202703" src="https://github.com/ultralytics/ultralytics/assets/143798298/26a7876c-ff73-4a54-89ce-b5b370bcc48e">

**Comment by Pandaliaojing** [comment] 2024-03-23 12:29
<img width="585" alt="image" src="https://github.com/ultralytics/ultralytics/assets/143798298/28d3d574-b4c6-44b4-b7ad-ae5ab93f2903">

**Comment by Pandaliaojing** [comment] 2024-03-23 12:38
<img width="308" alt="image" src="https://github.com/ultralytics/ultralytics/assets/143798298/898c5129-0008-4991-a890-fee2cffded07">
We can utilize the information presented in the preceding diagram to resolve the problem at hand.

**Comment by glenn-jocher** [comment] 2024-03-23 13:21
@Pandaliaojing hi there! It seems like there's an attempt to access an attribute (`clip_model`) that doesn't exist in the `WorldModel`. This might be caused by a few reasons, such as a typo in the attribute name, or perhaps `clip_model` is expected to be dynamically set and hasn't been yet.

Could you double-check if `clip_model` is the correct attribute name and that it's properly initialized within your `WorldModel` object? Sometimes, issues like these can occur if there's a mismatch between the expected state of the object and its actual state.

If you're dynamically setting attributes, ensure the `clip_model` is being assigned before it's accessed. Here is a generic example:

```python
class WorldModel:
    def __init__(self):
        self.clip_model = None  # Initialize attribute

# Later in your code
world_model = WorldModel()
world_model.clip_model = your_clip_model  # Properly assign it before usage
```

If this doesn't solve your issue, could you provide a bit more context or code where `clip_model` is being accessed? That could help pinpoint the issue more accurately. 😊

**Comment by Pandaliaojing** [comment] 2024-03-23 13:39
Thank you for replying. Your suggestions are highly practical and beneficial. I wish for your service to keep getting better!Develop an increasing number of excellent tools for society.

**Comment by Burhan-Q** [comment] 2024-03-23 17:54
FYI fixed in #9253

**Closed** 2024-03-23 17:54 UTC
Labels: question, fixed
