### ISSUE TITLE
'copy_paste_mode' is not a valid YOLO argument

### ISSUE THREAD

**Issue by dao027** [ultralytics/ultralytics#18302] opened 2024-12-18 11:46 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://github.com/user-attachments/assets/fa7bd938-d9ca-427c-b722-ade231bd369c)
copy_paste_mode is in ultralytics/cfg/default.yaml, why "not a valid YOLO argument"

**Comment by UltralyticsAssistant** [comment] 2024-12-18 11:47
👋 Hello @dao027, thank you for your interest in Ultralytics 🚀! We recommend checking out the [Docs](https://docs.ultralytics.com), where many common questions and usage examples, like those for [Python](https://docs.ultralytics.com/usage/python/) or [CLI](https://docs.ultralytics.com/usage/cli/), are covered in depth.

It appears you're encountering an issue related to the `copy_paste_mode` argument. If this is a 🐛 Bug Report, we kindly ask that you provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us pinpoint the issue more effectively. This could include a script snippet that demonstrates how the error occurs.

You can also verify the issue isn't resolved in the latest version. To upgrade to the latest `ultralytics` package and all dependencies in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/), run the command below:

```bash
pip install -U ultralytics
```

#### Environments

You can test YOLO in any of our verified environments (preconfigured with dependencies such as [CUDA](https://developer.nvidia.com/cuda), [CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/), and [PyTorch](https://pytorch.org/)):

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

#### Community Support

If you have further questions or would like to discuss this issue in real time, you can join our [Discord](https://discord.com/invite/ultralytics) 🎧. For deeper discussions, visit our [Discourse](https://community.ultralytics.com), or engage with others on our [Subreddit](https://reddit.com/r/Ultralytics).

#### Repository Status
<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>
If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing. CI tests run every 24 hours and for every new commit, verifying the functionality of all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) across macOS, Ubuntu, and Windows.

This is an automated response to get you started. An Ultralytics engineer will also review your issue and provide additional guidance soon. Thank you for your patience 😊!

**Comment by xceccon** [comment] 2024-12-18 14:41
Hello, could you add your code ?

**Comment by Y-T-G** [comment] 2024-12-18 14:43
Can you provide the output after running this command in terminal: `yolo checks`?

You probably have an old version of ultralytics installed and you're launching training from a local ultralytics directory without installing it. DDP training requires installing the package globally.

**Comment by dao027** [comment] 2024-12-19 01:23
> Can you provide the output after running this command in terminal: `yolo checks`?
> 
> You probably have an old version of ultralytics installed and you're launching training from a local ultralytics directory without installing it. DDP training requires installing the package globally.
> 
> Run `pip install ultralytics -U`

many thanks, it's fixed by updating the repo and installing the ultralytics package

**Closed** 2024-12-19 01:24 UTC
Labels: question

**Comment by glenn-jocher** [comment] 2024-12-19 12:38
You're welcome! Glad to hear the issue is resolved. If you have any more questions, feel free to ask. Happy training!
