### ISSUE TITLE
ckpt = torch.load(weight)

### ISSUE THREAD

**Issue by djdll** [ultralytics/ultralytics#17383] opened 2024-11-07 02:22 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I weight=' officially provided model path ', ckpt = torch.load(weight); model_names = ckpt['model'].names will print
`{0: 'plane', 1: 'ship', 2: 'storage tank', 3: 'baseball diamond', 4: 'tennis court', 5: 'basketball court', 6: 'ground track field', 7: 'harbor', 8: 'bridge', 9: 'large vehicle', 10: 'small vehicle', 11: 'helicopter', 12: 'roundabout', 13: 'soccer ball field', 14: 'swimming pool'}`

When I weight=' my train model path ', AttributeError: 'NoneType' object has no attribute 'names'
my_code:
`
class yolov8_heatmap:
    def __init__(self, weight, device, method, layer, backward_type, conf_threshold, ratio, show_box, renormalize):
        device = torch.device(device)
        ckpt = torch.load(weight)
        import ipdb;ipdb.set_trace();
        model_names = ckpt['model'].names
        model = attempt_load_weights(weight, device)
        
        model.info()
        for p in model.parameters():
            p.requires_grad_(True)
        model.eval()
        
        target = yolov8_target(backward_type, conf_threshold, ratio)
        target_layers = [model.model[l] for l in layer]
        method = eval(method)(model, target_layers, use_cuda=device.type == 'cuda')
        method.activations_and_grads = ActivationsAndGradients(model, target_layers, None)
        
        colors = np.random.uniform(0, 255, size=(len(model_names), 3)).astype(np.uint8)
        self.__dict__.update(locals())
`

**Comment by UltralyticsAssistant** [comment] 2024-11-07 02:23
👋 Hello @djdll, thank you for bringing your question to the Ultralytics community 🚀! We suggest you explore our [Docs](https://docs.ultralytics.com) where numerous [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) examples are available. These resources might already have the answers you're looking for.

If this is a 🐛 Bug Report, it would be helpful if you could include a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to assist us in resolving the issue.

For any custom training ❓ Questions, please provide detailed information including dataset image examples and training logs. Ensure you're following our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

Connect with the Ultralytics community where you feel most comfortable. For real-time discussions, join us on [Discord](https://ultralytics.com/discord) 🎧. If you're more into in-depth discussions, visit [Discourse](https://community.ultralytics.com). You can also engage with us and other users on our [Subreddit](https://reddit.com/r/ultralytics).

## Upgrade

Ensure you're using the latest version by upgrading the `ultralytics` package along with all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) environment, and verify your issue isn't already resolved in the latest version:

```bash
pip install -U ultralytics
```

## Environments

YOLO can work in several modern environments, each with all dependencies such as [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/), and [PyTorch](https://pytorch.org/) preinstalled:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. Refer to the [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See the [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. View the [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, it indicates that all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing. Our CI tests confirm correct operation of all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) on macOS, Windows, and Ubuntu every 24 hours and upon each commit.

This is an automated response 🌟, and an Ultralytics engineer will assist you further shortly.

**Closed** 2024-11-07 02:32 UTC
Labels: question

**Comment by glenn-jocher** [comment] 2024-11-09 04:05
@djdll it seems like the issue arises because your custom-trained model's checkpoint does not include the 'names' attribute. Ensure your training script saves the model with class names included, or manually add them to your checkpoint. If you need further assistance, please refer to the documentation or community discussions.
