### ISSUE TITLE
conf

### ISSUE THREAD

**Issue by 1yuechu1** [ultralytics/ultralytics#17548] opened 2024-11-15 03:44 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

"Hello, I found that when I was using YOLO11 for object detection, the image confidence of the model output was 0.25. I want to change it to a lower confidence,just like 0.05 . How should I proceed?"

**Comment by UltralyticsAssistant** [comment] 2024-11-15 03:44
👋 Hello @1yuechu1, thank you for reaching out and using Ultralytics 🚀! This is an automated response to assist you while an Ultralytics engineer reviews your inquiry.

For changing the confidence threshold in YOLO11, you can usually adjust this parameter in your model's configuration or during the inference process. Here's a quick guide to get you on track:

### Helpful Resources
- For new users or those needing a refresher, we highly recommend visiting our [Docs](https://docs.ultralytics.com) where you can find extensive resources, including [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples.

### Troubleshooting Steps 🔧
- If this is related to a potential 🐛 Bug, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us understand the scenario.
- For custom training or inference ❓ questions, offering additional details such as the dataset, configuration settings, or logs would be beneficial.

### Community & Support
- Need real-time help? Join the discussion on [Discord](https://ultralytics.com/discord) 🎧.
- For more thematic discussions, consider visiting our [Discourse](https://community.ultralytics.com) or engage with others on our [Subreddit](https://reddit.com/r/ultralytics).

### Upgrade & Environment
To ensure your issue isn't related to an outdated version, please upgrade to the latest `ultralytics` package and check that all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) are met:

```bash
pip install -U ultralytics
```

YOLO can run in several environments with all necessary dependencies:
- **Notebooks**: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Cloud Services** and **Docker**: More details are available in our guides.

### Status Check
<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

A green status indicates that all YOLO modes and tasks are functioning correctly across various platforms.

Thank you for your patience, and someone from our team will address your question directly soon! 😊

**Comment by akachammile** [comment] 2024-11-15 06:50
When making predictions, you can set the parameter conf=0.05 or lower, like this
![image](https://github.com/user-attachments/assets/89aa1fe8-e6ce-4c23-8324-4597aa1161a1)

**Comment by RizwanMunawar** [comment] 2024-11-15 12:16
Hi @1yuechu1! You can easily adjust the confidence threshold by using the `conf` argument in the `predict` method. Here's how:

### CLI Usage

```bash
yolo detect predict conf=0.25  # Replace with 0.05 or any value you prefer
```

### Python Usage

```python
from ultralytics import YOLO

# Load a pretrained YOLO11n model
model = YOLO("yolo11n.pt")

# Run inference on 'bus.jpg' with customized confidence
model.predict("bus.jpg", save=True, imgsz=320, conf=0.5)  # Adjust conf=0.05 as needed
```

Hi @akachammile! Thank you for sharing the code snippet—it’s super helpful! 😊

Since the issue seems resolved, I’ll go ahead and close it. If you run into any other challenges using Ultralytics, please don’t hesitate to open a new issue.

Thanks again,  
The Ultralytics Team 🚀

**Closed** 2024-11-15 12:16 UTC
Labels: question, detect
