### ISSUE TITLE
training on Apple M1 chip using Metal Performance Shaders (MPS) float64 issue

### ISSUE THREAD

**Issue by zay3d** [ultralytics/ultralytics#246] opened 2023-01-11 09:55 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

error when training with apple m1 MPS, due to MPS framework doesn't support float64. in train.py line 168. 
is there any workaround ? 

python3.10/site-packages/ultralytics/yolo/v8/detect/train.py", line 168, in __call__
    targets = self.preprocess(targets.to(self.device), batch_size, scale_tensor=imgsz[[1, 0, 1, 0]])
TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.

### Environment

- Ultralytics YOLOv8.0.3 🚀 Python-3.10.0 torch-2.0.0.dev20230107 MPS
- Apple MacBook Pro M1
- Metal Performance Shaders (MPS) 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment] 2023-01-11 09:59
@zay3d thanks for reporting.. We haven't tested MPS support yet but we plan to include it soon.

**Comment by vineetsharma14** [comment] 2023-02-01 03:40
I have the same issue.

**Comment by GameTL** [comment] 2023-02-16 08:41
second this was disappointed that I can train and interface on M2 Pro

**Comment by EnesGumuskaynak** [comment] 2023-02-24 09:06
This not this repo's isssue. when ı change float64 to 32 manually another error cames on. mps support dont entegrated fully on torch. torch integration issue [link](https://github.com/pytorch/pytorch/issues/77764)  we must to wait

**Comment by N-Friederich** [comment] 2023-03-20 15:09
The features relevant to this project were fixed in 2.0 (line [unique2](https://github.com/pytorch/pytorch/commit/fc59664ef4caa550ed02e5ab677134cb8d8cf74e).
But there are still some float64 uses internally. I will look at this and fix it. I will then create a PR after testing.

**Comment by glenn-jocher** [comment] 2023-03-20 16:55
@N-Friederich got it! Are there any changes that need to be done to better support MPS then?

**Comment by N-Friederich** [comment] 2023-03-20 16:59
@glenn-jocher I work on the PR :) Just a few small changes e.:g. to bring tensors from int64/float64 to int32/float32.

**Closed** 2023-03-23 23:22 UTC
Labels: bug, fixed

**Comment by wilsonlmh** [comment] 2023-04-10 07:15
I'm experiencing the same issue and found a simple workaround:
Just edit this line:
https://github.com/ultralytics/ultralytics/blob/95f96dc5bc1ad6fc22fa9ede1c9fe36d4c6abb56/ultralytics/yolo/v8/detect/train.py#L170
To:
```python
targets = torch.cat((batch['batch_idx'].view(-1, 1), batch['cls'].view(-1, 1), batch['bboxes'].to(dtype)), 1)
```
And it works! I found similar changes in #1512, but on another file. Maybe just overlooked a bit? Should I PR it?

**Comment by glenn-jocher** [comment] 2023-04-10 09:51
@wilsonlmh if this change improves the most recent version of ultralytics with MPS then yes please submit a PR and we can evaluate it there. I work on an M2 Macbook so I can test it personally :)

**Comment by wilsonlmh** [comment] 2023-04-10 18:44
@glenn-jocher Sure, it's here: #1939

**Comment by glenn-jocher** [comment] 2023-04-11 10:30
@wilsonlmh ok @Laughing-q has traced the source of the issue to some numpy functions creating float64, and we've solved the bug at the source of the problem now in https://github.com/ultralytics/ultralytics/pull/1956

**Comment by wilsonlmh** [comment] 2023-04-17 14:59
@glenn-jocher good to hear that!

**Comment by glenn-jocher** [comment] 2023-04-17 19:25
@wilsonlmh I'm glad to hear that too. Thank you for raising the issue and providing the initial workaround. At Ultralytics, we always strive to make our libraries work well across different hardware and environments, including Macbooks with MPS framework. This PR will help improve the user experience for those users. Let me know if there's anything else I can help with.

**Comment by awilbourn** [comment] 2023-06-21 12:02
Are there specific instructions to get the train to work on Mac M2 silicon? To pip install Ultralytics YOLOv8.0.120 🚀 Python-3.10.11 torch-2.0.1 it does not seem to recognize the GPU. The issue is in the torch_utils file.

Attempt to train using: model.train(data="coco128.yaml", epochs=100, device=0)

Tried passing MPS as the device and is not recognized.

Error:

File ~/anaconda3/envs/tensorflow/lib/python3.10/site-packages/ultralytics/yolo/utils/torch_utils.py:75, in select_device(device, batch, newline, verbose)
     72         LOGGER.info(s)
     73         install = 'See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no ' \
     74                   'CUDA devices are seen by torch.\n' if torch.cuda.device_count() == 0 else ''
---> 75         raise ValueError(f"Invalid CUDA 'device={device}' requested."
     76                          f" Use 'device=cpu' or pass valid CUDA device(s) if available,"
     77                          f" i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.\n"
     78                          f'\ntorch.cuda.is_available(): {torch.cuda.is_available()}'
     79                          f'\ntorch.cuda.device_count(): {torch.cuda.device_count()}'
     80                          f"\nos.environ['CUDA_VISIBLE_DEVICES']: {visible}\n"
     81                          f'{install}')
     83 if not cpu and not mps and torch.cuda.is_available():  # prefer GPU if available
     84     devices = device.split(',') if device else '0'  # range(torch.cuda.device_count())  # i.e. 0,1,6,7

ValueError: Invalid CUDA 'device=0' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): False
torch.cuda.device_count(): 0
os.environ['CUDA_VISIBLE_DEVICES']: 0
See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no CUDA devices are seen by torch.

**Comment by N-Friederich** [comment] 2023-06-21 18:58
Hi @awilbourn,

have you tried device='mps'? (Pay attention to the small notation)

Best,
Nils
