### ISSUE TITLE
Is it possible to use C++ (libtorch) for transfer learning training? Not inference.

### ISSUE THREAD

**Issue by hujhcv** [ultralytics/ultralytics#17679] opened 2024-11-21 03:50 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is it possible to use C++ (libtorch) for transfer learning training? How difficult is it? What knowledge is required?

**Comment by UltralyticsAssistant** [comment] 2024-11-21 03:51
👋 Hello @hujhcv, thank you for your interest in Ultralytics 🚀! We recommend a visit to the [Docs](https://docs.ultralytics.com) where you can find many useful resources that might help answer your question.

If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us debug it.

As for your inquiry about using C++ (libtorch) for transfer learning, an Ultralytics engineer will assist you soon to provide more insights. Meanwhile, exploring our [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples might offer additional context on how to tackle transfer learning.

Join the Ultralytics community to exchange more ideas and experiences. For real-time chat, head to our [Discord](https://ultralytics.com/discord) 🎧. For deeper discussions, check out [Discourse](https://community.ultralytics.com). Or visit our [Subreddit](https://reddit.com/r/ultralytics) to engage with fellow enthusiasts.

## Upgrade

Upgrade to the latest `ultralytics` package along with all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) environment and [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/) to ensure your setup is up to date:

```bash
pip install -U ultralytics
```

## Environments

YOLO can be run in any of these up-to-date verified environments:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing, ensuring reliable operation across all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) on multiple platforms.

**Comment by Y-T-G** [comment] 2024-11-21 11:24
Closing because this is not ultralytics related.

**Closed by Y-T-G** 2024-11-21 11:25 UTC
Labels: question
