### ISSUE TITLE
TensorRT installed by ultralytics installation?

### ISSUE THREAD

**Issue by Petros626** [ultralytics/ultralytics#18397] opened 2024-12-25 18:33 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey guys,

I checked the export and integrations guide https://docs.ultralytics.com/modes/export/ and https://docs.ultralytics.com/integrations/tensorrt/. One thing, which is not clear for me is, if `TensorRT` is already installed with the normal `ultralytics` installation. Pylance can't resolve it, which seems for me not to be installed.
![image](https://github.com/user-attachments/assets/934cb5b3-706a-434c-a332-2676c27c0061)

Can you advice a proper installation guide or just use the official guide https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html? Is `cuDNN` required for a better exporting results, because now I've only installed `CUDA`.

Thanks in advance

**Comment by UltralyticsAssistant** [comment] 2024-12-25 18:33
👋 Hello @Petros626, thank you for your interest in Ultralytics 🚀! We recommend visiting the [Docs](https://docs.ultralytics.com) to explore more about export options and TensorRT integration. The specific guides you mentioned, [Export Documentation](https://docs.ultralytics.com/modes/export/) and [TensorRT Guide](https://docs.ultralytics.com/integrations/tensorrt/), are great starting points for your query.

For further clarification:
- If this is a 🐛 Bug Report, and you're experiencing installation issues, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) and additional details like your Python environment, OS, and any error logs, to help us debug effectively.
- If this is a ❓ Question, your images and descriptions are helpful! Please also let us know your specific installation method for `ultralytics` (e.g., `pip install ultralytics`) and whether you’ve followed the [official NVIDIA TensorRT installation guide](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html). Also, if you are exporting models or integrating TensorRT, confirm your setup by reviewing our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

For real-time help, you can join our Ultralytics community:
- 🎧 [Discord](https://discord.com/invite/ultralytics)
- 📃 [Discourse](https://community.ultralytics.com)
- 💬 [Reddit](https://reddit.com/r/Ultralytics)

## Installation & Environment

To ensure you are using the latest version with all dependencies, upgrade `ultralytics` and verify your environment:

```bash
pip install -U ultralytics
```

TensorRT and cuDNN are not included in the standard `ultralytics` installation and must be installed separately. Refer to the [install guide](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html) and ensure your environment includes:
- **Python>=3.8**
- **CUDA** and **cuDNN** (when working with TensorRT, CUDA installs typically include cuDNN, but verify your setup for compatibility using their respective installation guides).

You can also run YOLO in one of our pre-configured environments, which simplifies dependency management:
- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Cloud Platforms:** [Google Cloud](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/), [AWS](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/), or [Docker](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>.

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

The status badge above ensures all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing for a variety of environments. CI runs validate the correct operation of YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/).

This is an automated message 🤖, and an Ultralytics engineer will assist further as soon as possible! 😊

**Comment by KishanPipariya** [comment] 2024-12-25 18:40
It is not installed with normal ultralytics installation.

**Comment by Y-T-G** [comment] 2024-12-25 18:44
It will be installed automatically from pip on export.

**Comment by Petros626** [comment] 2024-12-25 18:48
And what about the installation source and `cuDNN`?

**Comment by Y-T-G** [comment] 2024-12-25 19:04
You don't need to manually install those for the latest TensorRT.

**Comment by Petros626** [comment] 2024-12-25 19:17
Sorry but this statement is not clear enough. I was asking if ultralytics got a preferred installation source for `TensorRT` and if the export needs `cuDNN` for bête er exporting results.

**Comment by Y-T-G** [comment] 2024-12-25 20:07
Ultralytics automatically installs TensorRT from pip when you export in TensorRT. You don't need to do anything.

**Comment by Petros626** [comment] 2024-12-26 10:38
Okay that wasn't clear from the guide, so every package for exporting will be automatically installed. Does this also apply to the software (Tensorboard, CoreML, WandB etc.) for training and validation?

**Comment by Y-T-G** [comment] 2024-12-26 10:54
The guide doesn't mention you have to install anything because you don't have to. A lot of the dependencies are installed when they're used

**Comment by Y-T-G** [comment] 2024-12-26 11:00
WandB has to be installed manually. And the guide says that:
https://docs.ultralytics.com/integrations/weights-biases/

**Closed by Y-T-G** 2024-12-26 11:00 UTC
Labels: question, exports
