### ISSUE TITLE
About multi gpu training

### ISSUE THREAD

**Issue by Timmy-Eink** [ultralytics/ultralytics#17404] opened 2024-11-08 02:28 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I can run one gpu perfectly, but when i run multi gpu I got errors down below.

cuda test

```
CUDA is available!
CUDA version: 12.4
Number of available GPU(s): 2
GPU 0: NVIDIA L40-48C
GPU 1: NVIDIA L40-24C
```

cmd : `python -m torch.distributed.run --nproc_per_node 2 /home/timmy/ultralytics/yolo/train.py --batch 32 --data /home/timmy/ultralytics/data/TM2.yaml --weights /home/timmy/ultralytics/weights/yolo11m-seg.pt --device 0,1`

```

WARNING:__main__:

Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 

New https://pypi.org/project/ultralytics/8.3.28 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.27 🚀 Python-3.10.15 torch-2.5.1 CUDA:0 (NVIDIA L40-48C, 48851MiB)
                                                 CUDA:1 (NVIDIA L40-24C, 24326MiB)
Overriding model.yaml nc=80 with nc=3
Transferred 705/711 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
W1108 09:47:34.113000 16359 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 16370 closing signal SIGTERM
E1108 09:47:35.083000 16359 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: -11) local_rank: 1 (pid: 16371) of binary: /home/timmy/anaconda3/envs/ultralytics/bin/python
Traceback (most recent call last):
  File "/home/timmy/anaconda3/envs/ultralytics/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/timmy/anaconda3/envs/ultralytics/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/timmy/anaconda3/envs/ultralytics/lib/python3.10/site-packages/torch/distributed/run.py", line 923, in <module>
    main()
  File "/home/timmy/anaconda3/envs/ultralytics/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/home/timmy/anaconda3/envs/ultralytics/lib/python3.10/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/home/timmy/anaconda3/envs/ultralytics/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/timmy/anaconda3/envs/ultralytics/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/timmy/anaconda3/envs/ultralytics/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

/home/timmy/ultralytics/yolo/train.py FAILED

Failures:
  <NO_OTHER_FAILURES>

Root Cause (first observed failure):
[0]:
  time      : 2024-11-08_09:47:34
  host      : EIH1tm2p01-0.eih.eink.com
  rank      : 1 (local_rank: 1)
  exitcode  : -11 (pid: 16371)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 16371
```

after run `export OMP_NUM_THREADS=1`

```
Error decoding JSON from /home/timmy/.config/Ultralytics/settings.json. Starting with an empty dictionary.
New https://pypi.org/project/ultralytics/8.3.28 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.27 🚀 Python-3.10.15 torch-2.5.1 CUDA:0 (NVIDIA L40-48C, 48851MiB)
                                                 CUDA:1 (NVIDIA L40-24C, 24326MiB)
Overriding model.yaml nc=80 with nc=3
Transferred 705/711 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
W1108 10:25:30.709000 16847 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 16856 closing signal SIGTERM
E1108 10:25:31.728000 16847 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: -11) local_rank: 0 (pid: 16855) of binary: /home/timmy/anaconda3/envs/ultralytics/bin/python
Traceback (most recent call last):
  File "/home/timmy/anaconda3/envs/ultralytics/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/timmy/anaconda3/envs/ultralytics/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/timmy/anaconda3/envs/ultralytics/lib/python3.10/site-packages/torch/distributed/run.py", line 923, in <module>
    main()
  File "/home/timmy/anaconda3/envs/ultralytics/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/home/timmy/anaconda3/envs/ultralytics/lib/python3.10/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/home/timmy/anaconda3/envs/ultralytics/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/timmy/anaconda3/envs/ultralytics/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/timmy/anaconda3/envs/ultralytics/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=======================================================
/home/timmy/ultralytics/yolo/train.py FAILED
-------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-08_10:25:30
  host      : EIH1tm2p01-0.eih.eink.com
  rank      : 0 (local_rank: 0)
  exitcode  : -11 (pid: 16855)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 16855
=======================================================
```

**Comment by UltralyticsAssistant** [comment] 2024-11-08 02:29
👋 Hello @Timmy-Eink, thank you for reaching out and sharing your experiences with Ultralytics 🚀! This is an automated response to let you know that an Ultralytics engineer will assist you shortly. In the meantime, here are some resources and steps that might help you troubleshoot the multi-GPU training issue:

1. **Documentation and Resources**: If you haven't already, please consult the [Docs](https://docs.ultralytics.com) where you can find detailed guides on configuration and usage including Python and CLI examples.

2. **Bug Report**: As this may be a technical issue, could you please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and debug the situation?

3. **Environment**: Please ensure your environment is up-to-date. Upgrade to the latest `ultralytics` package and related dependencies in a [Python>=3.8](https://www.python.org/) environment:

    ```bash
    pip install -U ultralytics
    ```

   Also, double-check that you are using compatible versions of [PyTorch](https://pytorch.org/get-started/locally/) and related GPU dependencies.

4. **Community Support**: Join the Ultralytics community for additional help. Engage in real-time discussions on [Discord](https://ultralytics.com/discord) 🎧, explore in-depth topics on [Discourse](https://community.ultralytics.com), or interact with peers on our [Subreddit](https://reddit.com/r/ultralytics).

5. **Environments and Platforms**: Consider testing your training on different platforms to isolate the issue. We suggest using:

   - **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
   - **Docker Image**: See documentation for instructions on using Docker environments.

6. **Status**: Check our CI status for any known issues:
   <a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

All CI tests confirm the correct operation of YOLO tasks across macOS, Windows, and Ubuntu, which may help diagnose if the problem is environment-specific.

We appreciate your patience while we work on your request. Your collaboration helps us improve our software, and we look forward to resolving this issue together! 🌟

**Comment by Y-T-G** [comment] 2024-11-08 03:40
What's the code you're running?

You can try adding this before your code:
```
import os
os.environ["NCCL_NET"] = "Socket"
```

**Comment by Timmy-Eink** [comment] 2024-11-08 03:54
> What's the code you're running?
> 
> You can try adding this before your code:
> 
> ```
> import os
> os.environ["NCCL_NET"] = "Socket"
> ```

after add NCCL_NET I am runing with down below

> train.py

```

from ultralytics import YOLO
import os
import torch

os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
os.environ['TORCH_USE_CUDA_DSA'] = "1"
os.environ['OMP_NUM_THREADS'] = "1"
os.environ["NCCL_NET"] = "Socket"
torch.cuda.empty_cache()

if __name__ == '__main__':
    model = YOLO(
        model="weights/yolo11m-seg.pt",
        task="segment"
    )

    results = model.train(data="/home/timmy/ultralytics/data/TM2.yaml",
                          epochs=1000,
                          project="TM2",
                          name="1108-1280",
                          imgsz=1280,
                          cache=True,
                          overlap_mask=False,
                          batch=16,
                          device=[0,1],
                          )

    model.export(format="onnx")
```

**Comment by Y-T-G** [comment] 2024-11-08 04:30
Can you try without cache?

**Comment by Timmy-Eink** [comment] 2024-11-08 04:42
> Can you try without cache?

you mean set cache to False rights?
same errors as well

**Comment by Y-T-G** [comment] 2024-11-08 04:48
You can try downgrading PyTorch

**Comment by Timmy-Eink** [comment] 2024-11-08 06:05
thanks I downgrading PyTorch from 2.5.1 to 2.4.1 it worked !!!

**Closed** 2024-11-08 06:11 UTC
Labels: question, detect

**Comment by glenn-jocher** [comment] 2024-11-08 12:29
Great to hear that downgrading PyTorch resolved the issue! If you have any more questions or need further assistance, feel free to ask.

**Comment by glenn-jocher** [comment] 2025-01-07 23:41
@elyxlz the issue likely stems from compatibility problems between the specific PyTorch version (2.5.1) and the distributed training setup used. While downgrading PyTorch resolves it for now, checking for updates in both PyTorch and Ultralytics YOLO, or adjusting the distributed training configuration, might provide a more permanent solution.

**Comment by elyxlz** [comment] 2025-01-08 10:50
NCCL_SOCKET_IFNAME=lo
this solved the issue

**Comment by glenn-jocher** [comment] 2025-01-09 02:48
@elyxlz thank you for sharing your solution! Setting `NCCL_SOCKET_IFNAME=lo` is indeed a helpful workaround for addressing NCCL communication issues during multi-GPU training. This can assist others experiencing similar problems.

**Comment by elyxlz** [comment] 2025-01-09 09:24
Are you a bot

**Comment by glenn-jocher** [comment] 2025-01-09 22:48
No, I am here to assist with your Ultralytics YOLO-related questions and issues. Let me know how I can help!
