### ISSUE TITLE
Error Export default YOLOv8s Model to TensorFlow Lite Format (pt2tflite issue i think)

### ISSUE THREAD

**Issue by nikitaevstatera** [ultralytics/ultralytics#14266] opened 2024-07-08 10:14 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

Previously I wrote that there is an error in export.py in line number 1019:
https://github.com/ultralytics/ultralytics/pull/13176#issuecomment-2213267922

It should be:
if not ARM64:
instead of
if ARM64:

otherwise, in Windows 10 + Python 3.11 an error appears that the tensorflow_lite_support package does not exist.
There is only the tflite_support package.

In addition, if you try to convert the Yolov8 model file with the pt extension to the tflite format, then the tflite model file does not have metadata. This issue is reported by Android Studio Koala.

Original repository with an example program for Android:
lite/examples/object_detection/android

My version:
https://github.com/nikitaevstatera/tensorflow_examples/tree/master/lite/examples/object_detection/android

I added Python commands to the repository, with which I configure Python and convert pt files to tflite:
lite/examples/object_detection/android/yolo_commands/v8

Model files:
https://drive.google.com/drive/folders/1aaybCFmCa5FSzVRJEtOvUPpBjJLwq0V1?usp=drive_link

A screenshot of the conversion:
![convert](https://github.com/ultralytics/ultralytics/assets/165652154/85dce73a-39e1-4ecd-8d4d-e85edefd9888)

Screenshot #1 of the Android Studio error
![yolo2tflite no metadata 1](https://github.com/ultralytics/ultralytics/assets/165652154/ea0dfd31-7753-41ab-97e9-8fb0905e8e9e)

Screenshot #2 of the Android Studio error
![yolo2tflite no metadata 2](https://github.com/ultralytics/ultralytics/assets/165652154/ad85f2ca-3be2-4002-9c34-3173bfa35b12)

Must be like this:
![good metadata](https://github.com/ultralytics/ultralytics/assets/165652154/39176c01-2508-4c08-ad1e-abee0e46499d)

Android Studio Koala | 2024.1.1
Build #AI-241.15989.150.2411.11948838, built on June 10, 2024
Runtime version: 17.0.10+0--11609105 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
Kotlin Plugin: K2 Kotlin Mode (Alpha)
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 16
Registry:
  ide.instant.shutdown=false
  ide.experimental.ui=true
Non-Bundled Plugins:
  tamas_g_barna.whalelint (0.0.8)
  Batch Scripts Support (1.0.13)
  com.intellij.marketplace (241.15989.206)
  CMD Support (1.0.5)
  Dart (241.17502)
  tarn.gradle.dependencies (1.6.2)
  PythonCore (241.15989.150)
  pl.sudo.imageviewer.python (4.1.0)
  com.jetbrains.edu (2024.6-2024.1-1325)
  ru.rzn.gmyasoedov.gmaven (233.28)
  com.github.warningimhack3r.npmupdatedependencies (2.3.3)

List of installed python packages:

C:\>python -m pip list
Package                      Version
---------------------------- ------------
absl-py                      1.4.0
astunparse                   1.6.3
attributee                   0.1.9
attrs                        23.2.0
bidict                       0.23.1
cachetools                   5.3.3
certifi                      2024.7.4
charset-normalizer           3.3.2
cloudpickle                  3.0.0
colorama                     0.4.6
coloredlogs                  15.0.1
contourpy                    1.2.1
cuda-python                  12.5.0
cycler                       0.12.1
decorator                    5.1.1
dm-tree                      0.1.8
dominate                     2.9.1
filelock                     3.15.4
flatbuffers                  24.3.25
fonttools                    4.53.0
fsspec                       2024.6.1
gast                         0.6.0
genicam                      1.4.0
google-pasta                 0.2.0
grpcio                       1.64.1
gym                          0.26.2
gym-notices                  0.0.8
h5py                         3.11.0
harvesters                   1.4.3
humanfriendly                10.0
idna                         3.7
intel-openmp                 2021.4.0
Jinja2                       3.1.4
jsonschema                   4.22.0
jsonschema-specifications    2023.12.1
keras                        3.4.1
kiwisolver                   1.4.5
labelImg                     1.8.6
lazy-object-proxy            1.10.0
libclang                     18.1.1
llvmlite                     0.43.0
lxml                         5.2.2
Markdown                     3.6
markdown-it-py               3.0.0
MarkupSafe                   2.1.5
matplotlib                   3.9.1
mdurl                        0.1.2
mkl                          2021.4.0
ml-dtypes                    0.3.2
mpmath                       1.3.0
namex                        0.0.8
networkx                     3.3
numba                        0.60.0
numpy                        1.26.4
onnx                         1.16.1
onnx-graphsurgeon            0.5.2
onnx-tf                      1.10.0
onnx2tf                      1.22.3
onnxruntime                  1.18.1
onnxruntime-gpu              1.18.1
onnxslim                     0.1.31
opencv-python                4.10.0.84
opt-einsum                   3.3.0
optree                       0.11.0
ordered-set                  4.1.0
packaging                    24.1
pandas                       2.2.2
phx-class-registry           4.1.0
pillow                       10.4.0
pip                          24.1.2
protobuf                     4.25.3
psutil                       6.0.0
py-cpuinfo                   9.0.0
pybind11                     2.13.1
pycocotools                  2.0.8
Pygments                     2.18.0
PyLaTeX                      1.4.2
pyparsing                    3.1.2
pypylon                      3.0.1
PyQt5                        5.15.10
PyQt5-Qt5                    5.15.2
PyQt5-sip                    12.13.0
pyreadline3                  3.4.1
python-dateutil              2.9.0.post0
pytz                         2024.1
PyYAML                       6.0.1
referencing                  0.35.1
requests                     2.32.3
rich                         13.7.1
rpds-py                      0.18.1
scipy                        1.14.0
seaborn                      0.13.2
six                          1.16.0
sng4onnx                     1.0.4
sympy                        1.12.1
tbb                          2021.13.0
tensorboard                  2.16.2
tensorboard-data-server      0.7.2
tensorflow                   2.16.1
tensorflow-addons            0.22.0
tensorflow-estimator         2.13.0
tensorflow-intel             2.16.1
tensorflow-io-gcs-filesystem 0.31.0
tensorflow-probability       0.24.0
termcolor                    2.4.0
tf_keras                     2.16.0
tf2onnx                      1.16.1
tflite-support               0.1.0a1
torch                        2.3.1+cu121
torchaudio                   2.3.1+cu121
torchvision                  0.18.1+cu121
tqdm                         4.66.4
typeguard                    2.13.3
typing_extensions            4.12.2
tzdata                       2024.1
ultralytics                  8.2.50
ultralytics-thop             2.0.0
urllib3                      2.2.2
vot-toolkit                  0.7.1
vot-trax                     4.0.2
Werkzeug                     3.0.3
wheel                        0.43.0
wrapt                        1.16.0

### Environment

yolo checks
Ultralytics YOLOv8.2.50 🚀 Python-3.11.9 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060, 12288MiB)
Setup complete ✅ (16 CPUs, 63.8 GB RAM, 294.5/465.1 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.11.9
Install             pip
RAM                 63.78 GB
CPU                 12th Gen Intel Core(TM) i7-12700
CUDA                12.1

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.3.1+cu121>=1.8.0
torchvision         ✅ 0.18.1+cu121>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

yolo export model="yolov8s_imgsz1024_ep300_android_40.4.pt" format=tflite device=0 imgsz=1024 half=False int8=True data="D:\TEMP\YoloTrain\coco8.yaml"

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment] 2024-07-08 17:31
Hello @nikitaevstatera,

Thank you for your detailed report and for highlighting the issue with the `export.py` script. Your suggestion to modify the condition to `if not ARM64:` is noted and appreciated. We'll review this internally to ensure compatibility across different environments.

Regarding the metadata issue in the TFLite model, it's crucial for the exported model to include the necessary metadata for proper integration with Android Studio and other platforms. We'll investigate this further to identify the root cause and provide a fix.

In the meantime, please ensure you are using the latest version of the Ultralytics package by running:
```bash
pip install --upgrade ultralytics
```

Additionally, if you could provide a minimal reproducible example, it would greatly assist us in diagnosing and resolving the issue. You can find guidelines for creating a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

For your reference, here’s a concise example of exporting a YOLOv8 model to TFLite format using Python:
```python
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO("yolov8n.pt")

# Export the model to TFLite format
model.export(format="tflite")  # creates 'yolov8n_float32.tflite'
```

And using the CLI:
```bash
yolo export model=yolov8n.pt format=tflite
```

For more detailed instructions on exporting to TFLite, you can visit our documentation: [Export to TFLite](https://docs.ultralytics.com/integrations/tflite/).

Thank you for your contribution and for helping improve the Ultralytics YOLOv8 framework! If you have any further insights or updates, please feel free to share them.

**Comment by nikitaevstatera** [comment] 2024-07-09 06:44
Hello, @glenn-jocher !
First start for yours
```
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO("yolov8n.pt")

# Export the model to TFLite format
model.export(format="tflite")  # creates 'yolov8n_float32.tflite'
```
![Screenshot_1](https://github.com/ultralytics/ultralytics/assets/165652154/39620b66-27e6-403f-bc3c-a3f8efbdd549)

**Comment by nikitaevstatera** [comment] 2024-07-09 06:52
After manual change export.py:
![Screenshot_2](https://github.com/ultralytics/ultralytics/assets/165652154/80dfb7de-a58b-47e8-be37-69372cc74a27)

convertion result:
![Screenshot_3](https://github.com/ultralytics/ultralytics/assets/165652154/b51afa16-73a6-47b2-a0d4-537055ce308b)

and no tflite file in folder:
![Screenshot_4](https://github.com/ultralytics/ultralytics/assets/165652154/ac3cc1ea-2d8e-48b1-a31e-8243bd686813)

![Screenshot_5](https://github.com/ultralytics/ultralytics/assets/165652154/d1278d2c-fec6-4e0d-8511-f950f2d082e1)

**Comment by nikitaevstatera** [comment] 2024-07-09 09:08
Llama 3 write this info about this problem:

![Screenshot_6](https://github.com/ultralytics/ultralytics/assets/165652154/a77c1152-1dc9-4139-a5fe-7f395f87a55e)


_The program cannot execute the command to convert pt model files to tflite files because it requires additional dependencies such as TensorRT or OpenVINO to be installed on the system. Additionally, the command used in the code is not correct and needs to be modified accordingly._

**Comment by glenn-jocher** [comment] 2024-07-09 14:33
Hello @nikitaevstatera,

Thank you for your detailed follow-up and for providing the screenshots. It looks like you're encountering issues with the TFLite export process. Let's address the points you've raised:

1. **Manual Change to `export.py`**:
   - Your modification to the `export.py` script to handle the ARM64 condition is noted. This change should help ensure compatibility across different environments.

2. **Conversion Result**:
   - It appears that the conversion process completes without errors, but the TFLite file is not generated. This could be due to several reasons, including missing dependencies or incorrect configurations.

3. **Missing TFLite File**:
   - The absence of the TFLite file in the output directory suggests that the export process might not have been fully executed or completed successfully.

### Steps to Troubleshoot and Resolve:

1. **Verify Dependencies**:
   - Ensure that all necessary dependencies for TFLite export are installed. You can install TensorFlow Lite support using:
     ```bash
     pip install tflite-support
     ```

2. **Check for Errors**:
   - Review the console output for any warnings or errors that might indicate why the TFLite file was not generated.

3. **Reproducible Example**:
   - If possible, please provide a minimal reproducible example that demonstrates the issue. This will help us diagnose the problem more effectively. You can follow the guidelines here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

4. **Update Packages**:
   - Make sure you are using the latest versions of the Ultralytics and TensorFlow packages. You can update them using:
     ```bash
     pip install --upgrade ultralytics tensorflow
     ```

### Example Code for Exporting to TFLite:
Here’s a concise example to ensure the export process is correctly followed:
```python
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO("yolov8n.pt")

# Export the model to TFLite format
model.export(format="tflite")  # creates 'yolov8n_float32.tflite'
```

### Additional Resources:
For more detailed instructions on exporting to TFLite, please refer to our documentation: [Export to TFLite](https://docs.ultralytics.com/integrations/tflite/).

If the issue persists after following these steps, please let us know, and we will continue to assist you in resolving it.

Thank you for your patience and for helping improve the Ultralytics YOLOv8 framework! 😊

**Comment by nikitaevstatera** [comment] 2024-07-11 06:49
I run command

`pip install tflite-support`

and get result:

![Screenshot_7](https://github.com/ultralytics/ultralytics/assets/165652154/9efc5965-ed65-4526-84a1-0af373710d4c)

**Comment by nikitaevstatera** [comment] 2024-07-11 06:53
Run yours minimal test:

```
import torch

from ultralytics import YOLO

# Load the model
model = YOLO("yolov8n.pt")

# Load a 0-channel image
image = torch.rand(1, 0, 640, 640)

# Run the model
results = model(image)
```

and get:

![Screenshot_8](https://github.com/ultralytics/ultralytics/assets/165652154/b0b611b8-6505-471e-9a26-620241bc8408)

**Comment by nikitaevstatera** [comment] 2024-07-11 06:56
pip list

python -m pip list

Package                      Version
---------------------------- ------------
absl-py                      1.4.0
astunparse                   1.6.3
attributee                   0.1.9
attrs                        23.2.0
bidict                       0.23.1
cachetools                   5.3.3
certifi                      2024.7.4
charset-normalizer           3.3.2
cloudpickle                  3.0.0
colorama                     0.4.6
coloredlogs                  15.0.1
contourpy                    1.2.1
cuda-python                  12.5.0
cycler                       0.12.1
decorator                    5.1.1
dm-tree                      0.1.8
dominate                     2.9.1
filelock                     3.15.4
flatbuffers                  24.3.25
fonttools                    4.53.0
fsspec                       2024.6.1
gast                         0.6.0
genicam                      1.4.0
google-pasta                 0.2.0
grpcio                       1.64.1
gym                          0.26.2
gym-notices                  0.0.8
h5py                         3.11.0
harvesters                   1.4.3
huggingface-hub              0.23.4
humanfriendly                10.0
idna                         3.7
intel-openmp                 2021.4.0
Jinja2                       3.1.4
jsonschema                   4.22.0
jsonschema-specifications    2023.12.1
keras                        3.4.1
kiwisolver                   1.4.5
labelImg                     1.8.6
lazy-object-proxy            1.10.0
libclang                     18.1.1
llvmlite                     0.43.0
lxml                         5.2.2
Markdown                     3.6
markdown-it-py               3.0.0
MarkupSafe                   2.1.5
matplotlib                   3.9.1
mdurl                        0.1.2
mkl                          2021.4.0
ml-dtypes                    0.3.2
mpmath                       1.3.0
namex                        0.0.8
networkx                     3.3
numba                        0.60.0
numpy                        1.26.4
onnx                         1.16.1
onnx-graphsurgeon            0.5.2
onnx-tf                      1.10.0
onnx2tf                      1.22.3
onnxruntime                  1.18.1
onnxruntime-gpu              1.18.1
onnxslim                     0.1.31
opencv-python                4.10.0.84
opt-einsum                   3.3.0
optree                       0.11.0
ordered-set                  4.1.0
packaging                    24.1
pandas                       2.2.2
phx-class-registry           4.1.0
pillow                       10.4.0
pip                          24.1.2
protobuf                     4.25.3
psutil                       6.0.0
py-cpuinfo                   9.0.0
pybind11                     2.13.1
pycocotools                  2.0.8
Pygments                     2.18.0
PyLaTeX                      1.4.2
pyparsing                    3.1.2
pypylon                      3.0.1
PyQt5                        5.15.10
PyQt5-Qt5                    5.15.2
PyQt5-sip                    12.13.0
pyreadline3                  3.4.1
python-dateutil              2.9.0.post0
pytz                         2024.1
PyYAML                       6.0.1
referencing                  0.35.1
regex                        2024.5.15
requests                     2.32.3
rich                         13.7.1
rpds-py                      0.18.1
safetensors                  0.4.3
scipy                        1.14.0
seaborn                      0.13.2
six                          1.16.0
sng4onnx                     1.0.4
sympy                        1.12.1
tbb                          2021.13.0
tensorboard                  2.16.2
tensorboard-data-server      0.7.2
tensorflow                   2.16.2
tensorflow-addons            0.22.0
tensorflow-estimator         2.13.0
tensorflow-intel             2.16.2
tensorflow-io-gcs-filesystem 0.31.0
tensorflow-probability       0.24.0
termcolor                    2.4.0
tf_keras                     2.16.0
tf2onnx                      1.16.1
tflite-support               0.1.0a1
tokenizers                   0.19.1
torch                        2.3.1+cu121
torchaudio                   2.3.1+cu121
torchvision                  0.18.1+cu121
tqdm                         4.66.4
transformers                 4.42.3
typeguard                    2.13.3
typing_extensions            4.12.2
tzdata                       2024.1
ultralytics                  8.2.51
ultralytics-thop             2.0.0
urllib3                      2.2.2
vot-toolkit                  0.7.1
vot-trax                     4.0.2
Werkzeug                     3.0.3
wheel                        0.43.0
wrapt                        1.16.0

**Comment by nikitaevstatera** [comment] 2024-07-11 06:58
yolo checks

Ultralytics YOLOv8.2.51 🚀 Python-3.11.9 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060, 12288MiB)
Setup complete ✅ (16 CPUs, 63.8 GB RAM, 337.1/465.1 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.11.9
Install             pip
RAM                 63.78 GB
CPU                 12th Gen Intel Core(TM) i7-12700
CUDA                12.1

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.3.1+cu121>=1.8.0
torchvision         ✅ 0.18.1+cu121>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

**Comment by nikitaevstatera** [comment] 2024-07-11 07:01
As I understand it, there have been some changes in the Torch library.

**Comment by glenn-jocher** [comment] 2024-07-11 09:34
Hello @nikitaevstatera,

Thank you for your detailed follow-up and for providing the screenshots. It looks like you're encountering issues with the TFLite export process. Let's address the points you've raised:

1. **Manual Change to `export.py`**:
   - Your modification to the `export.py` script to handle the ARM64 condition is noted. This change should help ensure compatibility across different environments.

2. **Conversion Result**:
   - It appears that the conversion process completes without errors, but the TFLite file is not generated. This could be due to several reasons, including missing dependencies or incorrect configurations.

3. **Missing TFLite File**:
   - The absence of the TFLite file in the output directory suggests that the export process might not have been fully executed or completed successfully.

### Steps to Troubleshoot and Resolve:

1. **Verify Dependencies**:
   - Ensure that all necessary dependencies for TFLite export are installed. You can install TensorFlow Lite support using:
     ```bash
     pip install tflite-support
     ```

2. **Check for Errors**:
   - Review the console output for any warnings or errors that might indicate why the TFLite file was not generated.

3. **Reproducible Example**:
   - If possible, please provide a minimal reproducible example that demonstrates the issue. This will help us diagnose the problem more effectively. You can follow the guidelines here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

4. **Update Packages**:
   - Make sure you are using the latest versions of the Ultralytics and TensorFlow packages. You can update them using:
     ```bash
     pip install --upgrade ultralytics tensorflow
     ```

### Example Code for Exporting to TFLite:
Here’s a concise example to ensure the export process is correctly followed:
```python
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO("yolov8n.pt")

# Export the model to TFLite format
model.export(format="tflite")  # creates 'yolov8n_float32.tflite'
```

### Additional Resources:
For more detailed instructions on exporting to TFLite, please refer to our documentation: [Export to TFLite](https://docs.ultralytics.com/integrations/tflite/).

If the issue persists after following these steps, please let us know, and we will continue to assist you in resolving it.

Thank you for your patience and for helping improve the Ultralytics YOLOv8 framework! 😊

**Comment by nikitaevstatera** [comment] 2024-07-11 11:02
Hello @glenn-jocher !
I got error:

File ultralytics\data\loaders.py line 483, in _single_check
    if im.max() > 1.0 + torch.finfo(im.dtype).eps:  # torch.float32 eps is 1.2e-07

RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.

Phind.com write answer on this error:
Variant 1:
https://www.phind.com/search?cache=kxthlafuojg43l9kd1dkc5gh

Variant 2:
https://www.phind.com/search?cache=dtdmw6hodiha2x1dog13nxem

**Comment by glenn-jocher** [comment] 2024-07-11 12:46
Hello @nikitaevstatera,

Thank you for bringing this issue to our attention. The error you're encountering seems to be related to the handling of empty tensors within the `_single_check` function in `ultralytics/data/loaders.py`.

To help us better understand and resolve this issue, could you please provide a minimal reproducible example? This will allow us to replicate the problem on our end and identify the root cause more effectively. You can find guidelines for creating a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest versions of the Ultralytics and PyTorch packages, as updates often include important bug fixes and improvements. You can update them using the following commands:
```bash
pip install --upgrade ultralytics torch
```

In the meantime, a potential workaround for this issue is to modify the `_single_check` function to handle empty tensors gracefully. Here’s a quick example of how you might adjust the code:
```python
if im.numel() == 0:
    return
if im.max() > 1.0 + torch.finfo(im.dtype).eps:
    # Your existing logic here
```

This adjustment checks if the tensor is empty before attempting to find its maximum value, which should prevent the `RuntimeError` you encountered.

Please let us know if this helps or if you continue to experience issues. We're here to assist you! 😊

**Comment by nikitaevstatera** [comment] 2024-07-12 07:12
Hello @glenn-jocher !
I run this cmd file:

python -m pip install --upgrade pip
python -m pip install --upgrade ultralytics
python -m pip install --upgrade tensorflow
python -m pip install --upgrade ultralytics tensorflow
python -m pip install --upgrade mediapipe-model-maker

rem Установка PyTorch с поддержкой Cuda: https://pytorch.org/get-started/locally/
python -m pip install --upgrade --user torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

rem Установка зависимостей:
python -m pip install --upgrade pyyaml
python -m pip install --upgrade requests
python -m pip install --upgrade onnx
python -m pip install --upgrade onnxruntime-gpu
python -m pip install --upgrade onnxruntime
python -m pip install --upgrade opencv-python
python -m pip install --upgrade pycocotools
python -m pip install --upgrade numpy
python -m pip install --upgrade ultralytics
python -m pip install --upgrade cuda-python
python -m pip install --upgrade tflite_support

rem Install the ultralytics package from GitHub
python -m pip install --upgrade pip install --user git+https://github.com/ultralytics/ultralytics.git@main

Выполнить тесты:
python --version
yolo version

pause

And get result with some errors:

[errors on yolo update.txt](https://github.com/user-attachments/files/16189978/errors.on.yolo.update.txt)

C:\Users\Nikitaev>yolo check
Ultralytics YOLOv8.2.54 🚀 Python-3.11.9 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060, 12288MiB)
Setup complete ✅ (16 CPUs, 63.8 GB RAM, 332.7/465.1 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.11.9
Install             pip
RAM                 63.78 GB
CPU                 12th Gen Intel Core(TM) i7-12700
CUDA                12.1

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.3.1+cu121>=1.8.0
torchvision         ✅ 0.18.1+cu121>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

**Comment by glenn-jocher** [comment] 2024-07-12 09:48
@nikitaevstatera ok I will try to apply your logic change in a PR and see the result there, hold on.

**Comment by glenn-jocher** [comment] 2024-07-12 09:55
@nikitaevstatera the proposed idea crashes multiple tests in https://github.com/ultralytics/ultralytics/pull/14385, so this is clearly not a good change.

<img width="2139" alt="Screenshot 2024-07-12 at 11 55 13" src="https://github.com/user-attachments/assets/834ffdf7-73e2-4e6e-a5fb-15ee10b0c438">

**Closed** 2024-07-12 11:47 UTC
Labels: bug, fixed
