### ISSUE TITLE
When I add 'rect' arg, "RuntimeError : Sizes of tensors must match except in dimension 0" occurred

### ISSUE THREAD

**Issue by nameCDI** [ultralytics/ultralytics#1604] opened 2023-03-24 16:21 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

My original code :
yolo segment train data=custom_data.yaml model=yolov8s-seg.pt imgsz=640 epochs=600 batch=64 devoce='0,1' cache=true optimizer=Adam cos_lr=true momentum=0.99 classes=[1,2,3,4,5,6] 
This is good.

But, I just add **"rect=true"**,
_Error has occured_
yolo segment train data=custom_data.yaml model=yolov8s-seg.pt imgsz=640 epochs=600 batch=64 devoce='0,1' cache=true optimizer=Adam cos_lr=true momentum=0.99 classes=[1,2,3,4,5,6] **rect=true**

![image](https://user-images.githubusercontent.com/128284613/227579561-d56cfcc0-e78f-4ad2-99d8-0f2b8facdee2.png)

What happend? 
Did I do something wrong?

I think this is the point, but I don't know what it is.
RuntimeError : Sizes of tensors must match except in dimension 0. Expected size 160 but got size 120 for tensor number 16 in the list

**Comment by nameCDI** [comment] 2023-03-24 16:25
And warning message also occurred.

![image](https://user-images.githubusercontent.com/128284613/227584034-da5d3c8e-6a62-4051-a77e-ac3da0c2c1ee.png)

**Comment by glenn-jocher** [comment] 2023-03-24 17:44
@nameCDI thanks for the bug report, I'll take a look. In any case, rect=True is not recommended for training, you will likely get worse results as the mosaic presents 4x the amount of data to the model.

**Comment by glenn-jocher** [comment] 2023-03-24 17:48
@nameCDI I've trained a rect=True segment model with no problems, so I'm unable to reproduce any issues here:

<img width="1769" alt="Screenshot 2023-03-24 at 18 47 57" src="https://user-images.githubusercontent.com/26833433/227601995-d1f8792c-5166-49c8-b629-25a2dc967479.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by nameCDI** [comment] 2023-03-24 17:59
@glenn-jocher 
Thank you for your comment.

I've trained "yolo train model=yolov8n-seg.pt rect=True " just like you, and I didn't get an error either.
However, when I added device='0,1', an error occurred.  like "yolo train model=yolov8n-seg.pt rect=True device='0, 1' "

Then Multi-GPU issue?

![image](https://user-images.githubusercontent.com/128284613/227603945-e0f3992a-960a-43bc-89e4-fab66c81c4c7.png)

**Comment by glenn-jocher** [comment] 2023-03-26 13:37
@nameCDI yes I'm able to reproduce this error now. It appears that rect is simply not compatible with DDP, and the correct solution here is to add another warning and to force rect=True when DDP training is requested.

This is because each GPU is sampling the dataset from different areas, and rect=True attempts to collate rectangular images into a minimum size batch, the dimensions of which many vary across the dataset space.

**Closed** 2023-03-26 15:21 UTC
Labels: question, fixed
