### ISSUE TITLE
The terminal output results of Precision (P value) and Recall (R value) differ from the Precision and Recall values calculated using the confusion matrix in the validation results.

### ISSUE THREAD

**Issue by gulugulupa33** [ultralytics/ultralytics#17764] opened 2024-11-25 08:02 UTC
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The terminal output results of Precision (P value) and Recall (R value) differ from the Precision and Recall values calculated using the confusion matrix in the validation results.

**Comment by UltralyticsAssistant** [comment] 2024-11-25 08:03
👋 Hello @gulugulupa33, thank you for reaching out and for using Ultralytics 🚀! An Ultralytics engineer will assist you shortly, but in the meantime, here are a few steps to help clarify your issue.

For discrepancies between terminal output and confusion matrix calculations of Precision and Recall values, it could be useful to ensure you are consistently using the latest version of the software. Please upgrade your version of Ultralytics using the following command:

```bash
pip install -U ultralytics
```

Make sure your environment is set up as per the latest guidelines by visiting our [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) page.

If this is a 🐛 Bug Report, to facilitate our ability to help you, could you provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/)? This will greatly assist us in diagnosing the potential issue.

If your question is related to custom training ❓, please include any relevant details such as dataset examples and training logs. Additionally, ensure you’re following our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

Feel free to join our supportive community:
- Engage in real-time discussions on [Discord](https://ultralytics.com/discord) 🎧.
- Explore in-depth conversations on [Discourse](https://community.ultralytics.com).
- Share insights on our [Subreddit](https://reddit.com/r/ultralytics).

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

This badge indicates the status of Ultralytics CI tests. A green badge means all tests are passing, ensuring the integrity across different platforms.

Thank you for your patience, and we appreciate your collaboration in resolving this matter! 😊

**Comment by Y-T-G** [comment] 2024-11-25 08:17
Duplicate of #17047

> ### Search before asking
> 
> - [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
>

**Closed by Y-T-G** 2024-11-25 08:17 UTC
Labels: question

**Comment by gulugulupa33** [comment] 2024-11-25 08:48
Why is the F1-score calculated using the confusion matrix sometimes higher than the F1-score derived from the Precision and Recall values shown in the terminal output?
