### ISSUE TITLE
WARNING  'source' is missing. Using 'source=https://ultralytics.com/images/bus.jpg'.

### ISSUE THREAD

**Issue by nip6** [ultralytics/ultralytics#2717] opened 2023-05-20 12:28 UTC
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://github.com/ultralytics/ultralytics/assets/107199746/1d0cc002-03b4-49ee-847a-64bcc4282d61)

I encountered a warning message while using YOLOv8 for video detection. The warning message says, "WARNING 'source' is missing. Using 'source=https://ultralytics.com/images/bus.jpg'." Consequently, it keeps looking for the bus.jpg file and performs predictions, which is causing inconvenience in my predictions. I would like to know how to prevent this warning from appearing and stop it from searching for the bus.jpg file. Thank you！

**Comment by glenn-jocher** [comment] 2023-05-20 23:15
@nip6 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by mshibashish** [comment] 2023-05-25 11:19
If you are running a code over a video, you might not have put a condition to end the loop once the video ends. I was getting the same error because of that reason.

**Comment by glenn-jocher** [comment] 2023-05-26 09:53
@mshibashish thank you for providing this helpful information. This issue may potentially occur when the code performs predictions continuously without specifying an exit condition for the loop that reads the video frames. Therefore, it would be advisable to add an appropriate condition to exit the loop once all frames are processed, which should fix the issue. Please let us know if this resolves the problem for you, and feel free to reach out if you have further questions or concerns.

**Comment by AzwadFawadHasan** [comment] 2023-05-26 21:37
@mshibashish  @glenn-jocher  I have been facing the same issue. I tried putting a condition to end the loop once the video ends, but the issue still remains

**Comment by glenn-jocher** [comment] 2023-05-27 14:27
Hello @AzwadFawadHasan, thank you for reaching out to us and letting us know about the issue you are facing with YOLOv8. I'm sorry to hear that the previous suggestion has not resolved the issue for you.

In this case, it is possible that the warning message is being caused by other parts of the code. However, without additional information or a reproducible example, it is difficult to determine the root cause of the issue.

To further investigate the issue, it would be helpful if you could provide us with more details about the project you are working on, such as the version of the YOLOv8 repo you are using, the command you are running, and any modifications you have made to the code.

If possible, please share a minimal, reproducible example with us so that we can better understand and diagnose the problem. Once we have more information, we will be better equipped to provide appropriate guidance.

Thank you for your patience, and we look forward to helping you resolve the issue as soon as possible.

**Closed** 2023-05-30 07:26 UTC
Labels: question

**Comment by yuliya3000** [comment] 2023-06-04 02:42
@nip6 Hello ! did you manage to solve the issue?

**Comment by glenn-jocher** [comment] 2023-06-04 22:56
Hello @yuliya3000, thank you for reaching out to us regarding the source missing warning message in YOLOv8.

It is possible that the warning message is caused by a loop that is reading the video frames continuously without specifying an exit condition. You can try adding an appropriate exit condition to the loop to resolve this issue.

Alternatively, this warning message may be generated by other parts of the code. In this case, it would be helpful to provide a minimal, reproducible example that demonstrates the warning message, along with any additional information regarding the version of YOLOv8 you are using and any modifications you may have made to the code.

We hope this information is helpful, and please let us know if you have further questions or concerns.

**Comment by yuliya3000** [comment] 2023-06-05 06:42
Hello @glenn-jocher , yes thank you! i've already solved:
`cap = cv.VideoCapture(video)
 while True:
    ret, frame = cap.read()
     if ret:
         ...
     else:
         break
cap.release()
cv.destroyAllWindows()`

**Comment by glenn-jocher** [comment] 2023-06-05 23:54
Hello @yuliya3000, 

We're glad to hear that you have been able to solve the issue with the source missing warning message by adding an appropriate exit condition to the loop that reads the video frames. 

As you mentioned, by using `cap.read()` to read the frames, the loop will run until there are no longer any frames to read. You also added a break statement to ensure the loop exits when all frames have been processed.

Thank you for sharing your solution with the community. If you have any further questions or concerns, please feel free to reach out to us. 

Best regards!

**Comment by fridary** [comment] 2023-07-28 00:45
@mshibashish @glenn-jocher I need a help with the same problem..
I'm making service where people send by API image base64 string to get decetions.
Now I'm testing how system works if user sends not image. Txt, pdf, any other. When it happens, I get an error: 
`WARNING ⚠️ 'source' is missing. Using 'source=https://ultralytics.com/images/bus.jpg'.`

How can I prevent it? How can I catch if any error occurs? `try {} except Exception as e {}` doesn't help.
My code:
```python
# image_base64 is base64 string that user sends to server 
nparr = np.frombuffer(base64.b64decode(image_base64), np.uint8)
img_np = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
model.predict(source=img_np)
```

Example sending any file to check:
```python
with open("test.txt", 'rb') as f:
   image_data_binary = f.read()
   image_base64 = (base64.b64encode(image_data_binary)).decode('ascii')
```

**Comment by glenn-jocher** [comment] 2023-07-28 23:32
Hello @fridary,

It appears the issue might be due to the decodable content not being a valid image. The error message you're seeing is likely because the YOLOv8 model is expecting an image file, and if no such file or incorrect file is provided, it defaults to a known image URL as the source.

A possible solution would be to validate the base64 string to confirm that it can be decoded into a valid image before passing it to the `model.predict()` function. You can use the OpenCV function `cv2.imdecode()`, as you already do in your code, to attempt to decode the image. If the outcome of this operation is `None`, it indicates that the decoding failed and the content cannot be processed as an image.

You can then handle this as an error condition in your application and respond appropriately to the API request. This approach would allow the system to catch erroneous inputs before they reach the model prediction function and would thus prevent the occurrence of the warning message you've been seeing.

We hope this will help you make your service more robust against different types of user inputs. Please let us know if you have further questions!

**Comment by sujonahmed2500** [comment] 2023-08-02 03:49
> Hello @glenn-jocher , yes thank you! i've already solved:
> 
> ```
>  cap = cv.VideoCapture(video)
> 
>  while True:
> 
>     ret, frame = cap.read()
> 
>      if ret:
>          ...
>      else:
> 
>          break
> 
>  cap.release()
> 
>  cv.destroyAllWindows()
> ```

Thanks, It's work for me

**Comment by glenn-jocher** [comment] 2023-08-02 14:27
@sujonahmed2500 hello,

We're glad to hear that you were able to solve the issue! Your solution using the `cv.VideoCapture` function, along with the appropriate exit condition for the loop, is indeed the correct approach for handling video frame processing in YOLOv8. 

By checking if there are frames left to read with the `ret` variable, you prevent the model from unnecessarily looking for the default 'bus.jpg' file when there are no more frames to process. Releasing the video capture and destroying all windows at the end also ensures that resources are properly cleaned up.

Thanks for sharing your solution with the community. This can certainly be of help to others who might encounter the same issue. Should you run into any other problems or have further questions, please don't hesitate to reach out.

Best regards.

**Comment by poorneshwaran** [comment] 2023-08-24 13:02
Hi, can someone help me to write the Videofiles. I've wrote like 
results = model(frame)
annot = results[0].plot()
annot[..., ::-1] and  write the cv2.videocapture to save in .mp4. it doesn;t shows any error and also the video's saved less than 10kb i.e(no info). 

Thanks

**Comment by glenn-jocher** [comment] 2023-08-25 00:38
@poorneshwaran hello,

The issue you're experiencing may involve writing the frames to the video file after performing the detection and annotating the results. Make sure you're properly iterating over all the frames in the video, performing the detection, and saving the annotated frames back to the video. Moreover, make sure your video writer's settings - such as the FourCC codec, frames per second, and frame size - are correctly configured. If the frames per second setting doesn't match that of the input video, or if the frame sizes aren't consistent, it could result in an empty output file without any errors being displayed.

Also check the order of color channels (RGB or BGR) in the frames being written. OpenCV uses BGR color order and therefore the frames should be in this order (Blue, Green, Red) at the time of writing. The statement you're using 'annot[..., ::-1]' might be causing a color space reversal.

I hope this helps to resolve your issue. Feel free to reach out with any other questions or if you need more clarification.

Best of luck!

**Comment by andythegril** [comment] 2023-12-15 03:31
Hello,

My project is to upload a video and the model will detect accident. Also, stream a live video, and the model start detecting on that live video.
So far, it's been working fine for the live video but it still shows the below warning.
But for the upload video, it shows the warning but not showing any video with any boxes over it (it worked before)

WARNING ⚠️ 'source' is missing. Using 'source=/opt/homebrew/lib/python3.11/site-packages/ultralytics/assets'.

and yes I do have this part in my code
cap = cv.VideoCapture(video)
while True:

    ret, frame = cap.read()

     if ret:
         ...
     else:

         break

 cap.release()

 cv.destroyAllWindows()

<img width="954" alt="Screenshot 2023-12-15 at 10 31 02" src="https://github.com/ultralytics/ultralytics/assets/95900562/4b279b2f-eaf5-4364-91b2-39bf48208d7c">

**Comment by glenn-jocher** [comment] 2023-12-15 05:28
@andythegril hello,

The warning suggests that when the model is called, it's defaulting to a path inside the Ultralytics package for the source instead of the video file you intended to process. This could happen if the 'source' parameter isn't being set correctly when you initialize or call the detection. 

Ensure you're passing the correct path to the `cv.VideoCapture()` function as it looks like the 'video' variable may not be pointing to the source you desired. Also, verify that the video file path is accessible and spelled correctly before running the detection.

For the issue with the uploaded video not showing detections, double-check if any changes were made to the model configuration or input preprocessing. If everything worked before, consider what has changed since then—either in your code or environment.

I hope this helps to pinpoint the issue. If you continue to face challenges, make sure that the file paths and variables are correctly assigned and consider sharing the part of the code where you initiate the source and model detection for further assistance.

Best regards.

**Comment by andythegril** [comment] 2023-12-17 06:13
Thank you Glenn for such quick reply, I really appreciate it.
I checked my code and the path is all correct, I'll try my best to figure it out. Again, thank you very much for replying

**Comment by glenn-jocher** [comment] 2023-12-17 11:18
You're welcome, @andythegril! I'm glad to hear you've verified the path. Keep at it, and if you have further questions or need assistance, don't hesitate to reach out. Good luck with your project!
